- src/java/org/apache/cassandra/cql3/statements/schema/CreateIndexStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/CreateViewStatement.java
- src/java/org/apache/cassandra/guardrails/Guardrails.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- test/unit/org/apache/cassandra/cql3/ViewSchemaTest.java
- test/unit/org/apache/cassandra/index/internal/CassandraIndexTest.java
Tests: https://app.circleci.com/pipelines/github/nastra/cassandra/69/workflows/460e4b5b-8cec-4d55-8c8a-5c17d46c9591
> CDB-18: Introduce Guardrails for MV/2i

- conf/cassandra.yaml
- src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
Unit tests: https://app.circleci.com/pipelines/github/nastra/cassandra/100/workflows/36398ba6-1092-4310-a946-79e6bac963f7/jobs/742
> CDB-3: Add missing guardrail settings to cassandra.yaml and missing enabled check for tables limit GR

- src/java/org/apache/cassandra/index/sai/SSTableQueryContext.java
- src/java/org/apache/cassandra/index/sai/utils/OffsetFactory.java
- test/unit/org/apache/cassandra/index/sai/utils/OffsetFactoryTest.java
https://circleci.com/workflow-run/23652fea-e052-4cbb-b1d3-2ea5eeb16f5f
> Fix token skipping cache for wide partition schema - DSP-21244

- src/java/org/apache/cassandra/db/SystemKeyspace.java
- src/java/org/apache/cassandra/db/compaction/CompactionTask.java
Co-authored-by: Brandon Williams <brandon@datastax.com>
> STAR-392: Reuse compaction task ID in compaction history

- src/java/org/apache/cassandra/db/compaction/CompactionIterator.java
- src/java/org/apache/cassandra/db/compaction/CompactionTask.java
*Note:* Depends on https://github.com/datastax/cassandra/pull/93.
> STAR-391: Reduce garbage when debug/trace is off in CompactionTask

- test/unit/org/apache/cassandra/io/sstable/MutlipleSSTableFormatsTest.java
A smoke test which operates on a table whose sstables are in both formats - big and bti. We try to read and compact those sstables.
> STAR-400: Add a smoke test for mixed sstable formats (ds-trunk)

- src/java/org/apache/cassandra/cql3/statements/TruncateStatement.java
- src/java/org/apache/cassandra/guardrails/Guardrails.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- test/unit/org/apache/cassandra/guardrails/GuardrailTruncateTableTest.java
> STAR-513 Add Guardrail to disable TRUNCATE TABLE

- src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
- src/java/org/apache/cassandra/guardrails/Guardrails.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- test/unit/org/apache/cassandra/guardrails/GuardrailCounterTest.java
Co-authored-by: Zhao Yang <jasonstack.zhao@gmail.com>
> STAR-514 Add guardrail to disable counter columns

- conf/cassandra.yaml
- src/java/org/apache/cassandra/config/DatabaseDescriptor.java
- src/java/org/apache/cassandra/cql3/statements/schema/CreateIndexStatement.java
- src/java/org/apache/cassandra/guardrails/Guardrails.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- test/unit/org/apache/cassandra/guardrails/GuardrailMaterializedViewsPerTableTest.java
- test/unit/org/apache/cassandra/guardrails/GuardrailSAIIndexesTest.java
- test/unit/org/apache/cassandra/guardrails/GuardrailSASIIndexesPerTableTest.java
- test/unit/org/apache/cassandra/guardrails/GuardrailSecondaryIndexesPerTableTest.java
- test/unit/org/apache/cassandra/guardrails/GuardrailsOnTableTest.java
STAR-512 Add guardrails for total and per-table indexes for SAI
STAR-515 Add guardrail for SASI
> STAR-515 Add guardrail for SASI and STAR-512 Add guardrails for total and per-table indexes for SAI

- src/antlr/Lexer.g
- src/antlr/Parser.g
- src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
- src/java/org/apache/cassandra/db/marshal/AbstractType.java
- src/java/org/apache/cassandra/schema/ColumnMetadata.java
- src/java/org/apache/cassandra/schema/DroppedColumn.java
- src/java/org/apache/cassandra/schema/TableMetadata.java
- src/java/org/apache/cassandra/schema/ViewMetadata.java
- test/unit/org/apache/cassandra/cql3/statements/DescribeStatementTest.java
- test/unit/org/apache/cassandra/db/SchemaCQLHelperTest.java
Co-authored-by: Sylvain Lebresne <lebresne@gmail.com>
> STAR-426 Add specific CQL statement to record dropped columns

- bin/cqlsh.py
Co-authored-by: Robert Stupp <snazy@snazy.de>
> STAR-431: Add option to prevent any file-I/O from cqlsh

- test/unit/org/apache/cassandra/io/sstable/ReducingKeyIteratorTest.java
Both trunk and ds-trunk already apply the correction in the fix.
> STAR-567: Add test from DB-1208 (bug itself is not present)

- src/java/org/apache/cassandra/gms/Gossiper.java
- src/java/org/apache/cassandra/locator/TokenMetadata.java
PR comment:
The co-author line is generated automatically during the merge. I will double check that it will happen so.
This is port of https://github.com/riptano/apollo/commit/5fae81962c64d167b7f0321a4eb77f4f234d3161
> STAR-573 Make assassinate more resilient to missing tokens

- test/unit/org/apache/cassandra/guardrails/GuardrailDiskUsageTest.java
- test/unit/org/apache/cassandra/guardrails/GuardrailTester.java
STAR-654 Wait for granted permissions to be visible.
> STAR-654 Fix permissions race in GuardrailDiskUsageTest.testWriteRequests

- src/java/org/apache/cassandra/repair/RepairRunnable.java
- src/java/org/apache/cassandra/service/StorageService.java
Porting patch DB-1511, riptano/apollo#627
> STAR-582 avoid assertion when repairing 1 node cluster

- test/microbench/org/apache/cassandra/test/microbench/sstable/SSTableReaderBench.java
- test/microbench/org/apache/cassandra/test/microbench/sstable/SSTableWriterBench.java
https://jenkins-stargazer.build.dsinternal.org/job/ds-cassandra-build-jmh/11/
> STAR-795: Reduce test sizes

- build.xml
- relocate-dependencies.pom
- src/java/org/apache/cassandra/db/lifecycle/LogReplicaSet.java
- src/java/org/apache/cassandra/db/lifecycle/LogTransaction.java
- test/unit/org/apache/cassandra/db/lifecycle/LogReplicationSetTest.java
Harden txn log files against exceptions when adding records and improve log messages
Port of riptano/apollo@83b93bc434dc2f07371e848a9b24854403bf740e
> STAR-593 Harden txn log files against exceptions

- src/java/org/apache/cassandra/cql3/QueryProcessor.java
Also, make it clear that resultify is used for tests only
> STAR-594: prevent NPE in QueryProcessor::resultify

- src/java/org/apache/cassandra/db/view/ViewManager.java
Co-authored-by: Zhao Yang <zhaoyangsingapore@gmail.com>
> STAR-690: Port DB-2251 - Update view definition when down node restarts

- src/java/org/apache/cassandra/io/sstable/SSTableLoader.java
Co-authored-by: Joel Knighton <joel.knighton@datastax.com>
> STAR-689: Port DB-2027 - Release stream plan references for ignored nodes in sstableloader

- src/java/org/apache/cassandra/db/Directories.java
- src/java/org/apache/cassandra/db/lifecycle/AbstractLogTransaction.java
- src/java/org/apache/cassandra/db/lifecycle/ILogTransactionsFactory.java
- src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java
- src/java/org/apache/cassandra/db/lifecycle/LogTransaction.java
- src/java/org/apache/cassandra/db/lifecycle/Tracker.java
- src/java/org/apache/cassandra/io/sstable/Descriptor.java
- test/unit/org/apache/cassandra/db/lifecycle/LogTransactionTest.java
- test/unit/org/apache/cassandra/io/sstable/DescriptorTest.java
STAR-987: add OBSOLETE FileType
STAR-987: add Descriptor.validFilename
> STAR-987: make DD#setConfig public

- src/java/org/apache/cassandra/db/SortedLocalRanges.java
- test/unit/org/apache/cassandra/db/SortedLocalRangesTest.java
Fixes bug introduced by PR for STAR-1032
> Fix bug in obtaining keyspace name in SorteLocalRanges

- src/java/org/apache/cassandra/service/PendingRangeCalculatorService.java
This commit allows to avoid updating all keyspaces and only update the
specified in the filter. This can be usefull when keyspaces are used
for different tenants.
The PR is without test as I don't understand how to implement one. Existing test for pending writes doesn't really care about update.
> STAR-1036 Filter keyspaces to update in PendingRangeCalculatorService

- src/java/org/apache/cassandra/io/sstable/compaction/SortedStringTableCursor.java
...during compaction when compression is enabled
> STAR-1170: Fix missed marking corrupted sstable as suspected

- src/java/org/apache/cassandra/index/sai/IndexContext.java
- src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
- src/java/org/apache/cassandra/index/sai/disk/IndexSearcherContext.java
- src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
- src/java/org/apache/cassandra/index/sai/disk/v1/IndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
- src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
- test/unit/org/apache/cassandra/index/sai/SAITester.java
- test/unit/org/apache/cassandra/index/sai/disk/SingleNodeQueryFailureTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentMergerTest.java
Add new index option: enable_segment_compaction.
> Allow to disable index segment compaction

- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
Multiple tests in IndexConsistencyTest started failing
when we committed SAI row-awareness (STAR-406).
The StorageAttachedIndexSearcher was returning
a separate UnfilteredRowIterator for each row retrieved,
even if multiple rows belonged to the same partition.
Unfortunately C* coordinator code does not merge such partitions
properly in some cases.
This commit adds merging of the same-partition iterators to
the StorageAttachedIndexSearcher.
> STAR-1180: Fix IndexConsistencyTest

- src/java/org/apache/cassandra/cql3/restrictions/CustomIndexExpression.java
- src/java/org/apache/cassandra/cql3/restrictions/ExternalRestriction.java
- src/java/org/apache/cassandra/cql3/restrictions/IndexRestrictions.java
- src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
- src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
- src/java/org/apache/cassandra/db/filter/RowFilter.java
- test/unit/org/apache/cassandra/cql3/restrictions/ExternalRestrictionTest.java
Allows mutation of SelectStatement restrictions
by external QueryInterceptor implementations
> STAR-1218 - Implement ExternalRestriction

- src/java/org/apache/cassandra/db/compaction/AbstractCompactionStrategy.java
- src/java/org/apache/cassandra/db/compaction/AbstractCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/CompactionObserver.java
- src/java/org/apache/cassandra/db/compaction/CompactionStrategyManager.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionContainer.java
- test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
- test/unit/org/apache/cassandra/db/compaction/CompactionStrategyStatisticsTest.java
- test/unit/org/apache/cassandra/db/compaction/CompactionTaskTest.java
Port CNDB-1338 Pass to CompactionObserver#onCompleted if the task finished without exceptions
> STAR-1210 Port CNDB-1338 Pass to CompactionObserver#onCompleted if the task finished without exceptions

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/compaction/CompactionStrategyFactory.java
Makes `ColumnFamily.concatWithIndexes` and `CompactionStrategyFactory.getRealm` available for use by cndb.
> STAR-1213 Make ColumnFamily.concatWithIndexes and CompactionStrategyFactory.getRealm public

- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
Make the RowIteraror implementation conform to the iterator
contract.
> STAR-1223: Fix iterator in StorageAttachedIndexSearcher

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
Needed for CNDB
My understanding it cannot be tested since unit test reason is used in tests and thus coveragable will be unsuccesful.
> STAR-1231 Add BATCHLOG_REPLAY to ColumnFamilyStore.FlushReason

- src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java
- src/java/org/apache/cassandra/index/sai/disk/v1/MemtableIndexWriter.java
- src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
The purpose of this ticket is to provide clearer information about the index write process and the time taken by each step.
> STAR-1112 Improve debug logging for index writes

- src/java/org/apache/cassandra/gms/EndpointState.java
The deadlock happens when we want to flush a change as part of Nodes update, when we update some Nodes value which requires immediate flushing. Flushing triggers compaction, and compaction tries to update some endpoint state in Gossiper (sstable versions). Endpoint state in Gossiper is automatically synced with Nodes, so any update on endpoint state makes a synchronized request to update the relevant Nodes value. This way we attempt to update Nodes inside updating Nodes which causes a deadlock.
In general we should avoid such situations, but in this particular case, sstable versions is not maintained by Nodes and therefore we do not have sync such change with Nodes (in fact, it would be empty update). The fix consists of determining if updates on Nodes are really needed before actually …
> STAR-1235: Fix deadlock (STAR-996)

- src/java/org/apache/cassandra/db/compaction/AbstractCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/CompactionTask.java
- src/java/org/apache/cassandra/db/lifecycle/Tracker.java
STAR-1273 Make Tracker.notifyAdded visible to tests
STAR-1272 Add visible for testing API in AbstractCompactionTask
Needed for CNDB tests.
> STAR-1272 STAR-1273 Make Tracker and CompactionTask visible to tests

- src/java/org/apache/cassandra/io/sstable/Component.java
> STAR-1293 Allow to read string value of Component.repr enum

- src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
- src/java/org/apache/cassandra/db/compaction/CompactionAggregate.java
- test/unit/org/apache/cassandra/db/compaction/BackgroundCompactionsTest.java
- test/unit/org/apache/cassandra/db/compaction/CompactionAggregateTest.java
> STAR-1255 Port CNDB-3376 to fix problem with compaction statistics

- src/java/org/apache/cassandra/db/tries/MemtableTrie.java
Nodes must be created in bottom-up order, so that readers
cannot observe incomplete nodes.
Fixes:
java.lang.AssertionError
at org.apache.cassandra.db.tries.MemtableReadTrie$MemtableCursor.descendInSplitSublevel(MemtableReadTrie.java:676)
at org.apache.cassandra.db.tries.MemtableReadTrie$MemtableCursor.advanceToFirstChild(MemtableReadTrie.java:626)
at org.apache.cassandra.db.tries.MemtableReadTrie$MemtableCursor.advance(MemtableReadTrie.java:559)
at org.apache.cassandra.db.tries.MemtableReadTrie$MemtableCursor.advanceMultiple(MemtableReadTrie.java:567)
at org.apache.cassandra.db.tries.Trie$Cursor.advanceToContent(Trie.java:206)
at org.apache.cassandra.db.tries.TrieEntriesIterator.hasNext(TrieEntriesIterator.java:49)
at org.apache.cassandra.db.tries.MemtableTrieThreadedTest$1.run(MemtableTri …
> STAR-1339: Fix the race causing assertion failure in MemtableTrie

- test/burn/org/apache/cassandra/utils/memory/LongBufferPoolTest.java
Fixup of STAR-1262.
Fixes:
java.util.concurrent.BrokenBarrierException
at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250)
at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362)
at org.apache.cassandra.utils.memory.LongBufferPoolTest$1.freeAllAndSuspend(LongBufferPoolTest.java:448)
at org.apache.cassandra.utils.memory.LongBufferPoolTest$1.testOne(LongBufferPoolTest.java:355)
at org.apache.cassandra.utils.memory.LongBufferPoolTest$TestUntil.call(LongBufferPoolTest.java:638)
at org.apache.cassandra.utils.memory.LongBufferPoolTest$TestUntil.call(LongBufferPoolTest.java:616)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at …
> STAR-1346: Ignore BrokenBarrierExceptions past the end of the test

- src/java/org/apache/cassandra/db/compaction/Scrubber.java
> STAR-1349 Expose scrubbed SSTables in the result

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java
- src/java/org/apache/cassandra/db/lifecycle/Tracker.java
- src/java/org/apache/cassandra/index/SecondaryIndexManager.java
- src/java/org/apache/cassandra/notifications/SSTableAddedNotification.java
- src/java/org/apache/cassandra/notifications/SSTableListChangedNotification.java
- test/unit/org/apache/cassandra/db/compaction/CompactionStrategyManagerPendingRepairTest.java
- test/unit/org/apache/cassandra/db/lifecycle/TrackerTest.java
- test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
> STAR-1344 Port CNDB-3626 - add operation id to sstable notifications

- src/java/org/apache/cassandra/db/compaction/OperationType.java
- src/java/org/apache/cassandra/db/lifecycle/View.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
- src/java/org/apache/cassandra/repair/LocalSyncTask.java
- src/java/org/apache/cassandra/streaming/StreamPlan.java
Co-authored-by: Zhao Yang <jasonstack.zhao@gmail.com>
> STAR-1345 Port CNDB-4290: make GlobalTidy public and improve repair logging

- src/java/org/apache/cassandra/db/compaction/Verifier.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
- src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexFormat.java
- src/java/org/apache/cassandra/utils/OutputHandler.java
- test/unit/org/apache/cassandra/db/VerifyTest.java
Change Verifier to not require a column family store if the option mutateRepairStatus is false.
Port CNDB-3896
> STAR-1353 Change Verifier to allow no column family store

- src/java/org/apache/cassandra/db/compaction/CompactionAggregate.java
- src/java/org/apache/cassandra/db/compaction/CompactionPick.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
> STAR-1352 Port remainder of CNDB-4337 - expose all compaction picks in an aggregate, and their status

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java
- src/java/org/apache/cassandra/db/lifecycle/Tracker.java
- test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
Co-authored-by: Zhao Yang <jasonstack.zhao@gmail.com>
> STAR-1348 Port cndb-3889: do not drop data if cfs is invalidated with dropData=false

- src/java/org/apache/cassandra/locator/DynamicEndpointSnitch.java
- src/java/org/apache/cassandra/locator/IEndpointSnitch.java
- src/java/org/apache/cassandra/locator/ReplicaPlans.java
- src/java/org/apache/cassandra/service/StorageProxy.java
- test/unit/org/apache/cassandra/locator/ReplicaPlansTest.java
Co-authored-by: Sergio Bossa <sbtourist@users.noreply.github.com>
> STAR-1347 Port CNDB-4547 Add snitch method to sort by keyspace affinity used for reads and counters.

- src/java/org/apache/cassandra/transport/Server.java
> STAR-1494 allow coordinator driver change address lookups to be

- src/java/org/apache/cassandra/tools/CompactionLogAnalyzer.java
- src/resources/org/apache/cassandra/graph/graph.html
In the drop down menu, select W value to see how W changes
over your test (more useful for adaptive tests than
static scaling parameter tests).
> Addition to the compaction_report.html file which shows the W value changing over time graphically.

- src/java/org/apache/cassandra/db/compaction/CompactionStrategyOptions.java
This option is used by the CNDB compaction integration tests.
> STAR-1480: Port UCS log config option from CNDB-2264

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/db/compaction/CompactionTask.java
Co-authored-by: Jaroslaw Grabowski <jtgrabowski@users.noreply.github.com>
> STAR-1611 Port CNDB-2770 to add toggle to disable compaction history

- src/java/org/apache/cassandra/cql3/BatchQueryOptions.java
- src/java/org/apache/cassandra/cql3/QueryOptions.java
- test/unit/org/apache/cassandra/cql3/BatchTest.java
- test/unit/org/apache/cassandra/cql3/BatchTests.java
> Add method to update consistency level in query options

- test/distributed/org/apache/cassandra/distributed/shared/ClusterUtils.java
Added metadata directory to the list of data directories in in-jvm dtests
> STAR-1195: Fix IPMembershipTest

- src/java/org/apache/cassandra/metrics/TableMetrics.java
Port of CNDB-4308 for STAR-1509.
> STAR-1509 Add tombstone counter to table metrics

- src/java/org/apache/cassandra/io/sstable/SSTable.java
Needed for `CndbCompactionRealmTest`
> STAR-1680 Use interface PartitionPartition return type in getFirst and getLast

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/streaming/StreamReceiveTask.java
Co-authored-by: Matt Fleming <mfleming@users.noreply.github.com>
> STAR-1699 Port CNDB-3654: Streaming cdc-enabled SSTables will fail. Warn about it

- src/java/org/apache/cassandra/db/Keyspace.java
This is a port of CNDB-3190 and is required to make the CNDB unit test, TableDataDeletionTest.testDropTableAllDMsUploadFailed, work.
The main idea behind CNDB-3190 is that we don't want to allow any exceptions that occur when unloading a CF to interfere with tenant unassignment or make the schema inconsistent.
> STAR-1746: Don't throw an exception if we fail to unload a CF

- build.xml
...which makes the build put the test results in the repetition index based directory and add a suffix to the test name
> STAR-1604: Add the "repetition" property

- src/java/org/apache/cassandra/metrics/BufferPoolMetrics.java
- src/java/org/apache/cassandra/metrics/CodahaleBufferPoolMetrics.java
- src/java/org/apache/cassandra/metrics/CodehaleBufferPoolMetrics.java
- src/java/org/apache/cassandra/metrics/MicrometerBufferPoolMetrics.java
- src/java/org/apache/cassandra/utils/memory/BufferPool.java
- test/unit/org/apache/cassandra/metrics/BufferPoolMetricsTest.java
> STAR-1705 Port CNDB-4974 changes to add Micrometer BufferPoolMetrics

- src/java/org/apache/cassandra/cql3/BatchQueryOptions.java
- src/java/org/apache/cassandra/cql3/QueryInterceptor.java
- src/java/org/apache/cassandra/cql3/QueryProcessor.java
- src/java/org/apache/cassandra/db/ConsistencyLevel.java
- src/java/org/apache/cassandra/exceptions/CasWriteTimeoutException.java
- src/java/org/apache/cassandra/service/StorageProxy.java
- test/unit/org/apache/cassandra/cql3/BatchTest.java
- test/unit/org/apache/cassandra/cql3/QueryInterceptorTest.java
- test/unit/org/apache/cassandra/cql3/WhereClauseMutationTest.java
- test/unit/org/apache/cassandra/cql3/restrictions/ExternalRestrictionTest.java
* add `interceptBatchStatement` to `QueryInterceptor`
* expose wrapped QueryOptions and variables in `BatchQueryOptions`
> CNDB-5791-LWT: Add Cross-region LWT support

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/metrics/MessagingMetrics.java
- src/java/org/apache/cassandra/net/InboundMessageHandlers.java
- src/java/org/apache/cassandra/net/MessagingService.java
- test/burn/org/apache/cassandra/net/ConnectionBurnTest.java
- test/unit/org/apache/cassandra/net/MessagingServiceTest.java
MessagingMetrics are now configurable via system property.
+ additional minor changes to enable inheritance
> CNDB-6235 messaging metrics impl is configurable

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/virtual/TableMetricTables.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- src/java/org/apache/cassandra/metrics/KeyspaceMetrics.java
- src/java/org/apache/cassandra/metrics/TableMetrics.java
- test/distributed/org/apache/cassandra/distributed/test/MetricsCountQueriesTest.java
- test/distributed/org/apache/cassandra/distributed/test/RepairDigestTrackingTest.java
- test/unit/org/apache/cassandra/auth/RoleTestUtils.java
- test/unit/org/apache/cassandra/cql3/validation/miscellaneous/SSTablesIteratedTest.java
- test/unit/org/apache/cassandra/db/ColumnFamilyMetricTest.java
- test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
- test/unit/org/apache/cassandra/db/KeyspaceTest.java
- test/unit/org/apache/cassandra/db/MultiRangeReadCommandTest.java
- test/unit/org/apache/cassandra/db/ReadCommandTest.java
- test/unit/org/apache/cassandra/db/RowCacheTest.java
- test/unit/org/apache/cassandra/metrics/TableMetricsTest.java
- test/unit/org/apache/cassandra/schema/SchemaKeyspaceTest.java
- test/unit/org/apache/cassandra/service/reads/repair/RepairedDataVerifierTest.java
Go commit by commit and see commit messages for details.
This is a port, but the code is different as metrics are different for DSE and CC.
> CNDB-5691 port #5205 table metrics aggregation

- src/java/org/apache/cassandra/db/marshal/VectorType.java
- src/java/org/apache/cassandra/index/sai/IndexContext.java
- src/java/org/apache/cassandra/index/sai/SSTableIndex.java
- src/java/org/apache/cassandra/index/sai/disk/v1/PerIndexFiles.java
- src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
- src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexWriter.java
- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- test/unit/org/apache/cassandra/index/sai/cql/AnnTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/postings/TopDocsPostingListTest.java
* use dimension from VectorType
* close KnnVectorsReader
* skip per-column vector index file validation because lucene has different naming and manage its own validation
* add more comments about lucene file names
> fix TopDocsPostingList#advance and AnnTest

- src/java/org/apache/cassandra/db/compaction/CompactionAggregate.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- expose bucketMax
- adjust types in getLevel
> CNDB-6968 adjust UCSv2 to CNDB

- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- src/java/org/apache/cassandra/index/sai/utils/RangeIntersectionIterator.java
- test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
- test/unit/org/apache/cassandra/batchlog/BatchlogEndpointFilterTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentMergerTest.java
- test/unit/org/apache/cassandra/index/sai/plan/OperationTest.java
- BatchlogEndpointFilterTest
- rangeRestrictedTest
- SegmentFlushTest
- SegmentMergerTest
- OperationTest
- RangeIntersectionIteratorTest
> fix SAI test failures in vsearch branch

- conf/cassandra.yaml
Follow up to https://github.com/datastax/cassandra/pull/646
> CNDB-6974 Remove the table and keyspace thresholds from cassandra.yaml

- src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorMemtableIndex.java
- src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentTest.java
- test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java
- fixes VectorMemtableIndexTest
> Fix VectorMemtableIndex to handle max token and fix Segment#intersect

- CHANGES.txt
- conf/cassandra.yaml
- src/java/org/apache/cassandra/cql3/CQL3Type.java
- src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/AlterTypeStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
- src/java/org/apache/cassandra/cql3/statements/schema/CreateTypeStatement.java
- src/java/org/apache/cassandra/guardrails/Guardrails.java
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- test/unit/org/apache/cassandra/guardrails/GuardrailTester.java
- test/unit/org/apache/cassandra/guardrails/GuardrailVectorDimensionsTest.java
patch by Andrés de la Peña; reviewed by Brandon Williams and Maxwell Guo for CASSANDRA-18730
> VECTOR-76: Add back vector size guardrail

- src/java/org/apache/cassandra/index/sai/analyzer/README.md
- test/distributed/org/apache/cassandra/distributed/test/sai/AnalzyerDistributedTest.java
- test/long/index/sai/cql/AnalyzerQueryLongTest.java
Addressing https://github.com/datastax/cassandra/pull/721#discussion_r1312279574 and fixing another issue I noticed this week.
> Analyzer cleanup: add comments and fix docs

- src/java/org/apache/cassandra/index/sai/disk/v1/TermsIteratorMerger.java
- src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReader.java
- src/java/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingList.java
Optimizes MergePostingList.advance for the case where it is called repeatedly, as it is by RangeIntersectionIterator
> Vsearch 18

- src/java/org/apache/cassandra/db/compaction/unified/Controller.java
- src/java/org/apache/cassandra/db/compaction/unified/CostsCalculator.java
- test/distributed/org/apache/cassandra/distributed/test/UnifiedCompactionDensitiesTest.java
- test/unit/org/apache/cassandra/cache/ChunkCacheInterceptingTest.java
- test/unit/org/apache/cassandra/db/ImportTest.java
- test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/ShardedMultiWriterTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java
- test/unit/org/apache/cassandra/db/lifecycle/TrackerTest.java
Fix broken tests on vsearch branch
> Vector Search #34

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- src/java/org/apache/cassandra/index/IndexBuildDecider.java
- src/java/org/apache/cassandra/index/SecondaryIndexManager.java
- src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
- src/java/org/apache/cassandra/metrics/TableMetrics.java
- test/unit/org/apache/cassandra/index/sai/cql/TokenRangeReadTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentTest.java
* [CNDB-221: add IndexBuildDecider#isIndexQueryableWithoutInitialBuild](https://github.com/datastax/cassandra/commit/60a1761571170c3396575cd3e38efc149707b766)
* [CNDB-7079: fix SAI Segment#intersects to compare bound instead of token](https://github.com/datastax/cassandra/commit/4a303c5b6aebfebee537f1c63788c38460db18a6)
> Cndb 7553: merge DSE up to c0d7b22

- src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
- src/java/org/apache/cassandra/index/sai/utils/IndexFileUtils.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
- test/unit/org/apache/cassandra/index/sai/disk/io/BKDTempFilesDirectory.java
Fixes https://github.com/riptano/VECTOR-SEARCH/issues/35
> IndexDescriptor to open IndexOutputWriter in matching append mode to resume checksum if needed

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
Remove filterUnsuitable and relly solely on compactionFilter. The filter is now a bipredicate to support filtering sstables that are being compacted.
This will allow CNDB to getLevels for all sstables (not only for the non-compacting ones).
> CNDB-7264 simplify getLevels and getCompactionArenas signatures

- test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
With the addition of 1d3d9a7bc56154fb0cdf9fc5c326bee10d29da38, the semantics of analyzer text search changed. Before that, there was a bug where the analyzer's result would overwrite the expression's token, which meant that text search was only matching on the last token.
This PR assumes that the correct behavior is to AND together the tokens, as the test shows. Given that the previous behavior was broken and the new behavior is already in prod, I think it makes sense to continue in this direction.
> Add test for query analyzer behavior

- src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
> tracing log typo

- src/java/org/apache/cassandra/index/sai/plan/FilterTree.java
When we check if a row satisfies a query's predicates, there are some cases where we can exit a branch early. This logic was already present in some cases, but not all.
The primary benefit is possibly skipping byte buffer comparisons.
> Return earlier when possible in FilterTree#isSatisfiedBy

- src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
- test/unit/org/apache/cassandra/index/sai/SAITester.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorRecallOptimizedTest.java
Compresses low-d vectors less aggressively (which improves recall)
> Low dimension pq

- src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
Noticed the exception in the CI logs, not sure how to repro.
> Handle double close of PostingListRangeIterator

- src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
- src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CompactionVectorValues.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OrdinalsView.java
- src/java/org/apache/cassandra/index/sai/disk/vector/RemappingOnDiskGraphIndex.java
- src/java/org/apache/cassandra/index/sai/disk/vector/RemappingRamAwareVectorValues.java
- src/java/org/apache/cassandra/index/sai/disk/vector/RowIdsView.java
- src/java/org/apache/cassandra/index/sai/disk/vector/VectorPostings.java
- src/java/org/apache/cassandra/index/sai/disk/vector/VectorPostingsWriter.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/OnDiskOrdinalsMapTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/VectorCacheTest.java
fix of reverted https://github.com/datastax/cassandra/pull/762
> VECTOR-SEARCH-8: Add optimized version of OnDiskOrdinalsMap for common case

- test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
The `testBasicGeoSearch` test is failing. It looks like the main cause of error comes from early termination when searching the graph. Note that the `GeoDistanceAccuracyTest` also uses 85% as the benchmark.
> Expect 85% recall for geo distance

- src/java/org/apache/cassandra/db/filter/RowFilter.java
- src/java/org/apache/cassandra/index/sai/utils/GeoUtil.java
- test/unit/org/apache/cassandra/index/sai/cql/GeoDistanceInvalidQueryTest.java
Ensure the geo point is a valid lat/lon position.
> Verify GEO_DISTANCE search point is valid lat/lon pair

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
- src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
- src/java/org/apache/cassandra/index/sai/disk/vector/JVectorLuceneOnDiskGraph.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorBruteforceLocalTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
Fixes https://github.com/riptano/VECTOR-SEARCH/issues/50
> VECTOR-SEARCH 50: Accelerate brute-force search with compressed vectors

- src/java/org/apache/cassandra/db/commitlog/CommitLogDescriptor.java
- src/java/org/apache/cassandra/net/AcceptVersions.java
- src/java/org/apache/cassandra/net/HandshakeProtocol.java
- src/java/org/apache/cassandra/net/InboundConnectionInitiator.java
- src/java/org/apache/cassandra/net/MessagingService.java
- src/java/org/apache/cassandra/net/OutboundConnectionInitiator.java
- test/unit/org/apache/cassandra/net/ConnectionTest.java
- test/unit/org/apache/cassandra/net/HandshakeTest.java
Enforces OSS_30 protocol (PV 10) for DSE <-> CC connections by 
adjusting DSE -> CC and CC -> DSE handshake exchanges. 
The connections use 3-message handshakes to negotiate PV 10.
> CNDB-6317 Internode compatibility with DSE.

- src/java/org/apache/cassandra/index/sai/utils/RangeIntersectionIterator.java
Fixes https://github.com/riptano/VECTOR-SEARCH/issues/61
> VECTOR-SEARCH 61: Start with the most selective expression in the intersection loop

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
got a little excited simplifying the code here in the last commit
> add back ceiling call

- src/java/org/apache/cassandra/db/filter/RowFilter.java
- src/java/org/apache/cassandra/index/sai/utils/GeoUtil.java
- test/unit/org/apache/cassandra/index/sai/cql/GeoDistanceInvalidQueryTest.java
- test/unit/org/apache/cassandra/index/sai/cql/GeoDistanceRestrictionTest.java
We add support by injecting a second expression shifted by 360 degrees.
> Support geo distance over antimeridian

- src/java/org/apache/cassandra/schema/TableMetadataRefCache.java
Fix re-wrapping of TableMetadataRefCache fields in Collections.UnmodifiableMap, which was causing long reference chains where the underlying map was another instance of an UnmodifiableMap. Calls to `get` had to traverse all the way down the chain, and would eventually overflow the stack (and created a fair bit of extra garbage on the heap).
> CASSANDRA-19166: StackOverflowError on ALTER after many previous schema changes

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
- src/java/org/apache/cassandra/metrics/LinearFit.java
- src/java/org/apache/cassandra/metrics/PairedSlidingWindowReservoir.java
- src/java/org/apache/cassandra/metrics/QuickSlidingWindowReservoir.java
- test/unit/org/apache/cassandra/metrics/LinearFitTest.java
- test/unit/org/apache/cassandra/metrics/QuickSlidingWindowReservoirTest.java
- Revamp the estimation formula
- Encapsulate the shouldUseBruteForce logic in CostEstimate
- Add LinearFit to allow the runtime tuning to adjust the intercept independently from the slope
TODO: some manual testing
> Estimation rework

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OverqueryUtils.java
- test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java
https://github.com/riptano/VECTOR-SEARCH/issues/67
> Overquery uncompressed vectors including ones in memory

- src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
This commit is a copy of the fix from https://issues.apache.org/jira/browse/CASSANDRA-19032.
OS commit: https://github.com/apache/cassandra/commit/3928f2992f94aa2b4e56bee0f36a0bdb31087116
Copy of the JIRA ticket's description:
> The StorageAttachedIndexDDLTest.concurrentTruncateWithIndexBuilding has been showing flakiness in test runs and need investigating and fixing. Looking at the failure is seems that there is an edge condition where the index will fail to complete its build if a table truncate is triggered at the right moment.
> 
> We need to try and provoke this edge condition using injection and then see what can be done to fix the build failure.
>
> Provide truncate task for SAI

- src/java/org/apache/cassandra/index/sai/disk/vector/OverqueryUtils.java
I mangled this a bit in 893c1f4fe32cb1f2f74ba9843fec8d53869f45ae.  The idea is that most compressed vectors should be queried at 2x the uncompressed topk, and that got lost in the change with the result that we were returning an unnecessarily large topk for uncompressed.
> fix doing too much overquery against uncompressed vectors

- src/java/org/apache/cassandra/index/sai/QueryContext.java
- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
This reverts commit 73bead4e55f06632d404458908165eaca7091175.
> Revert "Fix SAIS#search to correctly count shadowed keys in termination logic (#927)"

- src/java/org/apache/cassandra/index/sai/plan/VectorTopKProcessor.java
If there is an exception in the `VectorTopKProcessor#filter` method, we do not close the source `partitions` object, which could result in a leak. I saw this in testing on #929 when I hit an NPE, and this fix prevent a resource leak. However, I don't see a good way to hit this exception with a normal test.
We could hit this for queries that timeout in the index search.
> VTKP#filter: close partitions iterator on failure

- src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
> Reduce cache distance to reduce heap usage

- src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
Fixes https://github.com/riptano/VECTOR-SEARCH/issues/86
See test for explanation.
> Fix fast ordinal mapping at segment boundary

- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
The wider the rows, the higher the cost of post-filtering. The coefficients were found empirically by comparing the time to run queries with post-filtering and varying the average number of cells per row and varying the average size of the row, on a table with 1M rows.
> Account for number of cells and row length in query cost estimation

- src/java/org/apache/cassandra/config/Config.java
Added toDebugString() method of Config.java
[Link to CNDB changes](https://github.com/riptano/cndb/pull/8589)
> CNDB-8477: HTTP endpoint that returns effective DB configuration

- src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java
This is a small followup to https://github.com/datastax/cassandra/pull/992. The latter let you pass a custom metrics instance to new chunk cache instance, but there is no point in not reusing the existing metrics implementation in practice, and the only reason we cannot right now is that everything in the definition of the metrics is hard-coded. This just make it so that the metrics prefix can be provided.
I'll not that on the C* side, there is 2 possible options for metrics, the codahale implementation and the micrometer one, but we seem to only use the micrometer one on cndb, so this PR only change that.
> Make the micrometer chunk cache metrics prefix configurable

- test/unit/org/apache/cassandra/index/sai/cql/GeoDistanceRestrictionTest.java
See comment in commit for details
> Fix GeoDistanceRestrictionTest#testGeoAndANNOnSameColumn test

- build.xml
- src/java/org/apache/cassandra/auth/AuthCache.java
- src/java/org/apache/cassandra/metrics/ChunkCacheMetrics.java
- src/java/org/apache/cassandra/metrics/CodahaleChunkCacheMetrics.java
- src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java
- test/unit/org/apache/cassandra/metrics/CodahaleChunkCacheMetricsTest.java
- test/unit/org/apache/cassandra/metrics/MicrometerChunkCacheMetricsTest.java
Related to [ #8722](https://github.com/riptano/cndb/issues/8722)
https://github.com/riptano/cndb/pull/8719
> VectorSearch branch -  upgrade Caffeine to 3.1.8

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/DiskBinarySearch.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OrdinalsView.java
- test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/OnDiskOrdinalsMapTest.java
- tools/stress/test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/DiskBinarySearchTest.java
optimization, reduce number of binary searches for ordinals
> Ordinalsview: foreach-like iteration

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/Mutation.java
- src/java/org/apache/cassandra/db/MutationVerbHandler.java
- src/java/org/apache/cassandra/db/ReadCommand.java
- src/java/org/apache/cassandra/db/ReadCommandVerbHandler.java
- src/java/org/apache/cassandra/net/Message.java
- src/java/org/apache/cassandra/net/SensorsCustomParams.java
- src/java/org/apache/cassandra/sensors/RequestSensors.java
- src/java/org/apache/cassandra/sensors/read/TrackingRowIterator.java
- test/unit/org/apache/cassandra/net/MessageTest.java
- test/unit/org/apache/cassandra/net/SensorsCustomParamsTest.java
- test/unit/org/apache/cassandra/sensors/RequestSensorsTest.java
- test/unit/org/apache/cassandra/sensors/SensorsReadTest.java
- test/unit/org/apache/cassandra/sensors/SensorsTestUtil.java
- test/unit/org/apache/cassandra/sensors/SensorsWriteTest.java
- test/unit/org/apache/cassandra/sensors/SensorsWriterTest.java
Addresses: https://github.com/riptano/cndb/issues/8463
First iteration to add UCU for writes, considering the first partition update only on a mutation
> CNDB-8463 Add WRITE_BYTES sensor to mutations

- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
- src/java/org/apache/cassandra/index/sai/disk/vector/OrdinalsView.java
- test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/OnDiskOrdinalsMapTest.java
fixes https://github.com/riptano/cndb/issues/8888
> optimized Bits object for RowIdMatchingOrdinalsView

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/index/sai/IndexContext.java
- src/java/org/apache/cassandra/service/reads/range/RangeCommandIterator.java
> CNDB-8909 enable disabling endpoint grouping

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/service/paxos/PaxosState.java
- **Configurable number of stripes in PaxosState.LOCKS**
- **TrieMemtable of system.paxos table sharded like any user table**
- **PaxosState::LOCKS stripe selection on basis of partition key and keyspace**
> lwt improvements

- src/java/org/apache/cassandra/db/filter/DataLimits.java
DSE CNDB doesn't know THRIFT_LIMIT(2) and SUPER_COLUMN_COUNTING_LIMIT(3) limits.
This makes the (de)serialization compatible with DSE CNDB.
Tested by DataLimitsTest.
> CNDB-9163 adjust data limit (de)serialization for DSE CNDB

- src/java/org/apache/cassandra/db/tries/CollectionMergeTrie.java
- src/java/org/apache/cassandra/db/tries/Direction.java
- src/java/org/apache/cassandra/db/tries/MemtableReadTrie.java
- src/java/org/apache/cassandra/db/tries/MemtableTrie.java
- src/java/org/apache/cassandra/db/tries/MergeTrie.java
- src/java/org/apache/cassandra/db/tries/SingletonTrie.java
- src/java/org/apache/cassandra/db/tries/SlicedTrie.java
- src/java/org/apache/cassandra/db/tries/Trie.java
- src/java/org/apache/cassandra/db/tries/Trie.md
- src/java/org/apache/cassandra/db/tries/TrieEntriesIterator.java
- src/java/org/apache/cassandra/db/tries/TrieValuesIterator.java
- test/microbench/org/apache/cassandra/test/microbench/tries/MemtableTrieReadBench.java
- test/unit/org/apache/cassandra/db/tries/CollectionMergeTrieTest.java
- test/unit/org/apache/cassandra/db/tries/MemtableTrieTestBase.java
- test/unit/org/apache/cassandra/db/tries/MergeTrieTest.java
- test/unit/org/apache/cassandra/db/tries/SlicedTrieTest.java
* STAR-1909: Reverse cursor and reverse iteration support for the trie interfaces
* Combined forward and reverse iteration code in MemtableReadTrie
(cherry picked from commit 909b5295b12539692d774452134c7b947fdfd1e9)
> Reverse cursor and iteration support (#1079)

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/db/marshal/VectorType.java
- test/unit/org/apache/cassandra/cql3/validation/entities/CQLVectorNotAllowedTest.java
fixes https://github.com/riptano/cndb/issues/9346
> Issue 9346: Add a flag to prevent users from using the VECTOR data type

- build.xml
- src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
- src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
- src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorDotProductWithLengthTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java
* cassandra.sai.write_jv3_format, default false
* cassandra.sai.ltm_construction, default true
> add flags to enable new on-disk features and larger-than-memory compaction path

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
- src/java/org/apache/cassandra/db/SystemKeyspace.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReaderBuilder.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReadsListener.java
- src/java/org/apache/cassandra/io/sstable/format/big/BigTableReader.java
- src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableReader.java
- src/java/org/apache/cassandra/metrics/RestorableMeter.java
- src/java/org/apache/cassandra/utils/BloomFilter.java
- src/java/org/apache/cassandra/utils/FilterFactory.java
- test/distributed/org/apache/cassandra/distributed/impl/IsolatedJmx.java
- test/unit/org/apache/cassandra/io/sstable/format/LazyBloomFilterTest.java
* include both CNDB-1823 and CNDB-4492
> CNDB-9511: port lazy bloom filter loading from DSE

- src/java/org/apache/cassandra/index/sai/plan/Plan.java
If org.apache.cassandra.index.sai.plan.Plan is set to TRACE,
it will log the initial plan, all candidate plans considered
and the final optimized plan.
> Add trace logging to Plan optimize method

- src/java/org/apache/cassandra/db/compaction/CompactionManager.java
- src/java/org/apache/cassandra/db/compaction/RepairFinishedCompactionTask.java
- src/java/org/apache/cassandra/db/repair/CassandraTableRepairManager.java
Adding some extra debugging for IR
> DSP-24288 Improved incremental repairs logging

- pylib/cqlshlib/tracing.py
It doesn't play nice with the left-padding but it's way way better than nothing
> special case tracing activity to allow newlines

- src/java/org/apache/cassandra/index/sai/disk/v1/bitpack/BlockPackedReader.java
- src/java/org/apache/cassandra/index/sai/disk/v1/bitpack/MonotonicBlockPackedReader.java
- src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDPostingsIndex.java
- src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/TraversingBKDReader.java
- src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/OnDiskVectors.java
- src/java/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsReader.java
- src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
- src/java/org/apache/cassandra/index/sai/disk/vector/NodeScoreToScoredRowIdIterator.java
- src/java/org/apache/cassandra/io/sstable/compaction/SortedStringTableCursor.java
- src/java/org/apache/cassandra/io/sstable/format/big/BigTableScanner.java
The result of going through all creators of `RandomAccessReader` in the current main and checking for potential unclosed readers.
> CNDB-10115: Check closing of RandomAccessReaders

- test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
Adds a unit test for #1189. The test fails without #1189.
A user can hit the underlying bug if they meet two conditions:
1. They have enough rows for PQ, 1024.
2. They delete at least one row.
These conditions are only known to be sufficient, but might not be necessary.
The underlying motivation is in the `rowsPerKey` logic where we call an sstable's `getMeanRowsPerPartition`. This method relies on a histogram internally, and can produce a result of 0 when a row is tombstoned in a later sstable. 
https://github.com/datastax/cassandra/blob/2cbdaf531a95b00cc220f3fce9e0e6babc681457/src/java/org/apache/cassandra/db/ColumnFamilyStore.java#L3060-L3071
In looking at that method, I wonder if perhaps we could use a `Math.round` to improve the accuracy of the value produced by …
> CNDB-10125: Add unit test to verify compaction bug fix

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
- src/java/org/apache/cassandra/io/storage/StorageProvider.java
https://github.com/riptano/cndb/pull/9450
> CNDB-9164: add StorageProvider#invalidateFileSystemCache(Descriptor) to clear cache when sstable GloabalTidy completes

- src/java/org/apache/cassandra/db/memtable/ShardBoundaries.java
- src/java/org/apache/cassandra/dht/AbstractBounds.java
- src/java/org/apache/cassandra/index/sai/IndexContext.java
- src/java/org/apache/cassandra/index/sai/memory/FilteringKeyRangeIterator.java
- src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
- src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
- src/java/org/apache/cassandra/index/sai/utils/LazyRangeIterator.java
- src/java/org/apache/cassandra/index/sai/utils/RangeAntiJoinIterator.java
- src/java/org/apache/cassandra/index/sai/utils/RangeIntersectionIterator.java
- src/java/org/apache/cassandra/index/sai/utils/RangeIterator.java
- test/unit/org/apache/cassandra/index/sai/memory/TrieMemoryIndexTest.java
- test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTest.java
- test/unit/org/apache/cassandra/index/sai/utils/RangeIntersectionIteratorTest.java
- test/unit/org/apache/cassandra/index/sai/utils/RangeUnionIteratorTest.java
- **Merge postings lazily in TrieMemoryIndex#rangeMatch**
- **Create SAI memory index shard iterators lazily**
> Lazy TrieMemoryIndex range scans

- src/java/org/apache/cassandra/io/compress/CompressedSequentialWriter.java
- src/java/org/apache/cassandra/io/storage/StorageProvider.java
build: https://jenkins-stargazer.aws.dsinternal.org/view/cc-builds/job/ds-cassandra-publish-j11/
> CNDB-10484: add Storage#writeTimeReadFileChannelFor for read channels opened during scrub

- src/java/org/apache/cassandra/index/sai/plan/Plan.java
- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java
Fixes https://github.com/riptano/cndb/issues/10507
> Make sure we never pass limit=0 to estimateAnnNodesVisited

- src/java/org/apache/cassandra/index/sai/plan/Operation.java
- test/unit/org/apache/cassandra/index/sai/cql/MapEntriesIndexTest.java
NEQ is unhandled in this switch, leading to a NPE under certain query conditions where an Expression is created and no operation is set for this expression.
> CNDB-10577: Handle NEQ Map comparison expressions when analyzing a group of SAI expressions

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/nodes/Nodes.java
- src/java/org/apache/cassandra/nodes/NodesPersistence.java
- src/java/org/apache/cassandra/schema/KeyspaceMetadata.java
Allow custom implementation of nodes persistence
Add methods to force persist information about all peers and local
> CNDB-10656

- src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java
- test/unit/org/apache/cassandra/metrics/MicrometerChunkCacheMetricsTest.java
Modifications:
- count evictions and not bytes
- add metrics by removal cause
> CNDB-11048 ChunkCache eviction metrics improvements

- test/unit/org/apache/cassandra/index/sai/functional/IndexBuildDeciderTest.java
`IndexBuildDeciderTest` sets a custom index build decider by setting the system property `CUSTOM_INDEX_BUILD_DECIDER` in its `init` method, marked with `@BeforeClass`. That system property is read when initializing `IndexBuildDecider.instance`. 
In CC the call to `IndexBuildDeciderTest.init` happened before `IndexBuildDecider.instance` was initialized, so the instance was set as desired by the test. 
However, in 5.0 `CQLTester.setUpClass`, which runs before `IndexBuildDeciderTest.init`, is doing some initialization that sets `IndexBuildDecider.instance` before the `CUSTOM_INDEX_BUILD_DECIDER` system property is changed. As a result, the test doesn't manage to set the custom decider.
The fix is simply making sure that `IndexBuildDeciderTest.init` runs before `CQLTester.setUpClass`, so the …
> CNDB-11154 main-5.0 : Fix IndexBuildDeciderTest

- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
- test/unit/org/apache/cassandra/index/sai/plan/OperationTest.java
Add missing parts of [CASSANDRA-18940](https://issues.apache.org/jira/browse/CASSANDRA-18940).
> CNDB-11186 main-5.0: Fix QueryMetricsTest.testSameIndexNameAcrossKeyspaces

- test/unit/org/apache/cassandra/index/sai/metrics/IndexMetricsTest.java
[CASSANDRA-19326](https://issues.apache.org/jira/browse/CASSANDRA-19326) has swithced `memtable_allocation_type` from `offheap_objects` to `heap_buffers` in `test/conf/cassandra.yaml`. As a result, the test doesn't see any off-heap memory usage in the `IndexMetrics.MemtableOffHeapIndexBytes` metric. 
I'm updating the test to consider what types of buffers we are using when doing the check. That way this should work independently of the test config.
> CNDB-11231 main-5.0: Fix IndexMetricsTest.testMetricsThroughWriteLifecycle

- test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
Fixes: https://github.com/riptano/cndb/issues/11345
> CNDB-11345: mock CFS#makeUCSEnvironment in ControllerTest

- test/unit/org/apache/cassandra/index/sai/cql/NotOnTruncatedKeyTest.java
Replaces duplicated code with parameterization. Tests only two index versions, which cover both planning path.
This is post work on merged fix for https://github.com/riptano/cndb/issues/11210
> CNDB-11210 simplify test of Non-eq on truncated types

- test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
The rejection of terms depends on `CassandraRelevantProperties.VALIDATE_MAX_TERM_SIZE_AT_COORDINATOR`. The test should check both the enabled and disabled scenarios.
> CNDB-11541 main: Fix testAnalyzerThatProducesTooManyBytesIsRejectedAtWriteTime

- test/unit/org/apache/cassandra/index/sai/cql/VectorCompactionTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorHybridSearchTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorRangeSearchTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTracingTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
> CNDB-11518 main: Split o.a.c.index.sai.cql.VectorTypeTest to prevent timeouts

- test/unit/org/apache/cassandra/db/compaction/CompactionControllerTest.java
> CNDB-11499: Fix incorrect thread names in CompactionControllerTest

- test/unit/org/apache/cassandra/index/sai/disk/vector/VectorCompressionTest.java
For now, improve assertions to be a bit more informative and increase the timeout of the waiting for the index build.
> CNDB-11574 main: Fix VectorCompressionTest.testBert

- src/java/org/apache/cassandra/index/sai/plan/Plan.java
Also includes minor code lines reorder to improve understanding, tries to improve a comment describing access pattern, and fixes a typo.
I tried to do a first improvement to a comment on access patterns, but might moved into wrong direction.
I wasn't able to come up with a test, which will demonstrate the bug fix.
> Fix minor bug in intersection's propagate access

- src/java/org/apache/cassandra/cql3/QueryProcessor.java
- src/java/org/apache/cassandra/transport/Message.java
- src/java/org/apache/cassandra/transport/messages/BatchMessage.java
- src/java/org/apache/cassandra/transport/messages/ExecuteMessage.java
- src/java/org/apache/cassandra/transport/messages/QueryMessage.java
Too coarse grained traces
This PR adds a couple of new traces to give us better insight what does
the system do during query handling
> CNDB-12051: addtional tracing messages about query execution

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
Expose some methods neeed for https://github.com/riptano/cndb/issues/12128
> CNDB-12128 Expose to CNDB some methods around ExpirationTask

- src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
Part of https://github.com/riptano/cndb/issues/12139
Moves constant shard count outside looping shards to reduce confusion.
> CNDB-12139 minor refactor row count estimation code

- src/java/org/apache/cassandra/io/util/RandomAccessReader.java
The specialized code to read `float[]`, `long[]` and `int[]` in `RandomAccessReader` only optimizes the memory-mapped aligned case and does several steps and allocations that can be eliminated.
Simplify the code to convert the prepared buffer to the needed type, which is at worst as bad as the earlier fast path but works in all cases, and to only do one pass through the loop when the buffer needs to advance.
> CNDB-12292: Improve typed reads in RandomAccessReader

- src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
- src/java/org/apache/cassandra/db/marshal/AbstractType.java
- src/java/org/apache/cassandra/db/marshal/CollectionType.java
- test/unit/org/apache/cassandra/cql3/validation/operations/AlterTest.java
Backport of CASSANDRA-18760 to CC
> CNDB-9233: Backport CASSANDRA-18760

- src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
- src/java/org/apache/cassandra/db/marshal/AbstractType.java
- src/java/org/apache/cassandra/db/marshal/CollectionType.java
- test/unit/org/apache/cassandra/cql3/validation/operations/AlterTest.java
This reverts commit 486479e8ebef597f53a9f3decba133820a21c60b.
...
...
> Revert "CNDB-9233: Backport CASSANDRA-18760 (#1293)"

- src/java/org/apache/cassandra/index/sai/disk/v5/V5VectorPostingsWriter.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorCompactionTest.java
https://github.com/riptano/cndb/issues/13027
> Fix V5VectorPostingsWriter to handle omitted ordinals correctly

- src/java/org/apache/cassandra/db/Columns.java
#12598
adds ks/table to error message
> CNDB-12598: mention ks/table for unknown columns during deserialization

- src/java/org/apache/cassandra/db/compaction/ShardTracker.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
> CNDB-12991: getMaxOverlapsMap does not correctly deal with multiple disks

- src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
> Fix memtable memory tracking problem for CNDB-12290

- CHANGES.txt
- conf/cassandra.yaml
- src/java/org/apache/cassandra/auth/AuthConfig.java
- src/java/org/apache/cassandra/auth/PasswordAuthenticator.java
- src/java/org/apache/cassandra/config/Config.java
- src/java/org/apache/cassandra/config/ParameterizedClass.java
- src/java/org/apache/cassandra/utils/FBUtilities.java
- test/unit/org/apache/cassandra/audit/AuditLoggerAuthTest.java
- test/unit/org/apache/cassandra/config/ParameterizedClassExample.java
- test/unit/org/apache/cassandra/config/ParameterizedClassTest.java
- test/unit/org/apache/cassandra/transport/CQLUserAuditTest.java
PR #1578 caused failures elsewhere and needed to be reverted.
This adds back changes after fixing those failures.
This reverts commit b6930b523962bb4a1a2ecf1a3c0e552b7a66a531 adding back #1578
> Adds back "HCD-82 Enables auth* classes configuration"

- src/java/org/apache/cassandra/db/ColumnFamilyStore.java
- src/java/org/apache/cassandra/db/compaction/AbstractCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
- src/java/org/apache/cassandra/db/compaction/CompactionManager.java
- src/java/org/apache/cassandra/db/compaction/CompactionPick.java
- src/java/org/apache/cassandra/db/compaction/CompactionSSTable.java
- src/java/org/apache/cassandra/db/compaction/CompactionTask.java
- src/java/org/apache/cassandra/db/compaction/CompositeCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/ExpirationTask.java
- src/java/org/apache/cassandra/db/compaction/LeveledGenerations.java
- src/java/org/apache/cassandra/db/compaction/LeveledManifest.java
- src/java/org/apache/cassandra/db/compaction/RepairFinishedCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/SingleSSTableLCSTask.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- src/java/org/apache/cassandra/db/compaction/unified/Controller.java
- src/java/org/apache/cassandra/db/compaction/unified/Environment.java
- src/java/org/apache/cassandra/db/compaction/unified/RealEnvironment.java
- src/java/org/apache/cassandra/db/compaction/unified/UnifiedCompactionTask.java
- src/java/org/apache/cassandra/db/compaction/writers/MajorLeveledCompactionWriter.java
- test/long/org/apache/cassandra/db/compaction/LongLeveledCompactionStrategyTest.java
- test/microbench/org/apache/cassandra/test/microbench/CachingBenchTest.java
- test/microbench/org/apache/cassandra/test/microbench/GcCompactionBenchTest.java
- test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionContainerPendingRepairTest.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyGetSelectionTest.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
CNDB-12599
Exposes the space requirements of compaction picks and compaction tasks for CNDB's compaction space management.
This PR it to be committed with https://github.com/riptano/cndb/pull/12610
> CNDB-12599: Expose compactions' space overhead for CNDB

- src/java/org/apache/cassandra/transport/Dispatcher.java
Dispatcher needs to possibly catch and handle exceptions from Message.execute
> CNDB 13119:  fix exception handling in Dispatcher

- src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
- test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
> CC5 Fix VectorInvalidQueryTest align with main branch for VECTOR_INDEXES_UNSUPPORTED_OP_MESSAGE

- CHANGES.txt
- src/java/org/apache/cassandra/auth/AuthConfig.java
- src/java/org/apache/cassandra/config/ParameterizedClass.java
- test/unit/org/apache/cassandra/config/ParameterizedClassExample.java
- test/unit/org/apache/cassandra/config/ParameterizedClassTest.java
Work done in HCD-82 was further refined in CASSANDRA-20368 and CASSANDRA-20450.
This backports C* changes in order to minimize the diff in future backports.
> HCD-122 Backports CASSANDRA-20368 and CASSANDRA-20450

- src/java/org/apache/cassandra/net/InboundSink.java
...
Follow up on CNDB-12620. I think we need to handle IndexBuildInProgress exception in InboundSink, same as IndexNotAvailableException.
...
> CNDB-13560: Handle IndexBuildInProgress exception in InboundSink

- src/java/org/apache/cassandra/cache/ChunkCache.java
- src/java/org/apache/cassandra/io/util/ChannelProxy.java
- src/java/org/apache/cassandra/io/util/SimpleChunkReader.java
This is only a POC, it only adds logs and introduces a little better errors handling
> CNDB-13591: Error while loading chunkcache: java.lang.IllegalArgumentException: Negative position

- test/distributed/org/apache/cassandra/distributed/test/metrics/CoordinatorReadLatencyMetricTest.java
With the rebase of CC on C* 5.0.2, there is a new test CoordinatorReadLatencyMetricTest and CoordinatorReadLatencyMetricTest.internalPagingWithAggregateTest is failing.
Uses paging in bytes instead of paging in rows in internalPagingWithAggregateTest.
> CNDB-13118 Fix CoordinatorReadLatencyMetricTest changing internalPagingWIthAggregateTest to use paging in bytes for CC.

- test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
This is a follow up test for https://github.com/riptano/cndb/issues/13696.
The fix was already merged, but this confirms that without the fix, collections are affected by the ~NPE~ NoSuchElementException bug.
> CNDB-13696: Add BM25 hybrid search test on collections

- build.xml
Relates to https://github.com/riptano/cndb/issues/13766
Brings in several improvements.
CNDB PR: https://github.com/riptano/cndb/pull/13789
> CNDB-13766: Upgrade to jvector 4.0.0-beta.4

- test/unit/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzerTest.java
Didn't create an issue as this is just a new test.
We implicitly rely on this and
are exposing this as a feature
to our end users, so we want
to confirm that the stop words
are the expected stop words.
> SAI: test that default stop words are the ENGLISH_STOP_WORDS_SET

- src/java/org/apache/cassandra/cql3/functions/AbstractFunction.java
- test/unit/org/apache/cassandra/cql3/validation/operations/AggregationTest.java
> CNDB-13902: Fix incorrect results of min / max in-built functions on clustering columns in descending order - port CASSANDRA-20295

- src/java/org/apache/cassandra/index/sai/IndexContext.java
- test/unit/org/apache/cassandra/index/sai/view/IndexViewManagerTest.java
Fixes: https://github.com/riptano/cndb/issues/14160
The loop is supposed to loop until the deadline, not after the deadline.
The test fails without the change.
> CNDB-14160: Fix IndexContext#getReferencedView

- src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
- test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
- test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTestBase.java
https://github.com/riptano/cndb/issues/14153
Cherry-picks the commits from https://github.com/datastax/cassandra/pull/1751
> CNDB-14153: Fix SAI updates (non-null solution)

- src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
- src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
- src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
- test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
- test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java
Reverts datastax/cassandra#1754
> Revert "CNDB-14614: abort compaction task or index build if index is unloaded after tenant unassignment"

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/RangedAggregatesTest.java
CNDB: https://github.com/riptano/cndb/pull/14203
> cndb-14201: allow UCS#getNextBackgroundTasks to config custom compaction observer for composite compaction

- build.xml
Fixes https://github.com/riptano/cndb/issues/14242
Commits: https://github.com/datastax/jvector/compare/4.0.0-beta.4...4.0.0-beta.5
CNDB test pr https://github.com/riptano/cndb/pull/14243
> CNDB-14242: Upgrade jvector to 4.0.0-beta.5

- src/java/org/apache/cassandra/cql3/Operator.java
- src/java/org/apache/cassandra/cql3/conditions/ColumnCondition.java
- src/java/org/apache/cassandra/cql3/conditions/ColumnConditions.java
- src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
- src/java/org/apache/cassandra/db/filter/RowFilter.java
- src/java/org/apache/cassandra/index/Index.java
- src/java/org/apache/cassandra/index/IndexRegistry.java
- src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
- src/java/org/apache/cassandra/index/sai/VECTOR.md
- src/java/org/apache/cassandra/index/sai/plan/Operation.java
- src/java/org/apache/cassandra/index/sai/utils/PrimaryKeyWithSortKey.java
- test/unit/org/apache/cassandra/cql3/OperatorTest.java
- test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
> CNDB-14419: Port CNDB-13075 d0701b316 and 67907507 to main-5.0 

- src/java/org/apache/cassandra/io/util/MmappedRegions.java
- test/unit/org/apache/cassandra/io/sstable/SSTableReaderTest.java
Fix MAX_SEGMENT_SIZE < chunkSize in MmappedRegions::updateState
> HCD-151: Port CASSANDRA-20636 (5.0)

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
- test/unit/org/apache/cassandra/db/compaction/unified/RangedAggregatesTest.java
CNDB: https://github.com/riptano/cndb/pull/14203
> cndb-14201: allow UCS#getNextBackgroundTasks to config custom compaction observer for composite compaction (#1767)

- test/unit/org/apache/cassandra/io/sstable/ReducingKeyIteratorTest.java
This test doesn't disable compaction and doesn't retain a reference to the sstables, so it can run with an unexpected amount of sstables and also race with the removal of the sstables backing the ReducingKeyIterator, which causes a variety of memory safety issues. This test fails approximately 1/30 times when multiplexed in CI.
This fixes several issues. First, it disables compaction after the schema is created. Second, it fulfills the contract of ReducingKeyIteratorTest by taking references to the sstables, which should be superfluous with compactions disabled, but I prefer testing the contract. Third, it verifies that nothing is changing the number of sstables in the system (which would have caught the previous compaction misconfiguration).
> CNDB-13563: Fix ReducingKeyIteratorTest#testTotalAndReadBytesManySSTables (#1762)

- src/java/org/apache/cassandra/db/compaction/SharedCompactionObserver.java
- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/SharedCompactionObserverTest.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
UCS didn't clear pending compaction tasks in
`BackgroundCompactions#compactions` for parallel background compaction
Register both UCS and composite compaction observer for parallel compaction task: both UCS and CNDB are notified
> CNDB-14237-main-cherry-pick: register composite compaction observer as additional obverser on top of UCS (#1783)

- src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
- test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
BM25 queries don't work on indexes on non-regular columns.
Until we have a way to support them, this PR simply forbids BM25 queries on non-regular columns.
The creation of analyzed indexes in those columns is still allowed because they can be successfully queried with regular expression filters using equality and match operators.
> CNDB-14348: Forbid BM25 queries on non-regular columns (#1793)

- src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
- test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
This is to fix a race in UCS:
1. sstable-1 is compacting
2. 2nd compaction thread fetches live sstable which includes sstable-1
3. sstable-1 is now compacted, no longer as compacting in Tracker
4. 2nd compaction thread continues: UCS#getCompactionArenas fetches list of compacting sstables which doesn't include sstable-1
5. sstable-1 is now included for next compaction but failed to create txn because it's already compacted
use non-compacting sstables instead of live sstables, so there won't be race
> CNDB-14353: fetch non-compacting sstables instead of live sstables for UCS (#1861)

- src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
- src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java
- src/java/org/apache/cassandra/index/sai/plan/QueryController.java
- src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
- src/java/org/apache/cassandra/utils/InsertionOrderedNavigableSet.java
- test/unit/org/apache/cassandra/index/sai/cql/LargePartitionsTest.java
- test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java
- test/unit/org/apache/cassandra/utils/InsertionOrderedNavigableSetTest.java
> CNDB-11666: Batch clusterings into single SAI partition post-filtering reads (#1883)

- src/java/org/apache/cassandra/service/StartupChecks.java
- test/unit/org/apache/cassandra/service/StartupChecksTest.java
Prevent users from anti-patterns and known bad/costly practices.
Warn when not using murmur3 partitioner
Warn on tables not using UCS
Prevent use of transient replication
Warn on use of JBOD (multiple data_dir)
Warn on use of Materialised Views
Warn on use of Legacy 2i and SASI
Warn on use of dropping compact storage
Warn on an increase in limit tombstones per read
Warn on an increase in limit batch size
Warn on an increase in limit num_tokens to 16
Warn when bti sstable format type is not used
> HCD-111 Usability Requirements and Checks

- conf/cassandra.yaml
- src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
- src/java/org/apache/cassandra/service/StartupChecks.java
- test/conf/cassandra-murmur.yaml
- test/conf/cassandra-seeds.yaml
- test/conf/cassandra.yaml
- test/unit/org/apache/cassandra/service/StartupChecksTest.java
This reverts commit 7940e9c59a094bfd104bf052dafe298c8aa628d1.
> CNDB-15041: Revert "HCD-179 Guardrail defaults for on-prem"

- test/unit/org/apache/cassandra/io/sstable/metadata/MetadataSerializerTest.java
CC5 adjustments made to call serializeWithEncryption and deserializeWithEncryption; use of current sstable format is already present.
The test serializes with the current SSTableFormat Type but hardcoded the type to BTI on the descriptor. Test failure can be reproduced by `ant test-bigtable -Dtest.name=MetadataSerializerTest`
Now, the descriptor is also initialized with the current type.
> CNDB-14983: Fix MetadataSerializerTest#testSerializationWithEncryption under bigtable test profile. (#1930)

- src/java/org/apache/cassandra/config/GuardrailsOptions.java
- test/unit/org/apache/cassandra/db/guardrails/GuardrailSecondaryIndexesPerTableTest.java
- test/unit/org/apache/cassandra/db/guardrails/GuardrailsConfigDefaultsTest.java
- test/unit/org/apache/cassandra/db/guardrails/ThresholdTester.java
Invalid guardrails can be caught sooner with a test
Tests that all guardrail profiles are valid
> CNDB-15363: add test to verify guardrails profiles defaults

- src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java
https://github.com/riptano/cndb/issues/15477
Port CNDB-15423 aae5c62 to main-5.0
Fixes: https://github.com/riptano/cndb/issues/15423 CNDB test: https://github.com/riptano/cndb/pull/15427
This PR fixes a subtle bug exposed by the
`FeaturesVersionSupportCATest.testANN` test, as well as other similarly named `FeaturesVersionSupport*Test` tests. The central issue is whether to create the `queryVector` object. The currently logic does so only when `useSyntheticScore()` is false. However, if a peer has it set to false and this node has it on true, we'll end up with an easily avoided NPE. I propose instead that we lazily load the vector when it is needed. This removes an unnecessary switch as well as removing an unnecessary ordering requirement on upgrades.
```
java.lang.NullPointerException
at …
```
> CNDB -15477: CNDB-15423: Make TopKProcessor lazily load queryVector (#2007)
