conf/cassandra.yaml
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/cql3/statements/BatchStatement.java
src/java/org/apache/cassandra/cql3/statements/ModificationStatement.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/ConsistencyLevel.java
src/java/org/apache/cassandra/guardrails/Guardrail.java
src/java/org/apache/cassandra/guardrails/Guardrails.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
src/java/org/apache/cassandra/schema/SchemaConstants.java
src/java/org/apache/cassandra/service/ClientState.java
src/java/org/apache/cassandra/service/StorageProxy.java
test/unit/org/apache/cassandra/cql3/ViewSchemaTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailConsistencyTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailTester.java
test/unit/org/apache/cassandra/guardrails/TableGuardrailsTest.java
test/unit/org/apache/cassandra/index/internal/CassandraIndexTest.java

Tests: https://app.circleci.com/pipelines/github/nastra/cassandra/63/workflows/48e511bf-dcf5-484c-ad54-d304e51f2ebb

CDB-22: Introduce disallowed write consistencies guardrail

---

conf/cassandra-dbaas-light.yaml
conf/cassandra.yaml
src/java/org/apache/cassandra/concurrent/Stage.java
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/service/paxos/PaxosState.java
src/java/org/apache/cassandra/transport/Message.java

* Properly disabling early open.
* Using either direct execution (where possible) or single threaded executor on the read/write path.
Patch by Sergio Bossa.
Reviewed by Stefania Alborghetti.

CDB-44 Improved performance of the dbaas-light profile by:

---

src/java/org/apache/cassandra/index/sai/ColumnContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/disk/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/plan/FilterTree.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/AbstractIndexQueryTest.java
test/unit/org/apache/cassandra/index/sai/cql/CompositePartitionKeyIndexTest.java
test/unit/org/apache/cassandra/index/sai/cql/DataModel.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/cql/SingleNodeQueryTest.java
test/unit/org/apache/cassandra/index/sai/plan/OperationTest.java

All of the machinery was already present, changes were:
* Remove validation that prevented the creation of indexes.
* Add logic to allow extraction of partition key components if the key type is compound.

DSP-20634 Enabled composite partition key indexing for SAI.

---

src/java/org/apache/cassandra/db/compaction/CompactionManager.java
src/java/org/apache/cassandra/db/compaction/CompactionTask.java

+ throttle RateLimiter acquire in compaction operations
Co-authored-by: nitsanw <nitsanw@yahoo.com>

STAR-374: Avoid redundant calls to RateLimiter in CompactionTask

---

pylib/cqlshlib/test/test_cqlsh_output.py

STAR-489: Add missing expected 'memtable' param of column family in cqlsh tests (ds-trunk)

---

src/java/org/apache/cassandra/cql3/statements/PropertyDefinitions.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
test/unit/org/apache/cassandra/cql3/statements/CreateTableStatementTest.java

Create table command overrides a recognized unsupported DSE
compaction strategy (MemoryOnlyStrategy and TieredCompactionStrategy)
with default Compaction Strategy (SizeTiered atm).
The table is created successfully, applied == true.
Additional warning is returned to the caller.

STAR-451 override unsupported DSE compaction strategies

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
test/unit/org/apache/cassandra/cql3/statements/CreateTableStatementCompactionStrategiesTest.java
test/unit/org/apache/cassandra/cql3/statements/CreateTableStatementNodeSyncTest.java

The table creation command ends successfully (applied == true).
`nodesync` table option is ignored, additional warning is
returned to the caller.

STAR-454 ignore 'nodesync' table option

---

src/antlr/Lexer.g
src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/statements/schema/CreateKeyspaceStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/KeyspaceAttributes.java
src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
test/unit/org/apache/cassandra/cql3/statements/CreateKeyspaceStatementTest.java
test/unit/org/apache/cassandra/cql3/statements/CreateTableStatementGraphTest.java

The DSE-specific graph properties are added to CQL syntax.
Once detected, a hint about them is provided to the node
via table properties: dse_vertex_label_property and
dse_edge_label_property.
The node returns a warning to the caller, ignores the
properties and creates the table.

STAR-455 ignore VERTEX|EDGE LABEL in CREATE TABLE statement

---

src/java/org/apache/cassandra/io/sstable/metadata/StatsMetadata.java
test/unit/org/apache/cassandra/io/sstable/metadata/MetadataSerializerTest.java

The problem was that at some point we refactored the code a bit and one detail got missed - for the min and max clustering bounds we should store clustering components until first null component is encountered.

STAR-539: Fix storing stats metadata for big table format (ds-trunk)

---

src/java/org/apache/cassandra/cql3/UntypedResultSet.java
src/java/org/apache/cassandra/cql3/statements/PropertyDefinitions.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/AlterViewStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateViewStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/TableAttributes.java
src/java/org/apache/cassandra/db/ConsistencyLevel.java
src/java/org/apache/cassandra/db/MultiRangeReadCommand.java
src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
src/java/org/apache/cassandra/db/ReadQuery.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
src/java/org/apache/cassandra/db/VirtualTableReadQuery.java
src/java/org/apache/cassandra/db/VirtualTableSinglePartitionReadQuery.java
src/java/org/apache/cassandra/guardrails/Guardrail.java
src/java/org/apache/cassandra/guardrails/Guardrails.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/service/pager/AbstractQueryPager.java
src/java/org/apache/cassandra/service/pager/AggregationQueryPager.java
src/java/org/apache/cassandra/service/pager/MultiPartitionPager.java
src/java/org/apache/cassandra/service/pager/QueryPager.java
test/unit/org/apache/cassandra/guardrails/GuardrailsOnTableTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailsTest.java

These changes mainly come from  [DB-4909](https://datastax.jira.com/browse/DB-4909) [DSE PR 19467](https://github.com/riptano/bdp/pull/19467/files)
Some pre-reqs come from [DB-3795](https://datastax.jira.com/browse/DB-3795) [DSE PR 16648](https://github.com/riptano/bdp/pull/16648/files)

STAR-511 Port guardrails: ignore table properties

---

conf/cassandra-env.sh
conf/cassandra.yaml
conf/jvm11-server.options
conf/jvm8-server.options
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java

Here are three settings from the DSE cassandra.yaml that have been shown to improve performance for running the 1TB density test and the write-throughput test.

STAR-674: Apply DSE cassandra.yaml settings to improve performance

---

src/java/org/apache/cassandra/io/sstable/BloomFilterTracker.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableReader.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableReader.java
src/java/org/apache/cassandra/metrics/TableMetrics.java

This is a port of CASSANDRA-15384 that was partially ported in the
last oss -> dse-db port. Only the corresponding dtest was ported
and now it constantly fails without the actual fix in dse-db code.
Patch by Jaroslaw Grabowski; reviewed by brandonwilliams and paulo for
CASSANDRA-15384
Before this change the bloom filter false positive rate was calculated
without true negatives which resulted in high rates. In an extreme case,
where all queries return no data, the false positive rate could go up to
1.0.
This change includes true negatives in [recent] bloom filter false ratio.

STAR-725 Bloom false positive rate includes true negatives

---

conf/cassandra.yaml
src/java/org/apache/cassandra/config/Config.java

DSE already has this option enabled by default since it can help performance when the host machine hasn't configure the VM dirty settings properly. I saw no improvement when running tests with this patch, and crucially, no performance regressions either:
- https://fallout.sjc.dsinternal.org/performance/matt.fleming@datastax.com/report/becb9cd1-6c46-47b9-aa11-61e75d65b470
- https://fallout.sjc.dsinternal.org/performance/matt.fleming@datastax.com/report/6ee5821a-0b1f-4e4e-8fd8-25124aab43ff

STAR-674: Enable trickle_fsync option by default

---

bin/cqlsh.py

DSE carries two copies of cqlsh.py and my previous patch applied the changes from dse-bin/bin/cqlsh.py.
These changes are from `resources/cassanda/bin/cqlsh.py`.

STAR-431: Add option to prevent any file-I/O from cqlsh (apply from correct version of cqlsh.py this time)

---

bin/cqlsh.py

We can disable saving of the history either via command-line parameter
--disable-history, or by setting disabled = True in the history section of the
cqlshrc. Both options will read existing history, and just won't save new commands.
Co-authored-by: Alex Ott alexott@gmail.com

STAR-429 cqlsh disable cqlsh_history logging

---

src/java/org/apache/cassandra/schema/SchemaKeyspace.java

Synchronize schema pull handling with applying new schema changes
There's a race condition around pulling schema changes, that can occur
in case the schema changes push/propagation mechanism is not
immediately effective (e.g. because of network delay, or because of
the pulling node being down, etc.).
If schema changes happen on node 1, these changes do not reach node 2
immediately through the SCHEMA.PUSH mechanism, and are first
recognized during gossiping, the corresponding SCHEMA.PULL request
from node 2 can catch the node 1 schema in the middle of it being
modified by another schema change request. This can easily lead to
problems (e.g. if a new table is being added, and the node 2 request
reads the changes that need to be applied to system_schema.tables, but
not the ones that need to …

STAR-570 Synchronize schema pull handling

---

src/java/org/apache/cassandra/cql3/statements/schema/AlterViewStatement.java

Improve error message when altering an MV with default ttl > 0.
Co-authored-by: Brandon Williams, driftx@gmail.com
Port of https://github.com/riptano/bdp/pull/15478

STAR-572 Improve error message when altering MV

---

src/java/org/apache/cassandra/index/internal/CassandraIndex.java
test/unit/org/apache/cassandra/cql3/validation/entities/SecondaryIndexTest.java

... of 2i on collections
Co-authored-by: Andrés de la Peña andres.de_la_pena_garcia@datastax.com

STAR-565  Use the indexed item type as backing table key validator

---

CHANGES.txt
src/java/org/apache/cassandra/cql3/statements/ModificationStatement.java

If a user has only MODIFY permission on a table and there is a 
materialized view built on the same table an insert will fail 
with the following error:
Unauthorized: Error from server: code=2100 [Unauthorized]
Only base MODIFY permission is required to update base with MV

STAR-564 Check only MODIFY on base when updating table with MV

---

bin/cqlsh.py

Allows overriding the default consistency-level (ONE) and the default serial-consistency-level (SERIAL) on the command line.
Co-authored-by: Robert Stupp <snazy@snazy.de>

STAR-432. Add options for consistency-level and serial-consistency-level

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/Memtable.java
src/java/org/apache/cassandra/io/util/SequentialWriter.java
test/unit/org/apache/cassandra/db/MemtableTest.java

If a flush is aborted, e.g. by exception thrown by `flushAllNonCFSBackedIndexesBlocking()`, this was done by closing the flush writer, potentially concurrent with operations on it. The latter is unsafe and may cause writes to released memory.
Fixed by adding an abort mechanism to the flush runnables.
Port of ac3f0d38d130891d3f75d87295601de4be12a40b and 3a88a826891776468ffc49e252eec443b9424609 (DB-962).
patch by Stefania Alborghetti, ported by Branimir Lambov

STAR-563: Fix SIGSEGVs on aborted flush

---

src/java/org/apache/cassandra/io/sstable/format/big/BigTableScanner.java
test/unit/org/apache/cassandra/io/sstable/SSTableReaderTest.java

This ports the up-to-date version of the test introduced by DB-1157
patch by Zhao Yang; reviewed by Branimir Lambov
ported by Branimir Lambov

STAR-566: Test for wrap-around in estimatedKeysForRanges

---

src/java/org/apache/cassandra/auth/FunctionResource.java
test/unit/org/apache/cassandra/auth/FunctionResourceTest.java

The problematic syntax was a function name with empty argument list.
Co-authored-by: kamlesh ghoradkar <kamlesh_ghoradkar@persistent.com>

STAR-749: Fixed ArrayIndexOutOfBoundsException in FunctionResource#fromName (STAR-99)

---

test/unit/org/apache/cassandra/locator/AlibabaCloudSnitchTest.java
test/unit/org/apache/cassandra/locator/CloudstackSnitchTest.java
test/unit/org/apache/cassandra/locator/EC2SnitchTest.java
test/unit/org/apache/cassandra/locator/GoogleCloudSnitchTest.java

Migrate to commit log initialization implemented by
ServerTestUtils that is race free. Files were removed by
the cleanup that followed CL init.

STAR-571 fix *SnichTests

---

src/java/org/apache/cassandra/db/compaction/Verifier.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReaderBuilder.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableWriter.java
src/java/org/apache/cassandra/io/sstable/metadata/IMetadataSerializer.java
src/java/org/apache/cassandra/io/sstable/metadata/MetadataSerializer.java
src/java/org/apache/cassandra/utils/BloomFilter.java
src/java/org/apache/cassandra/utils/BloomFilterSerializer.java
src/java/org/apache/cassandra/utils/FilterFactory.java
src/java/org/apache/cassandra/utils/obs/MemoryLimiter.java
src/java/org/apache/cassandra/utils/obs/OffHeapBitSet.java
test/microbench/org/apache/cassandra/test/microbench/BloomFilterSerializerBench.java
test/unit/org/apache/cassandra/Util.java
test/unit/org/apache/cassandra/io/sstable/SSTableReaderTest.java
test/unit/org/apache/cassandra/utils/BloomFilterTest.java
test/unit/org/apache/cassandra/utils/SerializationsTest.java
test/unit/org/apache/cassandra/utils/obs/OffHeapBitSetTest.java

In this PR it was a global memory limit added for all Bloom filters. It is configurable via a system property. 
Also, the FP chance is considered to change if the change is greater than the defined (also via system property) tolerance.
Optionally, the Bloom filters can be recreated when SSTable is being loaded (for example on startup) and FP chance changed since the last compaction - this behaviour is controlled also by a system property - by default we do not do that (the OSS way - see [CASSANDRA-11163](https://issues.apache.org/jira/browse/CASSANDRA-11163)), but in DSE we do (see [DSP-21344](https://datastax.jira.com/browse/DSP-21344)).
The implementation is a bit different to what we have in DSE, partially because to limit the amount of changes but also because my preference to limit …

STAR-745: Recreate BF on fp chance change and limit the total memory usage

---

src/java/org/apache/cassandra/auth/AuthCache.java
src/java/org/apache/cassandra/auth/AuthenticatedUser.java
src/java/org/apache/cassandra/auth/CassandraAuthorizer.java
src/java/org/apache/cassandra/auth/CassandraRoleManager.java
src/java/org/apache/cassandra/auth/PermissionsCache.java
src/java/org/apache/cassandra/auth/Roles.java
src/java/org/apache/cassandra/auth/RolesCache.java
test/unit/org/apache/cassandra/auth/AuthCacheInvalidationTest.java
test/unit/org/apache/cassandra/auth/CassandraNetworkAuthorizerTest.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/cql3/PreparedStatementsTest.java
test/unit/org/apache/cassandra/metrics/ClientRequestSizeMetricsTest.java

STAR-590 port of DB-1716
Note that in the first commit `AuthCacheInvalidationTest` was ported as is. Then in [commit cf440c4](https://github.com/datastax/cassandra/pull/207/commits/cf440c4e455b55416c4be3742b4a760182764c71) I made changes making it possible to see changes made during porting.

STAR-590 invalidate caches

---

build.xml

JMH jar was using the wrong directory for its support libraries (`build/lib/jars` instead of `build/test/lib/jars`) and missing junit and hamcrest (needed by e.g. `ReadTestSmallPartitions`).

STAR-825: Fix JMH libraries

---

build.xml
test/conf/logback-test-jenkins.xml

Also added logback-test-jenkins.xml which has disabled logging to console, default logs on trace level and filter out trace messages.

STAR-839: Add the ability to choose the log file configuration for testclasslist-xxx targets

---

src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/service/reads/ShortReadPartitionsProtection.java

This patch also sets the `rangeFetched` flag in the `ShortReadPartitionsProtection.applyToPartition` method. The `rangeFetched` flag is used by the `EndpointGroupingCoordinator.EndpointShortReadResponseProtection.rangeExhausted` method to check if the range was fetched by short read protection or by the original read command. This should have been set in the `applyToPartition` method, indicating that the range was read by the original read command but was missed out in the original PR for STAR-184.

STAR-815: MultiRangeReadCommand on by default and remove info log in query path

---

src/java/org/apache/cassandra/cql3/functions/FunctionCall.java
test/unit/org/apache/cassandra/cql3/ViewTest.java

Co-authored-by: Andrés de la Peña <a.penya.garcia@gmail.com>

STAR-687: materialized views' WHERE clauses stored in the schema should reference quoted functions when necessary

---

test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/guardrails/GuardrailTester.java

STAR-847 guardrail unit tests sometimes fail with `User guardrail_user has no SELECT permission on <table cql_test_keyspace.table_01> or any of its parents`
The `GuardrailTester. afterGuardrailTest` method drops the test user after each test, however the java driver cluster/session remains open. If the timing is right, the driver control connection will issue queries as the test user *after* the user has been dropped, and this can result in an empty entry in the Roles cache. If that entry does not expire before the next test starts and the test user is created again, the empty entry will result in no permissions being recognized for the user.
A previous attempt to fix the issue - issuing a LIST ROLES query and waiting for results - didn't actually go through the Roles cache, so wasn't …

STAR-847 Close client to prevent driver queries after dropping user

---

src/java/org/apache/cassandra/service/ActiveRepairService.java

In particular, show a better error message rather than NPE.
Note that upgrades from pre 3.0 are likely not supported in 4.0, thus I skipped the checks for messaging version
Co-authored-by: Robert Stupp <snazy@snazy.de>

STAR-688: Port DB-1985 - add extra checks for possible NPE during repair

---

src/java/org/apache/cassandra/db/compaction/BackgroundCompactionRunner.java
src/java/org/apache/cassandra/db/compaction/CompactionManager.java
test/unit/org/apache/cassandra/db/compaction/CompactionsBytemanTest.java

Since we now have a global trigger that visits all marked CFSs, it no longer makes sense to have special treatment for CFSs that don't have running compactions (the check will be triggered for all once a thread frees up). Thus we can simplify the processing:
- we can simply abort the `run` method whenever we have enough scheduled compactions
- it makes better sense to trigger a run after individual compaction tasks complete
This patch also makes sure that the futures we return cannot be cancelled by the caller.

Simplify background compaction check initiation logic

---

build.xml
src/java/org/apache/cassandra/db/virtual/SystemViewsKeyspace.java
src/java/org/apache/cassandra/index/sai/ColumnContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/JSONAnalyzerParser.java
src/java/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzer.java
src/java/org/apache/cassandra/index/sai/disk/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
src/java/org/apache/cassandra/index/sai/plan/Expression.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/virtual/AnalyzerView.java
src/java/org/apache/cassandra/index/sai/virtual/IndexesSystemView.java
src/java/org/apache/cassandra/index/sasi/analyzer/filter/StemmerFactory.java
src/java/org/apache/cassandra/index/sasi/analyzer/filter/StemmingFilters.java
src/java/org/apache/cassandra/schema/IndexMetadata.java
src/java/org/apache/cassandra/utils/bytecomparable/ByteComparable.java
test/unit/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/virtual/AnalyzerViewTest.java
test/unit/org/apache/cassandra/index/sai/virtual/IndexesSystemViewTest.java

added more language tests
added brazilian
cql test passes
added support for setting a lucene analyzer
cql json test passes
fixed up some things

STAR-123 custom lucene analyzer and some language unit tests

---

src/java/org/apache/cassandra/index/sai/disk/IndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/BKDReader.java
src/java/org/apache/cassandra/index/sai/disk/v1/PostingsReader.java
src/java/org/apache/cassandra/index/sai/disk/v1/PrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v1/TermsReader.java
src/java/org/apache/cassandra/io/util/FileUtils.java

Fixed FileHandle leaks caused by lack of proper closing of PrimaryKeyMap
in various places. Removed sharing of primaryKeyOffsets
between copies of PrimaryKeyMap.

STAR-867 Fix resource management errors related to PrimaryKeyMap

---

build.xml
src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/compaction/unified/RealEnvironment.java
src/java/org/apache/cassandra/db/virtual/CachesTable.java
src/java/org/apache/cassandra/metrics/CASClientRequestMetrics.java
src/java/org/apache/cassandra/metrics/CASClientWriteRequestMetrics.java
src/java/org/apache/cassandra/metrics/CacheMetrics.java
src/java/org/apache/cassandra/metrics/ChunkCacheMetrics.java
src/java/org/apache/cassandra/metrics/ClientRangeRequestMetrics.java
src/java/org/apache/cassandra/metrics/ClientRequestMetrics.java
src/java/org/apache/cassandra/metrics/ClientWriteRequestMetrics.java
src/java/org/apache/cassandra/metrics/CodahaleChunkCacheMetrics.java
src/java/org/apache/cassandra/metrics/CoordinatorClientRequestMetrics.java
src/java/org/apache/cassandra/metrics/CoordinatorClientRequestMetricsProvider.java
src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java
src/java/org/apache/cassandra/metrics/MicrometerMetrics.java
src/java/org/apache/cassandra/metrics/ViewWriteMetrics.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/service/reads/range/RangeCommandIterator.java
src/java/org/apache/cassandra/tracing/TraceStateImpl.java
test/distributed/org/apache/cassandra/distributed/test/sai/ConcurrencyFactorTest.java
test/long/org/apache/cassandra/cql3/CachingBench.java
test/unit/org/apache/cassandra/db/virtual/CachesTableTest.java
test/unit/org/apache/cassandra/metrics/CodahaleChunkCacheMetricsTest.java
test/unit/org/apache/cassandra/metrics/CoordinatorMetricsTest.java
test/unit/org/apache/cassandra/metrics/CustomCoordinatorMetricsTest.java
test/unit/org/apache/cassandra/metrics/MicrometerChunkCacheMetricsTest.java

Changes are mainly around:
* First commit: `ClientRequestMetrics` and subclasses from [cndb-884](https://github.com/riptano/bdp/commit/03b23db6a5697baaf71d46d661c0ac1c908bc33e) and riptano/bdp#19515
and
* Second commit: Porting `MicrometerChunkCacheMetrics` from [CNDB-780 - Add Micrometer metrics for the chunk cache
](https://github.com/riptano/bdp/commit/378a7a6dbafe6b71cb7820abe9fe2700c9218748)
Some differences from bdp/cndb are mention in code comments.

STAR-865 Refactor and port metrics code from cndb

---

src/java/org/apache/cassandra/metrics/DroppedMessageMetrics.java
src/java/org/apache/cassandra/metrics/MessagingMetrics.java
src/java/org/apache/cassandra/net/OutboundSink.java
src/java/org/apache/cassandra/net/Verb.java
src/java/org/apache/cassandra/repair/RepairMessageVerbHandler.java
src/java/org/apache/cassandra/service/ActiveRepairService.java
test/unit/org/apache/cassandra/net/MessagingServiceTest.java
test/unit/org/apache/cassandra/net/VerbTest.java
test/unit/org/apache/cassandra/repair/RepairJobTest.java

Add support for:
- registering new verbs at runtime
- decorating existing verb handlers with another method
- running a callback after the `MessagingService` sends a message

STAR-845: Port MessagingService implementation from DSE

---

test/distributed/org/apache/cassandra/distributed/test/FailingRepairTest.java

FailingRepairTest uses serialization to pass Verbs back and forth
between the nodes during the test. Unforuntately, Verbs aren't
serializable anymore because they're no longer enums and this broke
the test.
Instead of passing a verb around, pass the verb Id and lookup the
verb inside of the test method.

STAR-881: Fix FailingRepairTest after making Verb an object

---

CHANGES.txt
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/net/AbstractMessageHandler.java
src/java/org/apache/cassandra/net/FrameDecoder.java
src/java/org/apache/cassandra/net/InboundMessageHandler.java
src/java/org/apache/cassandra/net/ResourceLimits.java
src/java/org/apache/cassandra/service/StorageService.java
src/java/org/apache/cassandra/service/StorageServiceMBean.java
src/java/org/apache/cassandra/transport/CQLMessageHandler.java
src/java/org/apache/cassandra/transport/ClientResourceLimits.java
src/java/org/apache/cassandra/transport/Dispatcher.java
src/java/org/apache/cassandra/transport/ExceptionHandlers.java
src/java/org/apache/cassandra/transport/InitialConnectionHandler.java
src/java/org/apache/cassandra/transport/PreV5Handlers.java
src/java/org/apache/cassandra/transport/SimpleClient.java
src/java/org/apache/cassandra/utils/concurrent/NonBlockingRateLimiter.java
test/burn/org/apache/cassandra/transport/BurnTestUtil.java
test/burn/org/apache/cassandra/transport/SimpleClientPerfTest.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/net/ResourceLimitsTest.java
test/unit/org/apache/cassandra/transport/CQLConnectionTest.java
test/unit/org/apache/cassandra/transport/ClientResourceLimitsTest.java
test/unit/org/apache/cassandra/transport/RateLimitingTest.java
test/unit/org/apache/cassandra/utils/concurrent/NonBlockingRateLimiterTest.java

I was able to successfully rate limit the following test https://fallout.sjc.dsinternal.org/tests/ui/matt.fleming@datastax.com/STAR-887-cql-iot/41471571-5a1f-4a71-97f0-b02940e63b14/artifacts:
Saw these messages on the client:
```
021-10-06 20:59:35,270 [CmdOut:12772]        INFO  client-0             - STDOUT: using timestamp ?;' generated server side warning(s): Request breached global limit of 10000 requests/second and triggered backpressure.
```
And on the server:
```
INFO  [Native-Transport-Requests-9] 2021-10-06 21:04:16,983 NoSpamLogger.java:92 - Request breached global limit of 10000 requests/second and triggered backpressure.
```
And I verified using Grafana that the ops/s on the server side really was 10k ops/s.

STAR-887: Port Request-Based Native Transport Rate-Limiting (CASSANDRA-16663)

---

src/java/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoir.java

Makes Snapshot class of DecayingEstimatedHistogramReservoir public, so
its API is accessible by external components such as CNDB. Adds public
getter to retrieve the array of bucket offsets.

STAR-888 extend decaying histogram's snapshot API

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/locator/DynamicEndpointSnitch.java
src/java/org/apache/cassandra/locator/DynamicSnitchSeverityProvider.java
test/unit/org/apache/cassandra/locator/DynamicEndpointSnitchTest.java

Ports `DynamicSnitchSeverityProvider` in `cndb/bdp` that was introduced with [cndb-745 PR](https://github.com/riptano/bdp/pull/19400).
Note: C* 4.0/CC use `InetAddressAndPort` rather than `InetAddress` and I have made that change in this port.

STAR-909 Port DynamicSnitchSeverityProvider from bdp/cndb

---

src/java/org/apache/cassandra/db/filter/TombstoneOverwhelmingException.java
src/java/org/apache/cassandra/exceptions/IncompatibleSchemaException.java
src/java/org/apache/cassandra/exceptions/InternalRequestExecutionException.java
src/java/org/apache/cassandra/exceptions/RequestFailureReason.java
src/java/org/apache/cassandra/exceptions/UncheckedInternalRequestExecutionException.java
src/java/org/apache/cassandra/exceptions/UnknownColumnException.java
src/java/org/apache/cassandra/index/IndexNotAvailableException.java

Adding `InternalRequestExecutionException` as an interface so that it can be used with exceptions that extend `RuntimeException` as well as checked exceptions.
Also added `RequestFailureReason` codes for exceptions that implement IREE.

STAR-912 Add InternalRequestExecutionException

---

src/java/org/apache/cassandra/utils/INativeLibrary.java
src/java/org/apache/cassandra/utils/NativeLibrary.java

Extends the API of NativeLibrary to create a directory by providing
the path as string, so specialized implementations of a file system
don't to do additional conversion into Cassandra File, which is then
converted into string representation.

STAR-934 extend native library API for serverless

---

build.xml

CNDB uses methods from the later version of
org.apache.common.codec.binary.Hex and the methods are not available in
the current version 1.9. Thus updating the version, which is already
in use in DataStax, i.e., 1.15.
Needed to compile module cndb-common

Update version of common-codec to 1.15

---

src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/db/commitlog/AbstractCommitLogService.java
src/java/org/apache/cassandra/db/commitlog/CommitLog.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogBytemanTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogFailurePolicyTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogPolicyBytemanTest.java

Adds fail_writes policy to commit log failure policies, which rejects
writes on sync errors.

STAR-1015 add new CL error policy to reject writes on sync errors

---

src/java/org/apache/cassandra/utils/JVMStabilityInspector.java
test/unit/org/apache/cassandra/cql3/CompactionOutOfSpaceTest.java
test/unit/org/apache/cassandra/cql3/OutOfSpaceTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogFailurePolicyTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogPolicyBytemanTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogUpgradeTest.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
test/unit/org/apache/cassandra/net/ResourceLimitsTest.java
test/unit/org/apache/cassandra/utils/JVMStabilityInspectorTest.java

Interface `JVMKiller` was introduced in STAR-891; in order for alternate implementations to be used, use the interface rather than the concrete default implementation in `JVMStabilityInspector`.

STAR-1069 Use JVMKiller interface in JVMStabilityInspector to allow other implementations.

---

src/java/org/apache/cassandra/io/sstable/StorageHandler.java

This patch updates StorageHandler.ReloadReason to reflect the fact
that PERIODIC reloads will be replaced by reloads only when there is a
change in etcd.
Port of CNDB-2368

STAR-1078 extend StorageHandler.ReloadReason for CNDB

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/commitlog/AbstractCommitLogSegmentManager.java
src/java/org/apache/cassandra/db/commitlog/CommitLogSegment.java
src/java/org/apache/cassandra/db/commitlog/UncompressedSegment.java
src/java/org/apache/cassandra/io/compress/CompressedSequentialWriter.java
src/java/org/apache/cassandra/io/util/SequentialWriter.java
src/java/org/apache/cassandra/io/util/SimpleCachedBufferPool.java
test/unit/org/apache/cassandra/db/commitlog/BatchCommitLogTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java
test/unit/org/apache/cassandra/db/commitlog/GroupCommitLogTest.java

These changes come from [CNDB-153 changes in #18944](https://github.com/riptano/bdp/pull/18944/files).
I applied the changes that appeared to be relevant and tried to be careful to compare with current `6.8.-cndb` branch code.
There are a couple things I was not certain about:
1. In `CommitLogSegment`, DSE used `DatabaseDescriptor.getCommitlogAccessMode()` but CC has only `getDiskAccessMode` so that is what I used. If commit log access mode needs to be configured separately, it will need to be added.
2a. `UncompressedSegment` was ported from DSE under the assumption it will be needed as a non-memory mapped alternative.
2b. In `UncompressedSegment`, DSE explicitly set the `SimpleCacheBufferPool.preferredReusableBufferType` to `BufferType.OFF_HEAP`. In DSE the default was always `ON_HEAP`. …

STAR-1103 Port DSE code for uncompressed, non-memory mapped commit log segments needed to support remote storage

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateIndexStatement.java

I wish I could elaborate a better rationale for this change, but all I have knowledge to say is that a) other `Statement` classes use `keyspace.createReplicationStrategy()` this way and b) no other `Statement` class uses `Keysapce.open()`.

STAR-1126 Get replication strategy using KeyspaceMetadata.createReplicationStrategy

---

src/java/org/apache/cassandra/cache/AutoSavingCache.java
src/java/org/apache/cassandra/io/sstable/SSTableRewriter.java
src/java/org/apache/cassandra/service/CacheService.java
test/unit/org/apache/cassandra/db/KeyCacheTest.java

As part of STAR-782 key cache migration during compaction has been removed which means we do nothing with the cached keys. This is not a problem in case of our default TrieIndex sstable format because key cache is not used there at all. However it is a bit of a problem when the legacy format is used. The problem is that we do not invalidate the old keys pointing to the obsoleted sstables - that has been addressed in this PR.

STAR-1177: Fix accidentally removed keycache invalidation after compaction

---

src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java

Extends the commit log replayer to provide custom replayer filter
implementation.
It is port of CNDB-1285 and needed for CNBD.

STAR-1176 Add custom replayer filter

---

src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java
test/unit/org/apache/cassandra/db/RecoveryManagerTruncateTest.java

Extends the wrapper around initiating mutations read from the log to
allow custom methods to be called on replay or skip. Use it to test
commit log replayer with TRUNCATE.
This port of DB-2721 and needed for a test in CNDB.

STAR-1199 Test replayer on truncate

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
test/unit/org/apache/cassandra/metrics/TrieMemtableMetricsTest.java

The update is applied asynchronously and not waited for to complete flushes. This fixes the test to explicitly wait for the asynchronous reclamation task to complete before reading the metrics.

Fix flake in TrieMemtableMetricsTest

---

src/java/org/apache/cassandra/schema/KeyspaceParams.java
src/java/org/apache/cassandra/schema/ReplicationParams.java
test/unit/org/apache/cassandra/schema/SchemaKeyspaceTest.java

To allow creating Keyspace with Everywhere strategy the correct
approach is to extend its API with everywhere() method. This is then
tested in a very simple test.
Needed for tests in CNDB.
The test is naive. If there are good ideas and it is important, let me know or create a separate ticket for more meaningful test.

STAR-1205 Add everywhere() to KeyspaceParams API

---

src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java

In STAR-1180, the StorageAttachedIndexSearcher was modified
so that each computeNext() returns an iterator for a different
partition. This fixed the correctness issue, but the implementation
was far suboptimal - it required fetching all data of a partition
eagerly before the final merged partition iterator could be returned.
In case of extremely wide partitions that behavior could destabilize
the server.
This commit gets rid of eager creation of the row iterators.
It keeps only one iterator open at a time, and opens new iterators only
when the previous one runs out of data. The data retrieval commands
are issued lazily, while the returned iterator gets iterated.
In addition, the code has been tidied up, organized and documented
in order to improve readability and future maintenance.

STAR-1207: Open iterators lazily in StorageAttachedIndexSearcher

---

src/java/org/apache/cassandra/db/compaction/AbstractTableOperation.java
src/java/org/apache/cassandra/db/compaction/ActiveOperations.java
src/java/org/apache/cassandra/db/compaction/CompactionIterator.java
test/unit/org/apache/cassandra/db/compaction/CompactionsTest.java

Allows to register listeners to observe table operations called in
compaction manager.
This is port of CNDB-3258

STAR-1217 Add CompactionProgressListener

---

src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java

Generally try not to throw in constructors and if
an exception in a constructor is thrown,
make sure happens before allocating resources.
This fixes resource leaks reported by
SingleNodeFailureTest.testFailedBkdReaderOnMultiIndexesQuery.

STAR-1229: Fix resource leaks on unhappy path

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java

StorageAttachedIndexGroup was not thread safe and accessed
from multiple threads both for reads and writes, which resulted
in the following exception:
```
ERROR [MutationStage-1] node2 2022-03-31 11:11:31,938 AbstractLocalAwareExecutorService.java:169 - Uncaught exception on thread Thread[MutationStage-1,5,node2]
java.lang.RuntimeException: null for ks: sai_query_keyspace, table: table_2
at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1430)
at org.apache.cassandra.db.CassandraTableWriteHandler.write(CassandraTableWriteHandler.java:40)
at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:649)
at org.apache.cassandra.db.Keyspace.applyFuture(Keyspace.java:478)
at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:218)
at …
```

STAR-1233: Fix CME in StorageAttachedIndexGroup

---

src/java/org/apache/cassandra/db/commitlog/CommitLog.java
src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java
test/long/org/apache/cassandra/db/commitlog/CommitLogStressTest.java
test/unit/org/apache/cassandra/ServerTestUtils.java
test/unit/org/apache/cassandra/cql3/OutOfSpaceTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogApiTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogCQLTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogInitWithExceptionTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogSegmentBackpressureTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogSegmentManagerCDCTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java

Extends CommitLog's API to allow update its directory, so a commit log
from remote storage can be replayed.

STAR-1230 Provide CL API to update to remote storage

---

src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java

Fixes the following null pointer exception that may be raised
during a read query using index if the schema with that
index hasn't been fully propagated yet:
```
java.lang.RuntimeException: Can not deserialize message MessageImpl{verb=7, bytes=c22adae7cf7b0ca710070100817502041d84a560b22111ec9c92efe6fdbada366247a1a80300100c616262726576696174696f6e066163746976650d617265615f73715f6d696c65730c6176675f646d765f77616974036764700269640269700b6d75726465725f72617465106d7572646572735f7065725f79656172046e616d650b6e6f6e5f696e64657865640a706f70756c6174696f6e0b74656d706f72616c5f69641574696e795f6d7572646572735f7065725f79656172077669736974656411766973697465645f74696d657374616d7000020c616262726576696174696f6e0b74656d706f72616c5f6964000100000b74656d706f72616c5f6964000000000010ee6136d2d17c11e8a8d5f2801f1b9fd1 …
```

STAR-1239: Fix NPE in ReadCommand when index unavailable

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java

Apache Mina is not really in the direct dependencies
of the project. It compiled accidentally because it
got onto the classpath through one of the
transitive dependencies of Netty.

STAR-1233: Use Guava concurrent hash set instead of Apache Mina

---

src/java/org/apache/cassandra/db/compaction/BackgroundCompactionRunner.java
src/java/org/apache/cassandra/db/compaction/CompactionManager.java

STAR-1245 Refactor and expose startCompactionTasks in CompactionManager.
Make handleCompactionError public in BackgroundCompactionRunner.
These changes will allow cndb to submit compaction tasks in https://github.com/riptano/cndb/pull/4448

STAR-1245 Refactor and expose startCompactionTasks in CompactionManager

---

src/java/org/apache/cassandra/index/sai/disk/v1/MergeOneDimPointValues.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReader.java
test/resources/mockito-extensions/org.mockito.plugins.MockMaker
test/unit/org/apache/cassandra/index/sai/disk/v1/KDTreeSegmentMergerTest.java

All iterators added to MergeOneDimPointValues should
be eventually closed after use or immediately if unused.
Fixes code introduced in STAR-121.
Fixes flaky KDTreeSegmentMergerTest.

STAR-1253: Fix resource leak in SAI MergeOneDimPointValues

---

test/distributed/org/apache/cassandra/distributed/test/InternodeEncryptionOptionsTest.java

TLSv1.1 has been disabled globally in OpenJDK and various
other JVMs in April 2021. Although it is possible to unlock it
by editing the java.security file, the test cannot unlock
it by itself. Settings in the java.security file are stronger
than the settings passed at runtime when building the SslContext.
Fortunately, support for TLSv1.3 landed in OpenJDK 8 some time
ago (but is not selected by default), so we can use that protocol
to test the protocol options.

STAR-1261: Don't try to establish TLSv1.1 connections in test

---

test/resources/mockito-extensions/org.mockito.plugins.MockMaker
test/unit/org/apache/cassandra/index/sai/disk/v1/KDTreeSegmentMergerTest.java

Due to a limitation of distributed test API InstanceClassloader
that cannot load .raw classes, mock-maker-inline
extension fails to load in distributed tests.
Fixes distributed unit test failures caused by STAR-1253.
Partially reverts STAR-1253.

STAR-1263: Disable mock-maker-inline mockito extension

---

src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/BackgroundCompactionsTest.java

Port CNDB-2292 - fix memory leak due to lack of call to BackgroundCompactions.setPending
Adds UnifiedCompactionStrategy.setPendingCompactionAggregates for use by external callers.

STAR-1257 Port CNDB-2292 - fix memory leak due to lack of call to BackgroundCompactions.setPending

---

src/java/org/apache/cassandra/io/sstable/Component.java

This reverts commit ab7144312f4ee6e81841b765847f5bf1f3b61d85.
It was not needed as getter name(), which is already public, provides the same
value and thus should be used. CNDB is being already adjusted (see https://github.com/riptano/cndb/pull/4624).

Revert "STAR-1293 Allow to read string value of Component.repr enum (#432)"

---

src/java/org/apache/cassandra/utils/memory/BufferPool.java
test/burn/org/apache/cassandra/utils/memory/LongBufferPoolTest.java
test/unit/org/apache/cassandra/utils/memory/BufferPoolTest.java

LocalPool is meant to be managed by a single thread.
Unfortunately there was a code path that allowed
a thread enter the context of the LocalPool owned by another
thread by attempting to recycle a chunk using its
recycler reference.
The patch detects that situation and avoids attempts to recycle
a chunk from a wrong thread.
Fixes the following intermittent errors thrown by LongBufferPoolTest:
java.lang.AssertionError
at org.apache.cassandra.utils.memory.BufferPool$Chunk.get(BufferPool.java:1315)
at org.apache.cassandra.utils.memory.BufferPool$MicroQueueOfChunks.get(BufferPool.java:576)
at org.apache.cassandra.utils.memory.BufferPool$LocalPool.tryGetInternal(BufferPool.java:900)
at org.apache.cassandra.utils.memory.BufferPool$LocalPool.lambda$new$0(BufferPool.java:739)
at …

STAR-1262: Fix multiple bugs in BufferPool and LongBufferPoolTest

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
src/java/org/apache/cassandra/schema/Schema.java

Introduces an additional getter in ColumnFamilyStore and increases
usage of its getters, so ColumnFamilyStore can be mocked in a CNDB
test.
Checks properties in Schema for null to avoid NullPointerException.
It happens during CNDB mock test, while releasing resources when
tidy is called on Schema.instance. It's unclear how the properties can
be null.
This PR replaces #444. It minimizes number of changes and keeps inconsistent usage of the affected getters.

STAR-1314 Adjust Schema and CFS for CNDB mocked test

---

test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/cql3/statements/DescribeStatementTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailsOnTableTest.java

Wait until schema cleanup is completed before launching the
tests that rely on clean state. Some tests retrieve the
whole schema or the list of functions / aggregates, and they
don't expect objects left by other tests.

STAR-1321: Fix flaky DescribeStatementTest.testDescribeFunctionAndAggregate

---

test/distributed/org/apache/cassandra/distributed/test/SSTableLoaderEncryptionOptionsTest.java

Looks like SSTableLoader finally properly reports
errors to stderr, not stdout, but the test hasn't been updated.
Also, relying on a very specific exception on SSL failure is
very fragile. The exact type of exception is something that should be
tested by the java driver project, not here.

STAR-1192: Fix test assertion

---

test/distributed/org/apache/cassandra/distributed/test/sai/SAIUtil.java

Addresses:
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.cassandra.distributed.test.sai.SAIUtil that uses org.apache.cassandra.distributed.Cluster was not fulfilled within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
at org.apache.cassandra.distributed.test.sai.SAIUtil.waitForSchemaAgreement(SAIUtil.java:128)
at org.apache.cassandra.distributed.test.sai.SAIUtil.getIndexes(SAIUtil.java:117)

STAR-1422: Increase the schema agreement timeout in SAI tests to 60s

---

src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableReader.java

The TrieIndexSSTableReader was not calling discoverComponents
causing issues in CNDB with the SSTable components not being
loaded correctly.

STAR-1431 Make sure SSTableWatcher is called in Trie SSTable open

---

test/burn/org/apache/cassandra/utils/LongBTreeTest.java

This test required 1+ hour to finish and hit timeout on CI.

STAR-261: Reduce the running time of testRandomRangeAndBatches

---

build.xml
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/SystemKeyspace.java
src/java/org/apache/cassandra/io/sstable/SSTableId.java
src/java/org/apache/cassandra/io/sstable/SSTableIdFactory.java
src/java/org/apache/cassandra/io/sstable/ULIDBasedSSTableId.java
src/java/org/apache/cassandra/io/sstable/UUIDBasedSSTableId.java
src/java/org/apache/cassandra/utils/TimeUUID.java
test/unit/org/apache/cassandra/io/sstable/SSTableIdTest.java

Unlike in CNDB, universally unique identifiers were implemented in OSS using TimeUUID rather than ULID. Since CC needs to be able to at least read identifiers generated by CNDB, this patch adds back support for ULID based identifiers (in addition to TimeUUID based identifiers).

STAR-1265: Support for ULID based identifiers (additionally to UUID)

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/io/sstable/Descriptor.java

This includes the following fixes:
Allows the index to be queryable with status UNKNOWN
Caches component files in Descriptor to avoid a race condition
when the RemoteStorage for a tenant is unregistered

STAR-1487 Changes required for MetadataManagerTest

---

src/java/org/apache/cassandra/cql3/statements/TruncateStatement.java
test/unit/org/apache/cassandra/ServerTestUtils.java
test/unit/org/apache/cassandra/cql3/validation/operations/TruncateTest.java

Updates `TruncateStatement` to call `doTruncateBlocking` from `execute` (not `executeLocally`) so that it can be overridden by alt. implementations (via `TruncateStatementProvider`).
It also adds some tests to improve test coverage (required by SonarCloud).
The CNDB changes are: https://github.com/riptano/cndb/pull/5214

STAR-1505 doTruncateBlocking should be called from execute not executeLocally so it can be overridden by alternate implementations.

---

test/unit/org/apache/cassandra/db/RecoveryManagerTruncateTest.java

Fixes a race condition making the test flakey by persisting mutations to commit log as in other tests in this class.

STAR-1364 Use `Mutation.apply` instead of `applyUnsafe` to persist the commit log, so the expected mutations will be replayed.

---

test/distributed/org/apache/cassandra/distributed/impl/InstanceConfig.java

Adds missing `metadata_directory` to `InstanceConfig` so that tests can start.

STAR-1538 Add metadata_directory to InstanceConfig

---

src/java/org/apache/cassandra/auth/AuthCache.java
src/java/org/apache/cassandra/auth/AuthenticatedUser.java
src/java/org/apache/cassandra/auth/Roles.java
test/unit/org/apache/cassandra/auth/AuthCacheTest.java

This is used by cndb to clear all permission cache entries for a given user (RoleResource).
Add javadoc to otherwise unused methods to make it more clear they are used by cndb

STAR-1485 Ports code from DSE to clear AuthCache entries using a filter

---

src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/ColumnIdentifier.java
src/java/org/apache/cassandra/cql3/CqlBuilder.java
src/java/org/apache/cassandra/cql3/ReservedTypeNames.java
src/java/org/apache/cassandra/db/marshal/UserType.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
test/unit/org/apache/cassandra/cql3/ReservedTypeNamesTest.java

The following fixes are included in this PR:
- Bring in CNDB-1889 changes from DSE to allow  quoting of user type reserved names
- Fix comparison of table options in table_properties_ignored guardrail

STAR-1497 Fixes for CNDB SchemaTest

---

src/java/org/apache/cassandra/cql3/statements/BatchStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/AlterSchemaStatement.java

Enables overriding keypace with a prefixed keyspace (cndb-1496 port) and 
ports 1145b3e61f4 from DSE

STAR-1575 port cndb-1496

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/Keyspace.java

Offline services don't create memtables and thus may not flush on schema changes 
and tenant unassignment. Without the ported changes the following (or similar) 
exceptions were thrown.
```
java.lang.IndexOutOfBoundsException: Index: -1
at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
at org.apache.cassandra.db.lifecycle.View.getCurrentMemtable(View.java:106)
at org.apache.cassandra.db.ColumnFamilyStore.reload(ColumnFamilyStore.java:406)
at org.apache.cassandra.schema.Schema.alterTable(Schema.java:787)
at org.apache.cassandra.schema.Schema.lambda$alterKeyspace$17(Schema.java:696)
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
at org.apache.cassandra.schema.Schema.alterKeyspace(Schema.java:696)
at …
```

STAR-1600 DSE changes around schema changes for offline services

---

src/java/org/apache/cassandra/schema/TableMetadata.java
test/unit/org/apache/cassandra/schema/TableMetadataTest.java

If a user creates a prepared statement for a table and then enables the
CDC param, the prepared statement must be invalidated.
If we don't invalidate the prepared statement it'll be executed using
the old TableMetadata object and take the non-CDC write path and go
directly to CNDB writers instead of via Pulsar topics.

STAR-1598 port CNDB-3932

---

src/java/org/apache/cassandra/cql3/QueryProcessor.java
src/java/org/apache/cassandra/tracing/TraceState.java
src/java/org/apache/cassandra/tracing/Tracing.java
test/unit/org/apache/cassandra/tracing/TracingTest.java

We need to set the tracing keyspace per-statement since this info needs
to be passed from the coordinator to the writers in CNDB.
Without this change, the writer knows that a query is being traced but
not the keyspace/tenant and instead it'll bill the shared tenant.

STAR-1477: Port the rest of cndb-1116 to fix billing during tracing

---

src/java/org/apache/cassandra/db/compaction/Scrubber.java
src/java/org/apache/cassandra/service/DefaultFSErrorHandler.java
src/java/org/apache/cassandra/utils/JVMStabilityInspector.java
test/unit/org/apache/cassandra/cql3/OutOfSpaceTest.java
test/unit/org/apache/cassandra/db/ScrubTest.java
test/unit/org/apache/cassandra/utils/JVMStabilityInspectorTest.java

The problem here was that JVMStabilityInspector killed JVM in face of
CorruptSSTableException when the policy was set to die, regardless what
handlers were set.

STAR-1502: Fix JVMStabilityInspector behavior on CorruptSSTableException

---

test/distributed/org/apache/cassandra/distributed/test/NativeTransportEncryptionOptionsTest.java

TLSv1.1 is now disabled by default in Java

STAR-1191: Fix NativeTransportEncryptionOptionsTest

---

test/unit/org/apache/cassandra/db/VerifyTest.java

Basically there were two tests which verify the same thing, but one was intended to use BTI and the other one BIG format.
Since by default we run with BTI, the BIG test explicitly sets the property to use BIG format. However, we run the full tests suite for both BTI and BIG, so when we run with BIG by default, the BTI fails (because it has no explicit configuration and assumes we run with BTI as default). The fix is simple - just have a single test, which just uses the default sstable format, it will use BTI in one test run and BIG in the other. Those squashed tests didn't differ by anything but assertion on the created sstable format.

STAR-1443: Fix VerifyTest

---

src/java/org/apache/cassandra/io/sstable/metadata/MetadataSerializer.java
src/java/org/apache/cassandra/io/storage/StorageProvider.java
src/java/org/apache/cassandra/io/util/PathUtils.java

Use StorageProvider.getLocalPath in PathUtils.rename to ensure local paths when renaming files.
Note: this will require CNDB to implement `StorageProvider.getLocalPath(Path path)` in addition to the existing method that takes a `File` parameter.

STAR-1491 Use StorageProvider.getLocalPath in PathUtils.rename to ensure local paths when renaming files

---

src/java/org/apache/cassandra/db/repair/CassandraValidationIterator.java
src/java/org/apache/cassandra/repair/ValidationManager.java
src/java/org/apache/cassandra/repair/ValidationPartitionIterator.java

This is required to fix `RegionRepairTest.testContinuousRepairNonZcs` because the validation scanned metrics are checked.

STAR-1492: Track compaction ops during validation

---

src/java/org/apache/cassandra/repair/SyncTask.java

This string is expected by CNDB's `RegionRepairTest.testRepairWithTruncate()` and adding it fixes that test for Converged Cassandra.

STAR-1492: Print message when repair syncing starts

---

src/java/org/apache/cassandra/db/Mutation.java
src/java/org/apache/cassandra/io/util/DataOutputBuffer.java
src/java/org/apache/cassandra/net/MessagingService.java
src/java/org/apache/cassandra/service/StorageProxy.java
test/unit/org/apache/cassandra/io/util/DataOutputTest.java

This introduces a per-mutation cache of the
serialized representation of the mutation.

STAR-1641 Cached mutation serialization

---

src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/schema/DroppedColumn.java

This is needed in CNDB to avoid keyspace lookups that may fail when applying a schema during tenant assignment; this specifically is needed in `CommitLogTest. testCommitLogReplayAfterSchemaChange`

STAR-1478 Add Types parameter to DroppedColumn.prepare to avoid keyspace lookup

---

src/java/org/apache/cassandra/db/compaction/CompactionSSTable.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java

It’s needed for porting CNDB-4308 as part of STAR-1509.

STAR-1509 Add getFile to CompactionSSTable interface

---

src/java/org/apache/cassandra/io/util/CompressedChunkReader.java

In STAR-1335 we ported most of CNDB-4090 but we missed out a call to StorageProvider.invalidateFileSystemCache() which is required to invalidate the remote storage cache in CNDB whenever we encounter corruption.
This was discovered because the RemoteFileCacheCorruptedPageTest unit test is failing.

STAR-1691: Port more bits of CNDB-4090

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/db/compaction/CompactionController.java
src/java/org/apache/cassandra/metrics/TableMetrics.java

STAR-1683 Port remaining pieces of CNDB-4308

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/Environment.java
src/java/org/apache/cassandra/db/compaction/unified/RealEnvironment.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

Port of https://github.com/riptano/bdp/pull/20372
This patch adds a way to customize the compaction overhead, i.e. the transient
amount of space required by a compaction whilst both input and output sstables
are present. In BDP this is just estimated to be the size of the input sstables.
It's unclear if we can improve this in CNDB, but I kept the refactoring because
initially I got confused thinking that in CNDB we could just waive this requirement
since the input sstables are in the file cache. So I think it's good to spell
out why we use the input sstable sizes by encapsulating the calculation in a
method with javadoc.
The patch also adds a warning to the logs: if a compaction cannot be performed
because the space overhead is larger than the space available, then the logs now
contain …

STAR-1694 Configure max compaction overhead

---

src/java/org/apache/cassandra/schema/DroppedColumn.java
test/unit/org/apache/cassandra/db/SchemaCQLHelperTest.java

Port of CNDB-5113
Fixed DroppedColumn#toCQLString by using the CQL String version of the 
column name, which also double quotes the name if it's in mixed case.

STAR-1704 Fix DroppedColumn to use CQL string in column name

---

src/java/org/apache/cassandra/streaming/StreamCoordinator.java
src/java/org/apache/cassandra/streaming/StreamResultFuture.java
src/java/org/apache/cassandra/streaming/StreamSession.java

Port CNDB-4855
Fixed streaming to connect back using peer preferred address instead of Channel#remoteAddress

STAR-1706 Connect back using preferred address

---

src/java/org/apache/cassandra/hints/HintsWriteExecutor.java
src/java/org/apache/cassandra/io/util/FileUtils.java
src/java/org/apache/cassandra/utils/memory/BufferPool.java
test/distributed/org/apache/cassandra/distributed/impl/Instance.java

There are a couple of things here:
- `unsafeFree` method in `BufferPool` did not do what it was probably expected to do - that is, the direct buffer was not released properly because when it is allocated in `allocateDirectAligned` the method actually returns a slice of the original buffer, while the only reference to the original buffer is in `attachment` field of the returned buffer. It was mitigated by using a new method to clean, which can release the parent buffer by recursively go through the attachment hierarchy
- for in-jvm dtests, releasing of all buffers in buffer pools was added as the very last step of instance shutdown; it fixes memory leaking between the subsequent instance restarts; in production run, we just stop the JVM and the buffers are lost, but in case of those dtest …

STAR-1660: Fix and prevent direct memory leaks in dtests

---

.build/build-resolver.xml
build.properties.default

Basically, use repo.datastax.com as additional repository rather than a replacement of the public repos.

STAR-1639: Use repo.datastax.com/dse as alternative repository

---

src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
test/unit/org/apache/cassandra/cql3/BatchTest.java
test/unit/org/apache/cassandra/utils/UUIDTest.java

Enable disabled test in BatchTest, which was broken due to previous name violation in BatchTests. It is fixed by setting batch size guardrail to the same number as in Apache Cassandra.
Updated default batch size number in the comment in accordance to actual values.
Fix name violation in UUIDTests to UUIDTest, so the tests are executed.

STAR-1626 Enable BatchTest and UUIDTests to run fully

---

test/unit/org/apache/cassandra/index/sai/disk/SelectiveIntersectionTest.java

The setup phase of this test was not waiting
for indexes to be queryable before inserting
data and flushing. This was resulting in a
race condition during the flush leading to a
random occurence of higher posting reader
usage than expected.

STAR-1586 Fix SelectiveIntersectionTest

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
test/unit/org/apache/cassandra/cache/ChunkCacheTest.java

STAR-1739: Add a way to check the number of cached file chunks

---

test/burn/org/apache/cassandra/utils/LongBTreeTest.java

018c8e0d5e8bc55fc51d3361fcb27c3c1fd189f6 increased the number of iterations in testRandomRangeAndBatches by 100
subsequent bd41794af4cb29204e19ec360b7eea4830a0dac6 decreased it by 10
here, we're decreasing it by 10 again, to get down to the original
number (and avoid timeouts in CI)

reduce number of iterations in testRandomRangeAndBatches

---

src/java/org/apache/cassandra/repair/messages/RepairMessage.java

So the problem here is that Cassandra since 4.0.7 supports timeouts of repair requests. Though, it is enabled only if version is >= 4.0.7-SNAPSHOT, according to the comparison rules in `CassandraVersion`. In Jenkins, we build 4.0.7-<sha> which, according to that comparison, is lower than 4.0.7-SNAPSHOT.

STAR-1748: Fix RepairRequestTimeoutTest

---

test/burn/org/apache/cassandra/utils/LongBTreeTest.java

The original assertion `mid < fakeUb` might fail if
`fakeLb == fakeUb`, which could happen if `canonical` collection
contained two or more consecutive integers.
This situation is very unlikely, but not impossible.

STAR-1587: Fix incorrect assertion in random data generation proc

---

src/java/org/apache/cassandra/net/RequestCallbacks.java

The RequestCallbacks class now stops adding callbacks after it
is shutdown by the MessagingService when that is shutdown.

STAR-1690 Stop message processing after MessagingService shutdown

---

src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java

The `ds-trunk` was failing to compile with JDK8 because:
```    [javac] /home/mike/repos/cassandra/src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java:263: error: cannot infer type arguments for FutureCallback<V>
[javac]                 Futures.addCallback(f, new FutureCallback<>() {
[javac]                                                          ^
[javac]   reason: cannot use '<>' with anonymous inner classes
[javac]   where V is a type-variable:
[javac]     V extends Object declared in interface FutureCallback
```

STAR-1795 Fix JDK8 compilation error in CommitLogReplayer

---

src/java/org/apache/cassandra/guardrails/Guardrails.java
src/java/org/apache/cassandra/io/sstable/format/SortedTableWriter.java
test/unit/org/apache/cassandra/guardrails/GuardrailCollectionSizeTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailItemsPerCollectionTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailPartitionSizeTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailTester.java
test/unit/org/apache/cassandra/guardrails/GuardrailWarningOnSSTableWriteTester.java

This is a port of https://github.com/riptano/bdp/pull/20124 for CNDB-3630 from `master`

STAR-1812 Stop collection guardrails spamming logs

---

src/java/org/apache/cassandra/cql3/QueryProcessor.java
src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/AbstractCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/AbstractStrategyHolder.java
src/java/org/apache/cassandra/db/compaction/CompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/CompactionStrategyHolder.java
src/java/org/apache/cassandra/db/compaction/CompactionStrategyManager.java
src/java/org/apache/cassandra/db/compaction/PendingRepairHolder.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionContainer.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/unified/ShardedMultiWriter.java
src/java/org/apache/cassandra/db/memtable/Flushing.java
src/java/org/apache/cassandra/io/sstable/AbstractSSTableSimpleWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableTxnWriter.java
src/java/org/apache/cassandra/io/sstable/SimpleSSTableMultiWriter.java
src/java/org/apache/cassandra/io/sstable/format/RangeAwareSSTableWriter.java
test/unit/org/apache/cassandra/cql3/MemtableQuickTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableUtils.java

This was causing the cardinality information of an sstable to include more keys than it actually has, resulting in grossly overestimated key counts when picking a bloom filter size; the latter resulted in 4-5 times larger bloom filters on L1 than they should be.

Fix invalid reuse of metadata collector during flushing

---

src/java/org/apache/cassandra/net/MessagingService.java

Fixes:
[javac] cassandra/src/java/org/apache/cassandra/net/MessagingService.java:219: error: cannot find symbol
[javac]     static Map<Integer, Integer> versionOrdinalMap = Arrays.stream(Version.values()).collect(Collectors.toMap(v -> v.value, v -> v.ordinal()));

Fix compilation of MessagingService

---

src/java/org/apache/cassandra/utils/JVMStabilityInspector.java
test/unit/org/apache/cassandra/utils/JVMStabilityInspectorTest.java

You can go commit by commit.
Note that disk and commit handlers are now invoked before global handler (see commit desc).
Failure in one of the handlers breaks the execution.  This behavior remains unchanged.

CNDB-5690 Extract global handler and make it configurable

---

src/java/org/apache/cassandra/utils/memory/BufferPool.java
test/unit/org/apache/cassandra/utils/memory/BufferPoolTest.java

The counter was incorrectly decremented by the size of the unused portion of the provided buffer.
It is now decremented by the number of bytes actually returned to the pool (that may be different than "size"). The number is calculated as a difference between original and resulting buffer capacity.

CNDB-6532 fix BufferPool.memoryInUse counter

---

src/java/org/apache/cassandra/net/AbstractMessageHandler.java
src/java/org/apache/cassandra/net/InboundMessageHandler.java
src/java/org/apache/cassandra/transport/CQLMessageHandler.java

This is alternative solution for https://github.com/riptano/cndb/issues/6142
The idea is to not directly touch `ClientMetrics` from `AbstractMessageHandler`. Probably cleaner than the other solution proposed here: https://github.com/datastax/cassandra/pull/603
@jtgrabowski @jasonstack please let me know what you think

CNDB-6142 Don't directly use ClientMetrics in AbstractMessageHandler

---

src/java/org/apache/cassandra/io/util/Memory.java
src/java/org/apache/cassandra/io/util/SafeMemory.java
src/java/org/apache/cassandra/metrics/CodehaleNativeMemoryMetrics.java
src/java/org/apache/cassandra/metrics/MicrometerNativeMemoryMetrics.java
src/java/org/apache/cassandra/metrics/NativeMemoryMetrics.java
src/java/org/apache/cassandra/utils/memory/MemoryUtil.java
src/java/org/apache/cassandra/utils/memory/NativeAllocator.java
test/unit/org/apache/cassandra/io/util/FileUtilsTest.java
test/unit/org/apache/cassandra/metrics/MicrometerNativeMemoryMetricsTest.java
test/unit/org/apache/cassandra/metrics/NativeMemoryMetricsTest.java

Port `NativeMemoryMetrics` to CC. Go commit by commit. 
Note that `NativeMemoryMetrics` are not explicitly registered in CC, this is done in CNDB.

CNDB-6522 add NativeMemoryMetrics

---

src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/VectorTopKProcessor.java
src/java/org/apache/cassandra/index/sai/utils/InMemoryPartitionIterator.java
src/java/org/apache/cassandra/index/sai/utils/InMemoryUnfilteredPartitionIterator.java
src/java/org/apache/cassandra/index/sai/utils/PartitionInfo.java
test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java

* added `QueryPlan#postIndexQueryProcessor` to filter top-k at replica side before sending response to coordinator
Summary:
- Updated `VectorTopKProcessor` so it can handle `PartitionIterator` at coordinator and `UnfilteredPartitionIterator` at replica.
- Updated `VectorTopKProcessor` to collect top-k rows and all tombstones at replica side.
- Added some utility classes (`InMemoryPartitionIterator` and `InMemoryUnfilteredPartitionIterator`) to return collected top-k rows and tombstones in primary key order.

Add vector top-k filter at replica side before returning to coordinator

---

src/java/org/apache/cassandra/db/SerializationHeader.java
test/unit/org/apache/cassandra/io/sstable/UDTMoveTest.java

Note that, although we provided a test to verify that, that test did not fail when run without that additional operation. The fix is added just to ensure compatibility with DSE.

CNDB-6857: Add a method to override keyspace in serialization header

---

src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java
test/unit/org/apache/cassandra/metrics/MicrometerChunkCacheMetricsTest.java

Original description:
> It was noted that Chunk Cache evictions are not showing up in metrics and are always zero.
recordEvictions() in MicrometerChunkCacheMetrics now is properly overridden so that both overloadings increment the evictions counter.

CNDB-6522 port riptano/bdp/pull/20676

---

src/java/org/apache/cassandra/index/sai/disk/SSTableRowIdPostingList.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/view/View.java
test/unit/org/apache/cassandra/index/sai/cql/QueryTimeoutTest.java
test/unit/org/apache/cassandra/index/sai/disk/SingleNodeQueryFailureTest.java
test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java

- Union the results from multiple segments per index
- Revert intersection behavior to pick 2 most selective indexes if there is no ANN
- Fix SSTableRowIdPostingList to return END_OF_STREAM if next row is END_OF_STREAM
- Fixes:
- VectorMemtableIndexTest#randomQueryTest
- SegmentMergerTest
- SingleNodeQueryFailureTest#testFailedRangeIteratorOnMultiIndexesQuery
- SelectiveIntersectionTest
- QueryTimeoutTest

Union the results from multiple segments per index

---

src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/AbstractMarker.java
src/java/org/apache/cassandra/cql3/ArrayLiteral.java
src/java/org/apache/cassandra/cql3/CQL3Type.java
src/java/org/apache/cassandra/cql3/Lists.java
src/java/org/apache/cassandra/cql3/Operation.java
src/java/org/apache/cassandra/cql3/Vectors.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java
src/java/org/apache/cassandra/db/marshal/ValueAccessor.java
src/java/org/apache/cassandra/db/marshal/VectorType.java
src/java/org/apache/cassandra/index/sai/disk/hnsw/CassandraOnHeapHnsw.java
src/java/org/apache/cassandra/index/sai/disk/hnsw/ConcurrentVectorValues.java
src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/VectorTopKProcessor.java
src/java/org/apache/cassandra/index/sai/utils/TypeUtil.java
src/java/org/apache/cassandra/serializers/TypeSerializer.java
src/java/org/apache/cassandra/utils/vint/VIntCoding.java
test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSegmentationTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/IndexWriterConfigTest.java
test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java

- Now uses vector<type, dimension> to describe vector
- This commit does not bring in the whole 18504 patch only the essential grammar and type parts of the patch

Merge CASSANDRA-18504 vector grammar

---

src/java/org/apache/cassandra/transport/messages/OptionsMessage.java
src/java/org/apache/cassandra/transport/messages/StartupMessage.java
src/java/org/apache/cassandra/utils/ProductType.java
test/unit/org/apache/cassandra/utils/ProductTypeTest.java

Converged Cassandra needs to set SERVER_VERSION and PRODUCT_TYPE in the OPTIONS message returned to drivers on connection. The drivers use those OPTIONS to know they are talking to astra and to change the default CL to LOCAL_QUORUM for writes.

CNDB-6976 Set SEVER_VERSION and PRODUCT_TYPE

---

src/java/org/apache/cassandra/cql3/Ordering.java
src/java/org/apache/cassandra/cql3/restrictions/MultiColumnRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/Restriction.java
src/java/org/apache/cassandra/cql3/restrictions/RestrictionSet.java
src/java/org/apache/cassandra/cql3/restrictions/RestrictionSetWrapper.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/TokenFilter.java
src/java/org/apache/cassandra/cql3/restrictions/TokenRestriction.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/db/ReadQuery.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/disk/hnsw/CassandraOnHeapHnsw.java
src/java/org/apache/cassandra/service/pager/AggregationQueryPager.java
src/java/org/apache/cassandra/service/pager/PartitionRangeQueryPager.java
src/java/org/apache/cassandra/service/pager/QueryPager.java
src/java/org/apache/cassandra/service/reads/range/RangeCommands.java
test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java

- fix NPE in SelectStatement by skipping reversed() for null ColumnComparator
- fix getOrderingColumns() to return LinkedHashMap to preverse ordering columns' order
- fix VectorLocalTest compilation
- remove debug log in CassandraOnHeapHnsw

Vector 6 take 2: reapply Vector-6 commit and fix NPE in SelectStatement

---

src/java/org/apache/cassandra/cql3/Ordering.java
test/unit/org/apache/cassandra/cql3/statements/SelectStatementTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

Using an non-existent column with an ANN expression triggers an NPE like so,
java.lang.NullPointerException: null
at org.apache.cassandra.cql3.ArrayLiteral.forReceiver(ArrayLiteral.java:43)
at org.apache.cassandra.cql3.ArrayLiteral.prepare(ArrayLiteral.java:54)
at org.apache.cassandra.cql3.Ordering$Raw$Ann.bind(Ordering.java:178)
at org.apache.cassandra.cql3.Ordering$Raw.bind(Ordering.java:139)
Use TM.getExistingColumn() which throws InvalidRequestException if the column is undefined.

VECTOR-42: Check columns exist to avoid NPE during ANN expr binding

---

src/java/org/apache/cassandra/index/sai/disk/hnsw/CassandraOnHeapHnsw.java
src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorMemtableIndex.java

- using post-filter top-k processor instead of ANN: 14x improvement on partition-restricted query in VectorLongTest

VECTOR-44: improve in-memory partition-restricted query perf

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java

For offline services such as the compactor it's possible to not have live memtables. Account for this during flushing after removing indexes.

CNDB-7037: Check that memtable exists before flushing

---

src/java/org/apache/cassandra/db/lifecycle/Tracker.java
src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/SSTableQueryContext.java
src/java/org/apache/cassandra/index/sai/disk/PostingList.java
src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/ArrayPostingList.java
test/burn/org/apache/cassandra/index/sai/LongVectorTest.java
test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingListTest.java
test/unit/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsTest.java

- fix `primaryKeySearchTest` and `partitionKeySearchTest` to use correct selector and similarity function
- fix data visibility issue during flush: make sure `SSTableAddedNotification` is sent before `MemtableDiscardedNotification` and search memtable indexes before referencing sstable indexes
- optimize VectorIndexSearcher#searchPosting for partition/range restricted query
- return empty posting if key range is not found in current sstable
- return empty posting if all row ids are shadowed
- skip ANN if matching row ids are less than max of limit and brute-force-rows

Vector 53: fix data visibility issue during flush and optimize partition restricted on-disk searcher

---

src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/distributed/org/apache/cassandra/distributed/test/CompactionControllerConfigTest.java
test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java

- AdaptiveController now recognizes and uses SCALING_PARAMETER_OPTION or STATIC_SCALING_FACTOR_OPTION (deprecated) allowing initial scaling parameters to be set for each level instead of one scaling parameter applied to every level.  This also fixes potential schema inconsistencies when switching from static to adaptive.
- moved SCALING_PARAMETERS_OPTION and STATIC_SCALING_FACTORS_OPTION from StaticController to Controller since they are now used by both StaticController and AdaptiveController.

- AdaptiveController no longer uses STARTING_SCALING_PARAMETER.

---

src/java/org/apache/cassandra/db/compaction/CompactionPick.java
src/java/org/apache/cassandra/db/compaction/ShardManager.java
src/java/org/apache/cassandra/db/compaction/ShardManagerDiskAware.java
src/java/org/apache/cassandra/db/compaction/ShardManagerNoDisks.java
src/java/org/apache/cassandra/db/compaction/ShardManagerTrivial.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.md
src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/ShardedCompactionWriter.java
src/java/org/apache/cassandra/db/compaction/unified/ShardedMultiWriter.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
src/java/org/apache/cassandra/db/compaction/unified/UnifiedCompactionTask.java
src/java/org/apache/cassandra/db/compaction/unified/shards_graph_lambda_0.svg
src/java/org/apache/cassandra/db/compaction/unified/shards_graph_lambda_0_33.svg
src/java/org/apache/cassandra/db/compaction/unified/shards_graph_lambda_0_5.svg
src/java/org/apache/cassandra/db/compaction/unified/shards_graph_lambda_1.svg
src/java/org/apache/cassandra/tools/CompactionLogAnalyzer.java
src/java/org/apache/cassandra/utils/FBUtilities.java
src/java/org/apache/cassandra/utils/Overlaps.java
test/distributed/org/apache/cassandra/distributed/test/UnifiedCompactionDensitiesTest.java
test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionStrategyStatisticsTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyGetSelectionTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java
test/unit/org/apache/cassandra/utils/OverlapsTest.java

Add `sstable_growth` and `reserved_threads_per_level`.
Add support for V1-compatible mode.
Prioritize lower levels on equal overlap.
Remove `l0_shards_enabled` parameter, use `base_shard_count: 1`.
Correct rounding in `getNumShards`.
Deal with sstable repetition in non-transitive modes.
Extract Overlaps class.
Improve documentation.
Add a lot more tests.

STAR-1878: Add additional configuration parameters and tests for UCS density

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

Avoids the following exception when getting level for expired tables.
```
ERROR [compaction-scheduler] 2023-06-06 10:06:30,585 CompactionTasksOrganizer.java:536 - Error whilst supplying compaction tasks for "35376531663064332d313431372d343166662d393565372d353563666135313964656664_data_endpoint_auth"."token":
java.lang.IllegalArgumentException: Index should be >= 0: -1
at org.apache.cassandra.db.compaction.unified.StaticController.getScalingParameter(StaticController.java:134)
at org.apache.cassandra.db.compaction.UnifiedCompactionStrategy$Level.<init>(UnifiedCompactionStrategy.java:1167)
at org.apache.cassandra.db.compaction.UnifiedCompactionStrategy.getLevel(UnifiedCompactionStrategy.java:820)
at com.datastax.cndb.compactor.CompactionTasksOrganizer.createAggregate(CompactionTasksOrganizer …
```

CNDB-7007 return expired tables level from getLevels

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java

- make splitInNonOverlappingSets public, it will be used by CNDB to parallelize GC work

CNDB-6999 open UCS api

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.md
src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/Reservations.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyGetSelectionTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyGetSelectionWithRepeatsTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java

Last piece of the UCS improvements, to avoid making people choose between thread utilization and compaction responsiveness.
These fallout tests demonstrate the effect (1TB test):
- 30 threads max overlap graph [per level](http://fallout.aws.dsinternal.org/tests/ui/branimir.lambov@datastax.com/EC2-CC-1TB-key-value/54d3ee9d-7cf8-4f05-b1f1-e79cf2f6f9ba/artifacts/server/node0/cassandra_logs/compaction_report.html?metric=Max_overlapping_SSTables) vs. [no reservations](http://fallout.aws.dsinternal.org/tests/ui/branimir.lambov@datastax.com/EC2-CC-1TB-key-value/a554772f-f651-4e28-8e7a-4dc2bbf0c827/artifacts/server/node0/cassandra_logs/compaction_report.html?metric=Max_overlapping_SSTables) vs. [level or below](http://fallout.aws.dsinternal.org/tests/ui/branimir.lambov@datastax.com/EC2-CC-1TB-key- …

STAR-1880: Permit a mode where UCS reserved threads are also used for lower levels

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/CompactionManager.java
src/java/org/apache/cassandra/db/lifecycle/Tracker.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
src/java/org/apache/cassandra/notifications/MetricsNotification.java
test/distributed/org/apache/cassandra/distributed/test/CompactionControllerConfigTest.java
test/unit/org/apache/cassandra/db/compaction/BackgroundCompactionsTest.java
test/unit/org/apache/cassandra/db/lifecycle/TrackerTest.java

In order for Adaptive UCS to make good decisions, the compaction leader needs access to various metrics from writers:
- time to flush 1kb of data
- time per query on sstable
- number of read requests
In order to ensure the compaction leader is receiving metrics from each writer, writers periodically publish a `MetricsNotification` which translates to a `MetricsEvent` in CNDB. The `MetricsEvent` is published to etcd and contains the necessary writer metrics that the adaptive controller needs to make informed decisions. The `UnifiedCompactionEnvironment` in CNDB listens for these events and updates the respective values.
*Note* This currently only includes writer metrics. Compactor metrics will require something similar

CNDB-7135 Adaptive UCS Metrics in CNDB

---

src/java/org/apache/cassandra/index/sai/disk/hnsw/ExtendedHnswGraph.java

Some low-hanging fruit.
When writing the HNSW to disk, we:
- go through levels
- grab all ordinals showing up at that level in the HNSW
- sort the ordinals
- write them to disk
At level 0, we know every ordinal of the HNSW will necessarily show up, so we should be able to avoid any need to sort here.

Avoiding sorting node ordinals for level 0

---

src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorCache.java
test/unit/org/apache/cassandra/index/sai/disk/hnsw/RandomlyConnectedHnswGraph.java
test/unit/org/apache/cassandra/index/sai/disk/hnsw/VectorCacheTest.java

This PR is meant to simplify and "fix" how we populate the vector cache. As described, we are looking to run [breadth-first search](https://github.com/datastax/cassandra/blob/fab67bb13499691f813c893cd39a3bbd406653d2/src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorCache.java#L32-L35) at each level, but I don't believe we are quite achieving our goal.
**WHAT'S WRONG? AN EXAMPLE**
I initially confused myself a bit when attempting to track more complicated traversals in my head, so a really simple example may be best.
Consider the following example graph where maximum fanout `M` = 3 and `entry_node` = 0, let’s assume our cache can only accommodate 4 nodes:
Let:
- `q` = node queue
- `visited` = visited set (which is cleared between levels)
- `cached_nodes` = global set of visited nodes …

VECTOR-79: Simplify population of VectorCache

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

When the target column for an SAI is part of the primary key and is analyzed by the LuceneAnalyzer, queries do not return correct results. Until the underlying feature is solved, do not allow these kinds of indexes to be created.
This change is covered by a test to verify index creation and search works correctly for the `NoopAnalyzer` and another to verify index creation is rejected for the `LuceneAnalyzer`.

Fail SAI index creation when using analyzer on column in primary key

---

src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/MultiColumnRelation.java
src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/Relation.java
src/java/org/apache/cassandra/cql3/SingleColumnRelation.java
src/java/org/apache/cassandra/cql3/TokenRelation.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/Expression.java
test/long/index/sai/cql/AnalyzerQueryLongTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorAndLuceneTest.java

* Adds the `:` operator, a.k.a the ANALYZER_MATCHES operator. This operator only works on SAI indexes that are analyzed where analyzed means the values stored in the index are derivative values from the raw value in the column. The new operator uses the enum value `100` to prevent future collisions with the upstream CQL implementation.
* Disambiguate the `=` operator so that it cannot perform matches on an `SAI` column that is indexed. The primary motivation for this change is to prevent surprising matches. If a query is attempted using `=` where the target column only has analyzed indexes, the query must include `ALLOW FILTERING`.
* Updated many tests.

Add ANALYZER_MATCHES operation; Disallow = on analyzed SAI columns 

---

test/unit/org/apache/cassandra/service/QueryInfoTrackerTest.java
test/unit/org/apache/cassandra/service/ReadQueryTrackingTest.java

Additional test cases, as requested in https://github.com/datastax/cassandra/pull/691#discussion_r1286355413
Instead of cluttering `QueryInfoTrackerTest` with more and more test cases I wrote another, more generic test focusing more on the behaviour of tracking when there are different data models.

Additional testcases for read query tracking with different data models

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/conditions/ColumnCondition.java
src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
test/unit/org/apache/cassandra/index/sai/cql/AllowFilteringTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneUpdateDeleteTest.java

* When the `:` operator is used for indexes that do not support it, the current error is a recommendation to `ALLOW FILTERING` or an `AssertionError`. Instead, we should match the `LIKE` behavior and reject queries that attempt to use the `:` operator on columns that are not properly indexed. The `LIKE` conditional is slightly modified to simplify the logic for rejecting unsupported queries.
* When the `:` operator is used for `DELETE` and `UPDATE` queries, return a helpful error message.
* Update the `toString` method on the `ANALYZER_MATCHES` enum. The `toString` method is used to generate error messages, and it is confusing to see an error message with `: '<term>'` when it really should just be `:`.

Return more specific exception on incorrect usage of : operator

---

test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

I missed this comment https://github.com/datastax/cassandra/pull/702#discussion_r1302166034 when merging https://github.com/datastax/cassandra/pull/702. This PR adds the requested test coverage.

Test compound predicate queries for : operator

---

test/distributed/org/apache/cassandra/distributed/test/sai/IndexConsistencyTest.java

Merging https://github.com/datastax/cassandra/pull/702 broke some of the distributed integration tests because it removed the ability to search with `=` on an analyzed SAI. The fix is to selectively replace `=` with `:`.

Fix failing distributed SAI tests using : operator

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzer.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Remove the option to configure a separate query analyzer from the index's analyzer. This may be added back in the future, though we'll want to make sure that the semantics work correctly for both `:` and `=`. https://github.com/datastax/cassandra/pull/709 has some context on potential issues.

Remove ability to configure unique query_analyzer

---

test/unit/org/apache/cassandra/db/RecoveryManagerTruncateTest.java

RecoveryManagerTruncateTest::testTruncate incorrectly expected commit log replay to replay some mutations.
The condition has been changed to expect no mutations being replayed for the keyspace in which the
truncated table resides

STAR-1364: fix RecoveryManagerTruncateTest::testTruncate

---

test/unit/org/apache/cassandra/index/sai/disk/v1/KDTreeIndexSearcherTest.java

https://github.com/datastax/cassandra/pull/680 included a change that makes 5 of the `KDTreeIndexSearcherTest` tests fail. This PR essentially reverts back to the old behavior, and all of the failing tests pass.

Fix failing KDTreeIndexSearcherTest

---

src/java/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzer.java
test/distributed/org/apache/cassandra/distributed/test/sai/AnalzyerDistributedTest.java

When testing the analyzer with an integration test, I discovered an NPE from a part of the code that wasn't tested. 
Here is the code:
https://github.com/datastax/cassandra/blob/9cabec504d9f70ddfb345122dc4defed56a40f85/src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java#L91-L100
We build the Analyzer to use one of its methods, but not to analyze any text, hence the NPE.
Here is the NPE:
```
ERROR [Native-Transport-Requests-1] 2023-08-31 14:35:38,695 QueryMessage.java:121 - Unexpected error during query
java.lang.NullPointerException: null
at org.apache.cassandra.index.sai.analyzer.LuceneAnalyzer.end(LuceneAnalyzer.java:110)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.filterReplicaFilteringProtection(StorageAttachedIndexSearcher.java:99) …
```

Fix NPE in LuceneAnalyzer#end

---

src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyFactory.java
test/unit/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyTest.java

While working on #723, I was getting surprising results related to the optimization and when it was used. After digging in a bit, I discovered that the `PrimaryKey` generated by the method `PrimaryKeyMap#primaryKeyFromRowId(long)` builds a deferred key, and this key does not compute a consistent `hashCode` for the `RowAwarePrimaryKey` implementation because some values are null until `loadDeferred()` is called.
The proposed solution uses `return Objects.hash(token(), partitionKey(), clustering())`, which will always load a key if it hasn't yet been loaded.

Fix RowAwarePrimaryKey#hashCode for deferred keys

---

src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java

These are part of vector 14, but the fixes are just for exceptions while executing the queries incorrectly. Fixing the execution design will come later but in the meantime it's good to make query processing not crash, since we handle that poorly (eventually becomes a timed out query but no error as such makes its way back to the client).
Since I can't just push a fix (yay branch protection) I've included the failing tests, but commented them out because CI is dumb. What I would commit is just the two "fix" changes.

Fix exceptions when executing complex queries

---

src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

The `index_analyzer` and the non tokenizing analyzers are mutually exclusive, so we should return an error if an SAI is created with them. The current behavior is that the `index_analyzer` is used and the other options are ignored.

Reject SAI creation for invalid combinations of options

---

src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/plan/QueryViewBuilder.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java

check bloomFillter in `V1SearchableIndex#searchSSTableRowIds`, if the given keyRange is made of partition key, then check sstable BF and return empty iterator when BF check failed.
Here is the link to the issue: [Vector-72](https://datastax.jira.com/browse/VECTOR-72)

Optimize partition-aware queries to use bloom filter

---

src/java/org/apache/cassandra/index/sai/disk/hnsw/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexSearcher.java

// constants are computed by Code Interpreter based on observed comparison counts in tests
// https://chat.openai.com/share/29a25377-786f-4690-b146-12acb6acb75b

include LIMIT count in the calculation for brute force rows

---

src/java/org/apache/cassandra/index/sai/disk/format/IndexFeatureSet.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/utils/IndexFileUtils.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

rebase of https://github.com/datastax/cassandra/pull/738 on diskann3 with updates ot the changes in the branch

VECTOR-SEARCH 10: Add checksums to on-disk vector index components

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/README.md
src/java/org/apache/cassandra/index/sai/analyzer/filter/BuiltInAnalyzers.java
src/java/org/apache/cassandra/index/sai/plan/Expression.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

With https://github.com/datastax/cassandra/pull/712, we removed the `query_analyzer` because there were concerns about whether to count an index with a `query_analyzer` but no `index_analyzer` as an "analyzed column". See discussion on https://github.com/datastax/cassandra/pull/709 for additional context. In thinking through the concerns, I realized that we simply need to only allow for a `query_analyzer` to be configured when there is either an `index_analyzer` or one of the non-tokenizing analyzers.
Changes:
* Reject indexes that have invalid analyzer configuration.
* Allow users to configure different query analyzers 
* Use the right analyzer in the `Expression#validateStringValue` method (it's pretty surprising, but I noticed earlier today before knowing I would make this change that …

Add support for unique query_analyzer on analyzed SAI

---

src/java/org/apache/cassandra/index/sai/analyzer/filter/BuiltInAnalyzers.java

When the built-in analyzers were added, the `english` analyzer incorrectly mapped to the `StandardAnalyzer`. This PR fixes the mapping, but does not address the underlying indexing issues that may have already taken place.

Map built-in English analyzer to EnglishAnalyzer, not StandardAnalzyer

---

src/java/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzer.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
test/unit/org/apache/cassandra/index/sai/cql/CollectionIndexingTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

The current text search feature fails on the final line of this test:
```java
@Test
public void testEnglishStopWordTest() throws Throwable
{
createTable("CREATE TABLE %s (id text PRIMARY KEY, val text)");
executeNet("CREATE CUSTOM INDEX ON %s(val) USING 'StorageAttachedIndex' " +
"WITH OPTIONS = {'index_analyzer':'english'}");
waitForIndexQueryable();
execute("INSERT INTO %s (id, val) VALUES ('1', 'the test')");
flush();
assertRows(execute("SELECT id FROM %s WHERE val : 'test'"), row("1"));
assertRows(execute("SELECT id FROM %s WHERE val : 'the'"));
}
```
The problem is how we are building the query.
Changes:
* Update the `Operation#analyzeGroup` method to map an empty analyzer result to an empty byte buffer. This solution feels a bit like a hack, but it makes sense for a couple reasons. …

Fix text search queries filtered to empty string due to stop words

---

src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/v1/VectorIndexSearcher.java

Cherry picked from 03492e5c9bddc503f74b20b199989fd1ec7597e5. These tests were flaky but are not with the patch: 
Multiple tests fail intermittently at
```
java.lang.AssertionError: null
at org.apache.cassandra.index.sai.ScoreStoreProxyImpl.mapStoredScoreForRowIdToPrimaryKey(ScoreStoreProxyImpl.java:41)
```
VLT.multiSSTablesTest and multipleNonAnnSegmentsTest fail about 50% of the time, multipleSegmentsMultiplePostingsTest fails about 10% of the time

Skip similarity score caching when using brute force

---

src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorPostings.java

this also fixes a race between add and remove of the same key

fix race where addGraphNode can be skipped if multiple concurrent threads add the same vector + key

---

src/java/org/apache/cassandra/index/sai/analyzer/ArgsStringLoader.java
src/java/org/apache/cassandra/index/sai/analyzer/JSONAnalyzerParser.java
test/unit/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

The current analyzer implementation rejects certain stop word and synonym filters because they open files. We can instead allow for these parameters to be passed as part of the `args` block, as you can see in the tests.

Accept lucene file configs as json values in SAI OPTIONS

---

src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

Without the change to `VectorMemtableIndex`, we get the following error in the test:
```
java.lang.AssertionError: null - null 1
at org.apache.cassandra.index.sai.utils.RangeIterator.<init>(RangeIterator.java:56)
at org.apache.cassandra.index.sai.disk.vector.VectorMemtableIndex$ReorderingRangeIterator.<init>(VectorMemtableIndex.java:348)
at org.apache.cassandra.index.sai.disk.vector.VectorMemtableIndex.limitToTopResults(VectorMemtableIndex.java:224)
at org.apache.cassandra.index.sai.IndexContext.limitToTopResults(IndexContext.java:316)
at org.apache.cassandra.index.sai.plan.QueryController.getTopKRows(QueryController.java:308)
at org.apache.cassandra.index.sai.plan.Operation.buildIterator(Operation.java:227)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.analyze(Storag …
```

VectorMemtableIndex should be able to handle queries when empty

---

src/java/org/apache/cassandra/index/sai/view/IndexViewManager.java

While working on vsearch-14, I came across a potential data race. I'm not sure that it is an issue, but since we're using an `AtomicReference`, it seems like we should make sure to update the reference in an atomic way.

Fix IndexViewManager#invalidate race with AtomicRef

---

test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java

This PR should increase test coverage for `V2VectorIndexSearcher#bitsOrPostingListForKeyRange`.

Improve override of globalBruteForceRows to increase test coverage

---

src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/SSTableRowIdKeyRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/v1/PartitionAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsReader.java
test/microbench/org/apache/cassandra/test/microbench/index/sai/v2/sortedbytes/SortedTermsBenchmark.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/LegacyOnDiskFormatTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/KDTreeIndexBuilder.java
test/unit/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsTest.java

The `rowIdFromPrimaryKey` method is implemented as a `ceiling` method--it returns the row id for the least Primary Key greater than or equal to the passed PK. The name and the interface's javadoc imply a more straightforward definition: return the row id for the PK or return a `long` indicating there is no such row for the given PK.
The implementation's `ceiling` semantics cause a problem when we build the ignore bits for a pure ANN search becaus we do a reverse lookup from PK to sstable row id and assume that those row ids ought to be ignored.
Another minor detail: the two implementations of `PrimaryKeyMap` return different values to indicate a row was not found. In `PartitionAwarePrimaryKeyMap`, it returns a negative number but in `RowAwarePrimaryKeyMap`, it returns `Long.MAX_VALUE`. …

Fix RowID lookup from PK for shadowed key ignore bits

---

src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/SSTableRowIdKeyRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/v1/PartitionAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsReader.java
test/unit/org/apache/cassandra/index/sai/disk/v1/LegacyOnDiskFormatTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/KDTreeIndexBuilder.java
test/unit/org/apache/cassandra/index/sai/disk/v2/sortedterms/SortedTermsTest.java

Standardize the "not found" result for all `PrimaryKeyMap` implementations and return a negative value to indicate a row is not found. Remove the `isNotFound` method.
Context: `PartitionAwarePrimaryKeyMap` returns `-1` when there is no such value. `RowAwarePrimaryKeyMap` returns `Long.MAX_VALUE` when there is no such value for `#ceiling` and for `#exactRowIdForPrimaryKey`, but returns `-1` for `#floor`.

Standardize not found logic for PrimaryKeyMap

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java

This is required to fix the schema issue observed in https://github.com/riptano/cndb/issues/7820

CNDB-7820 Added CreateTableStatement#isCompactStorage to externally observe if the statement is meant to create a compact storage table

---

src/java/org/apache/cassandra/db/ReadExecutionController.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java

Fixes https://github.com/riptano/VECTOR-SEARCH/issues/27
Also fixes SinglePartitionReadCommand.queryMemtableAndSSTablesInTimestampOrder didn't update metrics.updateSSTableIterated()

VECTOR-SEARCH-27: Summarize sstable merging results for index queries

---

src/java/org/apache/cassandra/index/sai/utils/SegmentOrdering.java

I removed the detail about returning the results in PK ordering since it is not a strict requirement.

Update SegmentOrdering javadoc

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/utils/RangeConcatIterator.java
test/unit/org/apache/cassandra/index/sai/utils/AbstractRangeIteratorTest.java

The RangeConcatIterator is used to join ordered RangeIterators. As such, we can remove the PQ and replace it with a list/iterator. This change particularly benefits us for intersections because it is common for those to incur many calls to skipTo, which is where we currently remove and subsequently put range iterators.

Replace RangeConcatIterator's PriorityQueue with List

---

src/java/org/apache/cassandra/index/sai/utils/RangeConcatIterator.java

This reverts commit e0187ab19c4de00b73d17112343933fb59c2a8b6, which was merged in https://github.com/datastax/cassandra/pull/816.
I incorrectly assumed that the check to `range.getCount() > 0` meant all RangeIterators had PKs.

Revert "Simplify logic for computeNext"

---

src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java

fixes https://github.com/riptano/VECTOR-SEARCH/issues/41
Rootcause: https://github.com/datastax/cassandra/commit/1ff6992354e8411f9f7c48a76f0aadb4a00f2789#diff-413473b3c07156bafebdc9a25e51d4395101007fb9bb13cb03cec9fbc4b92040R207-L184

Still count metrics if trieSegmentsHit etc was incremented

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/sortedterms/ReversedTrieRangeIterator.java

This PR fixes two issues. Together, the two issues effectively cancel each other out and work correctly on `vsearch`, however, when we merge the switch proposed in #801, we do not get the cancellation.
The problem is that for range queries the right bound of an AbstractBound can be less than the left bound, and this matters when finding the `floor` for a token, since our definition of floor does not treat numbers as a ring. The current code works because when the PK does not have a floor, ReversedTrieRangeIterator returns Long.MAX_VALUE, and we get the correct range of sstable row ids.
The solution:
* Update ReversedTrieRangeIterator to return -1, and adopt the behavior we will see in #801.
* Update `V2VectorIndexSearcher#bitsOrPostingListForKeyRange` so that it correctly handles the …

Make ReversedTrieRangeIterator return correct value when term is not found

---

src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/metrics/KeyspaceMetrics.java
src/java/org/apache/cassandra/metrics/TableMetrics.java

https://github.com/riptano/VECTOR-SEARCH/issues/32
I decided on approach 1 ("add a new metric for shadowed rows"), otherwise it will be hard to match metrics for number of loops with number of shadowed rows if they are mixed with tombstones.

VECTOR-SEARCH 32: shadowed rows metrics

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

There is currently a bug where we add the ANN ordering clause to every level of a StatementRestriction. Before #758, that meant we were executing the order by clause for each nested group of clauses. After #758, those queries are actually broken.
The current approach for this PR is to only add the ANN restriction at the top level.

Only add ANN Ordering to top level of StatementRestrictions

---

test/unit/org/apache/cassandra/cql3/validation/entities/UFTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/AggregationTest.java
test/unit/org/apache/cassandra/db/SchemaCQLHelperTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/MultipleColumnIndexTest.java
test/unit/org/apache/cassandra/index/sasi/SASICQLTest.java

https://github.com/datastax/cassandra/pull/826 removed a wrapper for an exception, which broke several (brittle) tests.

Fix failing tests that relied on InvalidRequestException as cause of caught exception

---

src/java/org/apache/cassandra/index/sai/utils/RangeUnionIterator.java

Noticed while looking at his code.
New ArrayList() makes sense in case the iterator receives mutable list of ranges.

avoid causing double close calls of RangeIterators in RangeUnionIterator

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Fix the logic for determining when an index supports the `:` operator. If the operator is `:` or if the index is analyzed, we must verify that the index is analyzed and the operator is `:`.

Fix when an index accepts the : operator

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java

`topKFor` must return at least the `limit` to ensure correct results.

Ensure topKFor limit is at least the limit

---

src/java/org/apache/cassandra/repair/consistent/admin/PendingStats.java
test/distributed/org/apache/cassandra/distributed/test/IncRepairAdminTest.java

It seems that `repair_admin summarize-pending` command had a bug which resulted in it throwing `OpenDataException`. This patch adds a missing composite in `PendingStats.toComposite` which ensures the conversion happens correctly.

STAR-1897: Fix repair_admin summarize-pending command

---

src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java

zero impact on large embeddings (they fill up at 1.2 and 1.4 is a no-op) but increases performance for 2D indexes

build with alpha=1.2 instead of 1.4

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/distributed/org/apache/cassandra/distributed/test/sai/VectorDistributedTest.java
test/unit/org/apache/cassandra/index/sai/cql/GeoDistanceRestrictionTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorInvalidQueryTest.java

Previous errors looked like `Operation failed - received 0 responses and 2 failures: UNKNOWN from /127.0.0.2:7012, UNKNOWN from /127.0.0.1:7012` because the operation failed at the replica. This adds a coordinator check to provide a meaningful exception to the client.

Validate vector at coordinator

---

test/distributed/org/apache/cassandra/distributed/impl/Instance.java

Getting rid of random test failures with the same suppressed NPE in stack, like
```
org.apache.cassandra.distributed.shared.ShutdownException: Uncaught exceptions were thrown during test
at org.apache.cassandra.distributed.impl.AbstractCluster.checkAndResetUncaughtExceptions(AbstractCluster.java:910)
at org.apache.cassandra.distributed.impl.AbstractCluster.close(AbstractCluster.java:896)
at org.apache.cassandra.distributed.test.CasWriteTest.close(CasWriteTest.java:82)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Suppressed: …
```

Null check before logging in org.apache.cassandra.distributed.impl.Instance

---

src/java/org/apache/cassandra/index/sai/QueryContext.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

This adds two tests.  Both of them fail on current HEAD, but this patch also disables the assertion that causes the second one to fail, so it passes now.  This demonstrates that the assertion can be disabled without nasty side effects like an infinite loop.  Fixing both of these tests correctly is another ticket.

disable failing assert

---

test/distributed/org/apache/cassandra/distributed/test/RepairCoordinatorBase.java

Tests occasionally fail with stack like
```
org.apache.cassandra.distributed.shared.ShutdownException: Uncaught exceptions were thrown during test
at org.apache.cassandra.distributed.impl.AbstractCluster.checkAndResetUncaughtExceptions(AbstractCluster.java:910)
at org.apache.cassandra.distributed.impl.AbstractCluster.close(AbstractCluster.java:896)
at org.apache.cassandra.distributed.test.RepairCoordinatorBase.teardownCluster(RepairCoordinatorBase.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Suppressed: java.lang.RuntimeException: Could …
```

Flaky tests caused by exceptions in test teardown

---

src/java/org/apache/cassandra/utils/memory/BufferPool.java
test/distributed/org/apache/cassandra/distributed/impl/Instance.java
test/distributed/org/apache/cassandra/distributed/test/sai/NativeIndexDDLTest.java

sometimes test flakes with
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: Status of chunk [slab java.nio.DirectByteBuffer[pos=0 lim=131072 cap=131072], slots bitmap 0, capacity 131072, free 0, owner null, recycler org.apache.cassandra.utils.memory.BufferPool$GlobalPool@3b210747] was not EVICTED
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
at org.apache.cassandra.distributed.test.sai.NativeIndexDDLTest.verifyIndexWithDecommission(NativeIndexDDLTest.java:208)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) …
```

Flaky test NativeIndexDDLTest / Status of chunk was not EVICTED

---

pylib/cqlshlib/copyutil.py

This patch adds a converter that allows parsing vector literals passed via csv files to the COPY command (https://github.com/riptano/VECTOR-SEARCH/issues/54).
The test that covers the change has been implemented as a dtest - https://github.com/datastax/cassandra-dtest/tree/vsearch-54.

VECTOR-SEARCH-54: Add VECTOR type support to COPY command

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.md
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/shards_graph_lambda_1.svg
test/distributed/org/apache/cassandra/distributed/test/UnifiedCompactionDensitiesTest.java
test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ShardedMultiWriterTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java

* Changed default min_sstable_size from 0 to 100MiB
* Changed default sstable_growth from 0 to 0.333
* If baseShardCount is not a power of 2, split only to powers of 2 that are divisors of baseShardCount
* No longer set baseShardCount to 1 for system tables
* Updated unit tests to work with new defaults
* Updated UnifiedCompactionStrategy.md to include the new defaults

STAR-1898: Update UCS defaults and option names

---

src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyWithSource.java
src/java/org/apache/cassandra/index/sai/disk/v1/PartitionAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/KDTreeIndexBuilder.java

Rebooting https://github.com/datastax/cassandra/pull/889, didn't realize I'd need a new PR after force-pushing

add PrimaryKeyWithSource to accelerate same-sstable comparisons

---

src/java/org/apache/cassandra/index/sai/disk/PostingListRangeIterator.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/VectorTopKProcessor.java

Move checkpoint into try-with-resources block; prevent leak.
We are leaking references after `AbortedOperationException` is thrown by the `query.checkpoint()` in the modified code.
Also, unwrap the exception when it is an `AbortedOperationException` so we catch it later.

Improve timeout handling; prevent resource leaks

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

When a hybrid ANN query gets PKs in the hybrid query, we search all sstables and memtables with those PKs to get the topk. As such, we cannot assume that the source of a PK is an sstbale, even when we're searching an sstable.

Remove assumption that PK is PrimaryKeyWithSource in limitToTopResults

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

* In limit to top results, we can skip a call to `primaryKeyMap.exactRowIdOrInvertedCeiling(primaryKey);` when we know the `ceilingPrimaryKey` is equal to a primary key in the `keysInRange` list.
* Add a test to verify the fix from #902

Minor optimization for limitToTopResults; add test covering #902 patch

---

src/java/org/apache/cassandra/index/sai/IndexContext.java

This cuts startup time by ~50% on my single-ssd local machine with around a dozen sstables containing a total of ~1M rows with 3 SAI indexes.  (The actual index-opening speedup is even higher since there is other stuff happening on startup too.)
Machines with more concurrent iops available should benefit even more.

parallelize index opening

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java

Goal is to allow testing the versioning code without your test case vanishing out from under you if you make a mistake.
Needed to update the logic in three places.  Possibly more, but these three solve the problem of files vanishing immediately after startup.

add cassandra.sai.delete_corrupt_components, true by default

---

src/java/org/apache/cassandra/hints/HintMessage.java
src/java/org/apache/cassandra/hints/HintsDispatchExecutor.java
src/java/org/apache/cassandra/hints/HintsDispatcher.java
src/java/org/apache/cassandra/hints/HintsEndpointProvider.java
src/java/org/apache/cassandra/net/EndpointMessagingVersions.java
src/java/org/apache/cassandra/net/Message.java
test/unit/org/apache/cassandra/hints/HintMessageTest.java
test/unit/org/apache/cassandra/hints/HintsEndpointProviderTest.java
test/unit/org/apache/cassandra/hints/HintsServiceTest.java
test/unit/org/apache/cassandra/net/MessageSerializationPropertyTest.java

- Hint version is now optional. If the version is missing, the hint won't be sent. A retry will 
be attempted later.
- Messages pre 4.0 use peer address retrieved from the actual connection. 
Before this patch the messages used the address 
retrieved from message bytes, which didn't work in MR setups (non public address was used).
With the patch, message addressing pre 4.0 is consistent with messages post 4.0.

CNDB-8201 hint version is optional, also use the correct peer address

---

src/java/org/apache/cassandra/db/SortedLocalRanges.java
src/java/org/apache/cassandra/db/compaction/writers/CompactionAwareWriter.java
src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/utils/memory/SlabAllocator.java
test/unit/org/apache/cassandra/db/SortedLocalRangesTest.java
test/unit/org/apache/cassandra/db/memtable/MemtableSizeTestBase.java
test/unit/org/apache/cassandra/db/memtable/TrieMemtableConfigTest.java

Minor change: increase default shard count
Much bigger impact: fix the case where SortedLocalRanges ends up empty, if SLR.ranges is empty then you always only get a single shard

Tests go zoom

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

I attempted to fix this bug with #902. That fix missed the (common) case where an sstable has multiple segments making the `keys` a strict superset of the `keysInRange`.

V2VectorIndexSearcher: use correct keys list for seq scan

---

src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/utils/IndexFileUtils.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReaderBuilder.java
src/java/org/apache/cassandra/io/storage/StorageProvider.java

When dealing with remote storage, we need a way to impact what kind of access mode is used for sstable components. For sstable data and "primary" index, this can be somewhat configured, but for SAI index components, this is currently hard-coded.
This patch allows `StorageProvider` to customize the concrete `FileHandle` used for both sstable files and SAI ones.  As `StorageProvider` is about abstracting "storage" in order to potentially allow the use of tiered/remote storage, it feels like it should have a say in how file are acccessed in practice.

Allow `StorageProvider` to impact the creation of `FileHandle` builders

---

src/java/org/apache/cassandra/db/memtable/Memtable.java
src/java/org/apache/cassandra/db/memtable/SkipListMemtable.java
src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/utils/SoftLimitUtil.java
test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
test/unit/org/apache/cassandra/index/sai/utils/SoftLimitUtilTest.java

If there are too many rows matching the `WHERE` clause, do `ORDER BY column ANN OF ...` first and then post-filter.

wip: Alternate query path: search vector index first and post-filter

---

src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java

New SAI metrics:
- `SortThenFilterQueriesCompleted`
- `FilterThenSortQueriesCompleted`
The counters are increased by queries that involve both sorting and filtering.

Sort filter query metrics

---

src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

I missed the change on this line: https://github.com/datastax/cassandra/pull/915/files#r1445373254.
After writing a worst case scenario test, it looks like the logic before #915 was wrong too.

Fix SAIS#search to correctly count shadowed keys in termination logic

---

src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/CQL3Type.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/AlterTableStatement.java
src/java/org/apache/cassandra/db/Columns.java
src/java/org/apache/cassandra/db/SerializationHeader.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java
src/java/org/apache/cassandra/db/marshal/TupleType.java
src/java/org/apache/cassandra/db/marshal/TypeParser.java
src/java/org/apache/cassandra/exceptions/InvalidColumnTypeException.java
src/java/org/apache/cassandra/schema/CQLTypeParser.java
src/java/org/apache/cassandra/schema/ColumnMetadata.java
src/java/org/apache/cassandra/schema/DroppedColumn.java
src/java/org/apache/cassandra/schema/SchemaKeyspace.java
src/java/org/apache/cassandra/schema/TableMetadata.java
src/java/org/apache/cassandra/serializers/AbstractTypeSerializer.java
src/java/org/apache/cassandra/tools/JsonTransformer.java
src/java/org/apache/cassandra/utils/NativeSSTableLoaderClient.java
test/distributed/org/apache/cassandra/distributed/test/DropUDTWithRestartTest.java
test/unit/org/apache/cassandra/Util.java
test/unit/org/apache/cassandra/cql3/CQL3TypeLiteralTest.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/cql3/selection/TermSelectionTest.java
test/unit/org/apache/cassandra/cql3/validation/entities/TupleTypeTest.java
test/unit/org/apache/cassandra/db/ColumnsTest.java
test/unit/org/apache/cassandra/db/SchemaCQLHelperTest.java
test/unit/org/apache/cassandra/db/marshal/TypeParserTest.java
test/unit/org/apache/cassandra/schema/TableMetadataTest.java
test/unit/org/apache/cassandra/schema/TupleTypesRepresentationTest.java

Allow dropping non-frozen/multi-cell UDTs. This is done by adding partial support for non-frozen/multi-cell tuples, so dropped UDT columns are transformed into an equivalent tuple type. The support for non-frozen tuples is not user-facing, so users can't create non-frozen tuples. At the CQL level all tuples are considered frozen, so `tuple<>` and `frozen<tuple>` are still considered equivalent.
This PR is based on the PR for CNDB-7789, which is still to be reviewed.

CNDB-8229: Allow dropping non-frozen UDT columns

---

src/java/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingList.java
test/unit/org/apache/cassandra/index/sai/disk/PostingListRangeIteratorTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/KDTreeIndexBuilder.java
test/unit/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingListTest.java

Fixes https://github.com/riptano/VECTOR-SEARCH/issues/76

VSEARCH 76: IllegalArgumentException in MergePostingList.nextPosting

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/commitlog/MemoryMappedSegment.java
test/distributed/org/apache/cassandra/db/commitlog/MemoryMappedSegmentStartupTest.java
test/unit/org/apache/cassandra/db/commitlog/MemoryMappedSegmentTest.java

https://datastax.jira.com/browse/STAR-1902
Introduce system property "cassandra.commitlog.skip_file_advice" that allows to skip the native call to "fadvise" with "FADV_DONTNEED" argument. The native call is not skipped by default.
This patch was originally implemented in DSE 5.1 under DSP-22315.
**Some context for why it's needed**
As DSE7 depends on converged core, in particular on the [vsearch](https://github.com/datastax/cassandra/tree/vsearch) branch we need to merge it to that branch - the related PR https://github.com/datastax/cassandra/pull/933.
This patch aims to merge the same changes to ds-trunk to prevent history divergence.

STAR-1902: Option to disable call to NativeLibrary.trySkipCache

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/commitlog/MemoryMappedSegment.java
test/distributed/org/apache/cassandra/db/commitlog/MemoryMappedSegmentStartupTest.java
test/unit/org/apache/cassandra/db/commitlog/MemoryMappedSegmentTest.java

https://datastax.jira.com/browse/STAR-1902
Introduce system property "cassandra.commitlog.skip_file_advice" that allows to skip the native call to "fadvise" with "FADV_DONTNEED" argument. The native call is not skipped by default.
https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-pr-gate/view/change-requests/job/PR-933/
**Some context for why it's needed**
This patch was originally implemented in DSE 5.1 under DSP-22315.
The motivation for merging it to [vsearch](https://github.com/datastax/cassandra/tree/vsearch) branch is that DSE7 (that depends on that branch) will need it for backward compatibility with 5.1 for some customers.

STAR-1902: Option to disable call to NativeLibrary.trySkipCache (vsearch)

---

src/java/org/apache/cassandra/db/compaction/CompactionManager.java
test/unit/org/apache/cassandra/db/repair/PendingAntiCompactionBytemanTest.java

As reported by [DSP-23936](https://datastax.jira.com/browse/DSP-23936), it seems that `nodetool stop ANTICOMPACTION` doesn't have any effect.
I think this bug was introduced by [STAR-410](https://datastax.jira.com/browse/STAR-410), and it doesn't affect OSS. 
`CompactionManager#getAntiCompactionIterator` used to return an anonymous class extending `CompactionIterator` and overriding the `isStopRequested` method. OSS still has this behaviour: https://github.com/apache/cassandra/blob/43eb2a4bdee169e0f9338afab4f70009604997b2/src/java/org/apache/cassandra/db/compaction/CompactionManager.java#L1895-L1904
However, [STAR-410](https://datastax.jira.com/browse/STAR-410) modified that method so the anonymous `CompactionIterator` overrides the `CompactionIterator#createOperation` method to return an …

Fix ignored nodetool stop ANTICOMPACTION

---

src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
test/unit/org/apache/cassandra/index/sai/cql/AnalyzerTest.java

Fixes (or rather prevents) https://github.com/riptano/VECTOR-SEARCH/issues/81 and https://github.com/riptano/VECTOR-SEARCH/issues/80

Only allow analyzer on analyzable types

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/ConsistencyLevel.java
test/unit/org/apache/cassandra/db/ConsistencyLevelTest.java

https://datastax.jira.com/browse/STAR-1903
Add a system property (dse.consistency_level.three_means_all_but_one) that changes the behaviour of ConsistencyLevel.THREE to mean ALL_BUT_ONE, i.e. that all replicas except for at most one in the cluster (across all DCs) must accept the write for it to be successful. 
This is a bit disingenuous and hacky but a simple change that introduces a new
ConsistencyLevel, since otherwise that would require client and protocol changes.
https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-pr-gate/view/change-requests/job/PR-936/4/
Related dtest PR: https://github.com/datastax/cassandra-dtest/pull/69
* https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-build/696/testReport/dtest-bti.consistency_test/TestAllButOneAvailabilitySimpleStrategy …

STAR-1903: ConsistencyLevel.THREE means ALL_BUT_ONE (vsearch)

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/ConsistencyLevel.java
test/unit/org/apache/cassandra/db/ConsistencyLevelTest.java

https://datastax.jira.com/browse/STAR-1903
Add a system property (dse.consistency_level.three_means_all_but_one) that changes the behaviour of ConsistencyLevel.THREE to mean ALL_BUT_ONE, i.e. that all replicas except for at most one in the cluster (across all DCs) must accept the write for it to be successful.
This is a bit disingenuous and hacky but a simple change that introduces a new
ConsistencyLevel, since otherwise that would require client and protocol changes.
Related dtest PR: https://github.com/datastax/cassandra-dtest/pull/69
**Some context for why it's needed**
This patch was originally implemented in DSE under [DSP-22366](https://datastax.jira.com/browse/DSP-22366), the goal of this PR is to port it to CC to ensure DSE7 remains backwards compatible with 5.1 and 6.8.
This PR …

STAR-1903: ConsistencyLevel.THREE means ALL_BUT_ONE

---

src/java/org/apache/cassandra/db/ReadCommandVerbHandler.java
src/java/org/apache/cassandra/net/Message.java
src/java/org/apache/cassandra/net/SensorsCustomParams.java
src/java/org/apache/cassandra/sensors/Sensor.java
src/java/org/apache/cassandra/sensors/SensorsRegistry.java
test/unit/org/apache/cassandra/net/MessageTest.java
test/unit/org/apache/cassandra/net/SensorsCustomParamsTest.java
test/unit/org/apache/cassandra/sensors/SensorsReadTest.java
test/unit/org/apache/cassandra/sensors/SensorsRegistryTest.java

Addresses: #https://github.com/riptano/cndb/issues/8464
Add `READ_BYTES` and `READ_BYTES_TOTAL` sensor values to the ReadCommandVerbHandler outbound messages as a custom map header

CNDB-8464 Propagate UCUs (READ_BYTES) from Writer to Coordinator

---

src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReader.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReaderTest.java

#938 was merged with two test failures. This PR fixes the failures. Note that the test failures are not regressions in production code, so this isn't an urgent PR.

Return PostingList.EMPTY, not null; fix BKDReaderTest

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CloseableReranker.java
src/java/org/apache/cassandra/index/sai/disk/vector/JVectorLuceneOnDiskGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorSupplier.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorsView.java
test/unit/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIteratorTest.java

Fixes two key issues:
* The `CassandraOnDiskHnsw` implementation's `VectorsWithCache` was incorrectly accessed by multiple threads. It is now created once per query and closed when the query finishes using the object.
* `CassandraDiskAnn` created a vector view per thread without ever closing the view. This leaks random access readers.
Misc. cleanup:
* Removed unused reference to QueryContext in `VectorsWithCache`
* Converted `BruteForceRowIdIterator` to a `CloseableIterator`

Use vector view per query and close view when done

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/unified/ShardedMultiWriter.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/NumericIndexWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableMultiWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableRewriter.java
src/java/org/apache/cassandra/io/sstable/SSTableTxnWriter.java
src/java/org/apache/cassandra/io/sstable/SimpleSSTableMultiWriter.java
src/java/org/apache/cassandra/io/sstable/format/RangeAwareSSTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/SSTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/SSTableZeroCopyWriter.java
src/java/org/apache/cassandra/io/sstable/format/SortedTableWriter.java
src/java/org/apache/cassandra/io/storage/StorageProvider.java

There is currently 2 places where an sstable component is accessed during the flush of that sstable before the enclosing [`LifecycleTransation.prepareToCommit`](https://github.com/datastax/cassandra/blob/ds-trunk/src/java/org/apache/cassandra/db/ColumnFamilyStore.java#L1413) method has been called:
- for SAI numeric indexes, the `NumericIndexWriter` class does a reading of the `KD_TREE` component to finalize the `KD_TREE_POSTING_LISTS` one.
- the `SSTableReader` objects are opened in the `SSTableMultiWriter.prepareToCommit`, which happens before the `LifecycleTransaction` own `prepareToCommit`, and this opening also triggers some reads (of the partition index, at least with trie sstables).
That `LifecycleTransation.prepareToCommit` call is where sstable contents are uploaded to remote …

Fix early component reading

---

src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/NodeScoreToScoredRowIdIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/utils/MergeScoredPrimaryKeyIterator.java
src/java/org/apache/cassandra/index/sai/utils/PriorityQueueIterator.java
src/java/org/apache/cassandra/index/sai/utils/ScoredRowIdPrimaryKeyMapIterator.java

Clean up the iterators created by #929 based on this comment: https://github.com/datastax/cassandra/pull/955#discussion_r1470290255.
Changes:
* Use the `org.apache.cassandra.utils.AbstractIterator` abstract class to simplify iterators introduced in #929. The abstract class implements `Iterator<V>, PeekingIterator<V>, CloseableIterator<V>`, which means this is only an implementation change and doesn't affect signatures.

Replace CloseableIterator with AbstractIterator

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/unit/org/apache/cassandra/index/sai/cql/CollectionIndexingTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java

This PR sets 8KiB as the default for `cassandra.sai.max_string_term_size_kb`, instead of 1KiB.
It also increases the value of `cassandra.sai.max_frozen_term_size_kb` from 5KiB to the same 8KiB, because I think that the max term size for frozen collections should be at least as large as the one for individual items. I wonder if we should use an even larger value for frozen collections.
There are some additional tests, particularly for `cassandra.sai.max_vector_term_size_kb`. We aren't modifying that default here, but it seemed not covered by tests similar to the ones for the other term size limits.
By the way, `cassandra.sai.max_vector_term_size_kb` implictily sets a limit on the number of dimensions that an indexed vector column can have, if the vector subtype has fixed width. The default …

VECTOR-SEARCH-73: Increase SAI max_string_term_size_kb and max_frozen_term_size_kb to 8KiB

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java

We can revert this once we solve https://github.com/riptano/VECTOR-SEARCH/issues/85

Warn on create vector index with too many dimensions

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/TermIterator.java

When building the collection of sstable and memtable iterators for search, if we hit an exception, we must close the iterators that were already created successfully.

SAI: close iterators when search init fails

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/RangeIntersectionIterator.java
src/java/org/apache/cassandra/index/sai/utils/RangeUnionIterator.java

Let's say we want to query for rows with `a = 1 AND b = 1`. If predicate `a = 1` matches 10% rows and predicate `b = 1` matches 20% of rows, we estimate the whole where clause matches only 2% of rows.
Previously we used `getMaxKeys` on the final iterator, but that works differently - it gives the maximum number of keys that could be returned, which is often way off from the expected value. In the abovementioned case it would estimate the selectivity of 10%.

Assume predicates are independent in selectivity estimation

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

There is currently a bug where a hybrid query on an empty table fails with this exception:
```
Caused by: java.lang.IllegalArgumentException: perItemSuccessRate must not be NaN
at org.apache.cassandra.index.sai.utils.SoftLimitUtil.softLimit(SoftLimitUtil.java:49)
at org.apache.cassandra.index.sai.plan.QueryController.estimateSortThenFilterCost(QueryController.java:327)
at org.apache.cassandra.index.sai.plan.QueryController.decideFilterSortOrder(QueryController.java:302)
at org.apache.cassandra.index.sai.plan.QueryController.buildScoredPrimaryKeyIterator(QueryController.java:287)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.buildScoredPrimaryKeyIterator(StorageAttachedIndexSearcher.java:147)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.search(St …
```

Fix hybrid queries on empty tables

---

src/java/org/apache/cassandra/cache/ChunkCache.java
test/unit/org/apache/cassandra/cache/ChunkCacheTest.java

This PR optimizes the `ChunkCache#invalidateFile` method by introducing a map that keeps track of the file to key set in the `ChunkCache`. The current solution is costly, as it iterates over the whole cache.
Context: While working on https://github.com/datastax/cassandra/pull/974, I noticed that we have the relevant entry points to keep an accurate mapping from `file` to `Key` in the `ChunkCache`. This implementation might create more objects than one based on a unique counter (such as the one found in CNDB), but given its simplicity, I think it is worth considering.
This is an alternative to https://github.com/datastax/cassandra/pull/974.
Note:
I also explored the possibility of using a weak concurrent map, like the one [here](https://github.com/raphw/weak-lock-free/blob/master/src/main/j …

Optimize ChunkCache#invalidateFile by tracking keysByFile

---

test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

This test is flaky because it assumes we are guaranteed to get a certain row, but that assumption is wrong when we have two identical vectors. The test is no longer flaky when we use a different vector.

Fix testHybridIndexWithPartialRowInsertsAtSegmentBoundaries

---

CHANGES.txt
conf/cassandra.yaml
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/repair/RepairJob.java
src/java/org/apache/cassandra/repair/RepairRunnable.java
src/java/org/apache/cassandra/repair/RepairSession.java
src/java/org/apache/cassandra/repair/Scheduler.java
src/java/org/apache/cassandra/service/ActiveRepairService.java
test/distributed/org/apache/cassandra/distributed/test/OptimiseStreamsRepairTest.java
test/distributed/org/apache/cassandra/distributed/test/repair/ConcurrentValidationRequestsTest.java
test/unit/org/apache/cassandra/repair/RepairJobTest.java
test/unit/org/apache/cassandra/repair/RepairSessionTest.java

Add new concurrent_merkle_tree_requests config property to prevent OOM during multi-range and/or multi-table repairs.
It ensures that the space taken by the Merkle trees of a repair command should never be higher than `concurrent_merkle_tree_requests`*`repair_session_space`, even if that command includes multiple tables or virtual nodes. This is only applied to the Merkle tree part of repair, and the rest of the steps preserve the same parallelism that they had.

DSP-23942 vsearch: Port CASSANDRA-19336

---

src/java/org/apache/cassandra/cache/ChunkCache.java
test/unit/org/apache/cassandra/cache/ChunkCacheInterceptingTest.java
test/unit/org/apache/cassandra/metrics/CodahaleChunkCacheMetricsTest.java

For the storage service, we want to experiment with having a dedicated chunk cache instance for index reads, one that can cache some reads but does not impact the data chunk cache hit rate negatively. It's a bit hard to do at the moment because:
1. the ctor is private (workaroundable with reflection but ...).
2. the size is actually a static variable, so we can't have a new instance of a different size.
3. the metrics kind of hardcode names assuming there is just one instance, so we need to able to use some different metrics class to change that.
Note that regardless of whether the experiment pan out on the storage service side, it doesn't feel like the few visibility updates here hurt much.

Allow creating other instances of `ChunkCache`

---

src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java

Profiling indicates that this is the bottleneck on starting a node with many sstables / index segments.  With ~500 segments, the change here takes startup from minutes to seconds.

Cache most-accessed graph nodes asynchronously instead of blocking startup

---

src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java

Sample log line:
> INFO  [ForkJoinPool.commonPool-worker-5] 2024-02-15 12:45:14,841 Segment.java:97 - Opened searcher InvertedIndexSearcher for segment file:///Users/michaelmarshall/dev/apache/cassandra/bin/../data/data/keyspace/table-3f5c9290953911eebe8a2ff180e5ea33/cb-3gbp_1n19_3r1402f2khukes3gh5-bti:0 for index [table_metadata_s_idx] on column [metadata_s] at version ca
This additional information helps make these log lines distinguishable.

SAI: log segment's index and column names on init

---

src/java/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoir.java
test/unit/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoirTest.java

- Test exposing CASSANDRA-19365 race condition
- CASSANDRA-19365: introduce atomic change of decaying buckets and decay landmark in DecayingEstimatedHistogramReservoir to avoid update vs rescale and snapshot vs rescale race conditions

Fix race conditions in DEHR so that speculative retries are not issued needlessly

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java

Because the approximate scoring function is followed by a second pass of the full resolution scoring function, we can skip approximate scoring when there are less than topK vectors to score.
Adding a note for possible future optimizations, too.

Optimization: only use approx. scoring function for brute force sometimes

---

src/java/org/apache/cassandra/nodes/LocalInfo.java
src/java/org/apache/cassandra/nodes/Nodes.java
test/unit/org/apache/cassandra/nodes/NodesTest.java

The goal of this patch is to make LocalInfo class deserialization compatible with the local files that are created by DSE 6.8.
Equivalent patch for ds-trunk (https://github.com/datastax/cassandra/pull/1008)

DSP-23996: Ignore unknown fields while deserializing LocalInfo (vsearch)

---

src/java/org/apache/cassandra/nodes/LocalInfo.java
src/java/org/apache/cassandra/nodes/Nodes.java
test/unit/org/apache/cassandra/nodes/NodesTest.java

The goal of this patch is to make LocalInfo class deserialization compatible with the local files that are created by DSE 6.8.
Equivalent patch for vsearch (https://github.com/datastax/cassandra/pull/1008)

DSP-23996: Ignore unknown fields while deserializing LocalInfo (ds-trunk)

---

src/java/org/apache/cassandra/index/sai/utils/PrimaryKeys.java

Since the `PrimaryKeys` object is created for each unique term in an in memory SAI index, we can save some memory by making this value static.

Make SET_ENTRY_OVERHEAD private static final

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/IndexWriterConfig.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorCompression.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorSourceModel.java
test/unit/org/apache/cassandra/index/sai/cql/VectorCompressionTest.java

We still decide how to compress on save, but the logic is restructured:
* VectorCompression knows what compressed size should be, and adds a matches() method to use when we're looking for a previous codebook to refine.  (If we have a previous codebook, but it's for a different output size, we'll start fresh.)
* VectorSourceModel is where the per-model customization happens.  The guess-by-dimension logic also moves here.
Also pulled out some of the OPTIMIZE_FOR dead code while still allowing it as an option.
fixes #8711

add source_model sai option to allow model-specific compression tuning

---

src/java/org/apache/cassandra/metrics/ChunkCacheMetrics.java
src/java/org/apache/cassandra/metrics/MicrometerChunkCacheMetrics.java

For NSS we have a new instance of the ChunkCache that backs all the index accesses. This patch allows to register the metrics for the IndexChunkCache with a different prefix

ChunkCacheMetrics: allow to set a prefix (to separate the IndexChunkCacheMetrics)

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/io/util/Rebufferer.java

Vector SAI use RandomAccessReader.readFully(float[] dest) that in turn use Rebufferer.floatBuffer(). We implement this method in order to allow Vector to work with NSS and the IndexChunkCache
Summary for changes:
- implement floatBuffer(), intBuffer() and longBuffer() for the ChunkCache implementation and for the EMPTY bufffer
- add some logs when we decide to fall back to another version of the Vector index

Implement floatBuffer() for ChunkCache based Rebufferer

---

doc/modules/cassandra/pages/cql/functions.adoc
doc/modules/cassandra/partials/vector-search/vector_functions.adoc
src/java/org/apache/cassandra/cql3/Constants.java
src/java/org/apache/cassandra/cql3/UntypedResultSet.java
src/java/org/apache/cassandra/cql3/functions/AggregateFcts.java
src/java/org/apache/cassandra/cql3/functions/FromJsonFct.java
src/java/org/apache/cassandra/cql3/functions/FunctionFactory.java
src/java/org/apache/cassandra/cql3/functions/FunctionParameter.java
src/java/org/apache/cassandra/cql3/functions/ToJsonFct.java
src/java/org/apache/cassandra/cql3/functions/TokenFct.java
src/java/org/apache/cassandra/cql3/functions/VectorFcts.java
src/java/org/apache/cassandra/cql3/selection/Selectable.java
src/java/org/apache/cassandra/db/marshal/VectorType.java
test/unit/org/apache/cassandra/cql3/functions/FunctionFactoryTest.java
test/unit/org/apache/cassandra/cql3/validation/entities/CQLVectorTest.java

PR for [CNDB-8708](https://github.com/riptano/cndb/issues/8708). It adds a new `random_float_vector ` CQL native function. Its arguments are the number of dimensions of the vector, and the min and max values defining the range within the components will be. 
It also adds a new `normalize_l2` function. The functions can be used this way:
```
CREATE TABLE t (k int PRIMARY KEY, v vector<float, 1024>);
INSERT INTO t (k, v) VALUES (0, normalize_l2(random_float_vector(1024, -1, 1)));
```

CNDB-8708 vsearch: Add new random_float_vector CQL native function

---

src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java

Without this change the sample was added twice for both withSSTablesIterated invocations.

CNDB-8715 remove redundant addSample

---

src/java/org/apache/cassandra/cache/ChunkCache.java
test/unit/org/apache/cassandra/cache/ChunkCacheInterceptingTest.java
test/unit/org/apache/cassandra/cache/ChunkCacheTest.java

Optimize the `ChunkCache#invalidateFile` method by introducing a map that keeps track of the file to key set in the `ChunkCache`. The current solution is costly, as it iterates over the whole cache.

CNDB-8824 Optimize ChunkCache#invalidateFile by tracking keysByFile.

---

src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java

This is a hot fix. It works based on my testing locally and exposes two tailing test in `VectorTypeTest`.
I think we need a new way to configure brute force limits. Maybe we can do something as simple as setting a static variable and running all of our tests with and without brute force.

Fix VectorTester#setMaxBruteForceRows logic

---

src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java

Follow up on #1032 to address a test failure. The key change is to remove `assert endRowId > 0 : "endRowId must be greater than 0";`. The other changes are just cosmetic.

Remove invalid assertion in RowIdMatchingOrdinalsView

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java

After switching to Bounds, we can remove an unnecessary upper bound check because Bounds#contains is strict, while Range#contains assumes that when `left.equals(right)`, we have a wrap around range, and that doesn't give us what we really want for single partition reads.
Here is the logic where `Range` determines if a `Range` wraps around:
```java
/**
* Tells if the given range is a wrap around.
*/
public static <T extends RingPosition<T>> boolean isWrapAround(T left, T right)
{
return left.compareTo(right) >= 0;
}
```
Meanwhile, `Bounds` gives us what we want:
```java
public Bounds(T left, T right)
{
super(left, right);
// unlike a Range, a Bounds may not wrap
assert !strictlyWrapsAround(left, right) : "[" + left + "," + right + "]";
}
```

Use Bounds for SinglePartitionReadCommand DataRange in SAI

---

src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingList.java
src/java/org/apache/cassandra/index/sai/plan/Expression.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/utils/RangeIntersectionIterator.java
src/java/org/apache/cassandra/index/sai/utils/TermIterator.java
src/java/org/apache/cassandra/index/sai/utils/TreeFormatter.java
test/unit/org/apache/cassandra/index/sai/disk/SelectiveIntersectionTest.java
test/unit/org/apache/cassandra/index/sai/plan/OperationTest.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java
test/unit/org/apache/cassandra/index/sai/utils/LongIterator.java
test/unit/org/apache/cassandra/index/sai/utils/RangeIntersectionIteratorTest.java
test/unit/org/apache/cassandra/index/sai/utils/RangeUnionIteratorTest.java
test/unit/org/apache/cassandra/index/sai/utils/TreeFormatterTest.java

This commit improves performance of SAI queries by making SAI smarter
about selection of indexes.
Until that, for queries with multiple intersected predicates,
all available indices up to SAI_INTERSECTION_CLAUSE_LIMIT would be
picked. Because intersections are costly this might degrade performance
in some cases.
The new optimizer is much more flexible and attempts to select a better
plan by estimating the costs of plans with various number of
intersected clauses first. We've found experimentally there exist
queries which are several times faster if using 1 index to avoid
the costly intersection. There are also some edge cases where
intersecting 3 indexes may work better than 2. For hybrid
vector queries sometimes not using any index at all is the optimal
choice and the new optimizer …

Cost-based SAI query planner

---

src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/cql/types/QuerySet.java

Fixes: https://github.com/riptano/cndb/issues/8978
```
java.lang.UnsupportedOperationException: null
at org.apache.cassandra.index.sai.plan.Operation$Node.expression(Operation.java:269)
at org.apache.cassandra.index.sai.plan.Operation$Node.doTreeAnalysis(Operation.java:328)
at org.apache.cassandra.index.sai.plan.Operation$Node.doTreeAnalysis(Operation.java:333)
at org.apache.cassandra.index.sai.plan.Operation$Node.analyzeTree(Operation.java:319)
at org.apache.cassandra.index.sai.plan.QueryController.buildIterator(QueryController.java:282)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.analyze(StorageAttachedIndexSearcher.java:137)
at org.apache.cassandra.index.sai.plan.StorageAttachedIndexSearcher.search(StorageAttachedIndexSearcher.java:123)
at …
```

SAI: support `IN ()` predicate

---

src/java/org/apache/cassandra/index/sai/analyzer/JSONAnalyzerParser.java
test/unit/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Several error messages are now improved to help users understand what is incorrect about the analyzer config.
New checks:
* Better error message for invalid field names on the analyzer config itself
* Better error message for invalid `args` fields
* Better error message for invalid tokenizer, filter, and charFilter names
Here are the error messages for invalid tokenizer, filter, and charFilter names:
> Unknown tokenizer 'invalid'. Valid options: [simplePatternSplit, pattern, thai, edgeNGram, nGram, wikipedia, pathHierarchy, uax29UrlEmail, whitespace, classic, simplePattern, standard, keyword, letter]
> Unknown filter 'invalid'. Valid options: [brazilianStem, cjkBigram, truncate, fixBrokenOffsets, flattenGraph, concatenateGraph, greekLowercase, length, arabicNormalization, portugueseStem, …

Improve error messages for invalid SAI analyzer configuration

---

src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/CQL3Type.java
src/java/org/apache/cassandra/cql3/Constants.java
src/java/org/apache/cassandra/cql3/Vectors.java
src/java/org/apache/cassandra/cql3/functions/FunctionParameter.java
src/java/org/apache/cassandra/cql3/functions/VectorFcts.java
src/java/org/apache/cassandra/cql3/selection/MultiElementFactory.java
src/java/org/apache/cassandra/cql3/selection/Selectable.java
src/java/org/apache/cassandra/cql3/selection/SetSelector.java
src/java/org/apache/cassandra/cql3/selection/TupleSelector.java
src/java/org/apache/cassandra/cql3/selection/VectorSelector.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateAggregateStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateFunctionStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/DropAggregateStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/DropFunctionStatement.java
src/java/org/apache/cassandra/db/marshal/VectorType.java
test/unit/org/apache/cassandra/cql3/functions/VectorFctsTest.java
test/unit/org/apache/cassandra/cql3/functions/VectorSimilarityFctsTest.java
test/unit/org/apache/cassandra/cql3/validation/entities/CQLVectorTest.java
test/unit/org/apache/cassandra/db/marshal/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

While porting the vector data type to DSE 6.9, we found that OSS has several vector tests, fixes and improvements that never made it into vsearch. This PR ports those changes into vsearch to make OSS, vsearch and DSE better aligned.
The most relevant fixes are:
- Don't accept empty byte buffers in vector columns.
- Reject all-zero vectors in `similarity_cosine`
- Better management of null arguments in vector similarity functions
- Better error messages on function arguments with wrong types
One thing I'm not porting here is the fixes to make vectors work with UDFs. I think we don't allow UDFs in Astra, and whereas we do support them in DSE, the solution there would probably be different to what we would need here.

DSP-24082: Port OSS vector tests and fixes and improvements around them

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/concurrent/InlinedThreadLocalThread.java
src/java/org/apache/cassandra/concurrent/ParkedExecutor.java
src/java/org/apache/cassandra/concurrent/ParkedThreadsMonitor.java
src/java/org/apache/cassandra/concurrent/ShutdownableExecutor.java
src/java/org/apache/cassandra/metrics/MicrometerCacheMetrics.java
src/java/org/apache/cassandra/utils/Flags.java
src/java/org/apache/cassandra/utils/ThreadsFactory.java

This patch accumulates a few little improvements to how the ChunkCache uses Caffeine:
-  ability to configure the initial capacity of the cache inside of the ChunkCache (-cassandra.chunkcache_initialcapacity)
-  reduce the overhead of updating counters in the metrics (in DSE we have TPC that helps reducing contention)
-  port  https://datastax.jira.com/browse/DB-3063 "Use a non-blocking executor for ChunkCache cleanup", this required to import a few other classes related to ParkedExecutor

ChunkCache: improvements around Caffeine usage

---

src/java/org/apache/cassandra/io/sstable/format/big/BigFormat.java

Cassandra 4.0, and thus CC based on it supports BIG format up to N version. Token space coverage has been introduced in OSS starting from O version which comes with Cassandra 5.0.
We cannot support token space coverage in N version of BIG format as it would lead to producing sstables with the same format identifier and different binary structure.

STAR-1908: Do not support token space coverage in BIG format

---

src/java/org/apache/cassandra/io/util/BufferManagingRebufferer.java
src/java/org/apache/cassandra/io/util/RandomAccessReader.java
test/unit/org/apache/cassandra/io/util/RandomAccessReaderTest.java

This change saves some allocations in case we read a float[] larger than the bufferSize.
This change affects readFully for float[], long[] and int[].
There is also a fix in `BufferManagingRebufferer.buffer(),` probably that method from that class is used only in tests, otherwise we should have seen garbage reads in production.

Pool temporary ByteBuffers in RandomAccessReader#readFully(array)

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/io/util/BufferManagingRebufferer.java
src/java/org/apache/cassandra/io/util/MmappedRegions.java
src/java/org/apache/cassandra/io/util/RandomAccessReader.java
src/java/org/apache/cassandra/io/util/Rebufferer.java
src/java/org/apache/cassandra/io/util/WrappingRebufferer.java
test/unit/org/apache/cassandra/io/tries/AbstractTrieTestBase.java
test/unit/org/apache/cassandra/io/util/RandomAccessReaderTest.java
test/unit/org/apache/cassandra/io/util/WrappingRebuffererTest.java

Alternative to https://github.com/datastax/cassandra/pull/1066.
Calls to `asFloatBuffer`, `asIntBuffer`, and `asLongBuffer` on a `ByteBuffer` inherit the source buffer's `ByteOrder`. In the `RandomAccessReader`, we sometimes skip the call to `duplicate` a byte buffer before calling these methods to avoid unnecessary object creation. That is problematic because https://github.com/datastax/cassandra/pull/1030 introduced the ability to configure a `RandomAccessReader` with a byte order, but that PR didn't correctly account for byte order on these primitive buffer objects.
* Add a byte order config to the `Rebufferer`. I tried this, but it ended up with a sprawling diff that would be very brittle.
* Add a byte order config to the `BufferHolder` and partially implement the logic in the classes …

Fix RandomAccessReader byte order for {float|int|long}Buffer

---

src/java/org/apache/cassandra/index/sai/disk/v1/MemtableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/disk/v2/hnsw/OnDiskOrdinalsMapTest.java

Changes two components:
1. We will no longer write out the index components for vector indexes if all of the ordinals are deleted.
2. We can now handle vector graphs that were written without any non-deleted ordinals. This code is likely unnecessary, but protects us in the event any more of these indexes exist (the index that caused the issue was already deleted via compaction).

Skip writing vector graph if all ordinals are deleted

---

src/java/org/apache/cassandra/db/commitlog/AbstractCommitLogSegmentManager.java
src/java/org/apache/cassandra/db/commitlog/CommitLog.java
src/java/org/apache/cassandra/db/commitlog/CommitLogReadHandler.java
src/java/org/apache/cassandra/db/commitlog/CommitLogReader.java
src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java
test/long/org/apache/cassandra/db/commitlog/CommitLogStressTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogReaderTest.java

- tracked commit log files with invalid mutations with `segmentsWithInvalidMutations`
- after a replay cycle, those commit log files with invalid mutations are not deleted
- if a commit log with invalid mutations, is successfully replayed later, it is removed.

cassandra-8773 Commit log replayer deletes files with invalid mutations after each replay cycle

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoir.java
src/java/org/apache/cassandra/utils/EstimatedHistogram.java
test/unit/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoirTest.java
test/unit/org/apache/cassandra/utils/EstimatedHistogramTest.java

The behaviour is controlled via the cassandra.use_dse_compatible_histogram_boundaries system property

CNDB-9091: Histogram can now have the same boundaries as in DSE

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoir.java
src/java/org/apache/cassandra/utils/EstimatedHistogram.java
test/unit/org/apache/cassandra/metrics/DecayingEstimatedHistogramReservoirTest.java
test/unit/org/apache/cassandra/utils/EstimatedHistogramTest.java

* CNDB-9091: Histogram can now have the same boundaries as in DSE
The behaviour is controlled via the cassandra.use_dse_compatible_histogram_boundaries system property

CNDB-9091: Histogram can now have the same boundaries as in DSE (#1069)

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/MergeScoredPrimaryKeyIterator.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

As far as I can tell, this only impacts resumable search on memtable indexes because sstable indexes force all primary keys to load when building the `AcceptBits`.
Stack trace of bug:
```
java.lang.IllegalStateException: Attempted to seek in a closed RAR	
at org.apache.cassandra.io.util.RandomAccessReader.seek(RandomAccessReader.java:329)	
at org.apache.cassandra.index.sai.disk.io.IndexInputReader.seek(IndexInputReader.java:156)	
at org.apache.cassandra.index.sai.disk.v2.sortedterms.SortedTermsReader$Cursor.seekToPointId(SortedTermsReader.java:295)	
at org.apache.cassandra.index.sai.disk.v2.RowAwarePrimaryKeyMap.supplier(RowAwarePrimaryKeyMap.java:253)	
at org.apache.cassandra.index.sai.disk.v2.RowAwarePrimaryKeyMap.lambda$primaryKeyFromRowId$0(RowAwarePrimaryKeyMap.java:180)	
at …
```

Defer closing RangeIterator to prevent bug in resumable vector search

---

build.xml
src/java/org/apache/cassandra/cql3/functions/VectorFcts.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/utils/SAICodecUtils.java
test/unit/org/apache/cassandra/index/sai/cql/VectorDotProductWithLengthTest.java

(the churn around writeData is from the changes to the Writer api that allow jvector to own the lifecycle more cleanly)

update to beta3 and reuse Searcher objects

---

src/java/org/apache/cassandra/index/sai/disk/v1/trie/ReverseTrieTermsDictionaryReader.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/RowIndexReverseIterator.java
src/java/org/apache/cassandra/io/tries/BaseValueIterator.java
src/java/org/apache/cassandra/io/tries/ReverseValueIterator.java
src/java/org/apache/cassandra/io/tries/ValueIterator.java
src/java/org/apache/cassandra/io/tries/Walker.java
test/unit/org/apache/cassandra/index/sai/disk/v1/trie/TrieTermsDictionaryTest.java
test/unit/org/apache/cassandra/io/tries/AbstractTrieTestBase.java
test/unit/org/apache/cassandra/io/tries/WalkerTest.java

Motivation:
Be able to get the trie keys for SAI based descending ORDER BY queries.
Modifications:
* Lazily initialize `ReverseValueIterator`
* Support accumulating bytes in `ReverseValueIterator`
* Added `ReverseTrieTermsDictionaryReader` class to motivate changes to the `ReverseValueIterator` changes
This work mimics the changes made in https://github.com/datastax/cassandra/pull/876. It seems reasonable that we might want to create an abstraction to simplify the duplicated ideas in both the `ReverseValueIterator` and the `ValueIterator`, but I propose we defer that work for now.

Create ReverseTrieTermsDictionaryReader; add collector to ReverseValueIterator

---

src/java/org/apache/cassandra/cql3/statements/ModificationStatement.java

Fix for flaky test `MapEntriesIndexTest#testLWTConditionalUpdate`. It was flaky, and not always failing, because there was a garbage collection race such that we loaded chunks into the chunk cache, and the test only failed if GC happened before the test framework checked if any reference counted objects were leaked.
The other caller of `PartitionIterators#getOnlyElement` ultimately does the following, providing further validation for this solution:
https://github.com/datastax/cassandra/blob/233b9a4588f53c4c45a037476af481754a89c530/src/java/org/apache/cassandra/service/StorageProxy.java#L481-L484
Note that it doesn't look like the `Close` class defined in the `PartitionIterators#getOnlyElement` method is ever called. I'm not sure if that's an issue or not. However, I added some basic …

ModificationStatement#casInternal must close rows iterator

---

build.xml
src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/JVectorLuceneOnDiskGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorSourceModel.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java
test/unit/org/apache/cassandra/index/sai/disk/vector/VectorCompressionTest.java
test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java

- don't need to search as deep in any given index when we are combining results from multiple indexes
- enable rerankFloor to leverage information from previously searched indexes to tell us which candidates are most likely not worth doing the expensive rerank with
these have no effect when the table is perfectly compacted to a single sstable / single index segment; as the number of sstables grows, they help reduce the performance penalty without materially affecting recall.
for example, for the SIFT1M dataset we get about 93% recall in a single sstable, 95% when split across 5.
this patch saves ~50% of rerank effort in the 5-sstable case for ~0.3% degradation of recall and ~0.5% more calls to resume()
(so, recall is still significantly above the perfectly compacted base rate)

reduce compaction performance penalty

---

src/java/org/apache/cassandra/index/sai/disk/v1/IndexWriterConfig.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java

// For historical reasons (Lucene doubled the maximum node connections for its HNSW),
// maximumNodeConnections represents half of the graph degree, so double it
I'm not sure the "right" way to fix this, to be honest, since we're stuck with old-style configurations more or less permanently.

Double connections setting to get max degree

---

build.xml
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v2/hnsw/CassandraOnDiskHnsw.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/JVectorLuceneOnDiskGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorCompression.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorSourceModel.java
test/unit/org/apache/cassandra/index/sai/disk/vector/VectorCompressionTest.java

Enabling fused adc is easy (this is done in CassandraDiskANN) but there's a bunch of code churn because we need to load PQ codebooks (ProductQuantization instance) and metadata (VectorCompression instance) into memory without loading the compressed vectors (CompressedVectors = PQVectors instances).

enable fused adc and use VectorCompression and ProductQuantization instead of PQVectors

---

src/antlr/Parser.g
test/unit/org/apache/cassandra/cql3/validation/entities/CQLVectorTest.java
test/unit/org/apache/cassandra/cql3/validation/entities/FrozenCollectionsTest.java

When the CQL parser finds a syntax error in a type definition in `frozen<>` it produces a NPE that is caught and transformed into a `SyntaxException` [here](https://github.com/datastax/cassandra/blob/478ed37f6322128b5837ec826096bd35d56be25e/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L859-L866). That emits an error warning about the NPE that can bit quite alarming, and a not too helpful error message is presented to the user.
We have seen this happening with vectors, but it can also happen with other types. For example, this will have the same behaviour: `CREATE TABLE t (k int PRIMARY KEY, v frozen<map<text>>)`
The proposed patch fixes that by preventing the NPE, with an approach identical to what is done [here](https://github.com/datastax/cassandra/blob/478ed37f6322128b5837ec82 …

CNDB-9477 vsearch: Fix management of syntax errors in frozen types

---

src/java/org/apache/cassandra/db/CounterMutationCallback.java
src/java/org/apache/cassandra/db/CounterMutationVerbHandler.java
src/java/org/apache/cassandra/db/MutationVerbHandler.java
src/java/org/apache/cassandra/db/ReadCommandVerbHandler.java
src/java/org/apache/cassandra/net/Message.java
src/java/org/apache/cassandra/net/MessagingService.java
src/java/org/apache/cassandra/net/SensorsCustomParams.java
src/java/org/apache/cassandra/sensors/RequestSensors.java
src/java/org/apache/cassandra/sensors/SensorsRegistry.java
src/java/org/apache/cassandra/sensors/Type.java
test/unit/org/apache/cassandra/db/CounterMutationCallbackTest.java
test/unit/org/apache/cassandra/net/SensorsCustomParamsTest.java
test/unit/org/apache/cassandra/sensors/RequestSensorsTest.java
test/unit/org/apache/cassandra/sensors/SensorsInternodeTest.java
test/unit/org/apache/cassandra/sensors/SensorsRegistryTest.java

* Removed message count as bytes should really be the most important/accurate.
* Tracked both inbound and outbound bytes, as writes take up inbound bytes, while reads take up outbound bytes.
* Added internode sensors to custom params in the same place where we add the other sensors.
* Added internode sensors for request.

Opinionated changes to internode tracking

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexFormat.java

Non-native Vector kubes will set it to cb.
The migration tests uncovered an sstable incompatibility. DSE code is not compatible with cc sstable format produced by vector. To make DSE -> Vector migration and rollback possible, Vector will be pinned to cb format compatible with DSE code. Obviously, the cb format will be used only in "CC Vector" kubes, not actual Vector kubes.

CNDB-9360 Allow to set custom trie index format

---

src/java/org/apache/cassandra/index/sai/disk/RAMStringIndexer.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDTreeRamBuffer.java
test/unit/org/apache/cassandra/index/sai/disk/RAMStringIndexerTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDTreeRamBufferTest.java

This PR forces RAMStringSegmentBuilder to flush when the associated RAMStringIndexer hits maximum size of 2 GiB. Without this, if segment size is increased beyond the default config and the cardinality of postings is sufficiently high, index build can repeatably fail if the RAMStringSegmentBuilder tries to add terms beyond the maximum.

Trigger flush of RAMStringSegmentBuilder/BKDTreeRamBuffer when backing ByteBlockPools hit maximum size

---

src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java

The previous version eagerly iterated the whole partition and kept references to all rows in the array. This caused bad performance and wasted a lot of heap space, if the partitions were big, despite the query having a small LIMIT.

DSP-24254: Make applyIndexFilter lazy

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v3/CassandraDiskAnn.java

This is a regression introduced when adopting the new version of JVector in #1084. As noted in the JVector commit https://github.com/jbellis/jvector/commit/040baecee8041180691407c03ccae3fd757b8268, the deprecated `approximateScoreFunctionFor` API was replaced by two new APIs: `precomputedScoreFunctionFor` (which behaves the same as the deprecated `approximateScoreFunctionFor`) and `scoreFunctionFor`. In these cases, we did not replace with the equivalent API but instead the new API, which is designed for cases like parts of incremental graph construction, when only a small amount of scores will be computed.

Use precomputed PQ score functions for ANN search on both index and brute force paths

---

src/java/org/apache/cassandra/schema/Schema.java
src/java/org/apache/cassandra/service/PendingRangeCalculatorService.java
test/unit/org/apache/cassandra/gms/PendingRangeCalculatorServiceTest.java
test/unit/org/apache/cassandra/locator/SimpleStrategyTest.java

PRC is accounted for each keyspace separately. When PRC is requested, we select the affected keyspaces by the filter and add them to the CopyOnWriteArraySet. The PRC task consumes all the added keyspaces and removes them from the set.

CNDB-8538: Fix PendingRangesCalculatorService

---

src/java/org/apache/cassandra/db/compaction/CompactionTask.java
src/java/org/apache/cassandra/db/compaction/LeveledCompactionTask.java

issue: https://github.com/riptano/cndb/issues/9698

CNDB-9698: fix LCS partialCompactionsAcceptable when removing L0 sstable from L0/L1 compaction task for limited space

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java

This PR ports back some very minor fixes and improvements that have been done in `StatementRestrictions` while porting OR support to DSE. It's just fixing some typos, alignement issues and code duplication, as requested [during review](https://github.com/riptano/bdp/pull/21037#pullrequestreview-2028306165).

DSP-24122 vsearch: Port minor changes in StatementRestrictions

---

src/java/org/apache/cassandra/cql3/ResultSet.java
src/java/org/apache/cassandra/cql3/selection/ResultSetBuilder.java
src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectOffsetTest.java
test/unit/org/apache/cassandra/index/sai/StorageAttachedIndexTest.java

When using `ORDER BY` or `ANN`, `SELECT` queries collect all the rows found in each replica into a `ResultSet`, then order them, and finally trim the first `LIMIT` results. This can be seen [here](https://github.com/datastax/cassandra/blob/d45360170795aa4a535a410b0c754a9f5c94d2c8/src/java/org/apache/cassandra/cql3/statements/SelectStatement.java#L918-L934).
For index-based sorting, it means that the `ResultSet` holds up to num_replicas\*LIMIT in memory. If we were also using an `OFFSET`, it would hold num_replicas*(LIMIT+OFFSET) rows.
This PR uses online sorting in the `ResultSetBuilder` to limit its memory usage to just LIMIT rows, or LIMIT+OFFSET rows if we use an offset.

CNDB-9827: Online sorting and trimming of CQL result rows

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java

The operator was disabled by #702 as it may produce surprising matches. For backward compatibility, we allow this behavior.

CNDB-9967 re-enable = operator for analyzed SAI

---

conf/cassandra.yaml
doc/cql3/CQL.textile
doc/modules/cassandra/examples/BNF/select_statement.bnf
doc/modules/cassandra/pages/cql/cql_singlefile.adoc
doc/modules/cassandra/pages/cql/dml.adoc
pylib/cqlshlib/cql3handling.py
pylib/cqlshlib/test/test_cqlsh_completion.py
src/antlr/Lexer.g
src/antlr/Parser.g
src/java/org/apache/cassandra/cql3/ResultSet.java
src/java/org/apache/cassandra/cql3/selection/ResultSetBuilder.java
src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/view/View.java
src/java/org/apache/cassandra/guardrails/Guardrails.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/service/pager/PagedPartitionIterator.java
src/java/org/apache/cassandra/service/pager/QueryPager.java
test/microbench/org/apache/cassandra/test/microbench/SortedRowsBuilderBench.java
test/unit/org/apache/cassandra/cql3/WhereClauseMutationTest.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectOffsetTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailOffsetLimitRowsTest.java
test/unit/org/apache/cassandra/index/sai/StorageAttachedIndexTest.java

Add an optional `OFFSET` to CQL `SELECT` queries.
This can be used to do `LIMIT`/`OFFSET` paging.
The implementation involves the coordinator requesting offset+limit rows to
the replicas and then skipping the first offset rows. This way, large offsets
might be problematic performance-wise.
The offset is part of the limit clause, so it's not possible to use an offset
without a limit.
Using an offset disables regular key-based paging for the client, although
key-based paging will still be internally used if possible to reduce memory
pressure.
A new `offset_rows_warn_threshold`/`offset_rows_failure_threshold` guardrail
can be used to forbid problematically large offsets.

CNDB-9541 main: Support LIMIT/OFFSET paging for Data API

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/SerializationHeader.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java
src/java/org/apache/cassandra/db/marshal/DurationType.java
src/java/org/apache/cassandra/db/marshal/ListType.java
src/java/org/apache/cassandra/db/marshal/MapType.java
src/java/org/apache/cassandra/db/marshal/UserType.java
src/java/org/apache/cassandra/schema/ColumnMetadata.java
src/java/org/apache/cassandra/schema/SchemaKeyspace.java
src/java/org/apache/cassandra/schema/TableMetadata.java
test/unit/org/apache/cassandra/cql3/validation/operations/CreateTest.java

Add a flag to disable low-level check which makes it possible to load legacy data

CNDB-9753 (main): Disallow for using duration type in maps

---

src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectOffsetTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailOffsetRowsTest.java

The new `OFFSET` feature introduced by CDNB-9541 disables normal key-based paging when LIMIT/OFFSET paging is used.
However, the patch considered that queries without an explicit `OFFSET` and with `OFFSET 0` are the same. As a result, it doesn't disable key-based paging with `OFFSET 0`. Whereas the query results are perfectly correct, it can be a surprising behaviour that the first "page" of a LIMIT/OFFSET paging is also paged in a key-based way.
I think we should disable key-based paging also when `OFFSET` is explicitly set to 0.
The proposed PR uses a sentinel value to distinguish between no explicit offset and offset explicitly set to zero, and then it disables user-facing paging if the offset has been explicitly set to zero.

CNDB-10025 main: CQL queries with OFFSET 0 should disable paging

---

src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java

This commit introduces a new interface: `Plan.CostEstimator`. This allows to plug external cost estimators into the query planner. Therefore, the code in `Plan` is decoupled from the actual storage / indexing machinery and can be easily tested. We also don't leak index-specific stuff to the Plan.
Currently, `CostEstimator` implementation estimates the expected number of visited DiskANN index nodes, depending on the limit and total number of indexed rows. This is achieved by iterating through all vector indexes involved in the query and summing their estimates.

Use vector index node count estimates when planning TopK queries

---

src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Currently, we do UNION when we see OR. That breaks in cases when we use analyzers and ngrams with OR.
This PR tries to fix that by adding an AND node when we see ANALYZER_MATCHES.

Fix OR when using ANALYZER_MATCHES with ngrams

---

src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java

Post-filtering will reject many rows, so we need to compensate
for it by fetching more keys from the index.

Take post-filtering into account in the limit passed to TopK search

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/index/sai/disk/PerIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexComponents.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/v1/MemtableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sasi/SASIIndexBuilder.java
src/java/org/apache/cassandra/index/sasi/disk/PerSSTableIndexWriter.java
src/java/org/apache/cassandra/io/sstable/format/SSTableFlushObserver.java
src/java/org/apache/cassandra/io/sstable/format/SSTableWriter.java
test/unit/org/apache/cassandra/index/CustomIndexTest.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/EmptyMemtableFlushTest.java
test/unit/org/apache/cassandra/index/sai/functional/FlushingTest.java
test/unit/org/apache/cassandra/index/sasi/disk/PerSSTableIndexWriterTest.java
test/unit/org/apache/cassandra/io/sstable/format/SSTableFlushObserverTest.java

On flush, index components are registered early, before the actual start of the flush, and so we register all the components we expect to have on a successful build. But when an index for a particular sstable is empty (meaning that the memtable has nothing to index for that particular index), only the completion marker is written for that index but no other components, so the TOC file for the sstable ended up including components that don't actually exists.
Technically, this wasn't "breaking" anything as while the SAI code now uses the TOC to discover components, it detects this case and fallback to scanning disk (which will discover the right components). However this fallback is less efficient, particulary in CNDB, so it is worth avoiding it (besides, having the TOC file be incorrect is …

Fix TOC including non-existing files when flushing empty SAI index

---

src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java

This is my bad, I pushed the merge button for https://github.com/datastax/cassandra/pull/1188 too quickly and left this over.

Remove unecessary leftover log message

---

src/java/org/apache/cassandra/db/lifecycle/Tracker.java
test/unit/org/apache/cassandra/db/lifecycle/TrackerTest.java

The `INotificationConsumer` subscribers of `Tracker` fire in the order they are registered. For CNDB however, we want to register subscribers that fire only after all the internal subscribers of C* have fired, as some of those do important jobs (like the `SAIGroup` one, which essentially make built index visible on flush) that we want to make sure happen first.
This patch adds a new `Tracker.subscribeLaterConsumer`, which is similar to the existing `Tracker.subscribe`, but the former guarantees that the consumers it registers all fire after the ones registered by the later.

Allows to register `Tracker` subscribers that fire later than other ones

---

src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
test/microbench/org/apache/cassandra/test/microbench/SortedRowsBuilderBench.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectOffsetTest.java

Modify coordinator-side sorting of CQL result rows to use online heap-based sorting when the number of rows returned by the nodes gets to a certain size.
We use the current List#sort algorithm if the number of rows to sort is below 4*(LIMIT+OFFSET), and switch to heap sort above that number of rows.
Heap-based sort uses constant LIMIT+OFFSET memory and it's much faster with many rows, but List#sort is faster for fewer rows. Thereof the hybrid approach.

CNDB-9827 main: Online sorting and trimming of CQL result rows

---

src/java/org/apache/cassandra/io/compress/CompressedSequentialWriter.java
src/java/org/apache/cassandra/io/util/ChecksumWriter.java
src/java/org/apache/cassandra/io/util/DataIntegrityMetadata.java
test/unit/org/apache/cassandra/SchemaLoader.java
test/unit/org/apache/cassandra/db/ScrubTest.java
test/unit/org/apache/cassandra/io/compress/CompressedSequentialWriterTest.java

- Rescan the full file to compute CRC checksum in case of resetAndTruncate because we can't reset CRC value to previous offset.

CNDB-10161: fix CompressedSequentialWriter to record proper lastFlushOffset and checksum when corruption is found and resets position

---

src/java/org/apache/cassandra/index/sai/memory/FilteringKeyRangeIterator.java

We see a large amount of time spent on the
PriorityQueue initialization in the KeyRangeIterator.
Because the SortedSet is already ordered, we
don't need the PQ and can instead just use the
sorted set's iterator. I expect this to
decrease init time by skipping the creation
of a large array and an eager consumption
of the fully sorted set.

Optimize FilteringKeyRangeIterator initialization

---

src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectOffsetTest.java

The patch adding offset paging (CNDB-9541) and its follow-up for improving coordinator-side row sorting (CNDB-9827) contain additions of offset and limit that can overflow. 
For example, `SELECT * FROM t LIMIT 2147483646 OFFSET 2` will hit an overflow that will return wrong results (the limit is `Integer.MAX_VALUE - 1`). However, it won't happen if the limit is `Integer.MAX_VALUE` because `Integer.MAX_VALUE` means no limit, and that has special treatment.
This PR uses saturated addition for adding limit+offset, so it never exceeds `Integer.MAX_VALUE`.

CNDB-10324: Prevent overflows when calculating LIMIT+OFFSET

---

src/java/org/apache/cassandra/index/sai/disk/PostingList.java
src/java/org/apache/cassandra/index/sai/disk/v1/postings/MergePostingList.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/ScoredRowId.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java

In order to leverage this logic, I made
several utility objects comparable. These
objects have very limited use cases, so
I propose that it is acceptable that the
classes have different logic for equality
and for comparison. If that is not generally
accepted, we will need to tweak the PR.

Utilize PriorityQueue's O(N) constructor in several SAI use cases

---

bin/cqlsh.py
pylib/cqlshlib/cqlshhandling.py
pylib/cqlshlib/tracing.py

Sample output:
```
cqlsh> tracing compact;
Tracing set to COMPACT.
cqlsh> select passage from coherebench.embeddings_table order by embedding ann of random_float_vector(1024, -1, 1) limit 1;
passage
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
She was then sailed on Lake Wendouree, Ballarat, and presented with a new set of sails by local yachtsmen, before travelling to Geelong to be returned to the sea.
(1 rows)
Tracing session: fa8921c0-3e33-11ef-ba0d-9b64a7fb6e4b
Source mapping:
A -> 127.0.0.1
src | elapsed | activity
-----+---------+------------------------------------------------------------------------------------------------------------------------------------------ …
```

Compact tracing mode for cqlsh

---

src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java

`SortedRowsBuilder.WithHeapSort` could have very bad performance in some edge cases. 
If a query has a very large, non-max limit/offset, it will be initialized with that large capacity. A huge heap is quite slow. It would be wasteful if we ended up collecting only a few rows. Thus, a query of the form `SELECT * FROM %s WHERE k = 0 ORDER BY c1 LIMIT 10000000` without paging that only finds one row will be unusually slow when using the heap.
I think this is not a problem in practice because `SortedRowsBuilder.WithHybridSort` won't create the heap until it has collected `LIMIT` rows. Nevertheless, I think `SortedRowsBuilder.WithHeapSort` should also work fine on its own. I'm making the heap initialization lazy, so we avoid this performance problem.

CNDB-10338: Avoid unnecesarily large initializations in SortedRowsBuilder.WithHeapSort

---

src/java/org/apache/cassandra/db/lifecycle/Tracker.java
test/unit/org/apache/cassandra/db/lifecycle/TrackerTest.java

Allows to register `Tracker` subscribers that fire later than other ones (#1194)
The `INotificationConsumer` subscribers of `Tracker` fire in the order they are registered. For CNDB however, we want to register subscribers that fire only after all the internal subscribers of C* have fired, as some of those do important jobs (like the `SAIGroup` one, which essentially make built index visible on flush) that we want to make sure happen first.
This patch adds a new `Tracker.subscribeLaterConsumer`, which is similar to the existing `Tracker.subscribe`, but the former guarantees that the consumers it registers all fire after the ones registered by the later.

Backport datastax/cassandra#1194

---

src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/RangeUtil.java

The underlying problem is how bounds are handled in the `Range` class, which has exclusive bounds. This change centralizes the SAI logic for intersection in an SAI utility so that a segment and the `estimateTotalAvailableRows` both have the same logic.
It seems like it would be better to centralize this logic further, but I'm not quite sure what would be best.
This PR fixes the following failure in the `VectorTypeTest.rangeSearchTest`:
```
java.lang.AssertionError: 0
at org.apache.cassandra.index.sai.disk.v1.Segment.proportionalAnnLimit(Segment.java:241)
at org.apache.cassandra.index.sai.plan.QueryController.estimateAnnNodesVisited(QueryController.java:945)
at org.apache.cassandra.index.sai.plan.Plan$AnnScan.estimateCost(Plan.java:1174)
at …
```

CNDB-10386: SAI sstable intersection logic in row estimate

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/metrics/SegmentFlushingFailureTest.java

- Compaction will be aborted in case of index error and index remains queryable because no new sstables are added

CNDB-10165: propagate index build error to compaction task and index build task.

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/CounterMutationCallback.java
src/java/org/apache/cassandra/db/CounterMutationVerbHandler.java
src/java/org/apache/cassandra/db/MutationVerbHandler.java
src/java/org/apache/cassandra/db/ReadCommandVerbHandler.java
src/java/org/apache/cassandra/net/SensorsCustomParams.java
src/java/org/apache/cassandra/sensors/ActiveRequestSensors.java
src/java/org/apache/cassandra/sensors/ActiveRequestSensorsFactory.java
src/java/org/apache/cassandra/sensors/NoOpRequestSensors.java
src/java/org/apache/cassandra/sensors/RequestSensors.java
src/java/org/apache/cassandra/sensors/RequestSensorsFactory.java
src/java/org/apache/cassandra/sensors/SensorsRegistry.java
src/java/org/apache/cassandra/service/paxos/CommitVerbHandler.java
src/java/org/apache/cassandra/service/paxos/PrepareVerbHandler.java
src/java/org/apache/cassandra/service/paxos/ProposeVerbHandler.java
test/microbench/org/apache/cassandra/test/microbench/RequestSensorBench.java
test/unit/org/apache/cassandra/db/CounterMutationCallbackTest.java
test/unit/org/apache/cassandra/net/SensorsCustomParamsTest.java
test/unit/org/apache/cassandra/sensors/ActiveRequestSensorsFactoryTest.java
test/unit/org/apache/cassandra/sensors/ActiveRequestSensorsTest.java
test/unit/org/apache/cassandra/sensors/DisabledSensorsTest.java
test/unit/org/apache/cassandra/sensors/RequestSensorsFactoryTest.java
test/unit/org/apache/cassandra/sensors/SensorsIndexWriteTest.java
test/unit/org/apache/cassandra/sensors/SensorsInternodeTest.java
test/unit/org/apache/cassandra/sensors/SensorsReadTest.java
test/unit/org/apache/cassandra/sensors/SensorsRegistryTest.java
test/unit/org/apache/cassandra/sensors/SensorsTestUtil.java
test/unit/org/apache/cassandra/sensors/SensorsWriteTest.java

Addresses: https://github.com/riptano/cndb/issues/9707
Adds `RequestSensorsFactory` that can be provided from upstream dependents to effectively enable/disable sensors tracking per ks

CNDB-9707 Implement RequestSensorsFactory to control sensors tracking per keyspace

---

src/java/org/apache/cassandra/auth/CassandraRoleManager.java
test/distributed/org/apache/cassandra/distributed/test/AuthTest.java

Addresses: https://github.com/riptano/cndb/issues/8885
This patch partially ports https://github.com/riptano/bdp/pull/15854 to allow skipping default role creation for security purposes.

CNDB-8885: Add skip_default_role_setup system property to control default role creation

---

src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/disk/EmptyIndex.java
src/java/org/apache/cassandra/index/sai/disk/SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/IndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/KDTreeIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReader.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/MemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Orderer.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryViewBuilder.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/utils/MemtableOrdering.java
src/java/org/apache/cassandra/index/sai/utils/SegmentOrdering.java
src/java/org/apache/cassandra/index/sai/utils/TreeFormatter.java
test/unit/org/apache/cassandra/index/sai/cql/GenericOrderByTest.java
test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java
test/unit/org/apache/cassandra/index/sai/utils/TreeFormatterTest.java

Fixes [10400](https://github.com/riptano/cndb/issues/10400)
Schema:
Table with one indexed column `a` with random values ranging 0.0 to 1.0.
1M rows. 
Query:
`SELECT * FROM tab WHERE a > 0.8 ORDER BY a LIMIT 10`
Performance before: 0 req/sec (all timeouts)
Performance after: 7300 req/s (0 timeouts)

SAI fix performance when selection and order by on the same column

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/functional/CompactionTest.java

The context of this is https://github.com/riptano/cndb/issues/10519.

Add property to disable opening index searcher objects (for compactors)

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/OrdinalsView.java
src/java/org/apache/cassandra/index/sai/utils/IntIntPairArray.java
test/unit/org/apache/cassandra/index/sai/utils/IntIntPairArrayTest.java

In the brute force code path, we currently map row ids to ordinals twice. This is expensive and can easily be reduced to once, as shown in this PR. We can also defer building the `bits` object until we know we need it.

Only map rows to ordinals once for hybrid vector queries

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

- Add failing test
- SAI Update: ignore TTL when getting old row's vector value
The test fails on flush with the below error:
```
java.lang.IllegalArgumentException: value already present: 0
at com.google.common.collect.HashBiMap.put(HashBiMap.java:279)
at com.google.common.collect.HashBiMap.put(HashBiMap.java:260)
at org.apache.cassandra.index.sai.disk.v2.V2VectorPostingsWriter.buildOrdinalMap(V2VectorPostingsWriter.java:195)
at org.apache.cassandra.index.sai.disk.v2.V2VectorPostingsWriter.remapPostings(V2VectorPostingsWriter.java:209)
at org.apache.cassandra.index.sai.disk.vector.CassandraOnHeapGraph.flush(CassandraOnHeapGraph.java:392)
at org.apache.cassandra.index.sai.disk.vector.VectorMemtableIndex.writeData(VectorMemtableIndex.java:407)
at …
```

SAI Update: ignore TTL when getting old row's vector value

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/compaction/AbstractCompactionTask.java
src/java/org/apache/cassandra/db/compaction/CompactionTask.java
test/unit/org/apache/cassandra/db/compaction/CompactionTaskTest.java
test/unit/org/apache/cassandra/db/compaction/DisabledRepairStateCheckingTest.java

The new flag is -Dcassandra.compaction.skip_repair_state_checking=true

CNDB-10549: Introduce a flag to skip repair state checking

---

src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

Fixes a race condition when a filter-then-sort query gets intertwined with a deletion (or upsert) and a flush, only with `DC`/v5 format:
* The relevant part of the query: https://github.com/datastax/cassandra/tree/9fe9211f1213d9b342ea1f81d1c7740abb9db11d/src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java#L282-L285
* The deletion of postings on flush: https://github.com/datastax/cassandra/tree/9fe9211f1213d9b342ea1f81d1c7740abb9db11d/src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java#L374
If the deletion of postings happens between getting the vector and getting the postings, [`CassandraOnHeapGraph#getOrdinal`](https://github.com/datastax/cassandra/blob/9fe9211f1213d9b342ea1f81d1c7740abb9db11d/src/java/org/apache/cassandra/index/sai/disk/ …

CNDB-10536 main: Fix race between vector deletion and filter-then-sort queries

---

src/java/org/apache/cassandra/index/sai/plan/Plan.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java

This commit fixes a minor bug in SAI cost estimation code that caused the cost of intersections to be sometimes overestimated. The estimation code didn't account for the fact that we may reach the end of the iterator before finding a matching key.

Limit the number of intersection loops by the number of keys available

---

src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java

This is only for the following hotfix:
https://github.com/riptano/cndb/issues/10596.
They should be turned back on when we fix the issues.

CNDB-10625: Set reduce_topk_across_sstables and enable_jvector_deletes to false by default

---

src/java/org/apache/cassandra/index/internal/CollatedViewIndexBuilder.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexComponent.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/NumericIndexWriter.java
src/java/org/apache/cassandra/index/sasi/SASIIndexBuilder.java
src/java/org/apache/cassandra/io/sstable/SSTable.java
src/java/org/apache/cassandra/io/sstable/SSTableWatcher.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReaderBuilder.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableWriter.java
src/java/org/apache/cassandra/io/storage/StorageProvider.java

- Add SSTableWatcher#onIndexRebuild to be called before index rebuild
- Add primary index write time file handle builder for row index and partiton index when creating sstable
- Overwrite TOC directly instead of deleting then appending

CNDB-9441: fix SAI rebuild order to complete transaction first

---

src/java/org/apache/cassandra/db/commitlog/AbstractCommitLogSegmentManager.java
src/java/org/apache/cassandra/db/commitlog/CommitLog.java
src/java/org/apache/cassandra/db/commitlog/CommitLogReplayer.java
test/unit/org/apache/cassandra/db/RecoveryManagerTest.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogReplayerTest.java

Re-applying https://github.com/datastax/cassandra/commit/9fe9211f1213d9b342ea1f81d1c7740abb9db11d introduced in https://github.com/datastax/cassandra/pull/1228
CNDB change is approved so we need to get this in.

Re-applying CNDB-7178: Keep track of failed segments when applying mutations (#1228)

---

src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/utils/IndexFileUtils.java

- use writeTimeReadFileChannelFor() for recalculateChecksum on appending index segment

CNDB-10702: use indexBuildTimeFileHandleBuilderFor for vector PQ during index build

---

src/java/org/apache/cassandra/cql3/restrictions/ClusteringColumnRestrictions.java
src/java/org/apache/cassandra/cql3/restrictions/PartitionKeyRestrictions.java
src/java/org/apache/cassandra/cql3/restrictions/PartitionKeySingleRestrictionSet.java
src/java/org/apache/cassandra/cql3/restrictions/RestrictionSet.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/SingleRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/cql3/restrictions/TokenFilter.java
src/java/org/apache/cassandra/cql3/restrictions/TokenRestriction.java
src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupport.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sasi/conf/ColumnIndex.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Adds a new `equals_behaviour_when_analyzed` index config property allowing to define the behaviour of the `=` operator on analyzed indexes. Values are:
* `REJECT`: Reject the query
* `MATCH`: Behave the same as the `:` operator.
I think `REJECT` should be the ideal behaviour, but `MATCH` is the default for compatibility reasons.
Here is an example showing how it works:
```
CREATE TABLE t (k int PRIMARY KEY, v text);
INSERT INTO t (k, v) VALUES (1, 'Quick fox');
INSERT INTO t (k, v) VALUES (2, 'Lazy fox');
-- with defaults
CREATE CUSTOM INDEX idx ON t(v) USING 'StorageAttachedIndex'
WITH OPTIONS = { 'index_analyzer': 'standard' };
SELECT k FROM t WHERE v = 'Quick fox'; -- returns row 1
SELECT k FROM t WHERE v : 'Quick fox'; -- returns row 1
-- with MATCH
DROP INDEX idx;
CREATE CUSTOM INDEX …
```

CNDB-10647: Fix EQ queries on analyzed columns

---

src/java/org/apache/cassandra/utils/FilterFactory.java
src/java/org/apache/cassandra/utils/obs/OffHeapBitSet.java
test/unit/org/apache/cassandra/utils/BloomFilterTest.java

Add counter to track number of OOMs.
Alternatively we can propagate metadata information into FilterFactory to enrich counter with keyspace and table name. I went for minimal approach to avoid refactoring. 
Prometheus friendly metric is exposed through `bloom_filter_oom_errors`.

CNDB-10624: Add counter to track number of OOM errors when loading bloom filters

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

Fixes https://github.com/riptano/cndb/issues/10810
We hit:
```
java.lang.AssertionError: sstableRowId 315407 > maxSSTableRowId 315406
at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.flatmapPrimaryKeysToBitsAndRows(V2VectorIndexSearcher.java:615)
at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.orderResultsBy(V2VectorIndexSearcher.java:509)
at org.apache.cassandra.index.sai.disk.v1.Segment.orderResultsBy(Segment.java:183)
at org.apache.cassandra.index.sai.disk.v1.V1SearchableIndex.orderResultsBy(V1SearchableIndex.java:213)
at org.apache.cassandra.index.sai.SSTableIndex.orderResultsBy(SSTableIndex.java:292)
at org.apache.cassandra.index.sai.plan.QueryController.lambda$orderSstables$10(QueryController.java:623)
... 23 common frames omitted
```
Notably, this bug …

Fix hybrid vector query bug when sstable has rows with null vectors

---

src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/SSTableContextManager.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexComponents.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/format/OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
src/java/org/apache/cassandra/io/sstable/format/SSTableWriter.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/IndexParallelBuildTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java

Add missing CASSANDRA-18670 changes.
This fixes `ImportIndexedSSTablesTest`.
The `SIM#buildSSTableAttachedIndexesBlocking` method added by CASSANDRA-18670 is modified to build the indexes in parallel, in line with CNDB-7103.

CNDB-10210: Add missing CASSANDRA-18670 changes

---

src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/CostsCalculator.java
src/java/org/apache/cassandra/db/compaction/unified/DSECompatibilityUtils.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/unit/org/apache/cassandra/db/compaction/unified/DSECompatibilityUtilsTest.java

Legacy prefix is considered if property is not found with existing PREFIX.
Bumps `max_sstables_to_compact` default to 256.
Closes https://github.com/riptano/cndb/issues/10850

CNDB-10850: support legacy UCSv2 settings and change the default of max_sstables_to_compact to 256 (as in DSE)

---

src/java/org/apache/cassandra/db/compaction/unified/Controller.java

We change the default to 256, but with UCSv2 it is better to keep 0
See here:
https://github.com/riptano/cndb/issues/10856#issuecomment-2355117574

CNDB-10856 Revert default of max_sstables_to_compact to 0

---

src/java/org/apache/cassandra/db/compaction/unified/Controller.java

Port of https://github.com/datastax/cassandra/pull/1286
From commit b7def6348ec3c90840d2b49c220be362cfb5766b

Port: CNDB-10856 Change the default of max_sstables_to_compact to 32 (#1286)

---

src/java/org/apache/cassandra/db/MultiRangeReadCommand.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/net/Message.java
src/java/org/apache/cassandra/service/reads/range/EndpointGroupingCoordinator.java
test/distributed/org/apache/cassandra/distributed/test/guardrails/GuardrailDiskUsageTest.java
test/distributed/org/apache/cassandra/distributed/test/guardrails/GuardrailNonPartitionRestrictedQueryTest.java
test/distributed/org/apache/cassandra/distributed/test/guardrails/GuardrailTester.java
test/unit/org/apache/cassandra/schema/MigrationCoordinatorTest.java

This includes:
* Adding the missing call to the tested guardrail, Guardrails.saiSSTableIndexesPerQuery, which was missed on rebase.
* Fixes for the test itself, since row filter expression values are truncated at printing (CC-only behaviour).
* Fixes to make track warnings work with MultiRangeReadCommand. The former was ASF-only, whereas the latter was CC-only.

CNDB-9987: Fix GuardrailNonPartitionRestrictedQueryTest

---

src/java/org/apache/cassandra/index/sai/utils/PrimaryKeyWithByteComparable.java

This fixes an issue reading cell values in `ORDER BY`. It fixes multiple tests:
* GenericOrderByTest
* LiteralOrderTest
* StaticColumnIndexTest
* AsciiTest
* TextTest

CNDB-10801: Fix bug in SAI index ordering

---

src/java/org/apache/cassandra/io/compress/CompressedSequentialWriter.java
src/java/org/apache/cassandra/io/compress/CorruptBlockException.java
src/java/org/apache/cassandra/io/util/CompressedChunkReader.java

This additional metadata is somewhat valuable in the context of troubleshooting. Recently, we had an issue where the checksum itself was not (over)written and so it was stored as 0. In many cases, this won't be helpful, but since it is cheap and could be helpful, I propose adding some additional metadata when checksums don't match.

Include checksums in CorruptBlockException when relevant

---

src/java/org/apache/cassandra/io/FSError.java

For this code block:
```java
var t = new FSWriteError(new IOException("Test failure"), new File("my", "file"));
logger.error("error", t);
```
We used to log:
```
ERROR [main] 2024-09-19 11:09:18,599 VectorTypeTest.java:118 - error
org.apache.cassandra.io.FSWriteError: java.io.IOException: Test failure
at org.apache.cassandra.index.sai.cql.VectorTypeTest.endToEndTest(VectorTypeTest.java:117)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```

Implement FSError#getMessage to ensure file name is logged

---

src/java/org/apache/cassandra/cql3/restrictions/RestrictionSet.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectSingleColumnRelationTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/SelectTest.java

This commit fixes a serious correctness bug in the way we build RowFilter for expressions involving OR.
If a query contained multiple complex predicates such as NOT IN joined with the OR operator, the slices produced by NOT IN were incorrectly also joined by OR instead of by AND.
In addition, a NOT IN with an empty list, if ORed with another expression, was incorrectly treated as an expression matching 0 rows, instead of matching all rows.
Example 1:
`SELECT * FROM t WHERE x = 1 OR x NOT IN (2, 3, 4)`
was incorrectly matching all rows, including the ones with x = 2 or x = 3 or x = 4.
Example 2:
`SELECT * FROM t WHERE x = 1 OR x NOT IN ()`
was incorrectly matching only row with x = 1, instead of all rows.
The bug was technically not limited to NOT IN, but any single restriction that wanted …

CNDB-10923: Fix expressions accidentally joined by OR instead of AND

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java

This commit does not work because the queryView is not set until
after we get the plan. Since the view is only used to estimate
the cost of work and not to skip work, it is safe to use a
different view.
This reverts commit 9333708db652ec47a69d10326ae38ded998a174d.

Revert "Use query view's locked indexes for Plan#estimateAnnNodesVisited (#1238)"

---

src/java/org/apache/cassandra/db/compaction/CompactionStrategyFactory.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionContainer.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.md
src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
src/java/org/apache/cassandra/schema/TableMetadata.java
test/distributed/org/apache/cassandra/distributed/test/CompactionControllerConfigTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java

Added `unified_compaction.override_ucs_config_for_vector_tables` system property.  When set, the ucs configuration will be changed to the provided (or default) vector configuration whenever a new table with a `VectorType` is created or a `VectorType` is added to an existing table.  
I've added additional options to allow for different configurations for vector vs non-vector tables.  For instance, a user can set `unified_compaction.sstable_growth=0` and `unified_compaction.vector_sstable_growth=1`.  In this case, the value of 0 will be used unless the table has a `VectorType` and `unified_compaction.override_ucs_config_for_vector_tables` is set to `true`.
CNDB issue: https://github.com/riptano/cndb/issues/10455

CNDB-10455: Automatically tune compaction for vector tables

---

src/java/org/apache/cassandra/db/marshal/AbstractCompositeType.java
src/java/org/apache/cassandra/db/marshal/AbstractGeometricType.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java
src/java/org/apache/cassandra/db/marshal/AsciiType.java
src/java/org/apache/cassandra/db/marshal/BooleanType.java
src/java/org/apache/cassandra/db/marshal/BytesType.java
src/java/org/apache/cassandra/db/marshal/CounterColumnType.java
src/java/org/apache/cassandra/db/marshal/DateRangeType.java
src/java/org/apache/cassandra/db/marshal/DecimalType.java
src/java/org/apache/cassandra/db/marshal/DoubleType.java
src/java/org/apache/cassandra/db/marshal/EmptyType.java
src/java/org/apache/cassandra/db/marshal/FloatType.java
src/java/org/apache/cassandra/db/marshal/InetAddressType.java
src/java/org/apache/cassandra/db/marshal/Int32Type.java
src/java/org/apache/cassandra/db/marshal/IntegerType.java
src/java/org/apache/cassandra/db/marshal/LexicalUUIDType.java
src/java/org/apache/cassandra/db/marshal/LongType.java
src/java/org/apache/cassandra/db/marshal/TimeUUIDType.java
src/java/org/apache/cassandra/db/marshal/TimestampType.java
src/java/org/apache/cassandra/db/marshal/TupleType.java
src/java/org/apache/cassandra/db/marshal/UTF8Type.java
src/java/org/apache/cassandra/db/marshal/UUIDType.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
test/unit/org/apache/cassandra/db/marshal/AbstractTypeTest.java
test/unit/org/apache/cassandra/index/sai/cql/EmptyStringLifecycleTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Ports [CASSANDRA-19461](https://issues.apache.org/jira/browse/CASSANDRA-19461) into `main`.
Currently, SAI doesn't create an index entry for empty values. As a result, index queries such as `SELECT * FROM %s WHERE v = ''` will never find anything. However, the same query with `ALLOW FILTERING` can find rows.
The ported patch makes sure that empty values are indexed. However, existing indexes would need a rebuild to have these entries.
We need to evaluate if this can be a breaking change for some users. The only side effect I can think of is that indexes with many empty values that are never queries would become larger after this change.

CNDB-10939: Make SAI index empty column values

---

test/unit/org/apache/cassandra/index/sai/disk/io/TrackingIndexFileUtils.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReaderTest.java

Remove unnecessary closing of postings in `BKDReader.Intersection#mergePostings`.
The posting readers created by `BKDReader.Intersection#initPostingReader` already close their `IndexInput` on close.

CNDB-9804: Remove duplicated closing of postings IndexInput's

---

src/java/org/apache/cassandra/db/compaction/CompactionRealm.java
src/java/org/apache/cassandra/db/compaction/ShardManager.java
src/java/org/apache/cassandra/db/compaction/ShardManagerNoDisks.java
src/java/org/apache/cassandra/db/compaction/ShardManagerReplicaAware.java
src/java/org/apache/cassandra/db/compaction/ShardManagerTrivial.java
test/unit/org/apache/cassandra/db/compaction/BaseCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/ShardManagerReplicaAwareTest.java
test/unit/org/apache/cassandra/db/compaction/ShardManagerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ShardedMultiWriterTest.java

In addition to correcting for very small spans, this also corrects sstable spans for ones having a small number of partitions where keys can easily fall in a small range. For these cases we use a value derived from the number of partitions in the table, which should work well for all scenarios, including wide-partition tables with a very limited number of partitions.

CNDB-10945: Change calculation of sstable span for small sstables

---

CHANGES.txt
src/java/org/apache/cassandra/exceptions/UnaccessibleFieldException.java
src/java/org/apache/cassandra/utils/concurrent/Ref.java

The issue can be seen in the logs when running (even if the test completes successfully):
`ant testsome -Dtest.name=org.apache.cassandra.index.sai.disk.vector.VectorCompressionTest -Dcassandra.test.random.seed=792966663435 -Duse.jdk11=true`
After the patch, it is not reproducible anymore

CNDB-11078: Prevent InaccessibleObjectException when the Leak Detector is traversing objects (port CASSANDRA-18708)

---

src/java/org/apache/cassandra/index/sai/disk/v1/KDTreeIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReader.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReaderTest.java

The eagerly populated leafNodeToLeafFP TreeMap has been replaced with a LeafCursor which allows to traverse the index tree directly, in a lazy way.
The change significantly reduces the amount of up-front work we did to initialize the BKDReader.IteratorState.
It also reduces GC pressure and memory usage.
The user-facing effect is that `ORDER BY ... LIMIT ...` queries using a numeric index (KD-tree) are significantly faster.
Fixes https://github.com/riptano/cndb/issues/11021

CNDB-11021: Improve performance of ORDER BY using KD-tree index

---

test/unit/org/apache/cassandra/db/marshal/AbstractTypeTest.java
test/unit/org/apache/cassandra/utils/AbstractTypeGenerators.java

The failing test compares the ordering of decomposed values to the ordering of composed values defined in `AbstractTypeGenerators`. The latter is usually a call to the `compareTo` method of the base type of the `AbstractType`.
The problem here is that all the geometry types and `DateRange` don't implement `Comparable`. It seems correct that those types don't implement `Comparable`, since it doesn't seem there is a natural way of comparing that kind of data.
However, the `AbstractTypeGenerators` machinery seems to drag us into defining a comparator of composed types. Thus, CNDB-9145 provided comparators for the composed values of those types that were based on their decomposed values. 
However, those decomposed values are compared with the natural order of `ByteBuffer`, which is different …

CNDB-11105: Fix AbstractTypeTest#ordering()

---

test/distributed/org/apache/cassandra/distributed/test/ReadCoordinationMetricsTest.java

Fixes ReadCoordinationMetricsTest.testPreferredOtherReplicas

Disable dsnitch for ReadCoordinationMetricsTest > rf=1

---

src/java/org/apache/cassandra/db/tries/InMemoryTrie.java

Fixes this error while running on JDK22
```
Caused by: java.lang.ExceptionInInitializerError: null
5864
at org.apache.cassandra.db.memtable.TrieMemtable$MemtableShard.<init>(TrieMemtable.java:642)
5865
at org.apache.cassandra.db.memtable.TrieMemtable$MemtableShard.<init>(TrieMemtable.java:635)
5866
at org.apache.cassandra.db.memtable.TrieMemtable.generatePartitionShards(TrieMemtable.java:180)
5867
at org.apache.cassandra.db.memtable.TrieMemtable.<init>(TrieMemtable.java:169)
5868
at org.apache.cassandra.db.memtable.TrieMemtable$Factory.create(TrieMemtable.java:846)
5869
at org.apache.cassandra.db.memtable.DefaultMemtableFactory.create(DefaultMemtableFactory.java:38)
5870
at org.apache.cassandra.db.ColumnFamilyStore.createMemtable(ColumnFamilyStore.java:1494)
5871
at …
```

CNDB-10295 Followup - Do not use lambdas in InMemoryTrie

---

src/java/org/apache/cassandra/dht/tokenallocator/TokenAllocation.java

Fixes https://github.com/riptano/cndb/issues/11134
It's possible that there are external reasons why we won't hit an NPE here, but based on reading the code, it seems possible. Instead of two get calls with two different locks, I propose that we store the result of the call to `getEndpoint` and then use that result in the subsequent logic to check `inAllocationRing`

CNDB-11134: Fix data race in adjustForCrossDatacenterClashes to prevent NPE

---

conf/jvm17-server.options

Tested locally that Cassandra starts on JDK22

Fix access to JDK internals for jamm post CNDB-9850

---

build.xml
src/java/org/apache/cassandra/cql3/functions/JavaBasedUDFunction.java

Upgrade:
- ecj plus fix the java udf functions for JDK11+
- snakeyaml - it was already bumped in CNDB for security vulnerability
- test dependencies:
jacoco, byteman - higher version than CNDB but it is needed for catching up on JDK22 in tests
findbugs - aligned with CNDB version but we probably want at some point to get to major version upgrade; not a priority for now
jmh, bytebuddy - bumped to latest versions as they are known for not working on newer JDK versions
Butler reported some new test failures, but they were all some timeouts, not related to what we do here.

CNDB-11028:  Upgrade dependencies in preparation to test with newer JDK versions and to align CNDB and CC dependency versions

---

src/java/org/apache/cassandra/index/sai/utils/IndexFileUtils.java
src/java/org/apache/cassandra/io/util/SequentialWriter.java

Reuse CRC when appending index components

---

test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/functional/SnapshotTest.java

I think the failures of these tests are due to merge conflicts between https://github.com/datastax/cassandra/pull/1099 and [CASSANDRA-18714](https://issues.apache.org/jira/browse/CASSANDRA-18714).
https://github.com/datastax/cassandra/pull/1099 modified `SAITester.perSSTableValidationCounter` and `SAITester.perColumnValidationCounter` injections to only count checksum validations, instead of all kind of validations. However, [CASSANDRA-18714](https://issues.apache.org/jira/browse/CASSANDRA-18714) modified the way validations are done to do more checksum validations. As a result, the counting doesn't match what the tests expect.
I have modified those injections to count all validations again, so the new checksum validations are included. 
Additionally, I have made some changes in …

CNDB-11168 main-5.0: Fix NodeRestartTest and SnapshotTest

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
test/unit/org/apache/cassandra/index/sai/functional/GroupComponentsTest.java

This fixes `GroupComponentsTest.testInvalidateWithoutObsolete`. I wouldn't be surprised if it fixed some other issues.
Since we are here, I have also done some minor cleaning in `GroupComponentsTest`.

CNDB-11149: Add missing SAI implementation of Index.getUnloadTask

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/utils/Overlaps.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
test/unit/org/apache/cassandra/utils/OverlapsTest.java

- prioritize overlap set with more sstables in `Overlaps.constructOverlapSets`

CNDB-10991: skip aggregate that includes any sstables that are already selected by other aggregates

---

src/java/org/apache/cassandra/cql3/QueryProcessor.java

Concurrent computation of a value and invalidation of the same key can result in 'undefined' behavior in caffeine. We have observed occasional deadlocks.

DSP-24330 QueryProcessor evictPrepared deadlock

---

test/long/index/sai/cql/AnalyzerQueryLongTest.java
test/unit/org/apache/cassandra/index/sai/cql/IndexGroupRemovalTest.java
test/unit/org/apache/cassandra/index/sai/cql/IndexParallelBuildTest.java
test/unit/org/apache/cassandra/index/sai/cql/RandomisedComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/cql/TokenRangeReadTest.java
test/unit/org/apache/cassandra/index/sai/metrics/IndexGroupMetricsTest.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java

Fixes `QueryMetricsTest.testIndexQueryWithPartitionKey` and `AnalyzerQueryLongTest`.

CNDB-11189: Fix usages of waitForTableIndexesQueryable

---

src/java/org/apache/cassandra/service/reads/DataResolver.java

This fixes `IndexConsistencyTest`.

CNDB-11247: Fix pre-count filter in the first phase of RFP

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/metrics/KeyspaceMetrics.java
src/java/org/apache/cassandra/metrics/TableMetrics.java

While building the Grafana dashboards I found that:
- the time spent for memtable flush was taken in the wrong places (and in fact the time to write SAI was bigger then the time reported as total flush time)
- the histograms don't show well how much time we spend in compaction/flush vs Index build, because with the histograms you track only the distribution of many smaller events, and with BucketedGauge we cannot have the total sum
- nanosecond precision is useless
Modifications:
This patch reworks #1329 with these changes:
- metrics become counters
- we track microseconds instead of nanoseconds
- the time to flush is measoured in a better place

CNDB-8187 Move SAI writing metrics to micros and use counters

---

CHANGES.txt
src/java/org/apache/cassandra/auth/IAuthenticator.java
src/java/org/apache/cassandra/transport/messages/StartupMessage.java
test/unit/org/apache/cassandra/auth/CustomAuthenticatorTest.java
test/unit/org/apache/cassandra/auth/PasswordAuthenticatorTest.java

Allows custom implementations of IAuthenticator to return their own AuthenticateMessage based on ClientState information.
ClientState contains information about driver's name and version which could be used to determine the contents of the AuthenticateMessage that is sent back to the clients. This enables, for instance, returning driver's known authenticator implementations (e.g. DseAuthenticator) which enables SASL negotiation.
patch by Tiago Alves; reviewed by Mick Semb Wever, Andy Tolbert for CASSANDRA-19984

Enables IAuthenticator's to return own AuthenticateMessage

---

src/java/org/apache/cassandra/db/DiskBoundaryManager.java

If `localRanges` is <=1 then set `positions` to `null` for `DiskBoundaries`

CNDB-11137 Set positions to null when local ranges are <= 1

---

src/java/org/apache/cassandra/io/sstable/SSTable.java

When we call the method to rewrite the TOC file of an sstable, we expect that TOC to exists previously. It's not important to the rewrite itself, we can still get the end state we want regardless, but not having a TOC is unexpected and could be a delayed sign of an earlier issue. Before commit bc62d52652241866e00dea371d133ed0118946b6, we used to log a warning in that situation (technically, we used to log if we couldn't delete the prior version of the TOC, and having that file not existing was the main reason this would fail). This patch adds back a log warning for that situation, so we can keep an eye on that unexpected situation.

Add warning when rewriting TOC that does not exist

---

test/unit/org/apache/cassandra/index/sai/memory/AbstractTrieMemtableIndexTest.java
test/unit/org/apache/cassandra/index/sai/memory/OffHeapTrieMemtableIndexTest.java
test/unit/org/apache/cassandra/index/sai/memory/OnHeapTrieMemtableIndexTest.java

I think the problem is that the test sets `TrieMemtable.BUFFER_TYPE` through reflection multiple times, but there are other parts of the code reading and retaining that before the change. Also, separate accesses to the unmodified `DatabaseDescriptor.getMemtableAllocationType()` might conflict with the modified `TrieMemtable.BUFFER_TYPE`.
The proposed approach splits the test into separate classes for off-heap and on-heap scenarios, and sets `config.memtable_allocation_type` at the beginning of the tests, before initialization. That way we can ensure that we have the proper config everywhere.
Note also that [CASSANDRA-19326](https://issues.apache.org/jira/browse/CASSANDRA-19326) has switched memtable_allocation_type from offheap_objects to heap_buffers in `test/conf/cassandra.yaml`, while …

CNDB-11322 main-5.0: Fix TrieMemtableIndexTest.indexIteratorTest

---

src/java/org/apache/cassandra/db/ClusteringComparator.java
src/java/org/apache/cassandra/db/marshal/AbstractType.java

Jamm doesn't work on JDK22 with hidden classes, generated from Lamdas
```
java.lang.UnsupportedOperationException: can't get field offset on a hidden class: private final org.apache.cassandra.db.ClusteringComparator org.apache.cassandra.db.ClusteringComparator$$Lambda/0x00007f6b17593298.arg$1
at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:652)
at org.github.jamm.MemoryLayoutSpecification.sizeOfInstanceWithUnsafe(MemoryLayoutSpecification.java:108)
at org.github.jamm.MemoryLayoutSpecification.sizeOfWithUnsafe(MemoryLayoutSpecification.java:89)
at org.github.jamm.MemoryMeter.measure(MemoryMeter.java:217)
at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:259)
at org.apache.cassandra.utils.ObjectSizes.measureDeep(ObjectSizes.java:216)
at …
```

CNDB-10716: do not use lambdas as they don't work with Jamm 3 on JDK22

---

src/java/org/apache/cassandra/db/compaction/CompactionController.java
src/java/org/apache/cassandra/db/memtable/AbstractAllocatorMemtable.java
src/java/org/apache/cassandra/db/memtable/Memtable.java
src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/db/partitions/TrieBackedPartition.java
test/unit/org/apache/cassandra/db/compaction/CompactionControllerTest.java
test/unit/org/apache/cassandra/db/memtable/MemtableThreadedTest.java
test/unit/org/apache/cassandra/db/partition/PartitionImplementationTest.java
test/unit/org/apache/cassandra/db/rows/ThrottledUnfilteredIteratorTest.java

The PR fixes two problems:
- incorrect wiring of atomicity and consistency of trie writes, resulting in writes to the memtable that are not atomically visible to readers, or that could reflect an inconsistent write order.
- problems reading memtables from compaction when concurrent changes in the memtable modify data that the reads reference, https://github.com/riptano/cndb/issues/11398
The former problem was an incorrect type used in a check; patch also adds a test that will _intermittently_ fail if the problem reoccurs.
The latter is solved by getting an `OpOrder.Group` to guard the read state for its duration.

CNDB-11398: Fix concurrency issues with new TrieMemtable

---

build.xml

Sets `cassandra.test.processorCount` default to 4, same as in `main`. It will also make it consistent with the `-XX:ActiveProcessorCount=4` option used by `ide/idea/workspace.xml`.

CNDB-11391 main-5.0: Set cassandra.test.processorCount default to 4

---

test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java

I think the failure is due to the version of Mockito used in 5.0 having different behaviour than the one in `main`. The test expects that the mock defaults to the real methods if no specific behaviour has been defined for them. That seems to be the default behaviour in `main`, but in 5.0 we need to specify it with Mockito settings.

CNDB-11426 main-5.0: Fix PlanTest.testLazyAccessPropagation

---

test/unit/org/apache/cassandra/db/compaction/BaseCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionStrategyStatisticsTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java

Two tests in `CompactionStrategyStatisticsTest` are failing with NPE because `Controller.overlapInclusionMethod()` returns `null` on a mocked object. 
See: https://github.com/riptano/cndb/issues/11438
This changes the affected tests to return a value for `overlapInclusionMethod()` on the mocked object.

CNDB-11438 main: Fix CompactionStrategyStatisticsTest

---

pylib/cqlshlib/cqlhandling.py

The CQLSH TestConstants.test_cql_reserved_keywords has been failing since #837 
Adds missing `geo_distance` keyword to the list of cqlsh reserved words.

CNDB-11435 Fix CQLSH TestConstants.test_cql_reserved_keywords

---

CHANGES.txt
src/java/org/apache/cassandra/service/StorageService.java
test/distributed/org/apache/cassandra/distributed/impl/Instance.java
test/distributed/org/apache/cassandra/distributed/mock/nodetool/InternalNodeProbe.java

patch by Stefan Miklosovic; reviewed by Andrés de la Peña for CASSANDRA-18152
Fix for org.apache.cassandra.distributed.test.FullRepairCoordinatorFastTest
Port [CASSANDRA-18152](https://issues.apache.org/jira/browse/CASSANDRA-18152)

CNDB-11356: Remove mocking in InternalNodeProbe spying on StorageServiceMBean

---

pylib/cqlshlib/test/test_cqlsh_completion.py

Port of https://github.com/datastax/cassandra/commit/5652cd799452e14449fec05019847995801d42b5 from `main-5.0`.

CNDB-11436: Fix cqlsh test_complete_in_select_limit_clause

---

src/java/org/apache/cassandra/db/DiskBoundaryManager.java
src/java/org/apache/cassandra/db/SortedLocalRanges.java
test/unit/org/apache/cassandra/db/SortedLocalRangesTest.java

Fixes #11137 Undoes v1 and instead allows SortedLocalRanges to be empty, allowing scrub to work and passing the test that v1 broke: https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-build-fast-ci-5.0/22/#showFailuresLink

CNDB-11137 v2: Allow SortedLocalRanges to be empty

---

src/java/org/apache/cassandra/dht/tokenallocator/NoReplicationTokenAllocator.java
src/java/org/apache/cassandra/dht/tokenallocator/TokenAllocatorBase.java
test/unit/org/apache/cassandra/dht/tokenallocator/NoReplicationTokenAllocatorFastTest.java

https://github.com/riptano/cndb/issues/11219 - this work is part of an ongoing effort to make deterministic token allocation work. @blambov pointed out that it would be simplest to provide the seed token to the `TokenAllocatorBase`, so I do that here. I also revert part of the PR from https://github.com/riptano/cndb/issues/11217 that was not necessary.
This PR updates the TokenAllocatorBase and the
NoReplicationTokenAllocator by making each take
a Supplier<Token> object. This supplier is used
to allocate the first token in the ring. The
change is backwards compatible.

CNDB-11219: Make TokenAllocatorBase take a supplier for first token allocation

---

src/java/org/apache/cassandra/index/sai/disk/format/Version.java
test/unit/org/apache/cassandra/index/sai/plan/PlanTest.java

Additionally, this required a few minor query optimizer test adjustments because the ANN cost model coefficients changed in version DC.
Enable performance improvements introduced by version DC od SAI format.
We can do it now because the version already deployed in production (in September) understands DC format.

CNDB-11492: Bump up Version.LATEST to DC

---

src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

Fixes https://github.com/riptano/cndb/issues/11519
Partition key restrictions can be used to optimize certain hybrid vector queries.
It optimizes hybrid vector queries that have a partition key restriction and execute in a `search-then-sort` query pattern.

CNDB-11519: Apply pk restriction earlier in hybrid sai execution

---

src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/cql3/functions/TimeFcts.java

Deprecation annotation was done in javadoc but not on the fields themselves, which led to warnings. This commit corrects annotations and removes warnings.

Fix deprecation annotation

---

src/java/org/apache/cassandra/io/sstable/compaction/SortedStringTableCursor.java

CNDB-10118 correctly decode TTLs after 2037 in SortedStringTableCursor

---

src/java/org/apache/cassandra/index/sasi/utils/trie/AbstractPatriciaTrie.java
src/java/org/apache/cassandra/index/sasi/utils/trie/PatriciaTrie.java
src/java/org/apache/cassandra/utils/btree/BTreeSet.java

- `firstEntry()` and `lastEntry()` were trying to assign weaker access privileges (e.g., private or package-private) when they need to be public according to the interface they are implementing (SequencedMap).
- JDK 21+ adds `SequencedCollection`: The `List` and `NavigableSet` interfaces now inherit from a new interface called `SequencedCollection`, which introduces the `reversed()` method. However, `NavigableSet.reversed()` returns a `NavigableSet`, while `List.reversed()` returns a `List`. This results in a conflict, as the types are incompatible.
Open question:
Instead of making the two methods `public`, we can use some kind of wrapper/adapter, but it will probably affect performance. I would appreciate more eyes and opinions on that. 
...
...

CNDB-11498: Make main branch compile on JDK22

---

test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java

Increase the timeout for waiting on the index creation. We are indexing more vectors than usual, so the default one-minute timeout might not be enough.

CNDB-11535 main: Fix failure of VectorSiftSmallTest.testMultiSegmentBuild

---

test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java

Increase the timeout for waiting on the index creation. We are indexing more vectors than usual, so the default one-minute timeout might not be enough.

CNDB-11535 main-5.0: Fix failure of VectorSiftSmallTest.testMultiSegmentBuild

---

test/unit/org/apache/cassandra/index/sai/cql/VectorCompactionTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorHybridSearchTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorRangeSearchTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTester.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTracingTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

CNDB-11518 main-5.0: Split o.a.c.index.sai.cql.VectorTypeTest to prevent timeouts

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v1/PartitionAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcherTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/LegacyOnDiskFormatTest.java

Two issues: https://github.com/riptano/cndb/issues/11413 and https://github.com/riptano/cndb/issues/11459
This PR adds more logging to the vector indexing lifecycle events. We had two issues recently that needed more information, and this should help us get closer next time.
None of the logs should be excessive since they are only done on unexpected errors or at start up or flush.
Note that some of the errors are unreachable since we don't have an exact way to reproduce the issue.

CNDB-11459 and 11413: More logging for SAI vector index events

---

conf/jvm17-server.options
src/java/org/apache/cassandra/utils/SyncUtil.java

Clean SyncUtil for newer JDK versions
Remove --add-opens java.base/java.nio=ALL-UNNAMED which is not needed anymore and clean SyncUtil
patch by Ekaterina Dimitrova; reviewed by Jacek Lewandowki for CASSANDRA-17909

CNDB-1141: Update SyncUtil for JDK11 and JDK17

---

src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorPostings.java

fixes https://github.com/riptano/cndb/issues/11663
```
Uncaught exception on thread Thread[#436,ReadStage-24,5,main]
java.lang.RuntimeException: java.lang.AssertionError: ordinal not set
at org.apache.cassandra.net.InboundSink.accept(InboundSink.java:113)
at org.apache.cassandra.net.InboundSink.accept(InboundSink.java:46)
at org.apache.cassandra.net.InboundMessageHandler$ProcessMessage.run(InboundMessageHandler.java:436)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165)
at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137)
at …
```

CNDB-11663: Handle posting list ordinal assignment race

---

src/java/org/apache/cassandra/db/compaction/DelegatingShardManager.java
src/java/org/apache/cassandra/db/compaction/ShardManager.java
src/java/org/apache/cassandra/db/compaction/ShardManagerNoDisks.java
src/java/org/apache/cassandra/db/compaction/ShardManagerReplicaAware.java
test/unit/org/apache/cassandra/db/compaction/DelegatingShardManagerTest.java
test/unit/org/apache/cassandra/db/compaction/ShardManagerReplicaAwareTest.java

https://github.com/riptano/cndb/issues/11646
Instead of computing the value once and using that for the lifecycle of the `ShardManager`, we compute it each time to ensure better accuracy. The original concern was that the call was expensive, but that does not appear to be the case.

CNDB-11646: Reclaculate ShardManager#minimumPerPartitionSpan on each call

---

test/unit/org/apache/cassandra/index/sai/disk/vector/VectorCompressionTest.java

For now, improve assertions to be a bit more informative and increase the timeout of the waiting for the index build.

CNDB-11574 main-5.0: Fix VectorCompressionTest.testBert

---

.gitignore
src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/disk/PostingListKeyRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/v1/IndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/bitpack/AbstractBlockPackedReader.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/MemtableKeyRangeIterator.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
test/unit/org/apache/cassandra/index/sai/cql/QueryTimeoutTest.java
test/unit/org/apache/cassandra/index/sai/disk/PostingListKeyRangeIteratorTest.java
test/unit/org/apache/cassandra/index/sai/disk/SingleNodeQueryFailureTest.java
test/unit/org/apache/cassandra/index/sai/iterators/KeyRangeConcatIteratorTest.java

Part of CNDB-11563
Some leftovers found in https://github.com/datastax/cassandra/pull/1412.
Also adds a generated file to .gitignore in a separate commit.

CNDB-11563 Rename few iterators to KeyRangeIterator

---

test/unit/org/apache/cassandra/db/compaction/CQLUnifiedCompactionTest.java

`CQLUnifiedCompactionTest.testMultipleCompactionsDifferentWs` needs max_sstables_to_compact increased to pass.

CNDB-11627: increase max_sstables_to_compact in CQLUnifiedCompactionTest

---

src/java/org/apache/cassandra/service/StorageProxy.java

Restores the filter from CASSANDRA-13043 for nodes that are rpc_ready

CNDB-11594 fix test_counter_leader_with_partial_view by restoring CASSANDRA-13043

---

src/java/org/apache/cassandra/net/RequestCallbacks.java
src/java/org/apache/cassandra/schema/ColumnMetadata.java
test/unit/org/apache/cassandra/net/RequestCallbacksTest.java

response verb is null for deprecated REQUEST_RSP and INTERNAL_RSP. info.responseVerb.serializer() caused NullPointerExceptions.
The null serializer is later gracefully handled in deserializePayloadPre40.

CNDB-11118 return null serializer if response verb is null

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/conditions/AbstractConditions.java
src/java/org/apache/cassandra/cql3/conditions/ColumnCondition.java
src/java/org/apache/cassandra/cql3/conditions/ColumnConditions.java
src/java/org/apache/cassandra/cql3/conditions/Conditions.java
src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/cql3/statements/ModificationStatement.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/db/ReadQuery.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/IndexRegistry.java
src/java/org/apache/cassandra/index/RowFilterValidator.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupport.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/service/reads/DataResolver.java
test/unit/org/apache/cassandra/cql3/OperatorTest.java
test/unit/org/apache/cassandra/db/filter/RowFilterTest.java
test/unit/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneUpdateDeleteTest.java
test/unit/org/apache/cassandra/io/sstable/CQLSSTableWriterClientTest.java

Make `RowFilter` aware of index analyzers, so `:` and `=` CQL operators can operate according to any underlying analyzers even if the index is not selected.
This can happen for example with `OR` expressions where one expression has an analyzing index and the other doesn't have any index:
```
CREATE TABLE t (k int PRIMARY KEY, x int, y text);
CREATE CUSTOM INDEX ON t(y) USING 'StorageAttachedIndex' WITH OPTIONS = {'index_analyzer': 'standard'};
INSERT INTO t (k, x, y) VALUES (0, 0, 'a');
SELECT * FROM t WHERE x=1 OR y:'a' ALLOW FILTERING;
```
In this case, the index won't be used and both restrictions will be filtered. When the `RowFilter` sees the `ANALYZER_MATCHES` expression on the `y` column it fails because the CQL operator cannot work without knowledge of the index.
This PR adds a …

CNDB-10731: Add support for index analyzers to RowFilter

---

conf/cassandra.yaml
src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/guardrails/Guardrails.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
test/unit/org/apache/cassandra/guardrails/GuardrailQueryFiltersTest.java

Adds a new `query_filters` guardrail to limit the number of column value filters per query after applying index analyzers.
The guardrail is applied to the sum of all column filters, analyzed or not, indexed or not. Complete primary key restrictions are not considered column value filters so they don't count towards the configured limit.
This should be useful to limit the number of filtered columns in general, and to prevent the explosion of filtering operations produced by analyzers applied to large values.

CNDB-10085: Add guardrail for the number of column filters per query after applying analyzers

---

src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v5/V5OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v5/V5VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java

Fixes: https://github.com/riptano/cndb/issues/11680
When we resume the search for a vector query, it'd be helpful to know which sstable we're inspecting.
Add the sstable/memtable to the log.

CNDB-11680: Add source sstable/memtable id to vector traces

---

src/java/org/apache/cassandra/metrics/MessagingMetrics.java
src/java/org/apache/cassandra/net/InboundMessageHandlers.java
src/java/org/apache/cassandra/net/LatencyConsumer.java
test/burn/org/apache/cassandra/net/ConnectionBurnTest.java
test/unit/org/apache/cassandra/net/MessagingServiceTest.java

Cross-node messaging metrics are now collected per Verb. Cross-node measurements are reported
regardless of their absolute values, including negative values.
For an uknown reason InboundMessageHandlers was able to silently make a decision whether
a particular time measurement of a cross-node action is valid or not. Apart from it being
a perculiar design choice, the direct consequence was that we were loosing some measurements.
Additionally, the measurements are coarse-grained, per InboundMessageHandlers, whereas
the underlying messaging implementation may use more fine tuned approach (e.g. small vs
large messages using different connections). Another problem is that we don't have
visibility into load balancing wrt message types.
This PR makes the consumer of the cross-node latency …

CNDB-9046: cross-node messaging metrics fixes

---

src/java/org/apache/cassandra/metrics/MessagingMetrics.java
src/java/org/apache/cassandra/net/InboundMessageCallbacks.java
src/java/org/apache/cassandra/net/InboundMessageHandler.java
src/java/org/apache/cassandra/net/InboundMessageHandlers.java
test/burn/org/apache/cassandra/net/Connection.java
test/burn/org/apache/cassandra/net/ConnectionBurnTest.java

New message-oriented metrics: node message handling time (per message type), and time spent by each message handler on the relevant stage (again per message type)
The isssue is lack of visibility into how much time nodes actually spend handling messages.
So far, we only had cross-node metrics.
This PR adds two additional metrics:
- node total (queue+execution) message handling time
- execution time of the message handler in the relevant stage

CNDB-11782: additional messaging metrics

---

src/java/org/apache/cassandra/concurrent/Stage.java
src/java/org/apache/cassandra/concurrent/TaskExecutionCallback.java
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
src/java/org/apache/cassandra/gms/Gossiper.java
src/java/org/apache/cassandra/net/MessagingService.java
src/java/org/apache/cassandra/schema/DefaultSchemaUpdateHandler.java
src/java/org/apache/cassandra/schema/MigrationCoordinator.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/tracing/TraceStateImpl.java
test/long/org/apache/cassandra/cql3/ViewLongTest.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/cql3/ViewAbstractTest.java
test/unit/org/apache/cassandra/cql3/ViewComplexTester.java
test/unit/org/apache/cassandra/cql3/ViewFilteringTester.java
test/unit/org/apache/cassandra/cql3/ViewSchemaTest.java
test/unit/org/apache/cassandra/schema/MigrationCoordinatorTest.java

With this change an external actor can now track task queue and execution times on stages.
The Stage encapsulation was improved. Executor-related particulars can no longer leak out.
The issue is that we don't have visibility into where do the user requests spend time
in the system
This PR adds queue wait and execution time for the Stages. Additionally, the encapsulation
of Stages was improved and there is no longer an API to reach out directly to the executor
that powers the stage.

CNDB-11581: Stage metrics improvements

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/service/StorageProxyMBean.java

+ make it configurable
The length of this backoff sleep has huge impact on LWT and read latencies (LWT reads before paxos starts).
https://github.com/riptano/cndb/issues/10851#issuecomment-2506178919
...
...

CNDB-10851 Lower paxos max backoff sleep from 100 to 50 ms

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/locator/DynamicEndpointSnitch.java
src/java/org/apache/cassandra/locator/DynamicEndpointSnitchMBean.java
test/unit/org/apache/cassandra/locator/DynamicEndpointSnitchTest.java

This change let us:
* get rid of DES coarsening the replica latency measurements to ms
resolution.
* pick a specific quantile of replica latency for the score computation
On some clusters with fast reads p50 of replica latency can be so low
that most of the measurements will be 0ms. This can be disruptive to 
replica ordering.
This fix lets us configure if we want the coarsening of the latency measurements to ms.
Additionally, it lets us configure which quantile is used for computing the scores.
In particular, DSE uses p90, not p50.
This PR does *NOT* disable the use of approximate clock for replica latency
measurements. The clock will be switched via a property set in CNDB.

CNDB-11768: DynamicEndpointSnitch tweaks: quantization and quantile is configurable now

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/db/marshal/CollectionType.java
src/java/org/apache/cassandra/db/marshal/ListType.java
src/java/org/apache/cassandra/db/marshal/MapType.java
src/java/org/apache/cassandra/db/marshal/SetType.java
src/java/org/apache/cassandra/serializers/CollectionSerializer.java
test/microbench/org/apache/cassandra/test/microbench/CollectionContainsTest.java
test/unit/org/apache/cassandra/db/marshal/ListTypeTest.java
test/unit/org/apache/cassandra/db/marshal/MapTypeTest.java
test/unit/org/apache/cassandra/db/marshal/SetTypeTest.java

Prevent full deserialization in CQL's `CONTAINS`/`CONTAINS KEY` operators. This is done by reading the serialized elements of the collection one by one and comparing them in their serialized form to the serialized candidate value. This would save us the unnecessary deserialization of the collection elements. Also, we can stop reading the collection as soon as we find a matching collection element, without having to read the rest of the rest of the elements.
This is not only a performance improvement, but it also solves a minor correctness issue. The full-deserializing approach used the `Object#equals` method of the composed column value to test the identity of the values. This differs from what we do for other operators, conditions, non-frozen collections, etc., where identity is based on …

CNDB-11760: Prevent full deserialization in CQL's CONTAINS operator

---

src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Plan#optimize can take a very long time when given plans with thousands of intersected clauses, which can result from using ngram analyzers. Related issue: https://github.com/riptano/cndb/issues/10085.
Fixes https://github.com/riptano/cndb/issues/11655

CNDB-11655: Limit the number of clauses before optimizing the Plan

---

src/java/org/apache/cassandra/cql3/functions/IndexFcts.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
src/java/org/apache/cassandra/index/sai/analyzer/JSONAnalyzerParser.java
src/java/org/apache/cassandra/index/sai/analyzer/LuceneCustomAnalyzerConfig.java
test/unit/org/apache/cassandra/index/sai/analyzer/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

As mentioned in [CNDB-10085](https://github.com/riptano/cndb/issues/10085), it might be useful to throw a client warning when creating an index using an n-gram analyzer for queries. 
In most cases, users will want to use n-gram when indexing, but query with something simpler like a whitespace analyzer, or even a no-op analyzer. Besides functionality, n-gram can produce too many index predicates, for which [CNDB-10085](https://github.com/riptano/cndb/issues/10085) will add a guardrail.
I think we could emit the warning when there is no specific `query_analyzer` and the common analyzer for both reading and writing is n-gram. I think we don't need to warn if there is a specific n-gram `query_analyzer`, since that probably indicates intentionality, rather than a mistake.

CNDB-11742: Add a client warning when using an n-gram analyzer without a query analyzer

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/inject/Injections.java

The issue is that we assert the presence of the indexes at the boundary of the query being handled, and then the `QueryController` assumes these won't change. Two cases were identified:
- one where we use assertions that might not even be enabled in prod environments.
- another one where the precondition actually is doing what it is expected but it does not give enough information.
Added reproduction tests for both cases identified. Fix by adding `UnsupportedExceptions`, though I am not sure whether we won't prefer preconditions with improved messages for both places. Open to suggestions and to hear other people opinion.
Current CI looks good to me but there is issue with building artifacts today, thus I do not have CNDB PR to upgrade the CC version. Though I think in the meantime the PR …

CNDB-10732: Reproduction tests and fixes for CNDB-10732 and CNDB-10535

---

src/java/org/apache/cassandra/index/sai/disk/format/OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/format/SSTableIndexComponentsState.java
src/java/org/apache/cassandra/index/sai/disk/format/Version.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/disk/format/IndexDescriptorTest.java
test/unit/org/apache/cassandra/index/sai/disk/format/SSTableIndexComponentsStateTest.java

Adds/expose a few methods used by https://github.com/riptano/cndb/pull/11930, namely:
- adds a method to `SSTableIndexComponentsState` to figure out if a change created unused components.
- allows to get the set of per-index component types from the index type only (instead of the full index context): `IndexContext` is a pretty heavy object, which requires a lot of things to be setup. But all that is used to figure out which components the index use is the type of the index, so allow to provide just that.
- allows to format an index component name from just the index name, instead of the full index context: same exact idea as above.

Add method to check if component diff creates unused components

---

build.xml
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java

Fixes: https://github.com/riptano/cndb/issues/11988
Bumps the jvector release to introduce some optimizations for PQ memory utilization and cosine similarity computations.

CNDB-11988: Bump jvector to 3.0.4

---

src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java

https://github.com/riptano/cndb/issues/11950
We saw many test failures in `UnifiedCompactionStrategyTest` after #1407. After investigating it a bit, it seems that the root cause to the unit test failure is likely the cost associated with the mockito calls to get different values.
However, without changing anything in Mockito, I was able to optimize the `UCS::getLevels` method enough to make the test suite go from timing out to taking 3 minutes 11 seconds when running `ant test -Dtest.name=UnifiedCompactionStrategyTest` on the command line.
Let's see if the test passes in butler.

CNDB-11950: cache sstable density result to speed up test

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/Directories.java
src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java
src/java/org/apache/cassandra/io/sstable/DefaultStorageHandler.java
src/java/org/apache/cassandra/io/sstable/StorageHandler.java
src/java/org/apache/cassandra/io/sstable/StorageHandlerFactory.java
src/java/org/apache/cassandra/io/storage/StorageProvider.java
test/unit/org/apache/cassandra/db/CustomStorageProviderTest.java

- use `cassandra.remote_storage_handler_factory` to replace `cassandra.remote_storage_handler`
- add `TableMetadata` to `StorageProvider#createDataDirectories` signature
- use `enableAutoCompaction` to replace `StorageHandler#isRemote`
- emit SSTaleAddingNotification in LifecycleTransaction#checkpoint before new sstables are made visible. Note that early open is not supported because it opens sstables before `trackNewWritten`

CNDB-11495: add REMOTE_STORAGE_HANDLER_FACTORY

---

src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/SingletonIndexGroup.java
src/java/org/apache/cassandra/index/SingletonIndexQueryPlan.java
src/java/org/apache/cassandra/index/internal/CassandraIndex.java
src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java
src/java/org/apache/cassandra/index/sasi/SASIIndex.java
src/java/org/apache/cassandra/index/sasi/plan/QueryController.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/AllIndexImplementationsTest.java
test/unit/org/apache/cassandra/index/internal/CustomCassandraIndex.java
test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/cql/filtering/FilteredQueryTester.java

Make `RowFilter` non-iterable because that’s confusing in a tree of expressions.
Instead, add an explicit `#traversedExpressions()` to traverse the expressions. Also, add a `#withoutDisjunctions()` utility method for legacy indexes. That should allow us to remove the `warnIfFilterIsATree` warning since it should be clear what each method does.

CNDB-10718: Make RowFilter non-iterable

---

src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/cql/CollectionIndexingTest.java

Comments for reviewing:
- Full scan (e.g., on truncated types) is hacked by range index scan without bounds, since `Everything` plan cannot be translated to iterator and missing iterator info as it's purpose is intermediate during planning. If there is a better approach, welcome to suggest :)
Closes https://github.com/riptano/cndb/issues/11932
The anti-join strategy for the inequality operator, `!=`, can be replaced with a union strategy of two semi-ranges, which make the plan explicit and can be more efficient.
This PR plans the inequality operator with the union of two semi-ranges, thus no anti-join iterator is used for it. In the case of truncatable types as Big Decimal and Big Integer it implements full index scan as the range index scan plan node without bounds.
This PR also adds …

CNDB-11932 plan union of half-ranges for inequality

---

src/java/org/apache/cassandra/db/streaming/CassandraEntireSSTableStreamReader.java
src/java/org/apache/cassandra/net/AsyncStreamingOutputPlus.java

- add configuration to skip mutating STATS after receiving ZCS sstable

CNDB-12130: read source file sequentially when sending file through ZCS

---

src/java/org/apache/cassandra/schema/SchemaKeyspace.java
test/unit/org/apache/cassandra/cql3/validation/entities/UFTest.java
test/unit/org/apache/cassandra/cql3/validation/operations/AggregationTest.java

This patch replaces null values of `deterministic`, `monotonic` and `monotonic_on` columns in `system_schema.functions` and `system_schema.aggregates` with negative defaults. These defaults will be addressed if/once DB-672 gets ported to CC.

DSP-24606: Replace nulls with negative defaults in system_schema

---

src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java

Fixes https://github.com/riptano/cndb/issues/12239
We found the System.nanoTime was using significant cpu cost, but because the timeout is high enough, we can accept the inaccuracy.

CNBD-12239: Replace System.nanoTime with approxTime in SAI where appropriate

---

src/java/org/apache/cassandra/cache/ChunkCache.java

CNDB-12257: do not call System.getProperty on an hotpath (ChunkCache miss)

---

build.xml
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java

Fixes regression in jvector 3.0.4 when compacting PQVectors larger than 2GB
Fix http://github.com/riptano/cndb/issues/12277

CNDB-12277: Upgrade to jvector 3.0.6

---

test/burn/org/apache/cassandra/transport/SimpleClientBurnTest.java
test/burn/org/apache/cassandra/transport/SimpleClientPerfTest.java

SimpleClientPerfTest has been failing in CI since changes from CNDB-10759
This change in `SimpleClientPerfTest`, updates the anonymous class `Message.Codec<QueryMessage>` to override the correct method, `public CompletableFuture<Response> maybeExecuteAsync` from `QueryMessage`, whose signature was changed as part of CNDB-10759.

CNDB-12272: Fix SimpleClientPerfTest

---

src/java/org/apache/cassandra/concurrent/Stage.java
test/unit/org/apache/cassandra/concurrent/StageTimeMeasurementTest.java

Enqueue start time will now be correctly measured for every API for task execution
Enqueue start times are measured at a wrong moment for some APIs.
We now measure the enqueue start time as a time of entry to each task execution API.
It was fixed so that we see the correct enqueue times in metrics

CNDB-12346: Fix reporting enqueue time for stage tasks

---

test/unit/org/apache/cassandra/transport/TransportTest.java

...
TransportTest was not accounting for JEP-416 and failing on JDK22 as observed in #11508.
...
The PR contains:
-  the commits from #11508 that enable JDK22 and which should be merged until tomorrow as part of #11508.
- last commit fixes the issue we tackle here and we target to commit only that commit as part of this ticket. The #11508 commits are added just for test purposes.

CNDB-12393: Refactor TransportTest to account for JEP-416

---

src/java/org/apache/cassandra/db/ClusteringComparator.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
test/unit/org/apache/cassandra/index/sai/cql/ClusteringKeyIndexTest.java

Fixes: https://github.com/riptano/cndb/issues/12445
Appears to be a regression introduced by https://github.com/datastax/cassandra/commit/338902ce0849e2e6f9b11a689a9c478e0b20ad6c or https://github.com/datastax/cassandra/pull/1177
The general issue is that SAI uses `OSS41` to encode its primary keys in the trie index, but this code path attempted to interpret the clustering columns using `OSS50`.

CNDB-12445: parameterize ByteComparable.Version for clusteringFromByteComparable

---

bin/cassandra.in.sh
build.xml
conf/jvm22-clients.options
conf/jvm22-server.options
ide/idea/workspace.xml
pylib/cassandra-cqlsh-tests.sh
src/java/org/apache/cassandra/cql3/functions/JavaBasedUDFunction.java
src/java/org/apache/cassandra/service/StorageService.java
test/anttasks/org/apache/cassandra/anttasks/JdkProperties.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
tools/bin/cassandra.in.sh

...
CNDB-11508 for main-5.0
...
Squashed all the commits from CNDB-11508-5.0 on top of CNDB-12154

CNDB-11508:  Add config to enable JDK22 test and run

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/view/IndexViewManager.java
src/java/org/apache/cassandra/index/sai/view/View.java
src/java/org/apache/cassandra/notifications/SSTableAddedNotification.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/view/IndexViewManagerTest.java

This commit failed several CNDB tests.
This reverts commit 6a1e98148bc6ce02003d2569d66e7d31c216a0f1.

Revert "CNDB-12342: Avoid unnecessary looping in QueryView#build (#1491)"

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/view/IndexViewManager.java
src/java/org/apache/cassandra/index/sai/view/View.java
src/java/org/apache/cassandra/notifications/SSTableAddedNotification.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/view/IndexViewManagerTest.java

Instead of matching sstables and memtables to indexes we know, go in the opposite direction: find a corresponding index for each sstable and memtable. That limits the necessity of retrying. It also has an additional benefit of detecting
reliably the situation when the indexes are suddenly dropped during the query or when the indexes are permanently missing for any other reason - we can signal those situations immediately with an exception instead of looping until the query timeout.
Retrying is only needed whenever an index view update happens (e.g. due to a flush or compaction) and the index view is temporarily out of sync from the C* View.
We now detect this situation more accurately than before - the SAI View class now keeps track not only of the indexes, but also of all the sstables …

Cherry-pick: CNDB-12342: Avoid unnecessary looping in QueryView#build

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/view/IndexViewManager.java
src/java/org/apache/cassandra/index/sai/view/View.java
src/java/org/apache/cassandra/notifications/SSTableAddedNotification.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/view/IndexViewManagerTest.java

QueryView.Builder#build falls into an infinite loop sometimes and a query timeout happens
This PR changes the direction we match indexes with sstables/memtables.
Instead of going from the indexes to sstables/memtables, we start with sstables/memtables and then match indexes to them. 
This allows to limit the looping and also reliably detect the situations when an index is permanently missing (e.g. it was dropped or invalid).

CNDB-12342 Fix query view builder inifinite loop

---

.build/build-resolver.xml
build.xml
ide/idea/vcs.xml
ide/idea/workspace.xml
mount-tmpfs
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/SystemKeyspace.java
src/java/org/apache/cassandra/db/commitlog/CommitLogSegmentReader.java
src/java/org/apache/cassandra/repair/SystemDistributedKeyspace.java
src/java/org/apache/cassandra/schema/SchemaKeyspace.java
test/conf/logback-test.xml
test/distributed/org/apache/cassandra/distributed/Cluster.java
test/distributed/org/apache/cassandra/distributed/impl/AbstractCluster.java
test/distributed/org/apache/cassandra/distributed/impl/Instance.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/cql3/KeywordTestBase.java
test/unit/org/apache/cassandra/cql3/validation/entities/UserTypesTest.java
test/unit/org/apache/cassandra/db/compaction/ActiveOperationsTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ShardedMultiWriterTest.java
test/unit/org/apache/cassandra/db/memtable/FlushingTest.java
test/unit/org/apache/cassandra/nodes/virtual/LegacySystemKeyspaceToNodesTest.java
test/unit/org/apache/cassandra/schema/KeyspaceMetadataTest.java
test/unit/org/apache/cassandra/tools/nodetool/StatusTest.java

This pull request includes several changes to the build configuration and source code, primarily focused on improving the handling of temporary directories and enhancing the logging and schema management processes. The most important changes include modifications to the build files, the addition of a new script for mounting a tmpfs filesystem, and updates to logging and schema management in the source code.
* Added a `delete` task to clean up library directories before resolving libraries. This is important because when we update, say version of a library, and then build the project, the library at old version would stay along with the library at new version causing unpredictable behaviour unless explicit clean is run.
* The default tmp dir is set ot `${build.test.dir}/cassandra` instead …

CNDB-10289: Improve local testing

---

src/java/org/apache/cassandra/cql3/restrictions/MultiColumnRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/Restriction.java
src/java/org/apache/cassandra/cql3/restrictions/RestrictionSet.java
src/java/org/apache/cassandra/cql3/restrictions/RestrictionSetWrapper.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/cql3/restrictions/TokenFilter.java
src/java/org/apache/cassandra/cql3/restrictions/TokenRestriction.java
src/java/org/apache/cassandra/cql3/selection/SortedRowsBuilder.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java
src/java/org/apache/cassandra/index/sai/utils/InMemoryPartitionIterator.java
src/java/org/apache/cassandra/utils/TopKSelector.java
test/distributed/org/apache/cassandra/distributed/test/QueryInfoTrackerDistributedTest.java
test/distributed/org/apache/cassandra/distributed/test/sai/GenericOrderByTest.java
test/microbench/org/apache/cassandra/test/microbench/SortedRowsBuilderBench.java
test/unit/org/apache/cassandra/cql3/selection/SortedRowsBuilderTest.java
test/unit/org/apache/cassandra/index/sai/StorageAttachedIndexTest.java

It was recently found that index-based sorting is done twice in the coordinator. The first sorting is done by `StorageAttachedIndexQueryPlan#postProcessor`, at the service level, which sorts a `PartitionIterator`. Then a second sorting is done by `SortedRowsBuilder`, at the CQL level, which sorts a simpler `List<ByteBuffer>`.
[CNDB-11762](https://github.com/riptano/cndb/issues/11762) removed the entire `StorageAttachedIndexQueryPlan#postProcessor` method so sorting was not duplicated anymore. However, this was problematic for implementations of `QueryInfoTracker.ReadTracker`, which is applied after sorting with the postprocessor, but before sorting at the CQL level, [here](https://github.com/datastax/cassandra/blob/main/src/java/org/apache/cassandra/service/StorageProxy.java#L2304-L2310). …

CNDB-12308: Remove index-based sorting at CQL level

---

build.xml
src/java/org/apache/cassandra/utils/logging/LogbackLoggingSupport.java
test/conf/logback-burntest.xml
test/conf/logback-dtest.xml
test/conf/logback-test-jenkins.xml
test/conf/logback-test.xml
test/unit/org/apache/cassandra/cql3/validation/operations/AggregationTest.java
test/unit/org/apache/cassandra/utils/OrderCheckingIterator.java
test/unit/org/apache/cassandra/utils/logging/LogbackLoggingSupportTest.java

Old slf4j and logback are suffering from known security vulnerabilities.
This change upgrades the dependencies to versions with fixed vulnerabilities.

CNDB-11076: bump SLF4J version to 2.0.9; bump logback version to 1.4.14 to get rid of security holes

---

test/unit/org/apache/cassandra/index/sai/plan/SingleRestrictionEstimatedRowCountTest.java

Reduces amount of created tables by creating all needed tables in advance. As the result the test can be placed into single test function.
This improves local test execution time from 5.5 seconds down to 1.4 seconds. Reduction in CI from 13 to 5 seconds.
Also removes disabling optimizer, which wasn't necessary.

Improve performance of SingleRestrictionEstimatedRowCountTest

---

test/distributed/org/apache/cassandra/distributed/test/TestBaseImpl.java

Temp directory is not created.
Create temp directory when starting distributed tests.

CNDB-10289: Create missing tmp directory

---

src/java/org/apache/cassandra/index/sai/metrics/IndexMetrics.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/metrics/IndexMetricsTest.java

Reviewing comments:
- This PR contains few commits with improvements unrelated to the issue but in the same files
- Tests in `IndexMetricsTest` can be improved similarly to the added test, `testQueriesCount`, if the approach with the help function `assertIndexQueryCount` seems reasonable for reviewer. This is except `testSameIndexNameAcrossKeyspaces`, which is complicated due to several keyspaces.
Part of https://github.com/riptano/cndb/issues/9594
Some warnings and possibilities for minor improvements  in affected files.
Implements counting queries for each index in metrics. Adds unit tests for some cases.
Also minor improvements in separate commits:
- Fix warnings on unnecessary protected modifier for final classes' constructors by removing them on touched file Plan.java.
- Fix warnings …

CNDB-9594: collect query count in index metrics

---

src/java/org/apache/cassandra/index/sai/plan/QueryView.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java

When the index is missing we rethrow it as `InvalidRequestException`, but that exception is not expected to be thrown from the replica and the coordinator reports it as uncaught exception.
The sstable name is not recorded on the exception propagated up to the coordinator (but it is only logged).
Wrap MissingIndexException in IOError so the coordinator knows how to classify the exception.
Add memtable/sstable information to the exception object.

CNDB-12539: Improve reporting missing SAI indexes

---

src/java/org/apache/cassandra/io/compress/CompressionMetadata.java
src/java/org/apache/cassandra/io/util/Memory.java
src/java/org/apache/cassandra/metrics/MicrometerNativeMemoryMetrics.java
src/java/org/apache/cassandra/metrics/NativeMemoryMetrics.java

In CNDB-12471 we are deciding new setting for the memory for Cassandra nodes, but we lack metrics about how much native memory is used by CompressionMetadata.
Add a new metric

CNDB-12471: expose metric about Native memory used by CompressionMetadata

---

CHANGES.txt
src/java/org/apache/cassandra/schema/MemtableParams.java
test/unit/org/apache/cassandra/schema/MemtableParamsTest.java

Make configuration entries in memtable section order-independent
patch by Stefan Miklosovic; reviewed by David Capwell for CASSANDRA-19906
The configuration bug reported in [CASSANDRA-19906](https://issues.apache.org/jira/browse/CASSANDRA-19906) currently blocks HCD 1.2 from being used in [cass-operator](https://github.com/k8ssandra/cass-operator) as the server will not start.
This PR cherry-picks the Cassandra 5.0.1 patch for CASSANDRA-19906 which will allow HCD 1.2 versions based on it to start in k82 environments (cass-operator and other projects that use it). The upstream commit is [here](https://github.com/apache/cassandra/commit/971747e3e25b7dec6a8ed50ed56ac0d14a3de6b1)

Port CASSANDRA-19906 from Cassandra 5.0.1

---

test/unit/org/apache/cassandra/index/sai/plan/SingleRestrictionEstimatedRowCountTest.java

Fixes https://github.com/riptano/cndb/issues/12243
main-5.0 uses different default for memetable SAI structure than 5.0. This commits adjusts the expected row count values. Also removes assert on the total row count, since it varies in this branch for different column types.
This PR is likely to conflict with #1502 after the merge when rebased from `main`.

Fix expected values in SingleRestrictionEstimatedRowCountTest

---

src/java/org/apache/cassandra/schema/Schema.java
src/java/org/apache/cassandra/service/PendingRangeCalculatorService.java
test/unit/org/apache/cassandra/gms/PendingRangeCalculatorServiceTest.java
test/unit/org/apache/cassandra/locator/SimpleStrategyTest.java

Pending ranges calculator service in the original (C*5.0) version always processes all the keyspaces but don't allow to queue more than one run (in order to not do the work multiple times needlessly)
In CC we want to limit the processed keyspaces to those belonging to certain tenants - from CC point of view, this is just a keyspace name filter. However, running for different sets of keyspaces and not enqueueing more than one run was not achieved in 5.0 so far.
In particular, in this case the pending ranges calculation were run as much times as we scheduled it.
This change ports the fix from CNDB-8538 and adjust it to C*5.0 codebase. That is, when we request PRC for a set of the keyspaces, a PRC is guaranteed to run at least once after requesting it.

CNDB-10468: Port CNDB-8538 for C*5.0 codebase

---

src/java/org/apache/cassandra/db/compaction/AbstractTableOperation.java
src/java/org/apache/cassandra/db/compaction/ActiveOperations.java
src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
src/java/org/apache/cassandra/db/compaction/CompactionCursor.java
src/java/org/apache/cassandra/db/compaction/CompactionInterruptedException.java
src/java/org/apache/cassandra/db/compaction/CompactionIterator.java
src/java/org/apache/cassandra/db/compaction/CompactionManager.java
src/java/org/apache/cassandra/db/compaction/CompactionProgress.java
src/java/org/apache/cassandra/db/compaction/CompactionTask.java
src/java/org/apache/cassandra/db/compaction/CompositeCompactionTask.java
src/java/org/apache/cassandra/db/compaction/SharedCompactionProgress.java
src/java/org/apache/cassandra/db/compaction/SharedTableOperation.java
src/java/org/apache/cassandra/db/compaction/TableOperation.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/unified/UnifiedCompactionTask.java
src/java/org/apache/cassandra/db/repair/PendingAntiCompaction.java
src/java/org/apache/cassandra/db/virtual/SSTableTasksTable.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
test/microbench/org/apache/cassandra/test/microbench/CompactionBreakdownBenchmark.java
test/unit/org/apache/cassandra/db/compaction/ActiveOperationsConcurrencyTest.java
test/unit/org/apache/cassandra/db/compaction/BaseCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionAggregateTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionsTest.java
test/unit/org/apache/cassandra/db/compaction/CompositeCompactionTaskTest.java
test/unit/org/apache/cassandra/db/compaction/SharedCompactionProgressTest.java
test/unit/org/apache/cassandra/db/compaction/SharedTableOperationTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/unified/BackgroundCompactionTrackingTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ParallelizedTasksTest.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java

Partial compactions only report as total size the size of initiated compaction operations. This underrepresents the size of the operation, which can result in bad progress indications (going to 100% then back to 50% etc.), especially with the current implementation of major compaction in CNDB where partial tasks are started in sequence.
Additionally, CNDB is only using the `ActiveOperations` view to show operation progress, which is currently listing only composite compaction subtasks, with no information about the total size of operations, and way to understand the total progress and expected duration of e.g. a major compaction.
Starts presenting composite tasks as a single operation in the `ActiveOperations` view. Adds the ability to stop all subtasks through this, aborting them quicker …

CNDB-12431: Report correct total size of parallelized compactions

---

src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
test/unit/org/apache/cassandra/index/sai/cql/DBPE14965Test.java

An index on static column indexes static rows only,
an index on non-static column indexes regular rows only.
Because the partition key is always present in static rows,
before this patch,
an index on partition key received both static and non-static
rows which could lead to duplicates under some circumstances.

DBPE-14965: Don't mix indexing static and non-static rows

---

src/java/org/apache/cassandra/db/compaction/CompactionIterator.java
src/java/org/apache/cassandra/db/compaction/CompactionTask.java
test/unit/org/apache/cassandra/db/compaction/unified/BackgroundCompactionTrackingTest.java
test/unit/org/apache/cassandra/repair/ValidatorTest.java

Failing CNDB `MultiRegionUpgradeToImmutableSAIComponentsTest`, due to `CompactionIterator.bytesRead` being calculated from values updated when the iterator is closed.
Changes `CompactionIterator.bytesRead` to match what `getTotalBytesScanned` did and removes the latter, which is no longer needed.

CNDB-12431: Fix wrong bytes read value being reported on completion of validation

---

src/java/org/apache/cassandra/service/StorageProxy.java

I added this to fix test_counter_leader_with_partial_view test in CNDB-11594 but this breaks any counter usage in CNDB.

CNDB-12588: remove check for rpc_ready

---

.github/pull_request_template.md

PR checklist is already delivered in a comment in https://github.com/datastax/cassandra/pull/1541
Removing the checklist from the PR template, which was missed.
Closes https://github.com/riptano/cndb/issues/12526

CNDB-12526 remove PR checklist

---

src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
test/unit/org/apache/cassandra/index/sai/cql/DBPE14965Test.java

An index on static column indexes static rows only, an index on non-static column indexes regular rows only.
Because the partition key is always present in static rows, before this patch,
an index on partition key received both static and non-static rows which could lead to duplicates under some circumstances.

Cherry-pick: DBPE-14965: Don't mix indexing static and non-static rows

---

src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/utils/TypeUtil.java
test/unit/org/apache/cassandra/index/sai/cql/EmptyValuesTest.java

Skip indexing empty non-literal values. 
Ideally we should index those empty values to have the same behaviour as legacy table-based secondary indexes. However, SAI has never been able to index values non-literal values. CASSANDRA-19461 was meant to add support for this, but it only did it correctly for literal types (`text`, `ascii`, `boolean` and froze multicells), breaking index building for all other types. 
I think that, until we have a good way to represent empty values in the KD tree, we should skip indexing empty non-literal types, rather than fail the entire index build.
It's worth mentioning that all the types whose empty values will be ignored return `true` in `AbstractType#isEmptyValueMeaningless`. This means that an empty binary value doesn't represent any composed value. …

CNDB-12774: Not index empty non-literal values

---

src/java/org/apache/cassandra/db/compaction/CompactionRealm.java
src/java/org/apache/cassandra/db/compaction/DelegatingShardManager.java
src/java/org/apache/cassandra/db/compaction/ShardManagerNoDisks.java
src/java/org/apache/cassandra/db/compaction/ShardManagerReplicaAware.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
test/unit/org/apache/cassandra/db/compaction/DelegatingShardManagerTest.java
test/unit/org/apache/cassandra/db/compaction/ShardManagerReplicaAwareTest.java
test/unit/org/apache/cassandra/db/compaction/ShardManagerTest.java
test/unit/org/apache/cassandra/metrics/TableMetricsTest.java

[CNDB-12899](https://github.com/riptano/cndb/issues/12899) `CompactionRealm.estimatedPartitionCount()` is very expensive
Adds a cached version of the metric and removes the memtable partitions from the calculation to make it more precise for the compaction use case.
Also makes sure that the `estimatedPartitionCount` metric is not recalculated if the table's data view (i.e. sstable and memtable set) has not changed.

CNDB-12899: Add a cached version of the estimatedPartitionCount metric

---

src/java/org/apache/cassandra/repair/consistent/LocalSessions.java
test/unit/org/apache/cassandra/repair/consistent/LocalSessionTest.java

Long running repairs trigger auto failing prematurely
Capture status pings as liveness info to prevent early termination of repairs

HCD-31 Auto failing prematurely repair sessions

---

build.xml
test/unit/org/apache/cassandra/security/SSLFactoryTest.java

The primary motivation for this change is a bug that manifests in loading
the cipher list for inter-node connections, which is slightly wider than the
configured list. This bug appears to be a consequence of how OpenSSL handles
cipher loading. Changing it doesn't seem feasible.
Netty introduced changes to mitigate this misbehavior:
- https://github.com/netty/netty/issues/13810
- https://github.com/netty/netty/issues/13840
To take advantage of these fixes, we need to upgrade Netty to at least
version 4.1.108. Upgrading Netty also necessitates bumping BoringSSL.
I have found some old CC tests in fallout that I decided to reuse to ensure the performance stays unchanged:
- http://fallout.aws.dsinternal.org/tests/ui/szymon.miezal@datastax.com/cc-write-throughput
- …

HCD-63: Upgrade Netty to 4.1.117 and BoringSSL to 2.0.69

---

src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/unit/org/apache/cassandra/schema/CreateTableValidationTest.java

Handle FSError thrown when the controller config file is too long. Otherwise, the exception causes failures to create CFS instance.
...
...

CNDB-12683 handle too long controller config file names 

---

src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/unit/org/apache/cassandra/schema/CreateTableValidationTest.java

Handle FSError thrown when the controller config file name is too long. Otherwise, the exception causes failures to create CFS instance.
...
...

CNDB-12683 handle too long controller config file names  (#1565)

---

src/java/org/apache/cassandra/db/compaction/AbstractCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/AbstractCompactionTask.java
src/java/org/apache/cassandra/db/compaction/CompactionObserver.java
src/java/org/apache/cassandra/db/compaction/CompactionStrategyManager.java
src/java/org/apache/cassandra/db/compaction/SharedCompactionObserver.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionContainer.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionStrategyStatisticsTest.java
test/unit/org/apache/cassandra/db/compaction/CompactionTaskTest.java
test/unit/org/apache/cassandra/db/compaction/SharedCompactionObserverTest.java

https://jenkins-stargazer.aws.dsinternal.org/view/cc-builds/job/ds-cassandra-publish-j11/1293/

CNDB-12774: change CompactionObserver#onCompleted to include failure exception

---

src/java/org/apache/cassandra/io/util/FileHandle.java
src/java/org/apache/cassandra/io/util/MmappedRegions.java
test/unit/org/apache/cassandra/io/util/MmappedRegionsTest.java

Memory-mapping is done in buffers of size less than 2GiB.
When these buffers aren't aligned to 4KiB and the trie-index file
spans many buffers then reading it results in going out of buffer bounds.
This patch fixes it by making sure that the buffers are correctly aligned.

DSP-24615: Fix reading mmapped trie-index exceeding 2GiB

---

src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/distributed/org/apache/cassandra/distributed/test/CompactionControllerConfigTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java

Fixes [#13004](https://github.com/riptano/cndb/issues/13004)
When a compaction controller config options are being written or read for a table with long keyspace + table names, FileSystemException happens.
This commit fixes that such exception is caught and logged. Thus existing table with long name will continue to function.
Also it catches other exceptions.

CNDB-13004 don't fail on too long file name for options

---

src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/distributed/org/apache/cassandra/distributed/test/CompactionControllerConfigTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java

When a compaction controller config options are being written or read for a table with long keyspace + table names, FileSystemException happens.
This commit fixes that such exception is caught and logged. Thus existing table with long name will continue to function. Tests are added.
Also it catches other exceptions.

CNDB-13004 don't fail on too long file name for options (#1576)

---

build.xml
conf/jvm17-server.options
conf/jvm22-server.options

Missing add-opens causes an error while caching PreparedStatement on the server
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.nio.charset.Charset.name accessible: module java.base does not "opens java.nio.charset" to unnamed module @6009bea
at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:388)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:364)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:312)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
at …
```

CNDB-12915: --add-opens for java.nio.charset

---

src/java/org/apache/cassandra/index/sai/disk/vector/VectorSourceModel.java

CNDB-12981: Revert ADA002 VectorSourceModel change to BINARY_QUANTIZATION
Reverting the change to BINARY_QUANTIZATION from PRODUCT_QUANTIZATION.  A simple change to VectorSourceModel. 
Ensures that both new and existing indexes the using the ada002 embedding model continue to use PQ for now.  All of the other changes that were originally committed with it in 655080c43054fa9bf205106f93ef68a404c80aab remain intact.

CNDB-12981: Revert ADA002 VectorSourceModel change to BINARY_QUANTIZATION

---

src/java/org/apache/cassandra/index/sai/disk/v5/V5VectorPostingsWriter.java
test/unit/org/apache/cassandra/index/sai/cql/VectorCompactionTest.java

(cherry picked from commit 5ecb085c907eb6d03a73355ae28b3734925b0cab)
Porting of https://github.com/datastax/cassandra/pull/1584 to the Jan25 release

CNDB-13027 Fix V5VectorPostingsWriter to handle omitted ordinals correctly

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

Fix `RowFilter` application of analyzers to queries on collections.
`RowFilter.SimpleExpression#isSatisfiedBy` for `CONTAINS` and `CONTAINS_KEY` operators should extract the collection values and check them with `Operator.ANALYZER_MATCHES` rather than with equality.

CNDB-13022: Fix analyzers for collections

---

src/java/org/apache/cassandra/transport/Dispatcher.java

[#13077](https://github.com/riptano/cndb/issues/13077) Dispatcher not setting client warnings
CNDB-13077 Fix Dispatcher to set coordinator client warnings before warnings are set in the Message response.

CNDB-13077

---

test/distributed/org/apache/cassandra/distributed/test/sai/TraceTest.java

The optimizer sometimes decided to use another index which messed
up the post-filtering metrics. The test does not really need
the second index at all to test tracing. Removed.

CNDB-13067: Fix flaky TraceTest

---

pylib/cqlshlib/test/run_cqlsh.py

CNDB-11460 - several cqlsh (jvm dtest) tests in TestCqlshUnicode consistently fail, with an error like:
```
E           UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4-5: unexpected end of data
```
I took a look at the test code and asked Augment for suggestions - it recommended adding some code to handle UTF-8 characters that may be split across reads. I tried the code and it looks like it does the job.

CNDB-11460 Fix cqlsh unicode tests in TestCqlshUnicode by handling UTF-8 characters that are split across reads.

---

.build/run-python-dtests.sh
.build/run-tests.sh
pylib/cassandra-cqlsh-tests.sh
src/java/org/apache/cassandra/utils/NativeLibraryDarwin.java
src/java/org/apache/cassandra/utils/NativeLibraryLinux.java
src/java/org/apache/cassandra/utils/NativeLibraryWindows.java
src/java/org/apache/cassandra/utils/NativeLibraryWrapper.java

jvm-dtest-upgrade tests are currently broken in `main` and `main-5.0`
in main-5.0 we have help testing scripts under `build/`, but they don't work because CC has changed the ant build's project name.  The first commit fixes that.
In 9943514 a number of interface method signatures were changed (return types changed to `void`).  This broke jvm-dtest-upgrade tests with errors like
```
NoSuchMethodError: 'int org.apache.cassandra.utils.NativeLibraryWrapper.callFsync(int)'
```
NativeLibraryWrapper is a https://github.com/shared annotated class.  It is shared in the one classloader between different versions of C* when running jvm-dtest-upgrade tests.
1. The test helper scripts honour the ant build's project name.
2. Restore NativeLibraryWrapper interace method signatures.

Fix jvm-dtest-upgrade tests

---

src/java/org/apache/cassandra/db/compaction/ShardTracker.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

When multiple disks are defined, `getMaxOverlapsMap` fails. This is because the shard manager returns shard indexes that cover the whole space, including shards in other disks to be able to properly split files after the boundaries change.
Change `getMaxOverlapsMap` to correct the returned shard indexes.

CNDB-12991: getMaxOverlapsMap does not correctly deal with multiple disks

---

CHANGES.txt
src/java/org/apache/cassandra/auth/IAuthenticator.java
src/java/org/apache/cassandra/transport/messages/StartupMessage.java
test/unit/org/apache/cassandra/auth/CustomAuthenticatorTest.java
test/unit/org/apache/cassandra/auth/PasswordAuthenticatorTest.java

ClientState contains information about driver's name and version which could be used to determine the contents of the AuthenticateMessage that is sent back to the clients. This enables, for instance, returning driver's known authenticator implementations (e.g. DseAuthenticator) which enables SASL negotiation.
Allows custom implementations of IAuthenticator to return their own AuthenticateMessage based on ClientState information.
This PR back-ports [CASSANDRA-19984](https://issues.apache.org/jira/browse/CASSANDRA-19984).

HCD-83 Enables IAuthenticator's to return own AuthenticateMessage

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
test/long/org/apache/cassandra/io/memtable/FlushFailingOnNotificationSubscriberTest.java

Cassandra doesn't properly support throwing notification subscribers
that fail flushes. In such case the flush is interrupted (despite
multiple uses of exception-safe code and accumulating exceptions)
after the sstable creation transaction committed, but before the
memtable has been reclaimed. As a result the memtable allocator believes
more and more memory is being used and being reclaimed eventually
stopping writes due to apparent lack of memory in the memtable.
This patch changes memtable flushing behaviour so that the memtable
is reclaimed iff it has been removed from the View, regardless
of whether the flush fails or not.

CNDB-12553: ensure that memtable is reclaimed even when notification subscribers throw

---

CHANGES.txt
conf/cassandra.yaml
src/java/org/apache/cassandra/auth/AuthConfig.java
src/java/org/apache/cassandra/auth/PasswordAuthenticator.java
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/ParameterizedClass.java
src/java/org/apache/cassandra/utils/FBUtilities.java
test/unit/org/apache/cassandra/audit/AuditLoggerAuthTest.java
test/unit/org/apache/cassandra/config/ParameterizedClassExample.java
test/unit/org/apache/cassandra/config/ParameterizedClassTest.java
test/unit/org/apache/cassandra/transport/CQLUserAuditTest.java

Enabling advanced authentication in CC requires a way to configure the auth* classes in `cassandra.yaml`.
These changes have been implemented in C* 5 tickets CASSANDRA-18554 and CASSANDRA-19946.
Partially back-ports CASSANDRA-18554 introduced initial changes to support auth* classes configuration (ticket originally added mTLS support but those changes are not part of the current PR), and back-ports CASSANDRA-19946.
Triggered `ds-cassandra-build #953` shows no test failures.

HCD-82 Enables auth* classes configuration

---

src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
test/unit/org/apache/cassandra/index/sai/cql/VectorCompactionTest.java

Addresses [CNDB-12980](https://github.com/riptano/cndb/issues/12980)
The postingsMap in CompactionGraph reuses the VectorFloat object when reading from storage. We need to copy this vector before storing it in another data structure if we want it to hold the right information.

CNDB-12980: Clone the vectors issued by the postingsMap in CompactionGraph

---

src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
test/unit/org/apache/cassandra/db/memtable/MemtableSizeTestBase.java

This patch introduces two changes:
- it adds a reading group to guard against sweeping the memtable which the metric
is going to potentially iterate through (preventing crashes).
- changes the metric calculation by using an estimate (used already by SAI query planner) instead of iterating
through the whole memtable (which proves to be quite a heavy operation).

HCD-75: Fix and improve EstimatedRowCount metric

---

src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
test/unit/org/apache/cassandra/io/sstable/SSTableReaderTest.java

Adjust the partition position by 1 when reading the compression metadata.

HCD-74: Fix CorruptSSTableException in UCS with compression

---

src/java/org/apache/cassandra/cql3/QueryProcessor.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/index/sai/cql/GenericOrderByTest.java
test/unit/org/apache/cassandra/index/sai/cql/InetAddressTypeEquivalencyTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTracingTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/cql/types/InetTest.java
test/unit/org/apache/cassandra/index/sai/disk/NodeStartupTest.java
test/unit/org/apache/cassandra/index/sai/functional/CompactionTest.java
test/unit/org/apache/cassandra/index/sai/functional/FailureTest.java
test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTest.java
test/unit/org/apache/cassandra/nodes/virtual/LegacySystemKeyspaceToNodesTest.java

Many if not most of our unit tests extend `CQLTester`. `CQLTester#execute` executes CQL queries with `ReadQuery#executeInternal`, which is what is used for internal system queries, and it's pretty similar to the local execution done by replica nodes. This misses the full validation and all the reconciliation patch used by `ReadQuery#execute`. 
Missing reconciliation is particularly problematic for utests querying secondary indexes, because they miss the application of the full `RowFilter` by the coordinator.
A more realistic behaviour can be achieved by using `CQLTester#executeNet`, which will use a driver session that will exercise the entire path. However, this has to be done manually in every test and it's easy to miss when `executeNet` is necessary. Also, `executeNet` enables more …

CNDB-12905: Allow usage of ReadQuery#execute rather than only executeInternal in CQL utests

---

src/java/org/apache/cassandra/cql3/SingleColumnRelation.java
src/java/org/apache/cassandra/index/IndexRegistry.java

The `NON_DAEMON` IndexRegistry returns `true` for all calls to `supportsExpression`. This leads to an incorrect result from the `getEqBehavior` method where we get `MATCH` instead of `EQ` because the index indicates that it can handle `ANALYZER_MATCHES` expressions and `EQ` expressions.
It is an odd edge case because the javadoc for the `NON_DAEMON` object is:
```java
/**
* An {@code IndexRegistry} intended for use when Cassandra is initialized in client or tool mode.
* Contains a single stub {@code Index} which possesses no actual indexing or searching capabilities
* but enables query validation and preparation to succeed. Useful for tools which need to prepare
* CQL statements without instantiating the whole ColumnFamilyStore infrastructure.
*/
```
This presents a problem for the …

Fix EqBehavior bug introduced by #1434

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/dht/RangeStreamer.java
test/unit/org/apache/cassandra/dht/BootStrapperTest.java

The Ford Fulkerson optimization may take too long in some configs
Some configs make the FF computation take too long
This PR adds a feature flag so you can workaround it

HCD-84 Feature flag to skip Ford Fulkerson

---

build.xml

This patch updates Netty to address CVE-2025-24970.
It also adds the Netty native epoll dependency
that was missing when Netty was upgraded from
4.1.58 to 4.1.117. Since 4.1.58, the native
libraries are now separated out into new dependencies
and must be explicitly added for them to be bundled into the tarball.
When Netty was upgraded to 4.1.117.Final, the native epoll libraries that used to be shipped in the netty-all.jar were not included. At some point since Netty 4.1.58, the native epoll and native kqueue libraries were split inot their own architecture dependent jarfiles/artifacts and must be included explicitly to pick them up.
This patch adds the missing native epol dependencies. This is similar to what was done in OSS Cassandra when they upgraded to Netty 4.1.96 here: …

HCD-96: Upgrade Netty to 4.1.118.Final

---

src/java/org/apache/cassandra/db/CounterMutation.java
src/java/org/apache/cassandra/db/counters/CachedCounterLockManager.java
src/java/org/apache/cassandra/db/counters/CounterLockManager.java
src/java/org/apache/cassandra/db/counters/StripedCounterLockManager.java
test/unit/org/apache/cassandra/db/counters/CounterLockManagerTest.java
test/unit/org/apache/cassandra/metrics/CounterMutationMetricsTest.java

While working on CNDB-12382 I have seen that increasing the number of stripes helps to solve the timeout problems.
This PR introduces an abstraction over the LOCKS mechanism in CounterMutation and provides a different implementation.
The new implementation is not based on striping the locks (that is about sharing the same lock for different keys) but it maintains a set of reference counted objects that wrap the actual locks.
(The implementation of the Lock manager is the adaptaction of a similar mechanism taken from another OSS project)
This implementation also makes it clearer that the key for the locks is an Integer, computed  by summing some hash codes, and this already creates some kind of bucketing.
It is still possible that two mutations fall into the same lock key.
When do the new …

CNDB-12382 Implement Counter locks without Striped locks

---

pylib/cqlshlib/test/run_cqlsh.py

CNDB-11460 another fix for cqlsh unicode tests in TestCqlshUnicode - make a second read in read_until to get UTF-8 characters that are split across reads.
The original fix for CNDB-11460 added the ability for the `read_tty` method to decode UTF-8 characters that get split across reads, by saving a partial buffer when a `UnicodeDecodeError` happens, and use the partial buffer with the next read. When this happens, `read_tty` will return `''` to the `read_until` method. The first fix lacked having `read_until` initiate a second read to `read_tty` and still failed with an `EOFError`.
In this PR, the `read_until` method will make a second call to `read_tty` (via `self.read`), allowing `read_tty` to read another `blksize` buffer of characters and the chance to decode UTF-8 characters that were …

CNDB-11460 another fix for cqlsh unicode tests in TestCqlshUnicode

---

src/java/org/apache/cassandra/gms/Gossiper.java
src/java/org/apache/cassandra/gms/GossiperMBean.java
src/java/org/apache/cassandra/service/StorageService.java

Node crashes during node replacements result in hibernated nodes that cannot join the cluster anymore due to lack of SYN messages from seeds.
Port DB-1482 which allows to use a jmx endpoint on a seed to bring the hibernated node back to the gossip candidate list.
Tested via: https://github.com/datastax/cassandra-dtest/pull/75.
https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-pr-gate/view/change-requests/job/PR-1617/3/testReport/dtest-offheap-bti.replace_address_test/TestReplaceAddress/tests_stage_2___dtests___dtest_offheap_bti___dtest_offheap_bti_14___test_revive_endpoint/

HCD-73: Add a jmx endpoint to change the node state in gossip

---

src/java/org/apache/cassandra/index/sai/disk/v1/DocLengthsReader.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Fixes: https://github.com/riptano/cndb/issues/13196
We were incorrectly sharing a file reader across threads in BM25 queries, which can lead to invalid results, as I reproduced in the test.
The PR fixes the issue by creating a `DocLengthsReader` object per query.

CNDB-13196: Fix BM25 file access race condition 

---

src/java/org/apache/cassandra/db/filter/ANNOptions.java
src/java/org/apache/cassandra/net/EndpointMessagingVersions.java
src/java/org/apache/cassandra/net/InboundMessageHandler.java
src/java/org/apache/cassandra/net/InboundMessageHandlers.java
src/java/org/apache/cassandra/net/OutboundConnection.java
src/java/org/apache/cassandra/net/OutboundConnectionSettings.java
test/unit/org/apache/cassandra/db/filter/ANNOptionsTest.java
test/unit/org/apache/cassandra/net/ConnectionTest.java

Fixes https://github.com/riptano/cndb/issues/13203
The underlying problem is that the `OutboundConnection` needs to store the message version from the peer. Otherwise, when the local `current_version` is higher than the remove `current_version`, we store the wrong value (we were storing the local value, not the agreed upon value).
The PR also fixes an issue in the ANN_OPTIONS serialization logic that we can hit in rare cases where the peers haven't yet connected, so the validation logic that would prevent serialization due to a peer having too low of a message version is skipped.
This PR fixes several issues related to upgrades by improving handshake logic.

CNDB-13203: Use MessagingSuccess's version for cnx version

---

src/java/org/apache/cassandra/concurrent/Stage.java
src/java/org/apache/cassandra/schema/MemtableParams.java

withTimeMeasurement breaks system queries and some fuzz tests
conditionally enable only when CUSTOM_TASK_EXECUTION_CALLBACK_CLASS is used

CNDB 13202: Only measure task execution time if CUSTOM_TASK_EXECUTION_CALLBACK_CLASS is set

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
test/unit/org/apache/cassandra/schema/CreateTableValidationTest.java

Fixes https://github.com/riptano/cndb/issues/12683
Table names are used in file names. Since the table names were not validated on its length, creating or flushing a table with too long name fails on too long file name.
There are two cases with using table names in file names:
- keyspace name `. ` table name `-controller-config.JSON`
- table name `-` 32 chars table id 
The maximum allowed file name size is 255 chars. Thus, 
- keyspace and table name, which are together longer than 231 chars, will fail.
- a table name, which is longer than 222 chars, will fail.
This PR checks that creating new table name should not have too long table name.
New tables are identified through the query's client state, which should not be internal.
The limit is 222 chars for combined keyspace and table names. …

CNDB-12683 validate table name length for not-internal

---

pylib/requirements.txt

CCM's converged-cassandra branch moving from riptano/ccm to datastax/cassandra-ccm

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
test/unit/org/apache/cassandra/schema/CreateTableValidationTest.java

Fixes https://github.com/riptano/cndb/issues/12683
Table names are used in file names. Since the table names were not validated on its length, creating or flushing a table with too long name fails on too long file name.
There are two cases with using table names in file names:
- keyspace_name .table_name-controller-config.JSON
- table_name-32chars_table_id 
The maximum allowed file name size is 255 chars. Thus, 
- keyspace and table names, which are together longer than 231 chars, will fail.
- a table name, which is longer than 222 chars, will fail.
This PR checks that creating new table name should not have too long table name.
New tables are identified through the query's client state, which should not be internal.
The limit is 222 chars for combined keyspace and table names. This is …

CNDB-12683 validate table name length for not-internal (#1623)

---

src/java/org/apache/cassandra/concurrent/ExecutorLocal.java
src/java/org/apache/cassandra/concurrent/ExecutorLocals.java
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/ReadExecutionController.java
src/java/org/apache/cassandra/service/context/DefaultOperationContext.java
src/java/org/apache/cassandra/service/context/OperationContext.java
src/java/org/apache/cassandra/service/context/OperationContextTracker.java
src/java/org/apache/cassandra/utils/concurrent/Timer.java

The goal of this commit is to allow low-level code, typically at the
level of file reads (say, a custom `FileChannel` implementation), to
obtain context on which higher level operation they correspond to. A
typical use case may for tiered storage where `FileChannel`
implementations may forward reads to remote storage, and where having
context on the overall operation could help, say, take prior work done
to set timeout, or aggregate metrics per "user-level" operations (rather
than per `FileChannel` operation).
To do this, we reuse the existing `ExecutorLocals` mechanism, and simply
have the top-level operation setup the proper context as an
`ExecutorLocal`, allowing it to be accessed by any low-level operations
operating on behalf of that operation. This is, in many way, similar to …

Add support for a per-operation context

---

src/java/org/apache/cassandra/gms/Gossiper.java
src/java/org/apache/cassandra/service/StorageService.java
test/distributed/org/apache/cassandra/distributed/impl/Instance.java
test/distributed/org/apache/cassandra/distributed/test/hostreplacement/HostReplacementTest.java

When the node gets replaced, it announces itself as hibernated (one of the silent-shutdown states). When the node replacement fails, as the other nodes see the replacing node in that state then the replacing node won't receive any gossip message from the seed at subsequent startup - which ends up with an exception.
This patch adds an explicit shutdown announcement via gossip to let other nodes know that the node was explicitly shutdown - as it was due to the exception. That allows other nodes (seeds in particular) to contact the replacing node at its next startup, thus allowing to retry the replacement.
https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-pr-gate/view/change-requests/job/PR-1626/2/testReport/org.apache.cassandra.distributed.test.hostreplacement/HostReplacementTest …

HCD-73: Fix replacing node stuck in hibernation state

---

src/java/org/apache/cassandra/cql3/selection/Selection.java
src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

When a wildcard selection is used, the score column
must be included in the selection.
Fixes:
NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 10.87.217.86:9042 us-central1>: <Error from server: code=0000 [Server error] message="java.lang.ClassCastException:
class org.apache.cassandra.serializers.UTF8Serializer cannot be cast to class org.apache.cassandra.db.marshal.VectorType$VectorSerializer
(org.apache.cassandra.serializers.UTF8Serializer and org.apache.cassandra.db.marshal.VectorType$VectorSerializer are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @446c3920)">})

CNDB-13330: Fix wildcard select with BM25 order

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/analyzer/AbstractAnalyzer.java
test/unit/org/apache/cassandra/cql3/CQLTester.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/AnalyzerTest.java

It's not allowed to create an index with non-Lucene analysis options on a frozen collection. For example:
```
CREATE TABLE t(k int PRIMARY KEY, v frozen<set<text>>);
CREATE CUSTOM INDEX ON t(FULL(v)) 
USING 'StorageAttachedIndex' 
WITH OPTIONS = {'case_sensitive': false}; -- InvalidRequestException: CQL type frozen<set<text>> cannot be analyzed
```
This IMO makes sense because it won't support any meaningful operator. However, we don't get that rejection if we try to specify an `index_analyzer`. For example:
```
CREATE TABLE t(k int PRIMARY KEY, v frozen<set<text>>);
INSERT INTO %s (k, v) VALUES (0, {'apples'})
CREATE CUSTOM INDEX ON t(FULL(v)) 
USING 'StorageAttachedIndex' 
WITH OPTIONS = {'index_analyzer':'STANDARD'}; -- Accepted
SELECT k FROM %s WHERE v CONTAINS 'ABC'; -- Column 'v' …
```

CNDB-13074: Reject analysis options on frozen collections

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
test/unit/org/apache/cassandra/schema/CreateTableValidationTest.java

Part of https://github.com/riptano/cndb/issues/13375
Using keyspace name length in the error message for too long table name is confusing, since the length might include CNDB's generated prefix invisible to users.
Reformulates the error message for too long table name to avoid using the keyspace name length, since it might contain CNDB generated prefix, which is not visible to users.

CNDB-13375 don't use keyspace name length in error message

---

src/java/org/apache/cassandra/cql3/statements/schema/CreateIndexStatement.java
src/java/org/apache/cassandra/cql3/statements/schema/CreateTableStatement.java
src/java/org/apache/cassandra/schema/SchemaConstants.java
test/unit/org/apache/cassandra/index/IndexNameTest.java

Fixes https://github.com/riptano/cndb/issues/13299
Creating an index with too long index names leads to file errors or incorrect results.
This PR prevents creating new indexes, i.e., not internal, with provided index names longer than 182 characters. This constant is based on the most restrictive requirement from different index types. It comes from SAI by subtracting the longest file name addition from the file name limit of 255 characters.

CNDB-13299 prevent too long index names

---

build.xml
src/java/org/apache/cassandra/gms/Gossiper.java

The 4th component can be used to distinguish version which introduce breaking changes, especially we want to retain the appropriate version ordering.
...
...

CNDB-13342: Add 4th component to the version

---

src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/db/Columns.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java
src/java/org/apache/cassandra/schema/ColumnMetadata.java

Fixes https://github.com/riptano/cndb/issues/13403 by implementing one of the solutions.
The current synthetic column logic relies on convention to know that the synthetic column's source column is the SAI ORDER BY column. This seems fragile and will break if we find a reason to introduce a new synthetic column. I propose that we serialize the source column name so that we can more easily support multiple synthetic columns.
The urgency for this change is that we want to get it in before we are locked into a given serde protocol.
Note however, that I haven't solved the primary issue described in https://github.com/riptano/cndb/issues/13402.
CNDB tests https://github.com/riptano/cndb/pull/13418

CNDB-13403: Add source column to synthetic column's ColumnMetadata

---

src/java/org/apache/cassandra/db/filter/RowFilter.java
test/unit/org/apache/cassandra/guardrails/GuardrailQueryFiltersTest.java

The method `RowFilter.AnalyzableExpression#numFilteredValues`, which is used by the `query_filters` guardrail, uses the index analyzer, whereas it should use the query analyzer. This could lead to wrongly triggering the guardrail in some cases.

CNDB-13171: Fix query_filters guardrail using the index analyzer instead of the query analyzer

---

build.xml
src/java/org/apache/cassandra/config/YamlConfigurationLoader.java
src/java/org/apache/cassandra/tools/JMXTool.java
test/distributed/org/apache/cassandra/distributed/test/FailingRepairTest.java
test/distributed/org/apache/cassandra/distributed/test/IncRepairTruncationTest.java
test/distributed/org/apache/cassandra/distributed/test/PreviewRepairTest.java
tools/stress/src/org/apache/cassandra/stress/StressProfile.java

The customer requested an upgrade for some libraries (CVEs)
This PR upgrades to latest stable versions
- snappy to 1.1.10.7 fixing CVE-2023-43642
- guava to 33.4.0-jre fixing CVE-2023-2976 and CVE-2020-8908
- jackson to 2.18.0 fixing CWE-400
- snakeyaml to 2.4 fixing CVE-2022-1471

HCD-62 Upgrade of several libraries

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

see CNDB-13480
When BM25 processes a delete row there is a NPE
```
2025-03-27 11:53:55 ERROR [ReadStage-2] 2025-03-26 22:53:55,397 AbstractLocalAwareExecutorService.java:169 - Uncaught exception on thread Thread[ReadStage-2,5,main]
2025-03-27 11:53:55 java.lang.NullPointerException: null
2025-03-27 11:53:55     at org.apache.cassandra.index.sai.utils.BM25Utils$DocTF.createFromDocument(BM25Utils.java:89)
2025-03-27 11:53:55     at org.apache.cassandra.index.sai.memory.TrieMemtableIndex.lambda$orderBy$5(TrieMemtableIndex.java:269)
2025-03-27 11:53:55     at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
2025-03-27 11:53:55     at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
2025-03-27 11:53:55     at …
```

CNDB-13480: NullPointerException when using ORDER BY BM25 after deleting a row

---

src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
test/unit/org/apache/cassandra/index/sai/cql/GenericOrderByTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorInvalidQueryTest.java

Queries with index-based ordering (ANN, BM25, generic `ORDER BY`) don't support CQL's aggregation queries, such as `GROUP BY` or `SELECT COUNT(*)`. The reason is that the coordinator internally uses paging to fetch more results from the replicas until the aggregated limit is satisfied. Since top-k index-based ordering doesn't support paging, these queries will fail. 
We should reject these queries until we have a way to support them.

CNDB-13353: Queries with index-based ordering should reject aggregation queries

---

src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Fixes https://github.com/riptano/cndb/issues/13446
This pr fixes an issue in the search-then-sort path where we never apply the query term filter. The change is quite simple because we were already scoring these terms, so we just need to filter out the ones that do not have frequency of at least 1 for each query term.

CNDB-13446: Make search-then-sort BM25 queries apply BM25 filter

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/index/sai/IndexContext.java
test/unit/org/apache/cassandra/index/sai/cql/GenericOrderByInvalidQueryTest.java

...
ORDER BY queries return wrong result if we have an analyzed index, as reported in CNDB-13464
...
ORDER BY should not work with an analyzed index at all. This PR fixes it and improves the error message.

CNDB-13464: Ordering on non-clustering column requires the column to be indexed with a non-analyzed index

---

src/java/org/apache/cassandra/index/sasi/plan/SASIIndexQueryPlan.java

SASI doesn't support disjunction queries, which means that there shouldn't be a SASI-based query plan for these queries. However, SASI produces a plan for these queries that it later fails to execute. This breaks `ComplexQueryTest` and `AllIndexImplementationsTest`.
This malfunction happens in `main-5.0` because in that branch there is a dedicated `SASIIndexQueryPlan` added to 5.0 by [CASSANDRA-16092](https://issues.apache.org/jira/browse/CASSANDRA-16092). That class wasn't updated by [CNDB-10718](https://github.com/datastax/cassandra/commit/3800dfe16c4d3c88d4c49f49a3d78a73778d39e6) because it doesn't exist on `main`, where SASI still uses the generic `SingletonIndexQueryPlan`.
This PR simply modifies `SASIIndexQueryPlan` to only consider first-level conjuncted indexes as candidates for …

CNDB-12220: Make SASI reject disjunctions

---

.github/workflows/pr_checklist.md

…
...
New files should contain the DataStax copyright header instead of Apache License.
Automatically, we do not do that, but we add the Apache License. Related discussion on the why in the GH issue - linked Slack discussion
...

CNDB-13505: Update PR checklist reminding people about the correct license header in new files

---

src/java/org/apache/cassandra/repair/messages/RepairMessage.java

CNDB-13389: use localOrPeerInfoOpt in RepairMessage remoteVersion check

---

src/java/org/apache/cassandra/db/partitions/TriePartitionUpdate.java

In https://github.com/riptano/cndb/issues/13336 several tests are failing in `PaxosStateTest` since `TrieMemtable` has been made the default in `MemtableParams`
This PR adds an `equals` method to `TriePartitionUpdate` because `Commit.equals` includes a check for partition update equality and the the partition update is `TriePartitionUpdate` not haveing `equals` means object equality is used.

CNDB-13336 Add equals to TriePartitionUpdate

---

src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/NodeQueueRowIdIterator.java
src/java/org/apache/cassandra/index/sai/utils/SegmentRowIdOrdinalPairs.java
test/unit/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIteratorTest.java
test/unit/org/apache/cassandra/index/sai/utils/SegmentRowIdOrdinalPairsTest.java

Relates to https://github.com/riptano/cndb/issues/13417 (the issue has multiple PRs)
In hybrid ANN search resulting in brute force row sorting, we see many object allocations per row materialized (so O(n) space complexity), and this creates memory pressure leading to reduced performance. This PR reduces object allocation by using jvector's `NodeQueue` data structure that encodes an int and a float into a long and then sorts based on the float. I also renamed the IntIntPairArray because I needed more specialized methods.
- **Rename IntIntPairArray to SegmentRowIdOrdinalPairs**
- **CNDB-13417: Reduce object alloc. on brute force hybrid ann path**

CNDB-13417: Reduce object alloc. on brute force hybrid ann path

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/service/StorageProxyMBean.java
src/java/org/apache/cassandra/service/paxos/PaxosUtils.java
src/java/org/apache/cassandra/service/paxos/PaxosUtilsMBean.java
test/unit/org/apache/cassandra/service/PaxosUtilsTest.java

Resolves: https://github.com/riptano/cndb/issues/13372
Currently min paxos backoff is to `0` which doesn't help there is already contention. 
Introduced a new property `cassandra.lwt_min_backoff_ms` which defautls to 5ms (10x smaller that the default 50ms to give enough range and be conservative relative to the previous 0 value, but still a magic number) and fix the `contentionBackoffLatency` that accepts nanos

CNDB-13372 Introduce min Paxos backoff time

---

test/unit/org/apache/cassandra/repair/messages/RepairMessageTest.java

Fixes #13584
Instead of populating peers directly, initialize in the gossiper and let it populate local correctly.

CNDB-13584 initialize self in Gossiper to fix RepairMessageTest

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2OnDiskOrdinalsMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v5/V5OnDiskOrdinalsMap.java
src/java/org/apache/cassandra/index/sai/disk/vector/AutoResumingNodeScoreIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIterator.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/OnDiskOrdinalsMap.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/metrics/ColumnQueryMetrics.java
src/java/org/apache/cassandra/index/sai/metrics/QueryEventListener.java
src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java
test/unit/org/apache/cassandra/index/sai/cql/VectorMetricsTest.java
test/unit/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIteratorTest.java

https://github.com/riptano/cndb/issues/13583
This PR adds comprehensive metrics for Storage Attached Indexes (SAI) vector search operations, providing crucial insights into both ANN (Approximate Nearest Neighbor) graph searches and brute force operations.
New Vector Search Metrics:
Search Operation Counters:
- `ANNNodesVisited`: Total number of nodes visited during ANN searches (this is equivalent to approximate similarity score computations)
- `ANNNodesReranked`: Number of nodes that underwent exact distance computation for reranking (this is equivalent to exact similarity score computations)
- `ANNNodesExpanded`: Total number of nodes whose edges were explored
- `ANNNodesExpandedBaseLayer`: Number of nodes expanded in the base layer of the graph
- `ANNGraphSearches`: Count of new graph …

CNDB-13583: Add vector ann and brute force metrics

---

build.xml
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java
test/unit/org/apache/cassandra/index/sai/cql/VectorDotProductWithLengthTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java

https://github.com/riptano/cndb/issues/12937. This is a follow up on https://github.com/datastax/cassandra/pull/1676, which updated the jvector dependency but didn't update the jvector version in the actual graph builder.
* Adds jvector version configuration, defaulted to 4
* Tests jvector versions 2 and 4 to ensure we can query sstables with both kinds of graphs
* Makes the `enable_hierarchy` config backwards compatible by ignoring it if the jvector version is too low
* Removes the ability to write FusedADC since it does not work with the latest jvector version (discovered when writing compatibility tests)
* Does not remove FusedADC read path since there could be indexes based on it in production
* Replaces call to deprecated `graph.size()` method with `graph.size(0)`

CNDB-12937: enable jvector 4; remove jvector 3 write support

---

src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Executing a query with BM25 search and a condition on partial SSTable results in empty iterator access error. And there was no test with storing data in segments.
The PR implements BM25 search tests with splitting data into two tables. This reproduced this bug, CNDB-13696, and demonstrates current confusion on the BM25 ordering result to be fixed by CNDB-13553.
This PR adds a check for empty iterator created for a PK belonging to another segment. This fixes the bug of trying to get the first element of an empty iterator.
Fixes https://github.com/riptano/cndb/issues/13696, fixes https://github.com/riptano/cndb/issues/13553
It's based on #1688, which fixes https://github.com/riptano/cndb/issues/13671
~~It's planned to be two commits on top of the commit in #1688.~~ (it's okay to squash as …

CNDB-13696 fix empty iterator access in BM25 search on partial SSTable

---

test/unit/org/apache/cassandra/io/sstable/SSTableCorruptionDetectionTest.java

ChunkCache needs to invalidate the test file with invalidateFileNow

CNDB 13650: fix SSTableCorruptionDetectionTest.testSSTableScanner

---

test/unit/org/apache/cassandra/io/sstable/CQLSSTableWriterSAIClientTest.java
test/unit/org/apache/cassandra/io/sstable/CQLSSTableWriterSAIDaemonTest.java
test/unit/org/apache/cassandra/io/sstable/CQLSSTableWriterSAITest.java
test/unit/org/apache/cassandra/io/sstable/CQLSSTableWriterTest.java

The `main-5.0` branch uses `TrieMemtable` by default and the `test/conf/cassandra.yaml` configures `ByteOrderedPartitioner`.
In this environment, `CQLSSTableWriterDaemonTest` tests `testSkipBuildingIndexesWithSAI` and `testWriteWithSAI` are failing.
This fix moves the SAI specific tests from `CQLSSTableWriterTest` to a new `CQLSSTableWriterSAITest` so that `Murmur3Partitioner` can be explicitly set for the SAI specific tests.

CNDB-13401 Fix CQLSSTableWriterDaemon tests

---

test/unit/org/apache/cassandra/db/repair/PendingAntiCompactionTest.java

`PendingAntiCompactionTest.testRetriesTimeout` is flaky on `main` failing with a timeout reported in the junit test task. https://github.com/riptano/cndb/issues/13524 
`PendingAntiCompactionTest.testRetriesTimeout`, and a couple other tests, are calling `Future.get` without any timeout. This change adds a 30 seconds timeout to prevent an indefinite wait for the future and a log in the failing test rather than in the junit test task.

CNDB-13524 Adds a timeout to Future.get calls in PendingAntiCompactionTest

---

build.xml

Fixes: https://github.com/riptano/cndb/issues/13718
We had adopted this version of lucene https://github.com/datastax/lucene/commit/5ea8bb4f21cb8ad14cb2a861248e24a0aaf1af09 in order to support our custom modifications of HNSW on top of lucene. We now use https://github.com/datastax/jvector for vector search and no longer need a custom build.
I propose we use 9.8.0 since that is the closest release to the one we have been using.
CNDB test pr: https://github.com/riptano/cndb/pull/13757

CNDB-13718: Switch to official Apache Lucene 9.8.0 dep

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/compaction/CompactionController.java
src/java/org/apache/cassandra/db/compaction/Scrubber.java
src/java/org/apache/cassandra/db/compaction/Verifier.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexBuilder.java
src/java/org/apache/cassandra/index/sasi/SASIIndexBuilder.java
src/java/org/apache/cassandra/io/sstable/compaction/SortedStringTableCursor.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/SSTableSimpleScanner.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableReader.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableScanner.java
src/java/org/apache/cassandra/io/sstable/format/big/ScrubIterator.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/PartitionIndex.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexScanner.java
src/java/org/apache/cassandra/io/util/EmptyRebufferer.java
src/java/org/apache/cassandra/io/util/FileHandle.java
src/java/org/apache/cassandra/io/util/MmapRebufferer.java
src/java/org/apache/cassandra/io/util/PrefetchingRebufferer.java
src/java/org/apache/cassandra/io/util/ReadPattern.java
src/java/org/apache/cassandra/io/util/Rebufferer.java
test/distributed/org/apache/cassandra/io/sstable/format/ForwardingSSTableReader.java
test/unit/org/apache/cassandra/cache/ChunkCacheInterceptingTest.java
test/unit/org/apache/cassandra/cache/ChunkCacheLoadingTest.java
test/unit/org/apache/cassandra/cql3/validation/miscellaneous/CrcCheckChanceTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableWithZeroCopyMetadataTest.java
test/unit/org/apache/cassandra/io/util/PrefetchingRebuffererTest.java

This introduces a `PrefetchingRebufferer` that, when enabled, prefetches (read from the underlying reader) a configurable number of chunks in advance (so only work on top of rebufferer factories that work with chunks, i.e. not uncompressed mmap).
Prefetching must first be enabled globally by setting `-Dcassandra.read_prefetching_size_kb` to the desired value. With that, and assuming the disk access mode allows it (meaning, it's not uncompressed mmap), then prefetching will be applied to reads that are "clearly" sequential. Mostly, as of this patch, this means the sstable "scanners" and `SortedStringTableCursor`, so compaction, SAI index building and tools that read sstable fully (scrub, verifier) will benefit from it.
Since rebufferers are synchronous, prefetching is done through a fixed …

CNDB-13639: Adds optional prefetching for known sequential reads

---

build.xml
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/BruteForceRowIdIterator.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
src/java/org/apache/cassandra/index/sai/utils/SegmentRowIdOrdinalPairs.java
test/unit/org/apache/cassandra/index/sai/utils/SegmentRowIdOrdinalPairsTest.java

Fixes: https://github.com/riptano/cndb/issues/13689
This PR utilizes the NodeQueue::pushMany method to decrease the time complexity required to build the NodeQueue from `O(n log(n))` to `O(n)`. This is likely only significant for sufficiently large hybrid queries. For example, we have seen cases of the search producing 400k rows, which means that we do 400k insertions into these NodeQueue objects.

CNDB-13689: use NodeQueue::pushMany to decrease time complexity to build heap

---

src/java/org/apache/cassandra/db/filter/ANNOptions.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Orderer.java
test/distributed/org/apache/cassandra/distributed/test/sai/ANNOptionsDistributedTest.java
test/unit/org/apache/cassandra/db/filter/ANNOptionsTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java
test/unit/org/apache/cassandra/index/sai/memory/VectorMemtableIndexTest.java

Fixes https://github.com/riptano/cndb/issues/13822
CNDB test pr https://github.com/riptano/cndb/pull/13826
SAI’s DiskANN/JVector engine currently **always searches with pruning enabled**, trading recall for latency.  That is fine for most workloads, but:
* **Threshold / bounded ANN queries** can lose matches when pruning exits early.
* Performance‑testing users need an easy way to turn pruning off to measure the recall/latency curve.
This patch introduces a per‑query **`use_pruning`** option so users and operators can choose the trade‑off that suits them.
---
```cql
WITH ann_options = {'use_pruning': true|false}
```
*When omitted we fall back to the node level default (see below).*  
* Cluster‑wide default is controlled by the JVM system property:
``` …
```

CNDB-13822: Add ANN_OPTION use_pruning

---

test/unit/org/apache/cassandra/inject/Injections.java

...
QueryTimeoutTest on JDK22 fails on JDK22
...
We need to be explicit about the usage of long in `thread.sleep`

CNDB-13833: Fix QueryTimeoutTest on JDK22

---

src/java/org/apache/cassandra/db/filter/ANNOptions.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2VectorIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
test/unit/org/apache/cassandra/db/filter/ANNOptionsTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorHybridSearchTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorSiftSmallTest.java

Fixes: https://github.com/riptano/cndb/issues/13625
When `rerank_k` is non-positive, we will skip reranking where possible.
A minor note: this change is not strictly backwards compatible because of the original implementation. However, it will fail quickly if the coordinator accepts the value but the writer does not, and since this is only a query-time parameter, I propose that we move forward and accept the net-new value that was previously disallowed.
This PR will have conflicts with https://github.com/riptano/cndb/pull/13826. I plan on merging that PR and then resolving conflicts here.

CNDB-13625: Implement rerankless vector search through ANN_OPTIONS

---

src/java/org/apache/cassandra/dht/Murmur3Partitioner.java
src/java/org/apache/cassandra/dht/Token.java
src/java/org/apache/cassandra/index/sai/disk/v1/PartitionAwarePrimaryKeyMap.java
src/java/org/apache/cassandra/index/sai/disk/v2/RowAwarePrimaryKeyMap.java
test/unit/org/apache/cassandra/dht/LengthPartitioner.java
test/unit/org/apache/cassandra/dht/Murmur3PartitionerTest.java

Fixes: https://github.com/riptano/cndb/issues/13847
We already make use of the `Token#getLongValue` method in SAI, which only works for the Murmur partitioner, so I propose that we add a symmetric method that allows us to create tokens without converting a long to a byte buffer back to a long.

CNDB-13847: Add Token::fromLongValue method to simplify SAI token creation

---

src/java/org/apache/cassandra/index/sai/disk/v1/MemtableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentMetadataBuilder.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
test/unit/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcherTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/KDTreeIndexBuilder.java

Fixes https://github.com/riptano/cndb/issues/13739
The number of rows stored in SSTable's SAI index was incorrect for analyzed indexes and for indexes on collections as it was counting posting lists for each term. In non-analyzed or non-collection indexes there is a term per row, while in analyzed index there can be many terms in a row. This led to incorrect count of rows.
Fixes counting number of rows stored in SSTable SAI index.
Minor fixes of code warnings in the affected files.

CNDB-13739 count numRows correctly in SSTable SAI

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/conditions/ColumnCondition.java
src/java/org/apache/cassandra/cql3/conditions/ColumnConditions.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/db/filter/RowFilter.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/IndexRegistry.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/plan/Operation.java
test/unit/org/apache/cassandra/cql3/OperatorTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneAnalyzerTest.java

[CNDB-10731](https://github.com/riptano/cndb/issues/10731) added support for index analyzers to `RowFilter`. Currently, both the left and right operands of an expression are analyzed on every evaluation. However, the right operand has the same fixed value over the life of the expression, so we are doing the same analysis once and again. 
This PR memoizes the analyzed tokens of the right operand. It also adds some refactoring and simplifications around how analysis is dealt with in `RowFilter` and `Operator`.

CNDB-13075: Reuse the analyzed tokens of the right operand of an analyzed expression

---

src/java/org/apache/cassandra/cql3/functions/AbstractFunction.java
test/unit/org/apache/cassandra/cql3/validation/operations/AggregationTest.java

...
Incorrect results of min / max in-built functions on clustering columns in descending order
...
Port CASSANDRA-20295

CNDB-13902: Fix incorrect results of min / max in-built functions on clustering columns in descending order - port CASSANDRA-20295

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/io/util/ChannelProxy.java
src/java/org/apache/cassandra/io/util/SimpleChunkReader.java
test/unit/org/apache/cassandra/cache/ChunkCacheTest.java

The fix for CNDB-13591 was not ported to the May release branch.
commit 63ab9c44d63223a5a78dd07230cb5e1e9e57ed8b (HEAD -> cndb-13591-may25, origin/cndb-13591-may25)
Author: Jacek Lewandowski <lewandowski.jacek@gmail.com>
Date:   Fri Apr 4 16:14:24 2025 +0200
CNDB-13591: Fix unit tests (missed commit in previous hotfix)
(cherry picked from commit 7c5130359c398e63db1111c32dc602e7fa3acac7)
commit 1692a93cc5fbae0a3db025ce7496d04cc4fcac2f
Author: Enrico Olivelli <enrico.olivelli@datastax.com>
Date:   Fri Apr 4 14:18:30 2025 +0200
CNDB-13591: Error while loading chunkcache: java.lang.IllegalArgumentException: Negative position (#1677)
Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
(cherry picked from commit 09748bdc9122747912fcd8fcc8bd64af3d7f14ce)
commit …

CNDB-13591 ported to May 25 release

---

src/java/org/apache/cassandra/cache/ChunkCache.java
src/java/org/apache/cassandra/io/util/ChannelProxy.java
src/java/org/apache/cassandra/io/util/SimpleChunkReader.java
test/unit/org/apache/cassandra/cache/ChunkCacheTest.java

The fix for CNDB-13591 was developed and only committed to the March 25 release branch
commit e3dfead0d0cb616bf8cdd55827933be3850c954e (HEAD -> cndb-13591-main, origin/cndb-13591-main)
Author: Jacek Lewandowski <lewandowski.jacek@gmail.com>
Date:   Fri Apr 4 16:14:24 2025 +0200
CNDB-13591: Fix unit tests (missed commit in previous hotfix)
(cherry picked from commit 7c5130359c398e63db1111c32dc602e7fa3acac7)
commit b1f732efd01f32bcd010293e34650dac280709ca
Author: Enrico Olivelli <enrico.olivelli@datastax.com>
Date:   Fri Apr 4 14:18:30 2025 +0200
CNDB-13591: Error while loading chunkcache: java.lang.IllegalArgumentException: Negative position (#1677)
Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
(cherry picked from commit 09748bdc9122747912fcd8fcc8bd64af3d7f14ce)
commit …

Cherry-pick all the fixed about CNDB-13591 into main branch

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/view/IndexViewManager.java
src/java/org/apache/cassandra/index/sai/view/View.java
test/unit/org/apache/cassandra/index/SecondaryIndexManagerTest.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/view/IndexViewManagerTest.java

Fixes: https://github.com/riptano/cndb/issues/13693
The new design is to:
1. Make sai `View` reference-able so that it holds references to the underlying `SSTableIndex`s. When the `view` is released the final time, it releases the indexes. This moves all of the complexity of grabbing references to sstable update time and out of the query path, which seems like a generally good improvement.
2. Observe that `SSTableIndex` holds a reference to its associated sstable reader.
Note also that we need to create the memtable index on deletions in order to make the index-first solution work.
Also note that sstables indexes are added before they are removed on flush, so this change in design is safe for flush.

CNDB-13693: Make SAI's view referenceable to simplify locking query view

---

src/java/org/apache/cassandra/index/sai/disk/v1/MemtableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDTreeRamBuffer.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/kdtree/NumericIndexWriter.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/BKDReaderTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/kdtree/NumericIndexWriterTest.java

#1695 fixed the calculation of row count to be actually the row count and not number of postings/points. However, BKDWriter was expecting number of points behind the row count.
Fixes https://github.com/riptano/cndb/issues/13905
Renames confusing numRows arguments to totalPointCount in methods
propagating the value to BKDWriter, which expects the total point
count. Fixes to provide total point counts instead of row counts.
In the most of tests the point count and the row count are equivalent.
One unused test is removed.
This PR also brings #1715, which corrects the assert condition on expected number of points and improve the error message. This also makes down the code coverage below accepted minimum.
Also fixes few IntelliJ warnings in affected files.

CNDB-13905 provide total point count to BKDWriter

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/memtable/AbstractAllocatorMemtable.java
src/java/org/apache/cassandra/db/memtable/Memtable.java
src/java/org/apache/cassandra/db/memtable/PersistentMemoryMemtable.java
src/java/org/apache/cassandra/db/memtable/SkipListMemtable.java
src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/db/memtable/TrieMemtableStage1.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/v1/IndexWriterConfig.java
src/java/org/apache/cassandra/index/sai/disk/vector/AbstractMemtableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/MemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/service/StorageProxy.java
src/java/org/apache/cassandra/service/StorageProxyMBean.java
test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
test/unit/org/apache/cassandra/db/memtable/FlushConfigTest.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorLocalTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

- allow triggering memtable flush when SAI memtable indexed rows reaches threshold, default -1 as disabled. Can be enable via -Dcassandra.sai.vector_flush_threshold_max_rows and -Dcassandra.sai.non_vector_flush_threshold_max_rows
- allow triggering memtable flush after expiration period based on index type. Default negative value as disabled. Can be enabled via -Dcassandra.flush_period_in_millis, -Dcassandra.sai.non_vector_flush_period_in_millis and -Dcassandra.sai.vector_flush_period_in_millis
- added JMX mbean to update configs at runtime

CNDB-13994: trigger memtable flush when index memtable reaches size threshold or expiration period. Default disabled.

---

src/java/org/apache/cassandra/db/filter/DataLimits.java
src/java/org/apache/cassandra/db/rows/BTreeRow.java
src/java/org/apache/cassandra/db/rows/Row.java
src/java/org/apache/cassandra/index/sai/utils/RowWithSourceTable.java
test/unit/org/apache/cassandra/cql3/PagingQueryTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailPagingTest.java

Modify CQL counters calculation of bytes counted to exclude cell tombstones. That way, the counters will count the same size in bytes for filtered and unfiltered base partition/row iterators.
This solves a bug where byte-based paging is wrongly considering replicas as exhausted if their responses contain tombstones. This leads to queries using byte-based paging returning fewer rows than expected. It includes all aggregation queries, where byte-based paging is always used internally. The problem is that replicas apply counters to unfiltered iterators, whereas the coordinator controls paging by applying counters to reconciled and filtered iterators.

CNDB-13978: Don't count tombstones in DataLimits.Counter.CQLCounter#bytesCounted

---

src/java/org/apache/cassandra/db/filter/DataLimits.java
src/java/org/apache/cassandra/db/rows/BTreeRow.java
src/java/org/apache/cassandra/db/rows/Row.java
src/java/org/apache/cassandra/index/sai/utils/RowWithSourceTable.java
test/unit/org/apache/cassandra/cql3/PagingQueryTest.java
test/unit/org/apache/cassandra/guardrails/GuardrailPagingTest.java

Port of DSP-22813. 
Modify CQL counters calculation of rows data size to include cell deletions even after the row has been purged. That way, the counters will count the same size in bytes for filtered and unfiltered base partition/row iterators.
This solves a bug where byte-based paging is wrongly considering replicas as exhausted if their responses contain tombstones. This leads to queries using byte-based paging returning fewer rows than expected. It includes all aggregation queries, where byte-based paging is always used internally. The problem is that replicas apply counters to unfiltered iterators, whereas the coordinator controls paging by applying counters to reconciled and filtered iterators.

CNDB-13978: Count tombstones in DataLimits.CQLCounter.Counter#bytesCounted even if the row has been purged

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneUpdateDeleteTest.java

Fixes https://github.com/riptano/cndb/issues/14171
https://github.com/datastax/cassandra/pull/1200 introduced a bug for SAI indexes version AA that have clustering columns. As the tests show, updates incorrectly removed rows from the index.
We need the update logic for later versions of SAI, so it is key to keep the update feature, but AA does not support those features precisely because it only indexes the partition key, so this is a safe update.

CNDB-14171: handle update as insert for SAI version AA

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTestBase.java

- **Add failing test**
- **CNDB-14153: Fix SAI updates (non-null solution)**
Fixes https://github.com/riptano/cndb/issues/14153
This is meant as an alternative to https://github.com/datastax/cassandra/pull/1749. It fixes https://github.com/riptano/cndb/issues/14153 by never returning `null` from the `UpsertTransformer`.
#1749 is a more memory efficient solution, but has additional complexity, which is why I am proposing this as an alternative.

CNDB-14153: Fix SAI updates (non-null solution)

---

src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
test/unit/org/apache/cassandra/index/sai/cql/VectorDotProductWithLengthTest.java

Fixes: https://github.com/riptano/cndb/issues/14167
We upgraded to jvector 4 too soon. We need to use jvector 2 for a release cycle and then when we upgrade next, we can go to jvector 4. We needed a two phase release.
CNDB test PR: https://github.com/riptano/cndb/pull/14196

CNDB-14167: Set jvector_version on disk file format to 2

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java

When schema is unloaded after tenant unassignment, compaction task might finishes without corresponding index files, making index non-queryable.
Replace `isValid` with `isDropped` and `isUnloaded`. If index is dropped, compaction task or index build can proceed without the index, same behavior as before. If index is unloaded, compaction task or index build will be aborted to avoid completing without index files.

CNDB-14614: abort compaction task or index build if index is unloaded after tenant unassignment

---

test/unit/org/apache/cassandra/index/sai/utils/SaiRandomizedTest.java

The patch can be tested locally on `InvertedIndexSearcherTest`, for example.
...
`InvertedSearcherTest` fails locally with:
```
java.io.IOException: No such file or directory
at __randomizedtesting.SeedInfo.seed([515D37866AFB6CE1]:0)
at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.base/java.io.File.createTempFile(File.java:2129)
at org.junit.rules.TemporaryFolder.createTemporaryFolderIn(TemporaryFolder.java:237)
at org.junit.rules.TemporaryFolder.create(TemporaryFolder.java:147)
at org.junit.rules.TemporaryFolder.before(TemporaryFolder.java:133)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```
The test config points to …

CNDB-14175: Create necessary tmp directories in SaiRandomizedTest before we run tests.

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java

The data inserted into the trie in `TrieMemoryIndex` is `encodedTerm`, which is built from `term` and only on the "available" bytes (between `term.position()` and `term.limit()`). But the check that decides to use the (more efficient) recursive path or not uses `term.limit()` to assess the size of `encodedTerm`. If `term.position()` is not 0, this is incorrect, and can lead to using the less optimal pass completely unecessarily. This has been shown to happen when investigating https://github.com/riptano/cndb/issues/14153: the non-recursive path was taken even for boolean values (because the nodes were using `offheap_buffers`; with `offheap_objects`, the buffers getting to `TriMemoryIndex` are 0-positioned).
See https://github.com/riptano/cndb/issues/14184.

CNDB-141284: use `ByteBuffer.remaining` instead of `limit` to asset size

---

src/java/org/apache/cassandra/cql3/SingleColumnRelation.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
test/unit/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/AllowFilteringTest.java

- **CNDB-14210: Fix analyzed sai index on compound partition key column**
- **Cleanup clustering column : error message**
Fixes: https://github.com/riptano/cndb/issues/14210
Fixes some queries that were broken by the march and may release. In #1434, we introduced some logic to help make the eq behavior better, and it incorrectly handled compound partition keys. This fixes that.
The central fix is to use the `EQRestriction` any time we have a primary key column. This is necessary to ensure we can write and read data. The tests cover the relevant cases. I also fixed the error message returned when attempting to use `:` on a clustering column index. Please review the text of the error message.

CNDB-14210: Fix analyzed sai index on compound partition key column

---

test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Few indexes were created with `execute` method, which doesn't check if an index is ready.
Fixes https://github.com/riptano/cndb/issues/14232
Changing `execute` to `createIndex` fixes the observed flakiness.

CNDB-14232 fix flakiness in BM25 by createIndex

---

conf/cassandra.yaml
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/exceptions/ReadTimeoutException.java
src/java/org/apache/cassandra/exceptions/RequestTimeoutException.java
src/java/org/apache/cassandra/service/pager/AggregationQueryPager.java
test/conf/cassandra.yaml
test/unit/org/apache/cassandra/cql3/validation/operations/AggregationQueriesTest.java

CNDB-13770 Separate timeout for aggregation queries
In CC, aggregate user queries use the same range read timeout. In DSE, we had a separate timeout that defaulted to 120s. We would like to retain that functionality.
This PR adds a separate 120s timeout for aggregate queries. The timeout is configurable with aggregation_request_timeout_in_ms Config parameter

CNDB-13770: Separate timeout for aggregation queries

---

src/java/org/apache/cassandra/db/lifecycle/WrappedLifecycleTransaction.java
src/java/org/apache/cassandra/io/sstable/format/bti/BtiTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/bti/PartitionIndexBuilder.java
src/java/org/apache/cassandra/io/util/FileHandle.java
test/unit/org/apache/cassandra/db/compaction/CancelCompactionsTest.java
test/unit/org/apache/cassandra/io/sstable/EarlyOpenCachingTest.java
test/unit/org/apache/cassandra/io/sstable/EarlyOpenIterationTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableWriterTestBase.java

Failing `EarlyOpenCachingTest` due to incorrect assignment of data file length.
Passes the correct lengths to the early open sstable construction. This lets `SimpleSSTableScanner` correctly finish iteration.
This was already fixed in CC (as part of CNDB-9104).

CNDB-13163: Fix incorrect data file length for early open sstables

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/IndexRegistry.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/MultipleColumnIndexTest.java

Prefer not-analyzed indexes over analyzed indexes for contains queries, so they have a deterministic behaviour.
Also, emit a client warning when a not-analyzed index is selected over an analyzed index.
Otherwise, different points in the codebase will make different, pseudo-random decisions about what index should be used for a certain contains expression, leading to erratic behaviour.
Relevant Slack thread: https://datastax.slack.com/archives/C05LHP4HX5J/p1746005148167389

CNDB-13925: Prefer not analyzed indexes for contains queries

---

src/java/org/apache/cassandra/db/compaction/SharedCompactionObserver.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/SharedCompactionObserverTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

UCS didn't clear pending compaction tasks in `BackgroundCompactions#compactions`
Register both UCS and composite compaction observer for parallel compaction task: both UCS and CNDB are notified

CNDB-14237-202505-fix: register composite compaction observer as additional obverser on top of UCS

---

src/java/org/apache/cassandra/db/compaction/SharedCompactionObserver.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/compaction/SharedCompactionObserverTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

UCS didn't clear pending compaction tasks in `BackgroundCompactions#compactions` for parallel background compaction
Register both UCS and composite compaction observer for parallel compaction task: both UCS and CNDB are notified

CNDB-14237-main-cherry-pick: register composite compaction observer as additional obverser on top of UCS

---

src/java/org/apache/cassandra/db/memtable/TrieMemtable.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

This is needed for next step to calculate average document length on all documents of a table partition.
Closes https://github.com/riptano/cndb/issues/13997
Track the terms count when updating memtabel index and utilize it together with indexed rows in BM25 queries. The terms count is approximate, since memtable index doesn't account for deletes.

CNDB-13997 maintain total terms count in memindex

---

test/unit/org/apache/cassandra/index/sai/disk/SingleNodeQueryFailureTest.java

The tests in SingleNodeQueryFailureTest suite inject failures
into the code paths executed by a test query that uses two indexes.
This commit disables the query optimizer because it was interfering
by removing an index from the plan so sometimes
the path with the injected failure was not taken.
Fixes https://github.com/riptano/cndb/issues/14291

CNDB-14291: Fix flaky SingleNodeQueryFailureTest

---

src/java/org/apache/cassandra/gms/EndpointState.java
test/unit/org/apache/cassandra/gms/EndpointStateTest.java

…
VersionValue contains the CC version, which has a `-<sha>` suffix.
This isn't parsing in C* 3.x when it receives it in gossip.
```
ERROR [GossipStage:1] 2025-05-26 09:56:15,427 " CassandraDaemon.java:244 - Exception in thread ' Thread[GossipStage:1,5,main]
java.lang.IllegalArgumentException: Invalid version value: 4.0.11.0-90080e7b696d
at org.apache.cassandra.utils.CassandraVersion.<init>(CassandraVersion.java:64)
at org.apache.cassandra.gms.EndpointState.getReleaseVersion(EndpointState.java:180)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.tryAdvance(ConcurrentHashMap.java:3572)
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
at …
```

HCD-153 C* 3.x nodes don't like the trailing sha in the version sent over gossip (VersionedValue)

---

test/distributed/org/apache/cassandra/distributed/test/sai/IndexAvailabilityTest.java

...
The test was flaky because we were not waiting for some indexing status to get propagated before running queries
...
Wait for all statuses before running test queries to get deterministic results

CNDB-14374: Fix flaky test testIndexExceptionsTwoIndexesOn3NodeCluster

---

src/java/org/apache/cassandra/cql3/statements/SelectStatement.java
src/java/org/apache/cassandra/index/sai/disk/format/Version.java
test/unit/org/apache/cassandra/index/sai/disk/format/VersionTest.java

Fixes: https://github.com/riptano/cndb/issues/14306
When we upgrade past `EC`, we'll be able to send the scores instead of the vectors. The backwards compatibility for this will be covered in CNDB.

CNDB-14306: Update ANN_USE_SYNTHETIC_SCORE to default to true for SAI version >EC

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

- **CNDB-14317: Optimize doc freq computation for memtable BM25 queries**
- **Update approximateTotalTermCount() javadoc**
Fixes https://github.com/riptano/cndb/issues/14317
We optimize the in memory BM25 computation by using the trie to get the number of rows matching a query term. This change removes a memtable scan and analyze by replacing it with calls to the index to get the number of docs. There are no new tests because it is expected to maintain the same semantics. I will review the test coverage to verify that assertion.

CNDB-14317: Optimize doc freq computation for memtable BM25 queries

---

src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/disk/EmptyIndex.java
src/java/org/apache/cassandra/index/sai/disk/SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/AbstractMemtableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/MemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Orderer.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
test/unit/org/apache/cassandra/index/sai/cql/FeaturesVersionSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

BM25 score needs to use document average length aggregated on entire node.
Also a bug was discovered, which was introduced by #1789: term frequencies don't
include documents filtered by other predicates, which makes inconsistent result
between query plans.
Fixes https://github.com/riptano/cndb/issues/14361
Changes that BM25 score uses document count and term count aggregated
on entire node instead of per segment. Fixes a bug in calculating term frequencies, so
they count all documents.
As the work added more code duplication all duplicated code is
refactored in getTopKRows methods.
In addition removes unnecessary public modifier in afffected interface.

CNDB-14361 use node's total document and term counts

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

BM25 queries don't work on indexes on non-regular columns. 
Until we have a way to support them, this PR simply forbids BM25 queries on non-regular columns. 
The creation of analyzed indexes in those columns is still allowed because they can be successfully queried with regular expression filters using equality and match operators.

CNDB-14348: Forbid BM25 queries on non-regular columns

---

src/java/org/apache/cassandra/index/sai/disk/PostingListKeyRangeIterator.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyWithSource.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentMetadata.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/iterators/KeyRangeUnionIterator.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/PrimaryKeyListUtil.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/GenericOrderByUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorHybridSearchTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorTypeTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/LegacyOnDiskFormatTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java
test/unit/org/apache/cassandra/index/sai/iterators/KeyRangeUnionIteratorTest.java

This implements one of the possible fixes for
https://github.com/riptano/cndb/issues/12407.
This PR skips loading the PrimaryKey's token in the case where the sstables/memtables do not overlap, which is particularly helpful as datasets become more compacted (especially after major compaction).
It is implemented via a subtle change to the `PrimaryKeyWithSource` class that only loads the token info when the token is needed. We avoid this check by first checking to see if the sstable ranges overlap or if the key is contained in the sstable range. If it is not contained, we can short circuit the logic and avoid loading the primary key from disk. This results in a significant optimization for SAI hybrid queries that search-then-sort.
CNDB PR with passing tests: …

CNDB-12407: lazily load token in PrimaryKeyWithSource (#1500)

---

src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentMetadataBuilder.java
test/unit/org/apache/cassandra/index/sai/cql/AnalyzerTest.java

If an index analyzer produced no terms for a row, the index
build could not complete and broke sstable flushing.
This commit makes the SegmentBuilder ignore the whole row
if there are no terms. Additionally more assertions / preconditions
have been added to improve diagnostics.
Fixes:
Failed to complete an index build
java.lang.IllegalStateException: Term range not set
at org.apache.cassandra.index.sai.disk.v1.SegmentMetadataBuilder.build(SegmentMetadataBuilder.java:145)
at org.apache.cassandra.index.sai.disk.v1.SegmentBuilder.flush(SegmentBuilder.java:470)
at org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.flushSegment(SSTableIndexWriter.java:286)
at org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.complete(SSTableIndexWriter.java:151)

CNDB-14481: Fix IllegalStateException in SegmentMetadataBuilder

---

src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentMetadataBuilder.java

To avoid the risk that stricter checking would break something,
this commit reverts changes to asserts / preconditions made
by CNDB-14481. The fix for the bug and the new tests added
by CNDB-14481 are left intact.

Revert preconditions added by CNDB-14481

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemoryIndex.java
test/unit/org/apache/cassandra/index/sai/cql/ComplexQueryTest.java
test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTestBase.java

- **Add failing test**
- **CNDB-14153: Fix SAI updates (non-null solution)**
Fixes https://github.com/riptano/cndb/issues/14153
This is meant as an alternative to
https://github.com/datastax/cassandra/pull/1749. It fixes https://github.com/riptano/cndb/issues/14153 by never returning `null` from the `UpsertTransformer`.
#1749 is a more memory efficient solution, but has additional complexity, which is why I am proposing this as an alternative.

CNDB-14153: Fix SAI updates (non-null solution) (#1751)

---

src/java/org/apache/cassandra/db/compaction/Verifier.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/IndexRegistry.java
src/java/org/apache/cassandra/index/SingletonIndexGroup.java
src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
test/unit/org/apache/cassandra/index/CustomIndexTest.java
test/unit/org/apache/cassandra/index/sai/functional/VerifyTest.java

- **CNDB-14477: Validate SAI Components in Verifier**
- **Add follow up comment to vector corruption check**
Fixes: https://github.com/riptano/cndb/issues/14477
This PR leverages the existing SAI verification framework and wires it up to the `Verifier` logic in the code compaction code.

CNDB-14477: Validate SAI Components in Verifier

---

test/burn/org/apache/cassandra/index/sai/LongVectorTest.java

#13724 
reduce num of test keys and less flushes. Reduce the chances of hitting "too many open files"

CNDB-13724: reduce num of test keys in LongVectorTest to avoid jenkins timeout

---

src/java/org/apache/cassandra/db/filter/DataLimits.java
src/java/org/apache/cassandra/db/rows/BTreeRow.java
src/java/org/apache/cassandra/db/rows/Row.java
src/java/org/apache/cassandra/index/sai/utils/RowWithSourceTable.java
test/unit/org/apache/cassandra/cql3/PagingAggregationQueryTest.java
test/unit/org/apache/cassandra/cql3/PagingQueryTest.java

Only preserve the original data size or rows in case of purging.

CNDB-14602: Fix bytes-based paging for partition deletions

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/SSTableIndexWriter.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
test/unit/org/apache/cassandra/index/sai/cql/NativeIndexDDLTest.java
test/unit/org/apache/cassandra/index/sai/disk/v1/SegmentFlushTest.java

When schema is unloaded after tenant unassignment, compaction task might finishes without corresponding index files, making index non-queryable.
Replace `isValid` with `isDropped` and `isUnloaded`. If index is dropped, compaction task or index build can proceed without the index, same behavior as before. If index is unloaded, compaction task or index build will be aborted to avoid completing without index files.
---
https://github.com/datastax/cassandra/pull/1754 was reverted because[ CNDB PR](https://github.com/riptano/cndb/pull/14179) compiled failed with wrong hash. Re-merge it again.

CNDB-14614-re-merge: abort compaction task or index build if index is unloaded after tenant unassignment (#1766)

---

src/java/org/apache/cassandra/cql3/SingleColumnRelation.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
test/unit/org/apache/cassandra/index/sai/analyzer/AnalyzerEqOperatorSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/AllowFilteringTest.java

- **CNDB-14210: Fix analyzed sai index on compound partition key column**
Fixes: https://github.com/riptano/cndb/issues/14210
Fixes some queries that were broken by the march and may release. In #1434, we introduced some logic to help make the eq behavior better, and it incorrectly handled compound partition keys. This fixes that.
The central fix is to use the `EQRestriction` any time we have a primary key column. This is necessary to ensure we can write and read data. The tests cover the relevant cases. I also fixed the error message returned when attempting to use `:` on a clustering column index. Please review the text of the error message.
...
...

CNDB-14210: Fix analyzed sai index on compound partition key column (#1763)

---

test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Few indexes were created with execute method, which doesn't check if an index is ready. Changing it to createIndex fixes the observed flakiness.
...
...

CNDB-14232 fix flakiness in BM25 by createIndex (#1769)

---

src/java/org/apache/cassandra/db/tries/InMemoryTrie.java
test/unit/org/apache/cassandra/db/tries/CellReuseTest.java

Currently returning a null from an Upserter may corrupt the trie state which may end up in a serious problem. It is better to crash instead.

CNDB-14182: Add some null checks in InMemoryTrie

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
src/java/org/apache/cassandra/db/compaction/ShardManager.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTransactionClosingTest.java

Concurrent and incremental repairs would spin fail or deadlock.
Concurrent and incremental repairs would spin fail. This patch:
- Removes an optimization failing to observe max parallelism
- Provides an improved algorithm to enforce max parallelism
- Closes transactions on some exceptions failing to be caught
- Removes a deadlock between cfs and the compaction strategy for long
running sequential operations

Hcd-130 incremental repair failure during compaction

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/disk/EmptyIndex.java
src/java/org/apache/cassandra/index/sai/disk/SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/Segment.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/iterators/KeyRangeTermIterator.java
src/java/org/apache/cassandra/index/sai/memory/MemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Orderer.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
src/java/org/apache/cassandra/index/sai/utils/DocBm25Stats.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java
test/unit/org/apache/cassandra/index/sai/cql/FeaturesVersionSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/LuceneUpdateDeleteTest.java
test/unit/org/apache/cassandra/index/sai/cql/NonNumericTermsDistributionTest.java
test/unit/org/apache/cassandra/index/sai/cql/NumericTermsDistributionTest.java
test/unit/org/apache/cassandra/index/sai/memory/TrieMemtableIndexTestBase.java
test/unit/org/apache/cassandra/index/sai/plan/SingleRestrictionEstimatedRowCountTest.java

Aggregates document frequencies for each query term for entire node before passing to calculate BM25 scores. This removes unbalanced and inconsistent results between different splits to SSTables and MemTables. As the result the test, which was demonstrating this inconsistency, is fixed to provide the same result. The same result is moved into shared constants.
For SSTables created with older version total count is not stored and thus the document frequencies are not aggregated on those SSTables. Thus, the old way of calculating the average document frequencies per segment is used. This also creates difference in the test result for `EC` vs newer versions.
Document frequencies are calculated by searching the query terms, which gives more reliable statistics than using terms distribution …

CNDB-13553 aggregate document frequencies on entire node

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/unified/ShardedMultiWriter.java
src/java/org/apache/cassandra/db/streaming/CassandraStreamReceiver.java
src/java/org/apache/cassandra/index/sai/disk/format/DefaultIndexComponentDiscovery.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexComponentDiscovery.java
src/java/org/apache/cassandra/io/sstable/RangeAwareSSTableWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableMultiWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableRewriter.java
src/java/org/apache/cassandra/io/sstable/SSTableSimpleUnsortedWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableSimpleWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableTxnWriter.java
src/java/org/apache/cassandra/io/sstable/SSTableZeroCopyWriter.java
src/java/org/apache/cassandra/io/sstable/SimpleSSTableMultiWriter.java
src/java/org/apache/cassandra/io/sstable/StorageHandler.java
src/java/org/apache/cassandra/io/sstable/format/SSTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/SortedTableScrubber.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/bti/BtiTableWriter.java
test/unit/org/apache/cassandra/db/SerializationHeaderTest.java
test/unit/org/apache/cassandra/db/compaction/AntiCompactionTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableCorruptionDetectionTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableFlushObserverTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableRewriterTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableUtils.java
test/unit/org/apache/cassandra/io/sstable/SSTableWriterTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableZeroCopyWriterTest.java
test/unit/org/apache/cassandra/io/sstable/ScrubTest.java

For https://github.com/riptano/cndb/issues/14123, we want to be able to catch issues happening during the opening of just-flushed sstables to use shallow sstables. This commit enable this by adding a method to `StorageHandler` that is called on such issue, and allow to provide a "replacement" `SSTableReader` instance.

CNDB-14123: allows intercepting issues opening flushed sstables (#1742)

---

src/java/org/apache/cassandra/cql3/Operator.java
src/java/org/apache/cassandra/cql3/restrictions/SingleColumnRestriction.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/IndexRegistry.java
src/java/org/apache/cassandra/index/SecondaryIndexManager.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java

Prefer not-analyzed indexes over analyzed indexes for contains queries, so they have a deterministic behaviour.
Also, emit a client warning when a not-analyzed index is selected over an analyzed index.
Otherwise, different points in the codebase will make different, pseudo-random decisions about what index should be used for a certain contains expression, leading to erratic behaviour.

CNDB-13925: Prefer not analyzed indexes for contains queries (#1718)

---

src/java/org/apache/cassandra/db/compaction/BackgroundCompactionRunner.java
test/unit/org/apache/cassandra/db/compaction/BackgroundCompactionRunnerTest.java

CNDB-14722: OOM error is not handled by error handler
https://github.com/riptano/cndb/pull/14726/files
Handle OOM error for compaction tasks

CNDB-14722: handle OOM error for compaction task

---

test/distributed/org/apache/cassandra/distributed/test/sai/IndexAvailabilityTest.java

The test was flaky because we were not waiting for some indexing status to get propagated before running queries. This was fixed.

CNDB-14374: Fix flaky test testIndexExceptionsTwoIndexesOn3NodeCluster (#1796)

---

src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

This ports CNDB-14317 to main-5.0, but it is based off of CNDB-14791 which is needed.

CNDB 14808

---

src/java/org/apache/cassandra/index/sai/SSTableIndex.java
src/java/org/apache/cassandra/index/sai/disk/EmptyIndex.java
src/java/org/apache/cassandra/index/sai/disk/SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/v1/InvertedIndexSearcher.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1SearchableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/AbstractMemtableIndex.java
src/java/org/apache/cassandra/index/sai/disk/vector/VectorMemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/MemtableIndex.java
src/java/org/apache/cassandra/index/sai/memory/TrieMemtableIndex.java
src/java/org/apache/cassandra/index/sai/plan/Orderer.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/utils/BM25Utils.java
test/unit/org/apache/cassandra/index/sai/cql/FeaturesVersionSupportTest.java
test/unit/org/apache/cassandra/index/sai/cql/VectorUpdateDeleteTest.java

BM25 score needs to use document average length aggregated on entire node.
Also a bug was discovered, which was introduced by #1789: term frequencies don't
include documents filtered by other predicates, which makes inconsistent result
between query plans.
Fixes https://github.com/riptano/cndb/issues/14361
Changes that BM25 score uses document count and term count aggregated on entire node instead of per segment. Fixes a bug in calculating term frequencies, so
they count all documents.
As the work added more code duplication all duplicated code is refactored in getTopKRows methods.
In addition removes unnecessary public modifier in afffected interface.

CNDB-14361 use node's total document and term counts (#1791)

---

src/java/org/apache/cassandra/index/sai/disk/format/IndexComponent.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexComponents.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
test/unit/org/apache/cassandra/index/sai/SAITester.java

The existing `IndexComponents#validateComponents` method validates some group of index components files (ensure we have all the files we should have, and ensure they looks valid), but it also has some side-effect backed in. It potentially deletes invalid components it found, and invalidate the whole group if validation fails, which rewrite the sstable TOC and whatnot.
For CNDB, it would be useful to be able to validate components on reload without necessarily triggering the side effects, and the plan is to rely on such no-side-effect variant in the patch for
https://github.com/riptano/cndb/issues/14239. But I'd argue having this variant make sense in general and could easily have other uses later, and the changes are trivially backward compatible (they only introduce 2 new methods.

CNDB-14239: expose index components validation method with no side-effect (#1794)

---

src/java/org/apache/cassandra/index/sai/disk/format/IndexComponents.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentBuilder.java
src/java/org/apache/cassandra/index/sai/disk/v1/SegmentMetadataBuilder.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/AnalyzerTest.java

If an index analyzer produced no terms for a row, the index build could not complete and broke sstable flushing.
This commit makes the SegmentBuilder ignore the whole row if there are no terms. Additionally more assertions / preconditions have been added to improve diagnostics.
Fixes:
Failed to complete an index build
java.lang.IllegalStateException: Term range not set at
org.apache.cassandra.index.sai.disk.v1.SegmentMetadataBuilder.build(SegmentMetadataBuilder.java:145) at
org.apache.cassandra.index.sai.disk.v1.SegmentBuilder.flush(SegmentBuilder.java:470) at
org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.flushSegment(SSTableIndexWriter.java:286) at
org.apache.cassandra.index.sai.disk.v1.SSTableIndexWriter.complete(SSTableIndexWriter.java:151)

CNDB-14481: Fix IllegalStateException in SegmentMetadataBuilder (#1808)

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/iterators/KeyRangeTermIterator.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/QueryView.java
test/unit/org/apache/cassandra/index/sai/cql/DropIndexWhileQueryingTest.java
test/unit/org/apache/cassandra/index/sai/plan/FlushIndexWhileQueryingTest.java

- **Create a failing test**
- **Parameterize DropIndexWhileQueryingTest, making it fail**
- **CNDB-14392: Use QueryView's MemtableIndex references for search**
Fixes: https://github.com/riptano/cndb/issues/14392
We incorrectly use the `liveMemtables` at search time instead of the `QueryView.memtables` for the memory index search. This leads to incorrect behavior when a memtable is flushed or dropped after we acquire the `QueryView` and before we search the `liveMemtables`. The solution is easy: use the referenced `QueryView` to get the memtables

CNDB-14392: Use QueryView's MemtableIndex references for search (#1799)

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
test/unit/org/apache/cassandra/index/sai/functional/ValidateComponentsTest.java

- **CNDB-14477: Validate SAI Components**
- **Add follow up comment to vector corruption check**
Fixes: https://github.com/riptano/cndb/issues/14477
This PR leverages the existing SAI verification framework and wires it up to validate components.

CNDB-14477: Validate SAI Components (#1816)

---

src/java/org/apache/cassandra/schema/SchemaConstants.java

Fixes CNDB-14848, removing unused, duplicated constants from `SchemaConstants`
`SchemaConstants` contains unused and duplicated constants left over from previous rebases.

CNDB-14848 CC5 remove unused duplicated constants from SchemaConstants

---

test/burn/org/apache/cassandra/index/sai/LongVectorTest.java

#13724
reduce num of test keys and less flushes. Reduce the chances of hitting "too many open files"

CNDB-13724: reduce num of test keys in LongVectorTest to avoid jenkins timeout (#1831)

---

src/java/org/apache/cassandra/index/sai/disk/RAMPostingSlices.java
src/java/org/apache/cassandra/index/sai/disk/RAMStringIndexer.java
test/unit/org/apache/cassandra/index/sai/disk/RAMStringIndexerTest.java

#14773: Int2IntHashMap overflow when num of docs reaches 348_966_081
Trigger segment flush before overflow and include array memory usage to avoid undercounting memory usage

CNDB-14773: avoid Int2IntHashMap overflow in RAMStringIndexer and improve memory track to include array memory usage

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/utils/InsertionOrderedNavigableSet.java
test/unit/org/apache/cassandra/index/sai/cql/LargePartitionsTest.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java
test/unit/org/apache/cassandra/utils/InsertionOrderedNavigableSetTest.java

Fixes: https://github.com/riptano/cndb/issues/11666
Ports: https://issues.apache.org/jira/browse/CASSANDRA-19497
May fix: https://github.com/riptano/cndb/issues/14822
Here is a draft of porting the fix from upstream. Initial validation shows improved performance that gets much closer to the `aa` performance for low selectivity queries.
Test results from many different versions show that this patch gets us from ~39 qps to ~418 qps, giving us a 10x increase in throughput.
```
$ latte list --tag ondisk
File ─────────────────────────────────────────────────────────────────────────────────────────────   Workload   Function   Timestamp ─────────   Tags ──────────────────────────   Params   Rate   Thrpt. [req/s]   P50 [ms]   P99 [ms]
./wide.Test_Cluster.4.0.11.0-SNAPSHOT.ondisk.p128.t1.c1.2025071 …
```

CNDB-11666: Batch clusterings into single SAI partition post-filtering reads

---

src/java/org/apache/cassandra/index/sai/StorageAttachedIndexGroup.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexDescriptor.java
src/java/org/apache/cassandra/index/sai/disk/format/IndexFeatureSet.java
src/java/org/apache/cassandra/index/sai/disk/format/Version.java
src/java/org/apache/cassandra/index/sai/disk/v1/V1OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v2/V2OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v3/V3OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v6/V6OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/disk/v7/V7OnDiskFormat.java
src/java/org/apache/cassandra/index/sai/utils/SAICodecUtils.java
src/java/org/apache/cassandra/io/sstable/format/SortedTableVerifier.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/disk/v7/V7OnDiskFormatIntegrationTest.java
test/unit/org/apache/cassandra/index/sai/disk/v7/V7OnDiskFormatTest.java
test/unit/org/apache/cassandra/index/sai/functional/VerifyTest.java
test/unit/org/apache/cassandra/io/sstable/format/SortedTableVerifierTest.java

Fixes: https://github.com/riptano/cndb/issues/14501
CNDB test pr: https://github.com/riptano/cndb/pull/14660
This PR introduces vector index checksum validation starting with files in version `EC` at above. For non terms files, we compute the checksum correctly. For terms files, we skip validation of the checksum because it is not computed correctly. There is a new issue to track fixing the checksum logic on those TERMS files
https://github.com/riptano/cndb/issues/14656.
I implemented the version-dependent validation by overriding `V7OnDiskFormat#validateIndexComponent`. This allows us to validate new files while skipping the old ones. In doing so, I removed the misleading `IndexFeatureSet` method for checksums. The modified comment describes why that feature didn't make sense as an …

CNDB-14501: Enable checksum for jvector index files starting at version EC (#1841)

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/db/compaction/BackgroundCompactions.java
src/java/org/apache/cassandra/db/compaction/ShardManager.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
test/unit/org/apache/cassandra/db/ColumnFamilyStoreTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTransactionClosingTest.java

Concurrent and incremental repairs would spin fail or deadlock.
Concurrent and incremental repairs would spin fail. This patch:
- Removes an optimization failing to observe max parallelism
- Provides an improved algorithm to enforce max parallelism
- Closes transactions on some exceptions failing to be caught
- Removes a deadlock between cfs and the compaction strategy for long running sequential operations

HCD-130 incremental repair failure during compaction (#1728)

---

.build/parent-pom-template.xml
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraDiskAnn.java
src/java/org/apache/cassandra/index/sai/disk/vector/CassandraOnHeapGraph.java
src/java/org/apache/cassandra/index/sai/disk/vector/CompactionGraph.java

Fixes https://github.com/riptano/cndb/issues/14797
CNDB test PR https://github.com/riptano/cndb/pull/14799
Here is the list of commits included in the upgrade: https://github.com/datastax/jvector/compare/4.0.0-beta.5...4.0.0-rc.1
Here is a copy of the relevant `CHANGELOG.md` lines:
> ####
[4.0.0-rc.1](https://github.com/datastax/jvector/compare/4.0.0-beta.6...4.0.0-rc.1)
>
> - Fix issue when calling cleanup while concurrently executing searches
[`#483`](https://github.com/datastax/jvector/pull/483)
> - Improve the efficiency and memory usage of GraphIndexBuilder.cleanup
[`#477`](https://github.com/datastax/jvector/pull/477)
> - add PQ training benchmark
[`#482`](https://github.com/datastax/jvector/pull/482)
> - Remove extraneous character from datasets.yml …

CNDB-14797: Upgrade to jvector 4.0.0-rc1 (#1866)

---

src/java/org/apache/cassandra/crypto/LocalFileSystemKeyProvider.java
src/java/org/apache/cassandra/tools/NodeTool.java
src/java/org/apache/cassandra/tools/nodetool/CreateSystemKey.java
test/distributed/org/apache/cassandra/distributed/test/NodeToolTest.java
test/distributed/org/apache/cassandra/distributed/test/SSTableEncryptionTest.java
test/unit/org/apache/cassandra/crypto/LocalFileSystemKeyProviderTest.java

This commit extends nodetool with createsystemkey command.
The motivation is to allow users to create encryption keys that can
be used for flat-file based encryption in TDE.
CNDB PR: https://github.com/riptano/cndb/pull/14205.

HCD-147: Add createsystemkey subcommand to nodetool

---

test/unit/org/apache/cassandra/db/lifecycle/LogTransactionTest.java

This test is flaky. It stresses the log transaction framework by intentionally creating a race between transaction file cleanup and the listing of temporary files. It sometimes throws an exception during canonicalization of a file that has been removed, but this canonicalization is being done by the testing code, not the transaction code, and it does not indicate misbehavior by the log transaction.
Cherry-picks the fix for this in newer apache/cassandra releases. This ignores exceptions due to files not being found during canonicalization.
original patch authored by Jon Meredith, reviewed by Josh McKenzie for CASSANDRA-17286

CNDB-14683: Cherry-pick fix for flaky LogTransactionTest (#1870)

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/commitlog/CommitLogDescriptor.java
src/java/org/apache/cassandra/net/MessagingService.java
test/unit/org/apache/cassandra/db/commitlog/CommitLogDescriptorTest.java

CC4 can only communicate with DSE 6.8 on messaging version VERSION_3014 (messaging/protocol version 11) and VERSION_3014 (messaging/protocol version 11). Manully setting the CC4 node's `MessagingService.current_version` achieves this, done using the jvm flag `-Dds.current_messaging_version=11`.  Using VERSION_30 (messaging/protocol version 10) is also accepted, but hits the column filter bug on system tables `select *` queries during startup.
This commits automates the DSE 6.8 detection and negotiation when the maxMessagingVersion in the handshake is above 256, replying with a max accept of VERSION_3014. The ds.current_messaging_version flag is kept, as when it is used everything behaves as it previously did.  This is important for CNDB, as it hasn't dropped support for bdp/cndb-6.8 (a …

HCD-136 – DSE 6.8 to CC4 internode transport compatibility

---

test/microbench/org/apache/cassandra/test/microbench/index/sai/QuerySelectivityBench.java

Add a JMH benchmark to test the performance of filtering SELECT queries with different selectivities.

CNDB-14921: Add JMH benchmark for SAI queries selectivity

---

build.xml

The rationale is to remediate CVE-2025-48924.
The version before the upgrade was 3.11.

HCD-180: Cherrypick HCD-179 and HCD-178 into HCD-1.2.3

---

test/unit/org/apache/cassandra/cql3/validation/operations/AlterTest.java

Fixes https://github.com/riptano/cndb/issues/14954
Fixes CC5 test failure by removing an assert that was likely due to a rebase mistake.
```
assertThat(AbstractShardedMemtable.getDefaultShardCount()).isEqualTo(1);;
```
The assert comes from a CC ticket, STAR-840, but this assert does not appear on `main` branch in `AlterTest`. In fact `AbstractShardedMemtable` is a CC 5.0 only class.
Without digging more into the history of how/why this got added ... it's not needed here since the `main` branch version does not have any similar check.

CC5 fix AlterTest

---

src/java/org/apache/cassandra/io/sstable/SSTable.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/SSTableReaderBuilder.java
src/java/org/apache/cassandra/io/sstable/format/SSTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/SortedTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/big/BigTableWriter.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableReader.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableWriter.java
test/distributed/org/apache/cassandra/io/sstable/format/ForwardingSSTableReader.java
test/unit/org/apache/cassandra/db/lifecycle/LogTransactionTest.java
test/unit/org/apache/cassandra/io/sstable/SSTableReaderTest.java
test/unit/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexFormatUtil.java
test/unit/org/apache/cassandra/io/util/WriteAndReadTest.java
test/unit/org/apache/cassandra/schema/MockSchema.java

Every time you call getApproximateKeyCount Cassandra reads from storage and deserialize CompactionMetadata, and in order to do it it also reads CompressionMetadata in case of Compression.
```
at org.apache.cassandra.io.util.PathUtils.newFileChannel(PathUtils.java:113)
at org.apache.cassandra.io.util.PathUtils.newReadChannel(PathUtils.java:91)
at org.apache.cassandra.io.util.File.newReadChannel(File.java:597)
at org.apache.cassandra.io.util.FileInputStreamPlus.<init>(FileInputStreamPlus.java:39)
at org.apache.cassandra.io.util.File.newInputStream(File.java:634)
at org.apache.cassandra.io.compress.CompressionMetadata.<init>(CompressionMetadata.java:170)
at org.apache.cassandra.io.compress.CompressionMetadata.read(CompressionMetadata.java:138)
at …
```

CNDB-9018: cache SSTable:CompactionMetadata in order to not read from storage multiple times

---

src/java/org/apache/cassandra/io/util/SequentialWriter.java
test/unit/org/apache/cassandra/io/util/SequentialWriterReadableTest.java

SequentialWriter open a write-only channel by default
Defaults SequentialWriter channels to write-only

CNDB 15032 SequentialWriter should open a write-only channel by default

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.java
src/java/org/apache/cassandra/db/compaction/UnifiedCompactionStrategy.md
src/java/org/apache/cassandra/db/compaction/unified/AdaptiveController.java
src/java/org/apache/cassandra/db/compaction/unified/Controller.java
src/java/org/apache/cassandra/db/compaction/unified/StaticController.java
test/unit/org/apache/cassandra/db/compaction/CompactionSimulationTest.java
test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java
test/unit/org/apache/cassandra/db/compaction/unified/AdaptiveControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java
test/unit/org/apache/cassandra/db/compaction/unified/StaticControllerTest.java

CNDB-14577: [UCS by default does not compact many small non-overlapping sstables with very few
rows](https://github.com/riptano/cndb/issues/14577)
This PR limits the number of SSTables for a given compaction level shard by executing a major compaction of the shard instead of the regular compaction of overlapping SSTables if the number of SSTables reaches a threshold.
The threshold is controlled by the `max_sstables_per_shard_factor` setting:
```md
`max_sstables_per_shard_factor` Limits the number of SSTables per shard. If the number of sstables in a shard
exceeds this factor times the shard compaction threshold, a major compaction of the shard will be triggered.
Some conditions like slow writes can lead to SSTables being very small, and never overlap with enough other SSTables
to be …
```

CNDB-14577: Compact all SSTables of a level shard if their number reaches a limit (#1873)

---

test/microbench/org/apache/cassandra/test/microbench/index/sai/QuerySelectivityBench.java

Add a JMH benchmark to test the performance of SELECT queries with different selectivities using SAI.

CNDB-14921: Add JMH benchmark for SAI queries selectivity (#1913)

---

src/java/org/apache/cassandra/db/SerializationHeader.java
src/java/org/apache/cassandra/io/sstable/format/StatsComponent.java
src/java/org/apache/cassandra/io/sstable/format/big/BigSSTableReaderLoadingBuilder.java
src/java/org/apache/cassandra/io/sstable/format/bti/BtiTableReaderLoadingBuilder.java
test/unit/org/apache/cassandra/tools/SSTablePartitionsTest.java

SSTablePartitionsTest.testDirectory fails with an AssertionError deserializing a header
`StatsComponent.serializeHeader` needed to know about offline tools to avoid the assertion.  However, the `legacy_ma_tuple` test SSTable has an invalid schema (non-frozen tuple with non-frozen collections) and after the validation added by CNDB-10090, this is correctly detected, which doesn't happen in OSS.  As a result, the test has also been modified so that unclean stderr can optionally be allowed.

CND-14215: fix SSTablePartitionsTest.testDirectory

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/io/sstable/format/trieindex/TrieIndexSSTableWriter.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
src/java/org/apache/cassandra/utils/FilterFactory.java
test/unit/org/apache/cassandra/db/compaction/CompactionControllerTest.java

cndb-15058: table metrics - bloom filter memory usage doesn't include partially written sstables' if early open is not enabled
Include in flight BF memory usage if early open is not enabled

CNDB-15058: track in-flight BF memory usage from trie index writer if early open is not enabled

---

test/unit/org/apache/cassandra/db/compaction/UnifiedCompactionStrategyTest.java

UnifiedCompactionStrategyTest.textMaximalSelection has been failing since CNDB-15020
This prevents excessive heap pressure by using Mockito's stubonly where possible, and clears mocks between tests

CNDB-15097: Mock with stubOnly and clear mocks between runs to save heap

---

src/java/org/apache/cassandra/db/DataRange.java
src/java/org/apache/cassandra/db/filter/ClusteringIndexNamesFilter.java
test/unit/org/apache/cassandra/db/PartitionRangeReadCommandCQLTest.java
test/unit/org/apache/cassandra/db/SinglePartitionReadCommandCQLTest.java

Single partition queries using an index are internally mapped to range commands. Partition key restrictions are printed as token ranges. As a result a query like:
```
CREATE TABLE t (k int PRIMARY KEY, v int);
CREATE CUSTOM INDEX ON t(v) USING 'StorageAttachedIndex';
SELECT * FROM t WHERE v = 0 AND k = 0;
```
Will be logged as:
```
SELECT * FROM t WHERE v = 0 AND token(k) >= token(0) AND token(k) <= token(0)
```
While this format is kind of correct, it makes logs harder to read and makes one doubt for a second whether the query is a partition key. Note that this example is small, but it can look worse with multiple partition columns with long names and more index and clustering restrictions, as we have seen in production.
Also, the printed query is not strictly equivalent to the original …

CNDB-15153: Improve logging of partition-restricted index queries

---

src/java/org/apache/cassandra/db/filter/RowFilter.java

The row filter expression value truncation behavior is broken after CNDB-15000
Restores truncation of row filter expression values

CNDB-15177: fix GuardrailNonPartitionRestrictedQueryTest by restoring CQL truncation behavior

---

conf/cassandra.yaml
src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/DatabaseDescriptor.java
src/java/org/apache/cassandra/guardrails/GuardrailsConfig.java
src/java/org/apache/cassandra/service/StartupChecks.java
test/unit/org/apache/cassandra/service/StartupChecksTest.java

There are now three profiles for guardrail defaults: none|dbaas|hcd
This redoes the work in 7940e9c
The defaults introduced previously (as new non-dbaas defaults) are now applied to the hcd profile. 
--
HCD-179 Guardrail defaults for on-prem
Provide users defaults and feedback from startup checks/warnings sensible for production environments. Many users do not (and do not want to) understand the complexities of HCD/Cassandra, and such feedback helps them stay safely dumb. This is also expected to alleviate the impact on Support having to deal will silly abuses of the database.  It is also avoids operators having to retrospectively police their developers creating the data models and client applications.
Set on-prem guardrail defaults to be (keeping in mind these can be changed by …

CNDB-15022 Introduce additional guardrail profile for HCD

---

src/java/org/apache/cassandra/index/sai/IndexContext.java
src/java/org/apache/cassandra/index/sai/SSTableContext.java
src/java/org/apache/cassandra/index/sai/disk/PrimaryKeyMap.java

#15135
Avoid reading SAI per-sstable files if SAI_INDEX_READS_DISABLED is true

CNDB-15135: use EmptyFactory to avoid loading SAI per-sstable files if SAI_INDEX_READS_DISABLED is true

---

src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
src/java/org/apache/cassandra/db/filter/ClusteringIndexNamesFilter.java
src/java/org/apache/cassandra/db/filter/RowFilter.java

After CNDB-15000, cql string generation for read commands with clustering columns needs to be fixed, and value truncation is not working.
Refactor CQL string generation in PartitionRangeReadCommand and SinglePartitionReadCommand
to properly handle the interaction between row filters and clustering filters. This prevents
duplication of clustering column conditions when both regular filters and clustering
restrictions are present, particularly in queries using ALLOW FILTERING or secondary indexes
on clustering columns.
Fix value truncation in RowFilter CQL string generation.

CNDB-15039: fix AbstractReadQueryToCQLStringTest

---

src/java/org/apache/cassandra/db/ColumnFamilyStore.java
src/java/org/apache/cassandra/io/sstable/AbstractMetricsProviders.java
src/java/org/apache/cassandra/io/sstable/filter/BloomFilterMetrics.java
src/java/org/apache/cassandra/io/sstable/format/bti/BtiTableWriter.java
src/java/org/apache/cassandra/metrics/TableMetrics.java
src/java/org/apache/cassandra/utils/FilterFactory.java
test/unit/org/apache/cassandra/db/compaction/CompactionControllerTest.java

cndb-15058: table metrics - bloom filter memory usage doesn't include partially written sstables' if early open is not enabled
Include in flight BF memory usage if early open is not enabled

CNDB-15058: track in-flight BF memory usage from trie index writer if early open is not enabled (#1949)

---

src/java/org/apache/cassandra/db/compaction/BackgroundCompactionRunner.java
src/java/org/apache/cassandra/io/FSDiskFullWriteError.java
src/java/org/apache/cassandra/io/FSNoDiskAvailableForWriteError.java
src/java/org/apache/cassandra/io/compress/CompressedSequentialWriter.java
src/java/org/apache/cassandra/io/compress/CorruptBlockException.java
src/java/org/apache/cassandra/io/compress/EncryptedSequentialWriter.java
src/java/org/apache/cassandra/io/sstable/CorruptSSTableException.java
src/java/org/apache/cassandra/io/util/ChecksummedRebufferer.java
src/java/org/apache/cassandra/io/util/CompressedChunkReader.java
src/java/org/apache/cassandra/io/util/CorruptFileException.java
src/java/org/apache/cassandra/io/util/EncryptedChunkReader.java
src/java/org/apache/cassandra/repair/ValidationManager.java
src/java/org/apache/cassandra/utils/JVMStabilityInspector.java
test/unit/org/apache/cassandra/db/compaction/BackgroundCompactionRunnerTest.java

Corruption excetion from compaction task didn't notify error handler.
Compaction aborted/failed metrics were not updated in some cases.
Trigger JVMStabilityInspector for corruption exception from compaction task and update aborted/failed metircs properly.
Trigger JVMStabilityInspecto for error from repair validation.

CNDB-9697: notify JVMStabilityInspector when encountered corruption exception on compaction task

---

src/java/org/apache/cassandra/config/Config.java
src/java/org/apache/cassandra/config/GuardrailsOptions.java
src/java/org/apache/cassandra/config/YamlConfigurationLoader.java
test/distributed/org/apache/cassandra/distributed/test/sai/datamodels/MultiNodeQueryTester.java
test/unit/org/apache/cassandra/config/DatabaseDescriptorTest.java

Fixes CNDB-15137
The original port of STAR-543 incorrectly omitted the ability to enforce guardrail configuration defaults.
Restores the GuardrailsOptons.enforceDefault method that was omitted when STAR-543 was ported to CC 5.0. With this change, `YamlConfigurationLoader` tracks config options set in yaml, so that `GuardrailsOptions.enforceDetault` can determine when to set recommended values for on premise or CNDB uses.

CNDB-15137 Tracks config options set in yaml, used by GuardrailsOptions.enforceDetault to set recommended values.

---

src/java/org/apache/cassandra/cql3/restrictions/StatementRestrictions.java
src/java/org/apache/cassandra/db/filter/ClusteringIndexNamesFilter.java

IntersectFilteringQueryTest.shouldFailOnFilteringQuery and shouldWarnOnFilteringQuery are failing
needsReconciliation needs to be passed in order for a quorum level query to be used

CNDB-15262: add needsReconciliation flag to fix IntersectFilteringQueryTest

---

src/java/org/apache/cassandra/index/sai/disk/StorageAttachedIndexWriter.java
test/distributed/org/apache/cassandra/distributed/test/sai/ImportIndexedSSTablesTest.java
test/distributed/org/apache/cassandra/distributed/test/sai/IndexStreamingFailureTest.java
test/unit/org/apache/cassandra/index/sai/functional/FlushingTest.java

If the index fails to build, mark the index non-queryable, but don't fail the C* flush. This way the node can continue to run the other queries.

CNDB-14207: Don't mark the index non-queryable if flush fails (#1770)

---

test/unit/org/apache/cassandra/index/sai/cql/BM25Test.java

Code to generate collection values for BM25 test is difficult to follow. This commit refactors the generation code into methods with simpler code. Also this commit removes unused last column in the dataset.

CNDB-13408 Improve BM25 test with better logic (#1963)

---

test/unit/org/apache/cassandra/cql3/validation/operations/AggregationQueriesTest.java

AggregationQueriesTest failing quite often due to timing
Make the tests more predictable by explicitly controlling pagination behavior rather than relying on timing

CNDB-15265: fix AggregationQueriesTest using sub-page fetching

---

test/unit/org/apache/cassandra/service/reads/AbstractReadResponseTest.java

AbstractReadResponseTest is using READ_REQ instead of response verbs
uses the appropriate response verb

CNDB-15291: use correct response verb in AbstractReadResponseTest

---

test/distributed/org/apache/cassandra/distributed/test/sai/features/FeaturesVersionSupportTester.java

Synthetic scoring is not supported before ED
Disable synthetic scoring

CNDB-14657: disable synthetic score for older versions in FeaturesVersionSupportTester

---

src/java/org/apache/cassandra/db/AbstractReadQuery.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/schema/IndexMetadata.java
test/unit/org/apache/cassandra/db/PartitionRangeReadCommandCQLTest.java
test/unit/org/apache/cassandra/db/SinglePartitionReadCommandCQLTest.java

This makes the output of toCQLString a bit more distracting because AF is not always needed, but it aligns with ASF and it guarantees that the output of that method is always runnable.

CNDB-15239: Add ALLOW FILTERING to AbstractReadQuery#toCQLString (#1974)

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/MultiRangeReadCommand.java
src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
test/distributed/org/apache/cassandra/distributed/test/sai/TraceTest.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/QueryTimeoutTest.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java

SAI's tracks query metrics providing info about latency, partition reads, filtered rows, etc. These metrics are for all the SAI queries for a certain table. When we see problems in queries, for example a high latency, questions that can usually come next are what query is producing this high latency? Are there vector queries? Are queries for a single partition? In that case, what is the latency of those queries? How many rows are they selecting? To answer those questions, I think it can be useful to track metrics for specific types of query.
The types of query depend on multiple characteristics, like being top-k, containing disjunctions, etc. We can make an overwhelming number of combinations of query characteristics conforming types of query. Storing so many metrics is probably not …

CNDB-15155: Segregate SAI's query metrics per query type

---

src/java/org/apache/cassandra/config/GuardrailsOptions.java

Fixed CNDB-15401 to enforce guardrail default for `pageWeight` (paging in Bytes) instead of `pageSize` (paging by Rows)
This is needed in CNDB, where the default page size in Rows is unlimited, and enforcing the `pageSize` (rows) default in CC5 causes CNDB containers not to be able to start.

CNDB-15401 enforce default guardrail value for page_weight used for paging in Bytes instead of page_size that is used for paging in Rows in CC5

---

src/java/org/apache/cassandra/index/sai/plan/TopKProcessor.java

Fixes: https://github.com/riptano/cndb/issues/15423
CNDB test: https://github.com/riptano/cndb/pull/15427
This PR fixes a subtle bug exposed by the `FeaturesVersionSupportCATest.testANN` test, as well as other similarly named `FeaturesVersionSupport*Test` tests. The central issue is whether to create the `queryVector` object. The currently logic does so only when `useSyntheticScore()` is false. However, if a peer has it set to false and this node has it on true, we'll end up with an easily avoided NPE. I propose instead that we lazily load the vector when it is needed. This removes an unnecessary switch as well as removing an unnecessary ordering requirement on upgrades.
```
java.lang.NullPointerException
at io.github.jbellis.jvector.vector.VectorUtil.squareL2Distance(VectorUtil.java:85) …
```

CNDB-15423: Make TopKProcessor lazily load queryVector

---

src/java/org/apache/cassandra/locator/ReplicaPlans.java

If we intersect read and write replicas we need a way to check if intersection replicas satisfy CL requirements, thus
marking needed functions as public.
Related CNDB PR https://github.com/riptano/cndb/pull/15317

CNDB-14509: Mark functions as public

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/MultiRangeReadCommand.java
src/java/org/apache/cassandra/db/PartitionRangeReadCommand.java
src/java/org/apache/cassandra/db/ReadCommand.java
src/java/org/apache/cassandra/db/SinglePartitionReadCommand.java
src/java/org/apache/cassandra/index/Index.java
src/java/org/apache/cassandra/index/sai/QueryContext.java
src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexQueryPlan.java
src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
src/java/org/apache/cassandra/tools/NodeProbe.java
test/distributed/org/apache/cassandra/distributed/test/sai/TraceTest.java
test/unit/org/apache/cassandra/index/sai/SAITester.java
test/unit/org/apache/cassandra/index/sai/cql/QueryTimeoutTest.java
test/unit/org/apache/cassandra/index/sai/functional/GroupComponentsTest.java
test/unit/org/apache/cassandra/index/sai/metrics/AbstractMetricsTest.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java

See https://github.com/datastax/cassandra/pull/1969
Port CNDB-15155 to main-5.0
A second checkpoint (prefixed `SQUASH`) commit is kept separate in the PR where upstream `cassandra-5.0` code needed to be re-implemented.  This was for CASSANDRA-18940
This will be squashed before rebase+merge.

Port CNDB-15155 550263f to main-5.0

---

src/java/org/apache/cassandra/config/CassandraRelevantProperties.java
src/java/org/apache/cassandra/db/compaction/validation/CompactionValidationMetrics.java
src/java/org/apache/cassandra/db/compaction/validation/CompactionValidationTask.java
src/java/org/apache/cassandra/db/lifecycle/AbstractLogTransaction.java
src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java
test/unit/org/apache/cassandra/db/compaction/validation/CompactionValidationTest.java

https://github.com/riptano/cndb/issues/15141
Added compaction task verification before transaction commit to validate if all source sstables' min/max keys are present in output sstables or expired if missing from output sstables.
This is mainly to detect data loss caused by compaction strategy skipping some subranges of source sstables HCD-130.
It works as following:
1. Extract all boundary keys (min/max) from source sstable
2. Check if boundary keys exist in output sstables
a If all present, validation passes
b. If any keys are missing, continue validation
3. For missing keys, read partition data from source sstables
4. Apply tombstone purging by using `gc_grace_seconds=0`
5. Check purged content
a If there is no live data, validation passes. Keys are properly obsoleted
b If there is …

CNDB-15141: add LogTransaction#validate API to perform validation before txn prepare

---

src/java/org/apache/cassandra/index/sai/metrics/TableQueryMetrics.java
src/java/org/apache/cassandra/index/sai/plan/Plan.java
src/java/org/apache/cassandra/index/sai/plan/QueryController.java
test/unit/org/apache/cassandra/index/sai/metrics/QueryMetricsTest.java

It's simpler to understand SAI query metrics when they are split
into granular, non-overlapping categories. The fact they are
non-overlapping makes any of their combinations meaningful.
They can be also visualized in stacked charts.
Additionally, a bug was fixed that prevented proper updates of
SortThenFilterQueriesCompleted and FilterThenSortQueriesCompleted
metrics for non-ANN TopK queries and for some non-hybrid queries.
Now those metrics are bumped up by all hybrid topK queries, and
only by those.

CNDB-15452: Split SAI metrics query types into disjoint categories

---

src/java/org/apache/cassandra/index/sai/plan/StorageAttachedIndexSearcher.java
test/unit/org/apache/cassandra/index/sai/cql/LargePartitionsTest.java

https://github.com/riptano/cndb/issues/15485
This PR fixes a bug introduced to this branch via https://github.com/datastax/cassandra/pull/1884. The bug only impacts SAI file format `aa` when the index file was produced via compaction, which is why the modified test simply adds coverage to compact the table and hit the bug.
The bug happens when an iterator produces the same partition across two different batch fetches from storage. These keys were not collapsed in the `key.equals(lastKey)` logic because compacted indexes use a row id per row instead of per partition, and the logic in `PrimaryKeyWithSource` considers rows with different row ids to be distinct. However, when we went to materialize a batch from storage, we hit this code:
```java
ClusteringIndexFilter clusteringIndexFilter = …
```

CNDB-15485: Fix ResultRetriever key comparison to prevent dupes in result set

---

src/java/org/apache/cassandra/io/sstable/format/TOCComponent.java
src/java/org/apache/cassandra/io/sstable/metadata/MetadataSerializer.java

TOCComponent performs component discovery before loading the TOC. This can be detrimental to custom component loading and can be optimized to try loading the TOC directly first before resorting to discovery.
Load the TOC component without discovery if possible

CNDB-15526: Load TOC component before performing component discovery

---

src/java/org/apache/cassandra/db/compaction/unified/Controller.java
test/unit/org/apache/cassandra/db/compaction/unified/ControllerTest.java

https://github.com/riptano/cndb/issues/15253 large shard count jump caused HCD-130
Replace power-of-two shard progression with factorization-based smooth growth when num_shards is explicitly configured. This prevents problematic large jumps that can cause data loss (e.g., HCD-130). For example, with num_shards 1000 which is 5^3* 2^3:
- Before: 1 → 2 → 8 → 1000 (125x jump causes data loss due to hcd-130)
- After:  1 → 5 → 25 → 125 → 250 → 500 → 1000 (max 5x jump)
* new behavior can be disabled via `-Dunified_compaction.use_factorization_shard_count_growth`

CDNB-15253: make UCS shard progression smoother when num_shards and min sstable size are configured

---

src/java/org/apache/cassandra/cql3/QueryEvents.java
src/java/org/apache/cassandra/metrics/AllRequestsMetrics.java
src/java/org/apache/cassandra/metrics/ClientRequestsMetrics.java
test/unit/org/apache/cassandra/metrics/ClientRequestsMetricsAllRequestsTest.java

https://github.com/riptano/cndb/issues/8641
PR in CNDB: https://github.com/riptano/cndb/pull/15306
This pull request introduces new metrics for tracking invalid and other error requests for CQL statements, and integrates these metrics into the query failure notification logic. The main changes are the addition of the `AllRequestsMetrics` class, updates to the `ClientRequestsMetrics` class to include these new metrics, and modifications to the query event notification methods to record errors using the new metrics.
Metrics added:
* org.apache.cassandra.metrics.ClientRequest.Timeouts.All
* org.apache.cassandra.metrics.ClientRequest.Unavailables.All
* org.apache.cassandra.metrics.ClientRequest.Failures.All
* org.apache.cassandra.metrics.ClientRequest.Invalid.All
* …

CNDB-8641: Add a metric to count all request errors
